In [66]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 10-K Narrative Section Extraction — MD&A, Properties & Risk Factors

Pulls the **full text** of three 10-K sections from SEC EDGAR for the last 15 years and
stores one parquet per company in `bond_shared/data/raw/text/`

| Section | 10-K item | Column value |
|---|---|---|
| Management's Discussion & Analysis | Item 7 | `mda` |
| Properties | Item 2 | `properties` |
| Risk Factors | Item 1A | `risk_factors` |

**Steps**
1. Build the company universe (ticker + **industry**)
2. Attach CIK / company name from SEC's official ticker map
3. Keep only companies with **5+ fiscal years of 10-K history** — this drops foreign private
   issuers and recent IPOs in one rule — then count what is left
4. Extract Item 1A / Item 2 / Item 7 full text from every 10-K in the window
5. Pick the companies to process
6. Write one parquet per company into `data/raw/text/`
7. Read the parquet files back and sanity-check them

> **Where files are written.** The notebook writes to the Dropbox path below when it exists
> (i.e. when you run this on your Mac). On Colab that path does not exist, so it falls back to
> a local `./bond_shared/data/raw/text` folder and tells you so — mount Drive or copy the files
> across afterwards.

## 0. Setup

In [67]:
# Install anything missing (no-op when the package is already there).
import importlib.util, subprocess, sys

REQUIRED = [
    ("edgartools", "edgar"),
    ("pyarrow", "pyarrow"),
    ("lxml", "lxml"),
    ("html5lib", "html5lib"),
    ("beautifulsoup4", "bs4"),
]
missing = [pkg for pkg, mod in REQUIRED if importlib.util.find_spec(mod) is None]
if missing:
    print("Installing:", ", ".join(missing))
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", *missing], check=True)
else:
    print("All required packages already installed.")

All required packages already installed.

In [68]:
import os
import re
import time
import threading
import warnings
from io import StringIO
from urllib.parse import urlparse
from concurrent.futures import ThreadPoolExecutor

import requests
import pandas as pd
from bs4 import BeautifulSoup
from edgar import Company, set_identity

warnings.simplefilter(action="ignore", category=FutureWarning)

# ---- Configuration -------------------------------------------------------
IDENTITY = "Feriha Ozturk feriha.ozturk34@stu-mail.ccny.cuny.edu"
set_identity(IDENTITY)

SEC_HEADERS = {"User-Agent": IDENTITY, "Accept-Encoding": "gzip, deflate"}
WEB_HEADERS = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"}

YEARS_BACK = 15          # how far back to pull 10-K filings
MIN_10K_YEARS = 5        # drop companies with fewer than this many years of 10-K history
N_COMPANIES = len(universe) # how many companies to extract + store in this run



START_YEAR = pd.Timestamp.today().year - YEARS_BACK
print(f"10-K window: filings from {START_YEAR} onward; "
      f"companies need >= {MIN_10K_YEARS} fiscal years in that window.")

# Narrative text lives in data/raw/text/
DROPBOX_RAW = ("/Users/feriha/Library/CloudStorage/Dropbox-CityCollege/Feriha Ozturk/bond_shared/data/raw/text")
if not os.path.isdir(os.path.dirname(DROPBOX_RAW)):
    DROPBOX_RAW = os.path.abspath("./bond_shared/data/raw/text")
    print("Dropbox path not visible here — falling back to a local folder.")
os.makedirs(DROPBOX_RAW, exist_ok=True)
print("Writing to:", DROPBOX_RAW)

pd.set_option("display.width", 220)
pd.set_option("display.max_colwidth", 60)

10-K window: filings from 2011 onward; companies need >= 5 fiscal years in that window.
Dropbox path not visible here — falling back to a local folder.
Writing to: /content/bond_shared/data/raw/text

## 1. Company universe — ticker + industry


The industry name is taken from the URL so every row carries the industry it came from.
Duplicates are dropped keeping the **first** occurrence, which preserves the market-cap
ordering of the source pages.

In [69]:
INDUSTRY_URLS = [
    "https://stockanalysis.com/stocks/industry/biotechnology/",
    "https://stockanalysis.com/stocks/industry/biotechnology/?page=2",
    "https://stockanalysis.com/stocks/industry/semiconductors/",
    "https://stockanalysis.com/stocks/industry/internet-content-and-information/",
    "https://stockanalysis.com/stocks/industry/software-infrastructure/",
]


def extract_industry(url):
    """'.../industry/software-infrastructure/' -> 'Software Infrastructure'."""
    parts = urlparse(url).path.strip("/").split("/")
    return parts[parts.index("industry") + 1].replace("-", " ").title()


def scrape_industry_table(urls=INDUSTRY_URLS):
    rows = []
    for url in urls:
        industry = extract_industry(url)
        resp = requests.get(url, headers=WEB_HEADERS, timeout=60)
        resp.raise_for_status()
        table = pd.read_html(StringIO(resp.text), keep_default_na=False)[0]
        for _, r in table.iterrows():
            sym = str(r["Symbol"]).strip()
            if not sym or sym.lower() == "nan":
                continue
            rows.append({
                "ticker": sym,
                "company_name_web": str(r.get("Company Name", "")).strip(),
                "industry": industry,
                "market_cap": str(r.get("Market Cap", "")).strip(),
            })
        print(f"  {industry:<34} {len(table):>4} rows from {url}")
        time.sleep(0.4)

    df = pd.DataFrame(rows).drop_duplicates(subset="ticker", keep="first")
    return df.reset_index(drop=True)


ticker_df = scrape_industry_table()
print(f"\nUnique companies scraped: {len(ticker_df)}")

  Biotechnology                       500 rows from https://stockanalysis.com/stocks/industry/biotechnology/
  Biotechnology                        88 rows from https://stockanalysis.com/stocks/industry/biotechnology/?page=2
  Semiconductors                       70 rows from https://stockanalysis.com/stocks/industry/semiconductors/
  Internet Content And Information     70 rows from https://stockanalysis.com/stocks/industry/internet-content-and-information/
  Software Infrastructure             177 rows from https://stockanalysis.com/stocks/industry/software-infrastructure/

Unique companies scraped: 905

In [70]:
print("Companies per industry:")
print(ticker_df["industry"].value_counts().to_string())

Companies per industry:
industry
Biotechnology                       588
Software Infrastructure             177
Semiconductors                       70
Internet Content And Information     70

### All companies with their industry

In [71]:
# Show every company, not a truncated preview.
with pd.option_context("display.max_rows", None):
    display(ticker_df[["ticker", "company_name_web", "industry", "market_cap"]])

    ticker                                    company_name_web                          industry market_cap
0     VRTX                 Vertex Pharmaceuticals Incorporated                     Biotechnology    133.37B
1     MRNA                                       Moderna, Inc.                     Biotechnology     79.40B
2     REGN                     Regeneron Pharmaceuticals, Inc.                     Biotechnology     78.69B
3     ARGX                                           argenx SE                     Biotechnology     60.24B
4     RVMD                          Revolution Medicines, Inc.                     Biotechnology     43.93B
5      ONC                                  BeOne Medicines AG                     Biotechnology     41.03B
6     ALNY                       Alnylam Pharmaceuticals, Inc.                     Biotechnology     34.25B
7     RPRX                                  Royalty Pharma plc                     Biotechnology     33.47B
8     ROIV                               Roivant Sciences Ltd.                     Biotechnology     25.86B
9     INSM                                 Insmed Incorporated                     Biotechnology     25.73B
10    INCY                                  Incyte Corporation                     Biotechnology     25.11B
11    BNTX                                         BioNTech SE                     Biotechnology     24.75B
12    GMAB                                          Genmab A/S                     Biotechnology     20.74B
13    JAZZ                            Jazz Pharmaceuticals plc                     Biotechnology     15.45B
14    ASND                                 Ascendis Pharma A/S                     Biotechnology     14.82B
15    EXEL                                      Exelixis, Inc.                     Biotechnology     14.41B
16    HALO                         Halozyme Therapeutics, Inc.                     Biotechnology     12.93B
17    BBIO                              BridgeBio Pharma, Inc.                     Biotechnology     12.82B
18    CORT                   Corcept Therapeutics Incorporated                     Biotechnology     12.55B
19    SMMT                            Summit Therapeutics Inc.                     Biotechnology     12.45B
20    MDGL                      Madrigal Pharmaceuticals, Inc.                     Biotechnology     11.93B
21    BMRN                        BioMarin Pharmaceutical Inc.                     Biotechnology     11.66B
22    TWST                        Twist Bioscience Corporation                     Biotechnology     11.46B
23    TECH                              Bio-Techne Corporation                     Biotechnology     11.39B
24    KRYS                               Krystal Biotech, Inc.                     Biotechnology     10.24B
25    AXSM                           Axsome Therapeutics, Inc.                     Biotechnology     10.22B
26    ARWR                     Arrowhead Pharmaceuticals, Inc.                     Biotechnology      9.31B
27    KYMR                           Kymera Therapeutics, Inc.                     Biotechnology      9.31B
28    PTGX                      Protagonist Therapeutics, Inc.                     Biotechnology      9.18B
29     CAI                           Caris Life Sciences, Inc.                     Biotechnology      9.04B
30    CYTK                          Cytokinetics, Incorporated                     Biotechnology      8.99B
31    IBRX                                   ImmunityBio, Inc.                     Biotechnology      8.95B
32    PCVX                                       Vaxcyte, Inc.                     Biotechnology      8.36B
33    TGTX                               TG Therapeutics, Inc.                     Biotechnology      8.15B
34    ABVX                            ABIVAX SociÃ©tÃ© Anonyme                     Biotechnology      8.14B
35    PRAX                    Praxis Precision Medicines, Inc.                     Biotechnology      7.84B
36    SYRE                            Spyre Therapeutics, Inc.                     Biotechnology      7.56B
37    IONS                         Ionis Pharmaceuticals, Inc.                     Biotechnology      7.40B
38    IMVT                                    Immunovant, Inc.                     Biotechnology      6.88B
39    RYTM                        Rhythm Pharmaceuticals, Inc.                     Biotechnology      6.79B
40    BLTE                                     Belite Bio, Inc                     Biotechnology      6.74B
41    LGND                 Ligand Pharmaceuticals Incorporated                     Biotechnology      6.01B
42    CGON                                   CG Oncology, Inc.                     Biotechnology      5.95B
43    SRRK                    Scholar Rock Holding Corporation                     Biotechnology      5.92B
44    MIRM                         Mirum Pharmaceuticals, Inc.                     Biotechnology      5.82B
45    COGT                            Cogent Biosciences, Inc.                     Biotechnology      5.61B
46    TVTX                          Travere Therapeutics, Inc.                     Biotechnology      5.60B
47    ORKA                            Oruka Therapeutics, Inc.                     Biotechnology      5.59B
48    CRSP                              CRISPR Therapeutics AG                     Biotechnology      5.24B
49    PTCT                              PTC Therapeutics, Inc.                     Biotechnology      5.23B
50    ERAS                                        Erasca, Inc.                     Biotechnology      4.98B
51    IOVA                       Iovance Biotherapeutics, Inc.                     Biotechnology      4.98B
52    DNTH                         Dianthus Therapeutics, Inc.                     Biotechnology      4.95B
53    MANE                           Veradermics, Incorporated                     Biotechnology      4.87B
54    DFTX                         Definium Therapeutics, Inc.                     Biotechnology      4.86B
55    EWTX                         Edgewise Therapeutics, Inc.                     Biotechnology      4.27B
56    TNGX                            Tango Therapeutics, Inc.                     Biotechnology      4.20B
57    VKTX                           Viking Therapeutics, Inc.                     Biotechnology      4.15B
58    ABCL                            AbCellera Biologics Inc.                     Biotechnology      4.12B
59    CELC                                       Celcuity Inc.                     Biotechnology      3.89B
60    PBLS                           Parabilis Medicines, Inc.                     Biotechnology      3.85B
61    RLAY                            Relay Therapeutics, Inc.                     Biotechnology      3.83B
62     TLX                       Telix Pharmaceuticals Limited                     Biotechnology      3.79B
63    LEGN                          Legend Biotech Corporation                     Biotechnology      3.70B
64    XENE                          Xenon Pharmaceuticals Inc.                     Biotechnology      3.58B
65    ACAD                         Acadia Pharmaceuticals Inc.                     Biotechnology      3.56B
66    IDYA                            IDEAYA Biosciences, Inc.                     Biotechnology      3.54B
67    ARQT                       Arcutis Biotherapeutics, Inc.                     Biotechnology      3.38B
68    TARS                        Tarsus Pharmaceuticals, Inc.                     Biotechnology      3.32B
69    ELVN                          Enliven Therapeutics, Inc.                     Biotechnology      3.28B
70    DNLI                            Denali Therapeutics Inc.                     Biotechnology      3.26B
71    RCUS                             Arcus Biosciences, Inc.                     Biotechnology      3.18B
72     DYN                             Dyne Therapeutics, Inc.                     Biotechnology      2.99B
73    ZLAB                                     Zai Lab Limited                     Biotechnology      2.80B
74    PGEN                                      Precigen, Inc.                     Biotechnology      2.77B
75    NAMS                    NewAmsterdam Pharma Company N.V.                     Biotechnology      2.70B
76    QURE                                        uniQure N.V.                     Biotechnology      2.65B
77     MBX                               MBX Biosciences, Inc.                     Biotechnology      2.58B
78    GPCR                         Structure Therapeutics Inc.                     Biotechnology      2.56B
79    IRON                                 Disc Medicine, Inc.                     Biotechnology      2.50B
80    CLDX                          Celldex Therapeutics, Inc.                     Biotechnology      2.44B
81    IMNM                                      Immunome, Inc.                     Biotechnology      2.43B
82    BEAM                              Beam Therapeutics Inc.                     Biotechnology      2.43B
83    HRMY                  Harmony Biosciences Holdings, Inc.                     Biotechnology      2.40B
84    NRIX                            Nurix Therapeutics, Inc.                     Biotechnology      2.39B
85    VERA                             Vera Therapeutics, Inc.                     Biotechnology      2.34B
86     SLS                    SELLAS Life Sciences Group, Inc.                     Biotechnology      2.34B
87    VRDN                         Viridian Therapeutics, Inc.                     Biotechnology      2.32B
88    MLYS                        Mineralys Therapeutics, Inc.                     Biotechnology      2.29B
89    PHVS                                      Pharvaris N.V.                     Biotechnology      2.25B
90    AUPH                        Aurinia Pharmaceuticals Inc.                     Biotechnology      2.19B
91    OCUL                            Ocular Therapeutix, Inc.                     Biotechnology      2.12B
92    ADMA                                ADMA Biologics, Inc.                     Biotechnology      2.10B
93    ADRX                         ADARx Pharmaceuticals, Inc.                     Biotechnology      2.06B
94    TRVI                            Trevi Therapeutics, Inc.                     Biotechnology      2.05B
95    VCEL                                 Vericel Corporation                     Biotechnology      2.03B
96     KOD                                Kodiak Sciences Inc.                     Biotechnology      2.03B
97    URGN                                  UroGen Pharma Ltd.                     Biotechnology      2.02B
98    NUVB                                   Nuvation Bio Inc.                     Biotechnology      2.02B
99    RXRX                     Recursion Pharmaceuticals, Inc.                     Biotechnology      2.01B
100   PVLA                         Palvella Therapeutics, Inc.                     Biotechnology      1.99B
101   MRVI                 Maravai LifeSciences Holdings, Inc.                     Biotechnology      1.97B
102   SRPT                          Sarepta Therapeutics, Inc.                     Biotechnology      1.97B
103   MESO                                   Mesoblast Limited                     Biotechnology      1.97B
104   BHVN                                       Biohaven Ltd.                     Biotechnology      1.96B
105   NKTR                                 Nektar Therapeutics                     Biotechnology      1.95B
106   AGIO                         Agios Pharmaceuticals, Inc.                     Biotechnology      1.95B
107   GENB                         Generate Biomedicines, Inc.                     Biotechnology      1.94B
108   LKFT                        Lakefront Biotherapeutics NV                     Biotechnology      1.92B
109   FTRE                               Fortrea Holdings Inc.                     Biotechnology      1.89B
110   ZYME                                      Zymeworks Inc.                     Biotechnology      1.88B
111    VIR                             Vir Biotechnology, Inc.                     Biotechnology      1.80B
112   XNCR                                        Xencor, Inc.                     Biotechnology      1.77B
113   SEPN                                      Septerna, Inc.                     Biotechnology      1.76B
114   ZBIO                               Zenas BioPharma, Inc.                     Biotechnology      1.76B
115   NVAX                                       Novavax, Inc.                     Biotechnology      1.75B
116   NBTX                                     Nanobiotix S.A.                     Biotechnology      1.69B
117   ABSI                                   Absci Corporation                     Biotechnology      1.67B
118   NTLA                         Intellia Therapeutics, Inc.                     Biotechnology      1.65B
119   GHRS                                     GH Research PLC                     Biotechnology      1.64B
120   RAPP                          Rapport Therapeutics, Inc.                     Biotechnology      1.63B
121   SNDX                        Syndax Pharmaceuticals, Inc.                     Biotechnology      1.63B
122   COAG                   Hemab Therapeutics Holdings, Inc.                     Biotechnology      1.62B
123   STOK                            Stoke Therapeutics, Inc.                     Biotechnology      1.60B
124   IMCR                             Immunocore Holdings plc                     Biotechnology      1.58B
125   ANAB                                    AnaptysBio, Inc.                     Biotechnology      1.52B
126   TSHA                         Taysha Gene Therapies, Inc.                     Biotechnology      1.52B
127   INVA                                      Innoviva, Inc.                     Biotechnology      1.50B
128   TYRA                              Tyra Biosciences, Inc.                     Biotechnology      1.50B
129   INBX                           Inhibrx Biosciences, Inc.                     Biotechnology      1.47B
130   KLRA                          Kailera Therapeutics, Inc.                     Biotechnology      1.45B
131   OMER                                  Omeros Corporation                     Biotechnology      1.45B
132   MAZE                             Maze Therapeutics, Inc.                     Biotechnology      1.45B
133   RARE                      Ultragenyx Pharmaceutical Inc.                     Biotechnology      1.43B
134   KRSA                           Korsana Biosciences, Inc.                     Biotechnology      1.41B
135   AVBP                            ArriVent BioPharma, Inc.                     Biotechnology      1.40B
136   KARD                                      Kardigan, Inc.                     Biotechnology      1.38B
137   ORIC                          ORIC Pharmaceuticals, Inc.                     Biotechnology      1.36B
138   AAPG                Ascentage Pharma Group International                     Biotechnology      1.36B
139   BRVE                                Braveheart Bio, Inc.                     Biotechnology      1.35B
140   DRTS                              Alpha Tau Medical Ltd.                     Biotechnology      1.34B
141   DMRA                           Damora Therapeutics, Inc.                     Biotechnology      1.28B
142   BCAX                            Bicara Therapeutics Inc.                     Biotechnology      1.27B
143   SVRA                                         Savara Inc.                     Biotechnology      1.27B
144   AVLN                                  Avalyn Pharma Inc.                     Biotechnology      1.24B
145   TRAX                  First Tracks Biotherapeutics, Inc.                     Biotechnology      1.23B
146   LBRX                              LB Pharmaceuticals Inc                     Biotechnology      1.20B
147   REPL                               Replimune Group, Inc.                     Biotechnology      1.16B
148   SPTX                          Seaport Therapeutics, Inc.                     Biotechnology      1.15B
149   IMTX                                       Immatics N.V.                     Biotechnology      1.14B
150   LTGO                        Latigo Biotherapeutics, Inc.                     Biotechnology      1.14B
151    VOR                                  Vor Biopharma Inc.                     Biotechnology      1.10B
152   AKTS                                Aktis Oncology, Inc.                     Biotechnology      1.08B
153   MNKD                                MannKind Corporation                     Biotechnology      1.07B
154   MGTX                               MeiraGTx Holdings plc                     Biotechnology      1.05B
155   ANRO                             Alto Neuroscience, Inc.                     Biotechnology      1.04B
156   MLTX                         MoonLake Immunotherapeutics                     Biotechnology      1.02B
157   GLUE                       Monte Rosa Therapeutics, Inc.                     Biotechnology      1.00B
158    ANL                             Adlai Nortye Group Ltd.                     Biotechnology      1.00B
159   JANX                            Janux Therapeutics, Inc.                     Biotechnology    996.53M
160   ODTX                          Odyssey Therapeutics, Inc.                     Biotechnology    982.81M
161   CRVS                        Corvus Pharmaceuticals, Inc.                     Biotechnology    977.49M
162   ABUS                       Arbutus Biopharma Corporation                     Biotechnology    959.56M
163   KURA                                 Kura Oncology, Inc.                     Biotechnology    957.22M
164   CGEM                         Cullinan Therapeutics, Inc.                     Biotechnology    953.09M
165   HELP                                          Cybin Inc.                     Biotechnology    921.29M
166   ALMS                                         Alumis Inc.                     Biotechnology    918.99M
167   JBIO                              Jade Biosciences, Inc.                     Biotechnology    917.07M
168    SGP                               SpyGlass Pharma, Inc.                     Biotechnology    905.44M
169   RIGL                         Rigel Pharmaceuticals, Inc.                     Biotechnology    900.00M
170   SLBT                          SL Science Holding Limited                     Biotechnology    895.32M
171   SANA                            Sana Biotechnology, Inc.                     Biotechnology    881.62M
172   APMD                                       Apnimed, Inc.                     Biotechnology    877.99M
173   ARDX                                       Ardelyx, Inc.                     Biotechnology    852.22M
174   CADL                           Candel Therapeutics, Inc.                     Biotechnology    843.23M
175   AVTX                            Avalo Therapeutics, Inc.                     Biotechnology    829.66M
176   ATTO                          Attovia Therapeutics, Inc.                     Biotechnology    811.68M
177   GERN                                   Geron Corporation                     Biotechnology    809.52M
178   FDMT                     4D Molecular Therapeutics, Inc.                     Biotechnology    799.38M
179   LXRX                       Lexicon Pharmaceuticals, Inc.                     Biotechnology    798.70M
180    OBX                         Obsidian Therapeutics, Inc.                     Biotechnology    794.40M
181   IMMX                               Immix Biopharma, Inc.                     Biotechnology    784.79M
182   SLDB                              Solid Biosciences Inc.                     Biotechnology    781.67M
183   GYRE                             Gyre Therapeutics, Inc.                     Biotechnology    779.35M

## 2. Attach CIK and official SEC company name

`company_tickers.json` is SEC's own ticker → CIK map, so this is the authoritative link
between a ticker and its EDGAR filings.

In [72]:
def load_ticker_cik_map():
    r = requests.get("https://www.sec.gov/files/company_tickers.json",
                     headers=SEC_HEADERS, timeout=60)
    r.raise_for_status()
    return {v["ticker"].upper().strip(): (int(v["cik_str"]), v["title"])
            for v in r.json().values()}


ticker_to_cik = load_ticker_cik_map()
print(f"SEC ticker map entries: {len(ticker_to_cik):,}")

companies = ticker_df.copy()
companies["cik"] = companies["ticker"].str.upper().map(
    lambda t: ticker_to_cik.get(t, (None, None))[0])
companies["company_name"] = companies.apply(
    lambda r: ticker_to_cik.get(r["ticker"].upper(), (None, None))[1] or r["company_name_web"],
    axis=1)

print(f"Matched to a CIK: {companies['cik'].notna().sum()} / {len(companies)}")

SEC ticker map entries: 10,428
Matched to a CIK: 905 / 905

## 3. Build the usable universe

Each company's SEC *submissions* record carries its jurisdiction of incorporation, its
business address and its full filing history. These signals are computed from it:

| Column | Meaning |
|---|---|
| `n_10k_years` | distinct **fiscal years** covered by exact 10-K filings inside the 15-year window |
| `has_10k` | `n_10k_years > 0` |
| `is_fpi` | files foreign-private-issuer forms: 20-F, 40-F, 6-K, 20FR12B, 40FR12B or F-series |
| `foreign_incorporation` | `stateOfIncorporation` is not a US state/territory code (EDGAR uses codes like `E9` = Cayman Islands, `L3` = Israel, `P7` = Netherlands) |
| `foreign_address` | headquarters address is outside the US |

**A company is kept only if `n_10k_years >= 5`.** One rule covers both cuts: a foreign
private issuer has no 10-K so it scores 0, and a 2023 IPO scores 2 or 3. Both fail. This is
the condition the whole notebook depends on, since a company without 10-Ks has no
Item 1A / 2 / 7 to extract and a company with two of them is too short for panel work.

Fiscal years come from `reportDate` so they line up with the `fiscal_year` column the
extractor writes, `10-K/A` amendments are excluded so they cannot inflate a year count, and
only filings **inside the 15-year window** count — a company that filed 10-Ks in the 1990s
and then stopped scores 0, correctly.

Foreign *domicile* does **not** drop a company. Plenty of firms are incorporated in Ireland,
Bermuda, Switzerland, Cayman or British Columbia yet file ordinary 10-Ks — Jazz, Royalty
Pharma, Roivant, CRISPR, AbCellera, Zai Lab, Biohaven — and those 10-Ks are exactly as
extractable as a Delaware filer's.

> **History is counted against the full filing record.** The `recent` block of a submissions
> record holds only the latest ~1,000 filings, so a prolific filer's older 10-Ks can sit in
> paged files. Any company that looks short on history has those pages fetched and merged
> before it is dropped. Most companies have no extra pages, so this costs almost nothing.

> SEC asks for **no more than 10 requests/second**. The fetch below is throttled to ~8/s and
> retries anything that comes back empty — a rate-limited response must not be mistaken for
> "this company has no SEC record".

In [73]:
# EDGAR uses 2-letter codes for US states/territories and alphanumeric codes for elsewhere.
US_STATE_CODES = {
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI",
    "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN",
    "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
    "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA",
    "WV", "WI", "WY",
    "AS", "GU", "PR", "VI", "MP",   # US territories
    "X1",                            # EDGAR's "United States" catch-all
}

MIN_INTERVAL = 0.13          # ~7.7 requests/second
_throttle_lock = threading.Lock()
_last_call = [0.0]


def _throttle():
    """Global rate limiter shared by every SEC request in this notebook."""
    with _throttle_lock:
        wait = MIN_INTERVAL - (time.monotonic() - _last_call[0])
        if wait > 0:
            time.sleep(wait)
        _last_call[0] = time.monotonic()


def fetch_submission_meta(cik, session=None, retries=4):
    get = (session or requests).get
    url = f"https://data.sec.gov/submissions/CIK{int(cik):010d}.json"
    for attempt in range(retries):
        _throttle()
        try:
            r = get(url, headers=SEC_HEADERS, timeout=60)
            if r.status_code == 200:
                return r.json()
            if r.status_code == 404:
                return None
            time.sleep(1.0 + 2 * attempt)      # 403 = rate limited, back off
        except Exception:
            time.sleep(1.0 + 2 * attempt)
    return None


def tenk_years_from_block(block):
    """
    Distinct *fiscal* years covered by exact 10-K filings inside the window.

    `block` is a submissions `recent`-shaped dict of parallel arrays. Amendments are
    excluded (they duplicate a year), and the fiscal year comes from reportDate so it
    matches the `fiscal_year` column the extractor writes.
    """
    forms = block.get("form", []) or []
    filed = block.get("filingDate", []) or []
    reported = block.get("reportDate", []) or []

    years = set()
    for i, form in enumerate(forms):
        if form != "10-K":
            continue
        fdate = filed[i] if i < len(filed) else ""
        if not fdate[:4].isdigit() or int(fdate[:4]) < START_YEAR:
            continue
        rdate = reported[i] if i < len(reported) else ""
        years.add(int(rdate[:4]) if rdate[:4].isdigit() else int(fdate[:4]))
    return years


def classify_issuer(meta):
    """Turn a submissions JSON blob into foreign-issuer and filing-history signals."""
    if not meta:
        return {"sec_company_name": None, "entity_type": None,
                "state_of_incorporation": None, "incorporation_desc": None,
                "business_country": None, "business_country_desc": None,
                "has_10k": False, "has_20f_40f": False, "is_fpi": False,
                "n_10k_years": 0, "first_10k_fy": None, "last_10k_fy": None,
                "foreign_incorporation": False, "foreign_address": False,
                "domicile_note": "no SEC submissions record"}

    soi = (meta.get("stateOfIncorporation") or "").strip().upper()
    soi_desc = (meta.get("stateOfIncorporationDescription") or "").strip()
    addr = (meta.get("addresses") or {}).get("business") or {}
    biz = (addr.get("stateOrCountry") or "").strip().upper()
    biz_desc = (addr.get("stateOrCountryDescription") or "").strip()

    recent = meta.get("filings", {}).get("recent", {})
    forms = set(recent.get("form", []))
    tenk_years = tenk_years_from_block(recent)
    has_10k = bool(tenk_years)
    has_20f_40f = any(f.startswith(("20-F", "40-F")) for f in forms)

    # Foreign private issuers file 6-K instead of 8-K and register on 20FR12B / 40FR12B /
    # F-series. Matching only "20-F"/"40-F" misses an FPI that has registered but not yet
    # filed its first annual report (e.g. SK hynix, Clinuvel, Vicore, Gix, Bitzero).
    is_fpi = any(f.startswith(("20-F", "40-F", "6-K", "20FR", "40FR", "F-")) for f in forms)

    foreign_incorporation = bool(soi) and soi not in US_STATE_CODES
    foreign_address = bool(biz) and biz not in US_STATE_CODES

    notes = []
    if foreign_incorporation:
        notes.append(f"incorporated in {soi_desc or soi}")
    if foreign_address:
        notes.append(f"business address in {biz_desc or biz}")

    return {"sec_company_name": meta.get("name"), "entity_type": meta.get("entityType"),
            "state_of_incorporation": soi or None, "incorporation_desc": soi_desc or None,
            "business_country": biz or None, "business_country_desc": biz_desc or None,
            "has_10k": has_10k, "has_20f_40f": has_20f_40f, "is_fpi": is_fpi,
            "n_10k_years": len(tenk_years),
            "first_10k_fy": min(tenk_years) if tenk_years else None,
            "last_10k_fy": max(tenk_years) if tenk_years else None,
            "foreign_incorporation": foreign_incorporation,
            "foreign_address": foreign_address,
            "domicile_note": "; ".join(notes) or "US"}


def tenk_years_in_older_pages(meta, session=None):
    """
    `filings.recent` holds only the latest ~1,000 filings, so a prolific filer's older
    10-Ks can sit in paged files. Merge those years in before judging a company's history.
    """
    years = set()
    for page in (meta.get("filings", {}) or {}).get("files", []) or []:
        name = page.get("name")
        if not name:
            continue
        _throttle()
        try:
            r = (session or requests).get(f"https://data.sec.gov/submissions/{name}",
                                          headers=SEC_HEADERS, timeout=60)
            if r.status_code == 200:
                years |= tenk_years_from_block(r.json())
        except Exception:
            continue
    return years

In [74]:
def add_foreign_flags(companies, max_workers=4):
    known = companies[companies["cik"].notna()]
    ciks = known["cik"].astype(int).tolist()
    print(f"Fetching SEC metadata for {len(ciks)} CIKs "
          f"(~{len(ciks) * MIN_INTERVAL:.0f}s at {1 / MIN_INTERVAL:.0f} req/s) ...")

    session = requests.Session()
    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        metas = list(pool.map(lambda c: fetch_submission_meta(c, session=session), ciks))

    # Retry empties — these are almost always transient rate limiting.
    retry_idx = [i for i, m in enumerate(metas) if m is None]
    if retry_idx:
        print(f"  retrying {len(retry_idx)} CIKs that returned nothing ...")
        for i in retry_idx:
            metas[i] = fetch_submission_meta(ciks[i], session=session, retries=5)
        still = sum(1 for i in retry_idx if metas[i] is None)
        print(f"  {len(retry_idx) - still} recovered, {still} genuinely missing")

    classified = [classify_issuer(m) for m in metas]

    # The `recent` block truncates hard — Vertex shows 6 years there but has filed 16.
    # So every company with older pages gets them merged, not just ones that look short,
    # otherwise n_10k_years is wrong for most established filers.
    recheck = [i for i, _ in enumerate(classified)
               if (metas[i] or {}).get("filings", {}).get("files")]
    if recheck:
        print(f"  merging older filing pages for {len(recheck)} companies "
              "(the recent block only holds ~1,000 filings) ...")
        recovered = 0
        for i in recheck:
            extra = tenk_years_in_older_pages(metas[i], session=session)
            if not extra:
                continue
            recent_block = (metas[i] or {}).get("filings", {}).get("recent", {})
            merged = tenk_years_from_block(recent_block) | extra
            if len(merged) > classified[i]["n_10k_years"]:
                recovered += 1
            classified[i].update(has_10k=bool(merged), n_10k_years=len(merged),
                                 first_10k_fy=min(merged) if merged else None,
                                 last_10k_fy=max(merged) if merged else None)
        print(f"  {recovered} gained additional years from older pages")

    flags = pd.DataFrame(classified, index=known.index)
    out = companies.join(flags)

    missing = out["cik"].isna()
    out.loc[missing, "domicile_note"] = "ticker not found in SEC ticker map"
    for col in ["has_10k", "has_20f_40f", "is_fpi",
                "foreign_incorporation", "foreign_address"]:
        out[col] = out[col].fillna(False).astype(bool)
    out["n_10k_years"] = out["n_10k_years"].fillna(0).astype(int)
    out["domicile_note"] = out["domicile_note"].fillna("")
    return out


companies = add_foreign_flags(companies)
print("\nDone.")

Fetching SEC metadata for 905 CIKs (~118s at 8 req/s) ...
  merging older filing pages for 185 companies (the recent block only holds ~1,000 filings) ...
  115 gained additional years from older pages

Done.

### The companies being dropped

Split by *why* they fail, so the foreign issuers stay visible as a group and the
short-history cut is separated from the no-10-K-at-all cut.

In [75]:
companies["keeps"] = companies["n_10k_years"] >= MIN_10K_YEARS
dropped = companies[~companies["keeps"]].copy()

def drop_reason(r):
    if not r["has_10k"]:
        if r["has_20f_40f"]:
            return "no 10-K - foreign private issuer (files 20-F/40-F)"
        if r["is_fpi"]:
            return "no 10-K - foreign private issuer (6-K / 20FR / 40FR / F-series)"
        return "no 10-K - recent IPO / shell"
    return f"only {r['n_10k_years']} year(s) of 10-K history"

dropped["drop_reason"] = dropped.apply(drop_reason, axis=1)

print(f"Companies dropped: {len(dropped)}\n")
print("  no 10-K at all                  :", int((~dropped["has_10k"]).sum()))
print(f"  has 10-Ks but < {MIN_10K_YEARS} years       :", int(dropped["has_10k"].sum()))
print(f"  (of all dropped, foreign issuers: {int(dropped['is_fpi'].sum())})")

print("\nYears of history among those dropped for short history:")
print(dropped[dropped["has_10k"]]["n_10k_years"].value_counts().sort_index().to_string())

print("\nBy industry:")
print(dropped["industry"].value_counts().to_string())

Companies dropped: 313

  no 10-K at all                  : 200
  has 10-Ks but < 5 years       : 113
  (of all dropped, foreign issuers: 187)

Years of history among those dropped for short history:
n_10k_years
1    22
2    36
3    32
4    23

By industry:
industry
Biotechnology                       182
Software Infrastructure              73
Internet Content And Information     37
Semiconductors                       21

In [76]:
with pd.option_context("display.max_rows", None, "display.max_colwidth", 55):
    display(dropped[["ticker", "company_name", "industry", "incorporation_desc",
                     "n_10k_years", "first_10k_fy", "last_10k_fy", "drop_reason"]]
            .reset_index(drop=True))

    ticker                               company_name                          industry        incorporation_desc  n_10k_years  first_10k_fy  last_10k_fy                                             drop_reason
0     ARGX                                  ARGENX SE                     Biotechnology               Netherlands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
1     BNTX                                BioNTech SE                     Biotechnology                   Germany            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
2     GMAB                                 GENMAB A/S                     Biotechnology                      None            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
3     ASND                        Ascendis Pharma A/S                     Biotechnology                   Denmark            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
4      CAI                  Caris Life Sciences, Inc.                     Biotechnology                        TX            1        2025.0       2025.0                          only 1 year(s) of 10-K history
5     ABVX                                Abivax S.A.                     Biotechnology                    France            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
6     BLTE                            BELITE BIO, INC                     Biotechnology            Cayman Islands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
7     CGON                          CG Oncology, Inc.                     Biotechnology                        DE            3        2023.0       2025.0                          only 3 year(s) of 10-K history
8     MANE                           Veradermics, Inc                     Biotechnology                        DE            1        2025.0       2025.0                          only 1 year(s) of 10-K history
9     PBLS                  Parabilis Medicines, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
10     TLX                  Telix Pharmaceuticals Ltd                     Biotechnology                 Australia            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
11    LEGN                        Legend Biotech Corp                     Biotechnology            Cayman Islands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
12    NAMS                NewAmsterdam Pharma Co N.V.                     Biotechnology               Netherlands            3        2023.0       2025.0                          only 3 year(s) of 10-K history
13     MBX                      MBX Biosciences, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
14    GPCR                Structure Therapeutics Inc.                     Biotechnology            Cayman Islands            4        2022.0       2025.0                          only 4 year(s) of 10-K history
15    MLYS               Mineralys Therapeutics, Inc.                     Biotechnology                      None            4        2022.0       2025.0                          only 4 year(s) of 10-K history
16    PHVS                             Pharvaris N.V.                     Biotechnology               Netherlands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
17    ADRX                ADARx Pharmaceuticals, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
18    MESO                              MESOBLAST LTD                     Biotechnology                 Australia            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
19    BHVN                              Biohaven Ltd.                     Biotechnology   Virgin Islands, British            4        2022.0       2025.0                          only 4 year(s) of 10-K history
20    GENB                Generate Biomedicines, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
21    LKFT               Lakefront Biotherapeutics NV                     Biotechnology                   Belgium            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
22    FTRE                      Fortrea Holdings Inc.                     Biotechnology                      None            3        2023.0       2025.0                          only 3 year(s) of 10-K history
23    ZYME                             Zymeworks Inc.                     Biotechnology                        DE            4        2022.0       2025.0                          only 4 year(s) of 10-K history
24    SEPN                             Septerna, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
25    ZBIO                      Zenas BioPharma, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
26    NBTX                            Nanobiotix S.A.                     Biotechnology                    France            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
27    GHRS                            GH Research PLC                     Biotechnology                   Ireland            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
28    RAPP                 Rapport Therapeutics, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
29    COAG          Hemab Therapeutics Holdings, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
30    IMCR                    Immunocore Holdings plc                     Biotechnology            United Kingdom            3        2023.0       2025.0                          only 3 year(s) of 10-K history
31    INBX                  Inhibrx Biosciences, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
32    KLRA                 Kailera Therapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
33    MAZE                    Maze Therapeutics, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
34    AVBP                   ArriVent BioPharma, Inc.                     Biotechnology                        DE            3        2023.0       2025.0                          only 3 year(s) of 10-K history
35    KARD                             Kardigan, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
36    AAPG       ASCENTAGE PHARMA GROUP INTERNATIONAL                     Biotechnology            Cayman Islands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
37    BRVE                       Braveheart Bio, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
38    DRTS                     Alpha Tau Medical Ltd.                     Biotechnology                    Israel            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
39    BCAX                   Bicara Therapeutics Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
40    AVLN                         Avalyn Pharma Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
41    TRAX         First Tracks Biotherapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
42    LBRX                     LB PHARMACEUTICALS INC                     Biotechnology                        DE            1        2025.0       2025.0                          only 1 year(s) of 10-K history
43    SPTX                 Seaport Therapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
44    IMTX                              Immatics N.V.                     Biotechnology               Netherlands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
45    LTGO               Latigo Biotherapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
46    AKTS                       Aktis Oncology, Inc.                     Biotechnology                        DE            1        2025.0       2025.0                          only 1 year(s) of 10-K history
47    ANRO                    Alto Neuroscience, Inc.                     Biotechnology                        DE            3        2023.0       2025.0                          only 3 year(s) of 10-K history
48     ANL                    Adlai Nortye Group Ltd.                     Biotechnology                        DE            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
49    ODTX                 Odyssey Therapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
50    HELP                                 CYBIN INC.                     Biotechnology           Ontario, Canada            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
51    ALMS                                ALUMIS INC.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
52     SGP                      SpyGlass Pharma, Inc.                     Biotechnology                        DE            1        2025.0       2025.0                          only 1 year(s) of 10-K history
53    SLBT                     SL Science Holding Ltd                     Biotechnology            Cayman Islands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
54    APMD                              Apnimed, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
55    ATTO                 Attovia Therapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
56     OBX                Obsidian Therapeutics, Inc.                     Biotechnology                      None            0           NaN          NaN                            no 10-K - recent IPO / shell
57     IVA                             Inventiva S.A.                     Biotechnology                    France            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
58    PHAR                        Pharming Group N.V.                     Biotechnology               Netherlands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
59    ETRA                 Electra Therapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
60     SLN                   Silence Therapeutics plc                     Biotechnology            United Kingdom            2        2024.0       2025.0                          only 2 year(s) of 10-K history
61    BLSM             BlossomHill Therapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
62    MPLT                MapLight Therapeutics, Inc.                     Biotechnology                        DE            1        2025.0       2025.0                          only 1 year(s) of 10-K history
63    VALN                                 Valneva SE                     Biotechnology                    France            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
64    SGMT                   Sagimet Biosciences Inc.                     Biotechnology                        DE            3        2023.0       2025.0                          only 3 year(s) of 10-K history
65     OCS                          Oculis Holding AG                     Biotechnology               Switzerland            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
66    EPRX              EUPRAXIA PHARMACEUTICALS INC.                     Biotechnology  British Columbia, Canada            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
67    AGMB                     AgomAb Therapeutics NV                     Biotechnology                   Belgium            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
68    PRME                       Prime Medicine, Inc.                     Biotechnology                        DE            4        2022.0       2025.0                          only 4 year(s) of 10-K history
69    DRUG              BRIGHT MINDS BIOSCIENCES INC.                     Biotechnology  British Columbia, Canada            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
70    AUTL                   Autolus Therapeutics plc                     Biotechnology            United Kingdom            3        2023.0       2025.0                          only 3 year(s) of 10-K history
71    CTNM               Contineum Therapeutics, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
72    EIKN                   Eikon Therapeutics, Inc.                     Biotechnology                        DE            1        2025.0       2025.0                          only 1 year(s) of 10-K history
73    KYTX                 Kyverna Therapeutics, Inc.                     Biotechnology                        DE            3        2023.0       2025.0                          only 3 year(s) of 10-K history
74    YDES                                 YD Bio Ltd                     Biotechnology            Cayman Islands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
75    SCTX                  Scribe Therapeutics, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
76    TTRX                     Turn Therapeutics Inc.                     Biotechnology                        DE            1        2025.0       2025.0                          only 1 year(s) of 10-K history
77    ARTV               Artiva Biotherapeutics, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
78    VOGX                               Vogenx, Inc.                     Biotechnology                        DE            0           NaN          NaN                            no 10-K - recent IPO / shell
79    BBOT      BridgeBio Oncology Therapeutics, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
80    EVMN                             Evommune, Inc.                     Biotechnology                        DE            1        2025.0       2025.0                          only 1 year(s) of 10-K history
81     UPB                         Upstream Bio, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
82    CUVL               Clinuvel Pharmaceuticals Ltd                     Biotechnology                 Australia            0           NaN          NaN  no 10-K - foreign private issuer (6-K / 20FR / 40FR...
83    IFRX                               InflaRx N.V.                     Biotechnology               Netherlands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
84    VCRE                   Vicore Pharma Holding AB                     Biotechnology                    Sweden            0           NaN          NaN  no 10-K - foreign private issuer (6-K / 20FR / 40FR...
85    LXEO                   Lexeo Therapeutics, Inc.                     Biotechnology                      None            3        2023.0       2025.0                          only 3 year(s) of 10-K history
86    ACIU                               AC Immune SA                     Biotechnology               Switzerland            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
87    CAMP                    Camp4 Therapeutics Corp                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
88    SION                  Sionna Therapeutics, Inc.                     Biotechnology                        DE            2        2024.0       2025.0                          only 2 year(s) of 10-K history
89    PRQR                    ProQR Therapeutics N.V.                     Biotechnology               Netherlands            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
90    CGEN                               COMPUGEN LTD                     Biotechnology                    Israel            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
91    SLGL                  Sol-Gel Technologies Ltd.                     Biotechnology                    Israel            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
92    NGEN                       NERVGEN PHARMA CORP.                     Biotechnology  British Columbia, Canada            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)
93    VRXA           Veraxa Biotech AG - Post de-SPAC                     Biotechnology               Switzerland            0           NaN          NaN      no 10-K - foreign private issuer (files 20-F/40-F)

### Foreign-domiciled companies that are *kept*

These are incorporated or headquartered abroad but file ordinary 10-Ks, so their
Item 1A / 2 / 7 sections are extractable and they stay in the universe.

In [77]:
kept_foreign = companies[companies["keeps"] &
                         (companies["foreign_incorporation"] | companies["foreign_address"])]

print(f"Foreign-domiciled but retained (they file 10-Ks): {len(kept_foreign)}")
with pd.option_context("display.max_rows", None, "display.max_colwidth", 55):
    display(kept_foreign[["ticker", "company_name", "industry", "incorporation_desc",
                          "business_country_desc", "has_10k", "domicile_note"]]
            .reset_index(drop=True))

Foreign-domiciled but retained (they file 10-Ks): 33

   ticker                        company_name                 industry        incorporation_desc     business_country_desc  has_10k                                           domicile_note
0    RPRX                  Royalty Pharma plc            Biotechnology            United Kingdom                        NY     True                          incorporated in United Kingdom
1    ROIV               Roivant Sciences Ltd.            Biotechnology                   Bermuda                      None     True                                 incorporated in Bermuda
2    JAZZ            Jazz Pharmaceuticals plc            Biotechnology                   Ireland                      None     True                                 incorporated in Ireland
3    CRSP              CRISPR Therapeutics AG            Biotechnology               Switzerland                      None     True                             incorporated in Switzerland
4    DFTX         Definium Therapeutics, Inc.            Biotechnology  British Columbia, Canada                        NY     True                incorporated in British Columbia, Canada
5    ABCL            AbCellera Biologics Inc.            Biotechnology  British Columbia, Canada  British Columbia, Canada     True  incorporated in British Columbia, Canada; business ...
6    XENE          Xenon Pharmaceuticals Inc.            Biotechnology  British Columbia, Canada                      None     True                incorporated in British Columbia, Canada
7    ZLAB                         Zai Lab Ltd            Biotechnology            Cayman Islands                      None     True                          incorporated in Cayman Islands
8    AUPH        Aurinia Pharmaceuticals Inc.            Biotechnology                      None           Alberta, Canada     True                     business address in Alberta, Canada
9    URGN                  UroGen Pharma Ltd.            Biotechnology                    Israel                    Israel     True      incorporated in Israel; business address in Israel
10   MLTX         MoonLake Immunotherapeutics            Biotechnology            Cayman Islands               Switzerland     True  incorporated in Cayman Islands; business address in...
11   ABUS              Arbutus Biopharma Corp            Biotechnology  British Columbia, Canada                        PA     True                incorporated in British Columbia, Canada
12   DBVT               DBV Technologies S.A.            Biotechnology                    France                      None     True                                  incorporated in France
13   CBIO            CRESCENT BIOPHARMA, INC.            Biotechnology            Cayman Islands                        MA     True                          incorporated in Cayman Islands
14   PROK                     PROKIDNEY CORP.            Biotechnology            Cayman Islands                        NC     True                          incorporated in Cayman Islands
15   ENTX                     Entera Bio Ltd.            Biotechnology                    Israel                      None     True                                  incorporated in Israel
16   DMAC         DiaMedica Therapeutics Inc.            Biotechnology    Canada (Federal Level)                        MN     True                  incorporated in Canada (Federal Level)
17   PRTA         PROTHENA CORP PUBLIC LTD CO            Biotechnology                   Ireland                   Ireland     True    incorporated in Ireland; business address in Ireland
18   ZURA                        Zura Bio Ltd            Biotechnology            Cayman Islands                        CA     True                          incorporated in Cayman Islands
19   FENC         FENNEC PHARMACEUTICALS INC.            Biotechnology  British Columbia, Canada                        NC     True                incorporated in British Columbia, Canada
20   BCYC            BICYCLE THERAPEUTICS PLC            Biotechnology            United Kingdom            United Kingdom     True  incorporated in United Kingdom; business address in...
21   MIST      Milestone Pharmaceuticals Inc.            Biotechnology            Quebec, Canada            Quebec, Canada     True  incorporated in Quebec, Canada; business address in...
22   XBIT                       XBiotech Inc.            Biotechnology  British Columbia, Canada                        TX     True                incorporated in British Columbia, Canada
23   EDSA                 Edesa Biotech, Inc.            Biotechnology  British Columbia, Canada                      None     True                incorporated in British Columbia, Canada
24   AKTX              Akari Therapeutics Plc            Biotechnology            United Kingdom                        FL     True                          incorporated in United Kingdom
25   LEXX            Lexaria Bioscience Corp.            Biotechnology                        NV  British Columbia, Canada     True            business address in British Columbia, Canada
26   PPCB             Propanc Biopharma, Inc.            Biotechnology                        DE                 Australia     True                           business address in Australia
27   CRDO  Credo Technology Group Holding Ltd           Semiconductors            Cayman Islands            Cayman Islands     True  incorporated in Cayman Islands; business address in...
28   LEDS                       SemiLEDs Corp           Semiconductors                      None                    Taiwan     True                              business address in Taiwan
29     BB                      BLACKBERRY Ltd  Software Infrastructure                      None           Ontario, Canada     True                     business address in Ontario, Canada
30    TCX                     TUCOWS INC /PA/  Software Infrastructure                        PA           Ontario, Canada     True                     business address in Ontario, Canada
31    AVX            AVAX ONE TECHNOLOGY LTD.  Software Infrastructure  British Columbia, Canada                        FL     True                incorporated in British Columbia, Canada
32    DRK         DarkHorse Technologies Inc.  Software Infrastructure  British Columbia, Canada                        DE     True                incorporated in British Columbia, Canada

### Drop them and count what is left

In [78]:
universe = companies[companies["keeps"]].reset_index(drop=True)

no_10k = int((~companies["has_10k"]).sum())
short = int((companies["has_10k"] & ~companies["keeps"]).sum())

print(f"Total companies scraped          : {len(companies)}")
print(f"Dropped - no 10-K                : {no_10k}")
print(f"Dropped - < {MIN_10K_YEARS} years of history   : {short}")
print(f"Companies remaining              : {len(universe)}")

print("\nRemaining companies per industry:")
print(universe["industry"].value_counts().to_string())

n_foreign_kept = int((universe["foreign_incorporation"] | universe["foreign_address"]).sum())
print(f"\nOf those {len(universe)}, {n_foreign_kept} are foreign-domiciled 10-K filers "
      "that are deliberately retained.")

print("\nYears of 10-K history in the remaining universe:")
print(universe["n_10k_years"].describe()[["min", "25%", "50%", "75%", "max"]].to_string())
print("\nDistribution:")
print(universe["n_10k_years"].value_counts().sort_index().to_string())

assert universe["has_10k"].all(), "every remaining company must file 10-Ks"
assert (universe["n_10k_years"] >= MIN_10K_YEARS).all(), \
    f"every remaining company must have >= {MIN_10K_YEARS} years of 10-K history"
print(f"\nVerified: all {len(universe)} remaining companies file 10-Ks and have at least "
      f"{MIN_10K_YEARS} fiscal years of history since {START_YEAR}.")

Total companies scraped          : 905
Dropped - no 10-K                : 200
Dropped - < 5 years of history   : 113
Companies remaining              : 592

Remaining companies per industry:
industry
Biotechnology                       406
Software Infrastructure             104
Semiconductors                       49
Internet Content And Information     33

Of those 592, 33 are foreign-domiciled 10-K filers that are deliberately retained.

Years of 10-K history in the remaining universe:
min     5.0
25%     6.0
50%     9.0
75%    15.0
max    16.0

Distribution:
n_10k_years
5     101
6      85
7      43
8      34
9      34
10     26
11     25
12     31
13     25
14     14
15     39
16    135

Verified: all 592 remaining companies file 10-Ks and have at least 5 fiscal years of history since 2011.

In [79]:
with pd.option_context("display.max_rows", None):
    display(universe[["ticker", "company_name", "industry", "cik", "market_cap",
                      "n_10k_years", "first_10k_fy", "last_10k_fy", "domicile_note"]])

    ticker                                company_name                          industry      cik market_cap  n_10k_years  first_10k_fy  last_10k_fy                                                domicile_note
0     VRTX             VERTEX PHARMACEUTICALS INC / MA                     Biotechnology   875320    133.37B           16        2010.0       2025.0                                                           US
1     MRNA                               Moderna, Inc.                     Biotechnology  1682852     79.40B            8        2018.0       2025.0                                                           US
2     REGN             REGENERON PHARMACEUTICALS, INC.                     Biotechnology   872589     78.69B           16        2010.0       2025.0                                                           US
3     RVMD                  Revolution Medicines, Inc.                     Biotechnology  1628171     43.93B            7        2019.0       2025.0                                                           US
4      ONC                        BeOne Medicines Ltd.                     Biotechnology  1651308     41.03B           11        2015.0       2025.0                                                           US
5     ALNY               ALNYLAM PHARMACEUTICALS, INC.                     Biotechnology  1178670     34.25B           16        2010.0       2025.0                                                           US
6     RPRX                          Royalty Pharma plc                     Biotechnology  1802768     33.47B            6        2020.0       2025.0                               incorporated in United Kingdom
7     ROIV                       Roivant Sciences Ltd.                     Biotechnology  1635088     25.86B            5        2022.0       2026.0                                      incorporated in Bermuda
8     INSM                                  INSMED Inc                     Biotechnology  1104506     25.73B           16        2010.0       2025.0                                                           US
9     INCY                                 INCYTE CORP                     Biotechnology   879169     25.11B           16        2010.0       2025.0                                                           US
10    JAZZ                    Jazz Pharmaceuticals plc                     Biotechnology  1232524     15.45B           16        2010.0       2025.0                                      incorporated in Ireland
11    EXEL                              EXELIXIS, INC.                     Biotechnology   939767     14.41B           14        2010.0       2026.0                                                           US
12    HALO                 HALOZYME THERAPEUTICS, INC.                     Biotechnology  1159036     12.93B           16        2010.0       2025.0                                                           US
13    BBIO                      BridgeBio Pharma, Inc.                     Biotechnology  1743881     12.82B            7        2019.0       2025.0                                                           US
14    CORT                    CORCEPT THERAPEUTICS INC                     Biotechnology  1088856     12.55B           16        2010.0       2025.0                                                           US
15    SMMT                    Summit Therapeutics Inc.                     Biotechnology  1599298     12.45B            6        2020.0       2025.0                                                           US
16    MDGL              MADRIGAL PHARMACEUTICALS, INC.                     Biotechnology  1157601     11.93B           16        2010.0       2025.0                                                           US
17    BMRN                 BIOMARIN PHARMACEUTICAL INC                     Biotechnology  1048477     11.66B           16        2010.0       2025.0                                                           US
18    TWST                       Twist Bioscience Corp                     Biotechnology  1581280     11.46B            8        2018.0       2025.0                                                           US
19    TECH                             BIO-TECHNE Corp                     Biotechnology   842023     11.39B           16        2011.0       2026.0                                                           US
20    KRYS                       Krystal Biotech, Inc.                     Biotechnology  1711279     10.24B            9        2017.0       2025.0                                                           US
21    AXSM                   Axsome Therapeutics, Inc.                     Biotechnology  1579428     10.22B           11        2015.0       2025.0                                                           US
22    ARWR             ARROWHEAD PHARMACEUTICALS, INC.                     Biotechnology   879407      9.31B           15        2011.0       2025.0                                                           US
23    KYMR                   Kymera Therapeutics, Inc.                     Biotechnology  1815442      9.31B            6        2020.0       2025.0                                                           US
24    PTGX               Protagonist Therapeutics, Inc                     Biotechnology  1377121      9.18B           10        2016.0       2025.0                                                           US
25    CYTK                            CYTOKINETICS INC                     Biotechnology  1061983      8.99B           16        2010.0       2025.0                                                           US
26    IBRX                           ImmunityBio, Inc.                     Biotechnology  1326110      8.95B           11        2015.0       2025.0                                                           US
27    PCVX                               Vaxcyte, Inc.                     Biotechnology  1649094      8.36B            6        2020.0       2025.0                                                           US
28    TGTX                       TG THERAPEUTICS, INC.                     Biotechnology  1001316      8.15B           16        2010.0       2025.0                                                           US
29    PRAX            Praxis Precision Medicines, Inc.                     Biotechnology  1689548      7.84B            6        2020.0       2025.0                                                           US
30    SYRE                    Spyre Therapeutics, Inc.                     Biotechnology  1636282      7.56B           10        2016.0       2025.0                                                           US
31    IONS                   IONIS PHARMACEUTICALS INC                     Biotechnology   874015      7.40B           16        2010.0       2025.0                                                           US
32    IMVT                            Immunovant, Inc.                     Biotechnology  1764013      6.88B            7        2020.0       2026.0                                                           US
33    RYTM                RHYTHM PHARMACEUTICALS, INC.                     Biotechnology  1649904      6.79B            9        2017.0       2025.0                                                           US
34    LGND                  LIGAND PHARMACEUTICALS INC                     Biotechnology   886163      6.01B           16        2010.0       2025.0                                                           US
35    SRRK                   Scholar Rock Holding Corp                     Biotechnology  1727196      5.92B            8        2018.0       2025.0                                                           US
36    MIRM                 Mirum Pharmaceuticals, Inc.                     Biotechnology  1759425      5.82B            7        2019.0       2025.0                                                           US
37    COGT                    Cogent Biosciences, Inc.                     Biotechnology  1622229      5.61B            8        2018.0       2025.0                                                           US
38    TVTX                  Travere Therapeutics, Inc.                     Biotechnology  1438533      5.60B           15        2011.0       2025.0                                                           US
39    ORKA                    Oruka Therapeutics, Inc.                     Biotechnology   907654      5.59B           16        2010.0       2025.0                                                           US
40    CRSP                      CRISPR Therapeutics AG                     Biotechnology  1674416      5.24B           10        2016.0       2025.0                                  incorporated in Switzerland
41    PTCT                      PTC THERAPEUTICS, INC.                     Biotechnology  1070081      5.23B           13        2013.0       2025.0                                                           US
42    ERAS                                Erasca, Inc.                     Biotechnology  1761918      4.98B            5        2021.0       2025.0                                                           US
43    IOVA               IOVANCE BIOTHERAPEUTICS, INC.                     Biotechnology  1425205      4.98B           16        2010.0       2025.0                                                           US
44    DNTH            Dianthus Therapeutics, Inc. /DE/                     Biotechnology  1690585      4.95B            8        2018.0       2025.0                                                           US
45    DFTX                 Definium Therapeutics, Inc.                     Biotechnology  1813814      4.86B            5        2021.0       2025.0                     incorporated in British Columbia, Canada
46    EWTX                 Edgewise Therapeutics, Inc.                     Biotechnology  1710072      4.27B            5        2021.0       2025.0                                                           US
47    TNGX                    Tango Therapeutics, Inc.                     Biotechnology  1819133      4.20B            6        2020.0       2025.0                                                           US
48    VKTX                   Viking Therapeutics, Inc.                     Biotechnology  1607678      4.15B           11        2015.0       2025.0                                                           US
49    ABCL                    AbCellera Biologics Inc.                     Biotechnology  1703057      4.12B            6        2020.0       2025.0  incorporated in British Columbia, Canada; business addre...
50    CELC                               Celcuity Inc.                     Biotechnology  1603454      3.89B            9        2017.0       2025.0                                                           US
51    RLAY                    Relay Therapeutics, Inc.                     Biotechnology  1812364      3.83B            6        2020.0       2025.0                                                           US
52    XENE                  Xenon Pharmaceuticals Inc.                     Biotechnology  1582313      3.58B           12        2014.0       2025.0                     incorporated in British Columbia, Canada
53    ACAD                  ACADIA PHARMACEUTICALS INC                     Biotechnology  1070494      3.56B           16        2010.0       2025.0                                                           US
54    IDYA                    IDEAYA Biosciences, Inc.                     Biotechnology  1676725      3.54B            7        2019.0       2025.0                                                           US
55    ARQT               Arcutis Biotherapeutics, Inc.                     Biotechnology  1787306      3.38B            7        2019.0       2025.0                                                           US
56    TARS                Tarsus Pharmaceuticals, Inc.                     Biotechnology  1819790      3.32B            6        2020.0       2025.0                                                           US
57    ELVN                  Enliven Therapeutics, Inc.                     Biotechnology  1672619      3.28B            6        2020.0       2025.0                                                           US
58    DNLI                    Denali Therapeutics Inc.                     Biotechnology  1714899      3.26B            9        2017.0       2025.0                                                           US
59    RCUS                     Arcus Biosciences, Inc.                     Biotechnology  1724521      3.18B            8        2018.0       2025.0                                                           US
60     DYN                     Dyne Therapeutics, Inc.                     Biotechnology  1818794      2.99B            6        2020.0       2025.0                                                           US
61    ZLAB                                 Zai Lab Ltd                     Biotechnology  1704292      2.80B            6        2020.0       2025.0                               incorporated in Cayman Islands
62    PGEN                              PRECIGEN, INC.                     Biotechnology  1356090      2.77B           13        2013.0       2025.0                                                           US
63    QURE                                uniQure N.V.                     Biotechnology  1590560      2.65B           10        2016.0       2025.0                                                           US
64    IRON                         Disc Medicine, Inc.                     Biotechnology  1816736      2.50B            6        2020.0       2025.0                                                           US
65    CLDX                  Celldex Therapeutics, Inc.                     Biotechnology   744218      2.44B           16        2010.0       2025.0                                                           US
66    IMNM                               Immunome Inc.                     Biotechnology  1472012      2.43B            6        2020.0       2025.0                                                           US
67    BEAM                      Beam Therapeutics Inc.                     Biotechnology  1745999      2.43B            7        2019.0       2025.0                                                           US
68    HRMY          Harmony Biosciences Holdings, Inc.                     Biotechnology  1802665      2.40B            6        2020.0       2025.0                                                           US
69    NRIX                    Nurix Therapeutics, Inc.                     Biotechnology  1549595      2.39B            6        2020.0       2025.0                                                           US
70    VERA                     Vera Therapeutics, Inc.                     Biotechnology  1831828      2.34B            5        2021.0       2025.0                                                           US
71     SLS            SELLAS Life Sciences Group, Inc.                     Biotechnology  1390478      2.34B           16        2010.0       2025.0                                                           US
72    VRDN              Viridian Therapeutics, Inc.\DE                     Biotechnology  1590750      2.32B           12        2014.0       2025.0                                                           US
73    AUPH                Aurinia Pharmaceuticals Inc.                     Biotechnology  1600620      2.19B            6        2020.0       2025.0                          business address in Alberta, Canada
74    OCUL                     OCULAR THERAPEUTIX, INC                     Biotechnology  1393434      2.12B           12        2014.0       2025.0                                                           US
75    ADMA                        ADMA BIOLOGICS, INC.                     Biotechnology  1368514      2.10B           15        2011.0       2025.0                                                           US
76    TRVI                    Trevi Therapeutics, Inc.                     Biotechnology  1563880      2.05B            7        2019.0       2025.0                                                           US
77    VCEL                                Vericel Corp                     Biotechnology   887359      2.03B           15        2011.0       2025.0                                                           US
78     KOD                        Kodiak Sciences Inc.                     Biotechnology  1468748      2.03B            8        2018.0       2025.0                                                           US
79    URGN                          UroGen Pharma Ltd.                     Biotechnology  1668243      2.02B            8        2018.0       2025.0           incorporated in Israel; business address in Israel
80    NUVB                           Nuvation Bio Inc.                     Biotechnology  1811063      2.02B            6        2020.0       2025.0                                                           US
81    RXRX             RECURSION PHARMACEUTICALS, INC.                     Biotechnology  1601830      2.01B            5        2021.0       2025.0                                                           US
82    PVLA                 PALVELLA THERAPEUTICS, INC.                     Biotechnology  1583648      1.99B           12        2014.0       2025.0                                                           US
83    MRVI         MARAVAI LIFESCIENCES HOLDINGS, INC.                     Biotechnology  1823239      1.97B            6        2020.0       2025.0                                                           US
84    SRPT                  Sarepta Therapeutics, Inc.                     Biotechnology   873303      1.97B           16        2010.0       2025.0                                                           US
85    NKTR                         NEKTAR THERAPEUTICS                     Biotechnology   906709      1.95B           16        2010.0       2025.0                                                           US
86    AGIO                 AGIOS PHARMACEUTICALS, INC.                     Biotechnology  1439222      1.95B           13        2013.0       2025.0                                                           US
87     VIR                     Vir Biotechnology, Inc.                     Biotechnology  1706431      1.80B            7        2019.0       2025.0                                                           US
88    XNCR                                  Xencor Inc                     Biotechnology  1326732      1.77B           13        2013.0       2025.0                                                           US
89    NVAX                                 NOVAVAX INC                     Biotechnology  1000694      1.75B           16        2010.0       2025.0                                                           US
90    ABSI                                  Absci Corp                     Biotechnology  1672688      1.67B            5        2021.0       2025.0                                                           US
91    NTLA                 Intellia Therapeutics, Inc.                     Biotechnology  1652130      1.65B           10        2016.0       2025.0                                                           US
92    SNDX                  Syndax Pharmaceuticals Inc                     Biotechnology  1395937      1.63B           10        2016.0       2025.0                                                           US
93    STOK                    Stoke Therapeutics, Inc.                     Biotechnology  1623526      1.60B            7        2019.0       2025.0                                                           US

In [80]:
output_path = '/content/592_companies_universe.csv'

# Select relevant columns from the universe DataFrame
columns_to_save = [
    'ticker',
    'company_name',
    'industry',
    'cik',
    'market_cap',
    'n_10k_years',
    'first_10k_fy',
    'last_10k_fy',
    'domicile_note'
]

universe[columns_to_save].to_csv(output_path, index=False)

print(f"Successfully saved data for {len(universe)} companies to {output_path}")

Successfully saved data for 592 companies to /content/592_companies_universe.csv

## 4. Extract MD&A, Properties and Risk Factors from every 10-K

`edgartools` segments a 10-K into its items, which works well right back to 2011.
Two things still have to be handled, and both showed up in testing:

1. **Transient SEC failures.** A throttled request surfaces as an *empty* item rather than an
   exception, so an all-empty result is retried before it is believed.
2. **`filing.text()` can break.** For some filings edgartools cannot resolve the primary
   document (`'NoneType' object has no attribute 'download'`). `filing.filing_url` still points
   at the right document, so the fallback downloads it directly, strips the HTML and slices the
   items with a regex.

Only exact `10-K` forms are used — `10-K/A` amendments are normally Part III only and would
otherwise create empty duplicate fiscal years.

In [81]:
SECTIONS = [
    ("Item 1A", "Risk Factors", "risk_factors"),
    ("Item 2", "Properties", "properties"),
    ("Item 7", "Management's Discussion and Analysis", "mda"),
]

COLUMN_ORDER = [
    "ticker", "cik", "company_name", "form", "section", "item_label",
    "filing_date", "period_of_report", "fiscal_year", "accession_no",
    "text", "n_chars", "n_words", "source_url",
]


def clean_text(raw):
    if not isinstance(raw, str):
        return ""
    t = (raw.replace("\xa0", " ").replace(" ", " ").replace(" ", " "))
    t = re.sub(r"[ \t]+", " ", t)
    t = re.sub(r"\n\s*\n\s*\n+", "\n\n", t)
    return t.strip()


def html_to_text(html):
    """Strip an EDGAR HTML document down to readable text."""
    soup = BeautifulSoup(html, "lxml")
    for tag in soup(["script", "style"]):
        tag.decompose()
    for td in soup.find_all(["td", "th"]):       # keep table cells apart
        td.insert_after(" ")
    for br in soup.find_all(["br", "p", "div", "tr"]):
        br.insert_after("\n")
    return soup.get_text()


def filing_full_text(filing):
    """Primary-document text, downloading it directly if edgartools cannot."""
    try:
        fn = getattr(filing, "text", None)
        if callable(fn):
            t = fn()
            if t and len(t) > 2000:
                return t
    except Exception:
        pass

    url = getattr(filing, "filing_url", None)
    if not url:
        return ""
    for attempt in range(3):
        _throttle()
        try:
            r = requests.get(url, headers=SEC_HEADERS, timeout=120)
            if r.status_code == 200:
                return r.text if url.lower().endswith(".txt") else html_to_text(r.text)
            time.sleep(1.0 + 2 * attempt)
        except Exception:
            time.sleep(1.0 + 2 * attempt)
    return ""

In [82]:
# Where each item starts, and where the following item begins.
_ITEM_PATTERNS = {
    "Item 1A": r"item\s*1a\.?\s*[-–—:.]?\s*risk\s+factors",
    "Item 2":  r"item\s*2\.?\s*[-–—:.]?\s*propert(?:y|ies)",
    "Item 7":  r"item\s*7\.?\s*[-–—:.]?\s*management",
}
_NEXT_ITEM = {
    "Item 1A": r"item\s*1b\.?\s*[-–—:.]?\s*unresolved|item\s*2\.?\s*[-–—:.]?\s*propert",
    "Item 2":  r"item\s*3\.?\s*[-–—:.]?\s*legal",
    "Item 7":  r"item\s*7a\.?\s*[-–—:.]?\s*quantitative|item\s*8\.?\s*[-–—:.]?\s*financial",
}


def regex_slice(full_text, item_key):
    """Last-resort slicer. The table of contents also matches, so keep the longest slice."""
    if not full_text:
        return ""
    start_pat, end_pat = _ITEM_PATTERNS.get(item_key), _NEXT_ITEM.get(item_key)
    if not start_pat:
        return ""
    best = ""
    for m in re.finditer(start_pat, full_text, re.I):
        s = m.start()
        ends = [e.start() for e in re.finditer(end_pat, full_text[s + 50:], re.I)]
        e = s + 50 + ends[0] if ends else min(len(full_text), s + 400_000)
        chunk = full_text[s:e]
        if len(chunk) > len(best):
            best = chunk
    return best


def _items_from_obj(filing, attempts=3):
    """Ask edgartools for the three items, retrying transient SEC failures."""
    last = {}
    for attempt in range(attempts):
        try:
            obj = filing.obj()
        except Exception:
            time.sleep(1.0 + 2 * attempt)
            continue

        got = {}
        for item_key, _, section in SECTIONS:
            text = ""
            try:
                text = obj[item_key] or ""
            except Exception:
                text = ""
            if not text and section == "mda":
                text = getattr(obj, "management_discussion", "") or ""
            if not text and section == "risk_factors":
                text = getattr(obj, "risk_factors", "") or ""
            got[item_key] = text

        if any(got.values()):
            return got
        last = got                      # all empty -> probably throttled, try again
        time.sleep(1.5 + 2 * attempt)
    return last

In [83]:
def extract_filing_sections(ticker, cik, company_name, filing):
    """One row per section found in a single 10-K filing."""
    rows = []
    items = _items_from_obj(filing)
    full_text = None                    # fetched only if an item lookup came back empty

    period = str(getattr(filing, "period_of_report", "") or "")
    fdate = str(filing.filing_date)
    fiscal_year = int(period[:4]) if period[:4].isdigit() else int(fdate[:4])

    for item_key, item_label, section in SECTIONS:
        text = items.get(item_key, "")
        if not text:
            if full_text is None:
                full_text = filing_full_text(filing)
            text = regex_slice(full_text, item_key)

        text = clean_text(text)
        if not text:
            continue

        rows.append({
            "ticker": ticker,
            "cik": int(cik),
            "company_name": company_name,
            "form": filing.form,
            "section": section,
            "item_label": f"{item_key} - {item_label}",
            "filing_date": fdate,
            "period_of_report": period or None,
            "fiscal_year": fiscal_year,
            "accession_no": filing.accession_no,
            "text": text,
            "n_chars": len(text),
            "n_words": len(text.split()),
            "source_url": getattr(filing, "filing_url", None),
        })
    return rows


def extract_company_sections(ticker, cik, company_name, years=YEARS_BACK, verbose=True):
    start_year = pd.Timestamp.today().year - years
    filings = Company(ticker).get_filings(form="10-K")
    if not filings or len(filings) == 0:
        raise ValueError(f"No 10-K filings found for {ticker}")

    in_window = [f for f in filings if int(str(f.filing_date)[:4]) >= start_year]
    keep = sorted([f for f in in_window if f.form == "10-K"], key=lambda f: str(f.filing_date))
    if verbose:
        n_amend = len(in_window) - len(keep)
        extra = f" ({n_amend} amendment(s) skipped)" if n_amend else ""
        print(f"  {ticker}: {len(keep)} 10-K filings since {start_year}{extra}")

    rows = []
    for f in keep:
        try:
            got = extract_filing_sections(ticker, cik, company_name, f)
            rows.extend(got)
            if verbose:
                found = ", ".join(sorted({g["section"] for g in got})) or "NONE"
                print(f"    {f.filing_date}  FY{str(f.period_of_report)[:4]}:  {found}")
        except Exception as e:
            print(f"    {f.filing_date}: FAILED {type(e).__name__}: {e}")
        time.sleep(0.2)

    if not rows:
        raise ValueError(f"No sections extracted for {ticker}")
    return pd.DataFrame(rows)[COLUMN_ORDER].sort_values(
        ["fiscal_year", "section"]).reset_index(drop=True)

## 5. Pick the first 3 companies

`universe` keeps the market-cap ordering of the source pages, so "the first 3 companies" are
the three largest in the list. Switch to `universe.sort_values("ticker")` first if you would
rather take them alphabetically.

In [84]:
targets = universe

print("Companies selected for this run:")
display(targets[["ticker", "company_name", "industry", "cik", "market_cap"]])

print(f"\nParquet files go straight into: {DROPBOX_RAW}")

Companies selected for this run:

    ticker                     company_name                 industry      cik market_cap
0     VRTX  VERTEX PHARMACEUTICALS INC / MA            Biotechnology   875320    133.37B
1     MRNA                    Moderna, Inc.            Biotechnology  1682852     79.40B
2     REGN  REGENERON PHARMACEUTICALS, INC.            Biotechnology   872589     78.69B
3     RVMD       Revolution Medicines, Inc.            Biotechnology  1628171     43.93B
4      ONC             BeOne Medicines Ltd.            Biotechnology  1651308     41.03B
..     ...                              ...                      ...      ...        ...
587   BLIN         Bridgeline Digital, Inc.  Software Infrastructure  1378590     10.48M
588   AUID                      authID Inc.  Software Infrastructure  1534154      7.76M
589    OLB                  OLB GROUP, INC.  Software Infrastructure  1314196      4.89M
590   YYAI                       AIRWA INC.  Software Infrastructure  1674440      3.64M
591   CETX                      CEMTREX INC  Software Infrastructure  1435064      3.49M

[592 rows x 5 columns]

Parquet files go straight into: /content/bond_shared/data/raw/text

## 6. Extract and store one parquet per company

Each file holds the columns requested: `ticker`, `cik`, `company_name`, `form`, `section`,
`item_label`, `filing_date`, `period_of_report`, `fiscal_year`, `accession_no`, `text`,
`n_chars`, `n_words`, `source_url`.

In [85]:
def store_sections_parquet(df, ticker, raw_path, overwrite=True):
    """One flat file per company: <raw_path>/<TICKER>_10K_sections.parquet"""
    os.makedirs(raw_path, exist_ok=True)
    path = os.path.join(raw_path, f"{ticker}_10K_sections.parquet")
    if os.path.exists(path) and not overwrite:
        print(f"  Skipping (exists): {path}")
        return path
    df.to_parquet(path, index=False, compression="snappy")
    return path


written, failed = [], []
for _, row in targets.iterrows():
    print(f"\n=== {row.ticker} — {row.company_name} (CIK {int(row.cik)}) ===")
    try:
        sections_df = extract_company_sections(row.ticker, int(row.cik), row.company_name)
        path = store_sections_parquet(sections_df, row.ticker, DROPBOX_RAW)
        print(f"  -> {len(sections_df)} rows | {sections_df.n_words.sum():,} words "
              f"| {os.path.getsize(path) / 1e6:.2f} MB")
        print(f"  -> {path}")
        written.append(path)
    except Exception as e:
        print(f"  FAILED: {type(e).__name__}: {e}")
        failed.append({"ticker": row.ticker, "error": str(e)})

print(f"\nStored {len(written)} file(s); {len(failed)} failed.")

=== VRTX — VERTEX PHARMACEUTICALS INC / MA (CIK 875320) ===
  VRTX: 16 10-K filings since 2011
    2011-02-17  FY2010:  mda, properties, risk_factors
    2012-02-22  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-02-11  FY2013:  mda, properties, risk_factors
    2015-02-13  FY2014:  mda, properties, risk_factors
    2016-02-16  FY2015:  mda, properties, risk_factors
    2017-02-23  FY2016:  mda, properties, risk_factors
    2018-02-15  FY2017:  mda, properties, risk_factors
    2019-02-13  FY2018:  mda, properties, risk_factors
    2020-02-13  FY2019:  mda, properties, risk_factors
    2021-02-11  FY2020:  mda, properties, risk_factors
    2022-02-09  FY2021:  mda, properties, risk_factors
    2023-02-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 140 public document(s) but only 138 were parsed (accession 0000875320-24-000062). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-13  FY2024:  mda, properties, risk_factors
    2026-02-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 454,484 words | 1.40 MB
  -> /content/bond_shared/data/raw/text/VRTX_10K_sections.parquet

=== MRNA — Moderna, Inc. (CIK 1682852) ===
  MRNA: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-03-13  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0001682852-24-000015). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-20  FY2025:  mda, properties, risk_factors
  -> 24 rows | 361,654 words | 1.12 MB
  -> /content/bond_shared/data/raw/text/MRNA_10K_sections.parquet

=== REGN — REGENERON PHARMACEUTICALS, INC. (CIK 872589) ===
  REGN: 16 10-K filings since 2011
    2011-02-17  FY2010:  mda, properties, risk_factors
    2012-02-21  FY2011:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s3AD530D688C518A40F05C2B0E71DB976: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2013-02-15  FY2012:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s4633F24EBD8F616BD8A52F0E9EDCC34C: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2014-02-13  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s58FB784A222D6C4437AB4B1428E93596: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2015-02-12  FY2014:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sB0124FC1ECAB51C28D21BA4954856F3D: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2016-02-11  FY2015:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s8DE02E1D7A5053008905A6C74EBC90A9: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2017-02-09  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sAEA310569CE958359C8EC17259D75B12: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2018-02-08  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s1290A477D3B85B86B51E5C78EBD9A71F: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2019-02-07  FY2018:  mda, properties, risk_factors
    2020-02-07  FY2019:  mda, properties, risk_factors
    2021-02-08  FY2020:  mda, properties, risk_factors
    2022-02-07  FY2021:  mda, properties, risk_factors
    2023-02-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 139 public document(s) but only 137 were parsed (accession 0001804220-24-000009). The submission may be truncated or malformed.

    2024-02-05  FY2023:  mda, properties, risk_factors
    2025-02-05  FY2024:  mda, properties, risk_factors
    2026-02-04  FY2025:  mda, properties, risk_factors
  -> 48 rows | 611,665 words | 1.80 MB
  -> /content/bond_shared/data/raw/text/REGN_10K_sections.parquet

=== RVMD — Revolution Medicines, Inc. (CIK 1628171) ===
  RVMD: 7 10-K filings since 2011
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-02  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 103 public document(s) but only 101 were parsed (accession 0000950170-24-020145). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 21 rows | 338,027 words | 1.00 MB
  -> /content/bond_shared/data/raw/text/RVMD_10K_sections.parquet

=== ONC — BeOne Medicines Ltd. (CIK 1651308) ===
  ONC: 11 10-K filings since 2011 (2 amendment(s) skipped)
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-22  FY2016:  mda, properties, risk_factors
    2018-02-28  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 186 public document(s) but only 184 were parsed (accession 0001651308-24-000014). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 33 rows | 597,802 words | 1.79 MB
  -> /content/bond_shared/data/raw/text/ONC_10K_sections.parquet

=== ALNY — ALNYLAM PHARMACEUTICALS, INC. (CIK 1178670) ===
  ALNY: 16 10-K filings since 2011
    2011-02-18  FY2010:  mda, properties, risk_factors
    2012-02-13  FY2011:  mda, properties, risk_factors
    2013-02-19  FY2012:  mda, properties, risk_factors
    2014-02-20  FY2013:  mda, properties, risk_factors
    2015-02-13  FY2014:  mda, properties, risk_factors
    2016-02-12  FY2015:  mda, properties, risk_factors
    2017-02-15  FY2016:  mda, properties, risk_factors
    2018-02-15  FY2017:  mda, properties, risk_factors
    2019-02-14  FY2018:  mda, properties, risk_factors
    2020-02-13  FY2019:  mda, properties, risk_factors
    2021-02-11  FY2020:  mda, properties, risk_factors
    2022-02-10  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 111 public document(s) but only 109 were parsed (accession 0001178670-24-000008). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-13  FY2024:  mda, properties, risk_factors
    2026-02-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 565,539 words | 1.71 MB
  -> /content/bond_shared/data/raw/text/ALNY_10K_sections.parquet

=== RPRX — Royalty Pharma plc (CIK 1802768) ===
  RPRX: 6 10-K filings since 2011

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2021-02-24  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2022-02-15  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2023-02-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 89 public document(s) but only 87 were parsed (accession 0001802768-24-000012). The submission may be truncated or malformed.
WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2024-02-15  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2025-02-12  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2026-02-11  FY2025:  mda, properties, risk_factors
  -> 18 rows | 240,134 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/RPRX_10K_sections.parquet

=== ROIV — Roivant Sciences Ltd. (CIK 1635088) ===
  ROIV: 5 10-K filings since 2011
    2022-06-28  FY2022:  mda, properties, risk_factors
    2023-06-28  FY2023:  mda, properties, risk_factors
    2024-05-30  FY2024:  mda, properties, risk_factors
    2025-05-29  FY2025:  mda, properties, risk_factors
    2026-05-20  FY2026:  mda, properties, risk_factors
  -> 15 rows | 336,527 words | 1.02 MB
  -> /content/bond_shared/data/raw/text/ROIV_10K_sections.parquet

=== INSM — INSMED Inc (CIK 1104506) ===
  INSM: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-03-13  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-06  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-25  FY2015:  mda, properties, risk_factors
    2017-02-23  FY2016:  mda, properties, risk_factors
    2018-02-23  FY2017:  mda, properties, risk_factors
    2019-02-22  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-17  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 115 public document(s) but only 113 were parsed (accession 0001104506-24-000008). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 48 rows | 395,701 words | 1.20 MB
  -> /content/bond_shared/data/raw/text/INSM_10K_sections.parquet

=== INCY — INCYTE CORP (CIK 879169) ===
  INCY: 16 10-K filings since 2011 (4 amendment(s) skipped)
    2011-02-23  FY2010:  mda, properties, risk_factors
    2012-02-22  FY2011:  mda, properties, risk_factors
    2013-02-21  FY2012:  mda, properties, risk_factors
    2014-02-21  FY2013:  mda, properties, risk_factors
    2015-02-17  FY2014:  mda, properties, risk_factors
    2016-02-12  FY2015:  mda, properties, risk_factors
    2017-02-14  FY2016:  mda, properties, risk_factors
    2018-02-15  FY2017:  mda, properties, risk_factors
    2019-02-14  FY2018:  mda, properties, risk_factors
    2020-02-13  FY2019:  mda, properties, risk_factors
    2021-02-09  FY2020:  mda, properties, risk_factors
    2022-02-08  FY2021:  mda, properties, risk_factors
    2023-02-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 111 public document(s) but only 109 were parsed (accession 0000879169-24-000045). The submission may be truncated or malformed.

    2024-02-13  FY2023:  mda, properties, risk_factors
    2025-02-10  FY2024:  mda, properties, risk_factors
    2026-02-10  FY2025:  mda, properties, risk_factors
  -> 48 rows | 394,764 words | 1.19 MB
  -> /content/bond_shared/data/raw/text/INCY_10K_sections.parquet

=== JAZZ — Jazz Pharmaceuticals plc (CIK 1232524) ===
  JAZZ: 16 10-K filings since 2011 (15 amendment(s) skipped)
    2011-03-08  FY2010:  mda, properties, risk_factors
    2012-02-28  FY2011:  mda, properties, risk_factors
    2013-02-26  FY2012:  mda, properties, risk_factors
    2014-02-25  FY2013:  mda, properties, risk_factors
    2015-02-24  FY2014:  mda, properties, risk_factors
    2016-02-23  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-23  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 142 public document(s) but only 140 were parsed (accession 0001232524-24-000015). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 48 rows | 744,057 words | 2.19 MB
  -> /content/bond_shared/data/raw/text/JAZZ_10K_sections.parquet

=== EXEL — EXELIXIS, INC. (CIK 939767) ===
  EXEL: 16 10-K filings since 2011
    2011-02-22  FY2010:  mda, properties, risk_factors
    2012-02-22  FY2011:  mda, properties, risk_factors
    2013-02-21  FY2012:  mda, properties, risk_factors
    2014-02-20  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2016:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-02-26  FY2017:  mda, properties, risk_factors
    2019-02-22  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2020:  mda, properties, risk_factors
    2021-02-11  FY2021:  mda, properties, risk_factors
    2022-02-18  FY2021:  mda, properties, risk_factors
    2023-02-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 102 public document(s) but only 100 were parsed (accession 0000939767-24-000028). The submission may be truncated or malformed.

    2024-02-06  FY2023:  mda, properties, risk_factors
    2025-02-11  FY2025:  mda, properties, risk_factors
    2026-02-10  FY2026:  mda, properties, risk_factors
  -> 48 rows | 431,057 words | 1.29 MB
  -> /content/bond_shared/data/raw/text/EXEL_10K_sections.parquet

=== HALO — HALOZYME THERAPEUTICS, INC. (CIK 1159036) ===
  HALO: 16 10-K filings since 2011
    2011-03-11  FY2010:  mda, properties, risk_factors
    2012-03-12  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-02-28  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-02-20  FY2017:  mda, properties, risk_factors
    2019-02-21  FY2018:  mda, properties, risk_factors
    2020-02-24  FY2019:  mda, properties, risk_factors
    2021-02-23  FY2020:  mda, properties, risk_factors
    2022-02-22  FY2021:  mda, properties, risk_factors
    2023-02-21  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 120 public document(s) but only 118 were parsed (accession 0001159036-24-000008). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-18  FY2024:  mda, properties, risk_factors
    2026-02-17  FY2025:  mda, properties, risk_factors
  -> 48 rows | 304,709 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/HALO_10K_sections.parquet

=== BBIO — BridgeBio Pharma, Inc. (CIK 1743881) ===
  BBIO: 7 10-K filings since 2011
    2020-03-03  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 116 public document(s) but only 114 were parsed (accession 0000950170-24-018811). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item_2_properties: part_i_item_2 keeps the anchor; ['part_i_item_1c'] still resolve(s) to the same span (part_i_item_1c: body anchor item_1b_unresolved_staff_comments already claimed)

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 21 rows | 419,676 words | 1.24 MB
  -> /content/bond_shared/data/raw/text/BBIO_10K_sections.parquet

=== CORT — CORCEPT THERAPEUTICS INC (CIK 1088856) ===
  CORT: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-15  FY2010:  mda, properties, risk_factors
    2012-03-13  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-06  FY2016:  mda, properties, risk_factors
    2018-02-28  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-24  FY2019:  mda, properties, risk_factors
    2021-02-23  FY2020:  mda, properties, risk_factors
    2022-02-15  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 80 public document(s) but only 78 were parsed (accession 0001628280-24-005055). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 48 rows | 286,290 words | 0.90 MB
  -> /content/bond_shared/data/raw/text/CORT_10K_sections.parquet

=== SMMT — Summit Therapeutics Inc. (CIK 1599298) ===
  SMMT: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 113 public document(s) but only 111 were parsed (accession 0001599298-24-000031). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-24  FY2024:  mda, properties, risk_factors
    2026-02-23  FY2025:  mda, properties, risk_factors
  -> 18 rows | 215,605 words | 0.66 MB
  -> /content/bond_shared/data/raw/text/SMMT_10K_sections.parquet

=== MDGL — MADRIGAL PHARMACEUTICALS, INC. (CIK 1157601) ===
  MDGL: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-11  FY2010:  mda, properties, risk_factors
    2012-02-22  FY2011:  mda, properties, risk_factors
    2013-03-14  FY2012:  mda, properties, risk_factors
    2014-03-11  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-03-13  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 78 public document(s) but only 76 were parsed (accession 0001628280-24-007376). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 48 rows | 390,706 words | 1.20 MB
  -> /content/bond_shared/data/raw/text/MDGL_10K_sections.parquet

=== BMRN — BIOMARIN PHARMACEUTICAL INC (CIK 1048477) ===
  BMRN: 16 10-K filings since 2011
    2011-02-24  FY2010:  mda, properties, risk_factors
    2012-02-22  FY2011:  mda, properties, risk_factors
    2013-02-26  FY2012:  mda, properties, risk_factors
    2014-02-26  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-02-26  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 119 public document(s) but only 117 were parsed (accession 0001048477-24-000016). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-24  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 482,726 words | 1.46 MB
  -> /content/bond_shared/data/raw/text/BMRN_10K_sections.parquet

=== TWST — Twist Bioscience Corp (CIK 1581280) ===
  TWST: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2018-12-20  FY2018:  mda, properties, risk_factors
    2019-12-13  FY2019:  mda, properties, risk_factors
    2020-11-27  FY2020:  mda, properties, risk_factors
    2021-11-23  FY2021:  mda, properties, risk_factors
    2022-11-28  FY2022:  mda, properties, risk_factors
    2023-11-21  FY2023:  mda, properties, risk_factors
    2024-11-18  FY2024:  mda, properties, risk_factors
    2025-11-17  FY2025:  mda, properties, risk_factors
  -> 24 rows | 242,503 words | 0.74 MB
  -> /content/bond_shared/data/raw/text/TWST_10K_sections.parquet

=== TECH — BIO-TECHNE Corp (CIK 842023) ===
  TECH: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-08-29  FY2011:  mda, properties, risk_factors
    2012-08-29  FY2012:  mda, properties, risk_factors
    2013-08-29  FY2013:  mda, properties, risk_factors
    2014-08-29  FY2014:  mda, properties, risk_factors
    2015-08-31  FY2015:  mda, properties, risk_factors
    2016-08-29  FY2016:  mda, properties, risk_factors
    2017-09-07  FY2017:  mda, properties, risk_factors
    2018-08-27  FY2018:  mda, properties, risk_factors
    2019-08-28  FY2019:  mda, properties, risk_factors
    2020-08-26  FY2020:  mda, properties, risk_factors
    2021-08-25  FY2021:  mda, properties, risk_factors
    2022-08-24  FY2022:  mda, properties, risk_factors
    2023-08-23  FY2023:  mda, properties, risk_factors
    2024-08-22  FY2024:  mda, properties, risk_factors
    2025-08-22  FY2025:  mda, properties, risk_factors
    2026-08-24  FY2026:  mda, properties, risk_factors
  -> 48 rows | 213,580 words | 0.67 MB
  -> /content/bond_shared/data/raw/text/TECH_10K_sections.parquet

=== KRYS — Krystal Biotech, Inc. (CIK 1711279) ===
  KRYS: 9 10-K filings since 2011
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-03-10  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 81 public document(s) but only 79 were parsed (accession 0001711279-24-000005). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-02-17  FY2025:  mda, properties, risk_factors
  -> 27 rows | 293,873 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/KRYS_10K_sections.parquet

=== AXSM — Axsome Therapeutics, Inc. (CIK 1579428) ===
  AXSM: 11 10-K filings since 2011 (1 amendment(s) skipped)
    2016-03-24  FY2015:  mda, properties, risk_factors
    2017-03-07  FY2016:  mda, properties, risk_factors
    2018-03-07  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.9' is not an English number; the raw display text is used instead

    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 109 public document(s) but only 107 were parsed (accession 0000950170-24-019118). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-02-18  FY2024:  mda, properties, risk_factors
    2026-02-23  FY2025:  mda, properties, risk_factors
  -> 33 rows | 501,411 words | 1.50 MB
  -> /content/bond_shared/data/raw/text/AXSM_10K_sections.parquet

=== ARWR — ARROWHEAD PHARMACEUTICALS, INC. (CIK 879407) ===
  ARWR: 15 10-K filings since 2011 (1 amendment(s) skipped)
    2011-12-20  FY2011:  mda, properties, risk_factors
    2012-12-28  FY2012:  mda, properties, risk_factors
    2013-12-18  FY2013:  mda, properties, risk_factors
    2014-11-25  FY2014:  mda, properties, risk_factors
    2015-12-14  FY2015:  mda, properties, risk_factors
    2016-12-14  FY2016:  mda, properties, risk_factors
    2017-12-12  FY2017:  mda, properties, risk_factors
    2018-12-11  FY2018:  mda, properties, risk_factors
    2019-11-25  FY2019:  mda, properties, risk_factors
    2020-11-23  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM_1_BUSINESS: part_i_item_1a keeps the anchor; ['part_i_item_1'] still resolve(s) to the same span (part_i_item_1: body anchor NotesToConsolidatedFinanStatements does not follow the shared one)

    2021-11-22  FY2021:  mda, properties, risk_factors
    2022-11-28  FY2022:  mda, properties, risk_factors
    2023-11-29  FY2023:  mda, properties, risk_factors
    2024-11-26  FY2024:  mda, properties, risk_factors
    2025-11-25  FY2025:  mda, properties, risk_factors
  -> 45 rows | 295,898 words | 0.90 MB
  -> /content/bond_shared/data/raw/text/ARWR_10K_sections.parquet

=== KYMR — Kymera Therapeutics, Inc. (CIK 1815442) ===
  KYMR: 6 10-K filings since 2011
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 155 public document(s) but only 153 were parsed (accession 0000950170-24-018414). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 289,863 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/KYMR_10K_sections.parquet

=== PTGX — Protagonist Therapeutics, Inc (CIK 1377121) ===
  PTGX: 10 10-K filings since 2011
    2017-03-07  FY2016:  mda, properties, risk_factors
    2018-03-07  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-03-10  FY2019:  mda, properties, risk_factors
    2021-03-10  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 102 public document(s) but only 100 were parsed (accession 0001558370-24-001850). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_611152: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_95714 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_349128: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_994436: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_51645: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrants_334448: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysis_85: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficers_302483: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_184435: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnership_537465: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationships_158382: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountantFees_983878: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancial_120427: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_140453: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 30 rows | 318,512 words | 0.94 MB
  -> /content/bond_shared/data/raw/text/PTGX_10K_sections.parquet

=== CYTK — CYTOKINETICS INC (CIK 1061983) ===
  CYTK: 16 10-K filings since 2011
    2011-03-11  FY2010:  mda, properties, risk_factors
    2012-03-13  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-07  FY2013:  mda, properties, risk_factors
    2015-03-06  FY2014:  mda, properties, risk_factors
    2016-03-03  FY2015:  mda, properties, risk_factors
    2017-03-06  FY2016:  mda, properties, risk_factors
    2018-03-05  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-04  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 76 public document(s) but only 74 were parsed (accession 0000950170-24-022256). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 476,856 words | 1.43 MB
  -> /content/bond_shared/data/raw/text/CYTK_10K_sections.parquet

=== IBRX — ImmunityBio, Inc. (CIK 1326110) ===
  IBRX: 11 10-K filings since 2011
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-13  FY2018:  mda, properties, risk_factors
    2020-03-25  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ib5760b47e59d4c7c9ba2771e8a39ffc5_229: part_iv_item_15 keeps the anchor; ['part_i_item_15'] still resolve(s) to the same span (part_i_item_15: no body header for this item)

    2023-03-01  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-23  FY2025:  mda, properties, risk_factors
  -> 33 rows | 607,073 words | 1.80 MB
  -> /content/bond_shared/data/raw/text/IBRX_10K_sections.parquet

=== PCVX — Vaxcyte, Inc. (CIK 1649094) ===
  PCVX: 6 10-K filings since 2011
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 130 public document(s) but only 128 were parsed (accession 0000950170-24-021145). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 18 rows | 291,643 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/PCVX_10K_sections.parquet

=== TGTX — TG THERAPEUTICS, INC. (CIK 1001316) ===
  TGTX: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-14  FY2011:  mda, properties, risk_factors
    2013-03-21  FY2012:  mda, properties, risk_factors
    2014-03-07  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 90 public document(s) but only 88 were parsed (accession 0001437749-24-006144). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 491,981 words | 1.51 MB
  -> /content/bond_shared/data/raw/text/TGTX_10K_sections.parquet

=== PRAX — Praxis Precision Medicines, Inc. (CIK 1689548) ===
  PRAX: 6 10-K filings since 2011
    2021-03-17  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0001689548-24-000034). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 18 rows | 301,619 words | 0.90 MB
  -> /content/bond_shared/data/raw/text/PRAX_10K_sections.parquet

=== SYRE — Spyre Therapeutics, Inc. (CIK 1636282) ===
  SYRE: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-03-23  FY2016:  mda, properties, risk_factors
    2018-03-13  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-02-24  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-08  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.6' is not an English number; the raw display text is used instead

    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 121 public document(s) but only 119 were parsed (accession 0001636282-24-000005). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i71ced85e36034183a6c2d4df9e40bea0_163: part_ii_item_9c keeps the anchor; ['part_ii_item_9'] still resolve(s) to the same span (part_ii_item_9: body anchor i71ced85e36034183a6c2d4df9e40bea0_154 does not follow the shared one)

    2025-02-27  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i4239289f41804bf78920a5c992d63e00_208: part_ii_item_9c keeps the anchor; ['part_ii_item_9'] still resolve(s) to the same span (part_ii_item_9: body anchor i4239289f41804bf78920a5c992d63e00_199 does not follow the shared one)

    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 30 rows | 393,871 words | 1.17 MB
  -> /content/bond_shared/data/raw/text/SYRE_10K_sections.parquet

=== IONS — IONIS PHARMACEUTICALS INC (CIK 874015) ===
  IONS: 16 10-K filings since 2011
    2011-03-01  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-02-28  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-02-28  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-22  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 121 public document(s) but only 119 were parsed (accession 0000874015-24-000116). The submission may be truncated or malformed.

    2024-02-21  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 303,486 words | 0.91 MB
  -> /content/bond_shared/data/raw/text/IONS_10K_sections.parquet

=== IMVT — Immunovant, Inc. (CIK 1764013) ===
  IMVT: 7 10-K filings since 2011
    2020-06-29  FY2020:  mda, properties, risk_factors
    2021-06-01  FY2021:  mda, properties, risk_factors
    2022-06-08  FY2022:  mda, properties, risk_factors
    2023-05-22  FY2023:  mda, properties, risk_factors
    2024-05-29  FY2024:  mda, properties, risk_factors
    2025-05-29  FY2025:  mda, properties, risk_factors
    2026-05-20  FY2026:  mda, properties, risk_factors
  -> 21 rows | 341,084 words | 1.03 MB
  -> /content/bond_shared/data/raw/text/IMVT_10K_sections.parquet

=== RYTM — RHYTHM PHARMACEUTICALS, INC. (CIK 1649904) ===
  RYTM: 9 10-K filings since 2011
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-08  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0001558370-24-002181). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysis_56: part_i_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_i_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 27 rows | 433,321 words | 1.31 MB
  -> /content/bond_shared/data/raw/text/RYTM_10K_sections.parquet

=== LGND — LIGAND PHARMACEUTICALS INC (CIK 886163) ===
  LGND: 16 10-K filings since 2011 (5 amendment(s) skipped)
    2011-03-03  FY2010:  mda, properties, risk_factors
    2012-02-23  FY2011:  mda, properties, risk_factors
    2013-03-14  FY2012:  mda, properties, risk_factors
    2014-02-24  FY2013:  mda, properties, risk_factors
    2015-02-23  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s2BFE2C04B1525D45ADA0068012A4A472: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s1FA161CE8AEE52BEB212C6A7F7643CE9: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 108 public document(s) but only 106 were parsed (accession 0000886163-24-000009). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 295,242 words | 0.91 MB
  -> /content/bond_shared/data/raw/text/LGND_10K_sections.parquet

=== SRRK — Scholar Rock Holding Corp (CIK 1727196) ===
  SRRK: 8 10-K filings since 2011
    2019-03-19  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-09  FY2020:  mda, properties, risk_factors
    2022-03-07  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 24 rows | 352,633 words | 1.05 MB
  -> /content/bond_shared/data/raw/text/SRRK_10K_sections.parquet

=== MIRM — Mirum Pharmaceuticals, Inc. (CIK 1759425) ===
  MIRM: 7 10-K filings since 2011
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-09  FY2020:  mda, properties, risk_factors
    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 101 public document(s) but only 99 were parsed (accession 0000950170-24-032289). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 21 rows | 358,173 words | 1.08 MB
  -> /content/bond_shared/data/raw/text/MIRM_10K_sections.parquet

=== COGT — Cogent Biosciences, Inc. (CIK 1622229) ===
  COGT: 8 10-K filings since 2011
    2019-03-28  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 102 public document(s) but only 100 were parsed (accession 0000950170-24-019770). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-17  FY2025:  mda, properties, risk_factors
  -> 24 rows | 207,479 words | 0.63 MB
  -> /content/bond_shared/data/raw/text/COGT_10K_sections.parquet

=== TVTX — Travere Therapeutics, Inc. (CIK 1438533) ===
  TVTX: 16 10-K filings since 2011 (5 amendment(s) skipped)
    2011-05-25  FY2011:  mda, properties, risk_factors
    2012-05-24  FY2012:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on 38: part_ii_item_6 keeps the anchor; ['part_ii_item_7', 'part_ii_item_7a'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors; part_ii_item_7a: no body-header anchors)

    2013-06-13  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-11  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-24  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 137 public document(s) but only 135 were parsed (accession 0001438533-24-000005). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 48 rows | 443,070 words | 1.36 MB
  -> /content/bond_shared/data/raw/text/TVTX_10K_sections.parquet

=== ORKA — Oruka Therapeutics, Inc. (CIK 907654) ===
  ORKA: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-09  FY2010:  mda, properties, risk_factors
    2012-03-27  FY2011:  mda, properties, risk_factors
    2013-03-21  FY2012:  mda, properties, risk_factors
    2014-03-20  FY2013:  mda, properties, risk_factors
    2015-03-19  FY2014:  mda, properties, risk_factors
    2016-03-17  FY2015:  mda, properties, risk_factors
    2017-03-21  FY2016:  mda, properties, risk_factors
    2018-03-22  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-18  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-14  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 61 public document(s) but only 59 were parsed (accession 0000950170-24-009809). The submission may be truncated or malformed.

    2024-02-01  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 375,671 words | 1.13 MB
  -> /content/bond_shared/data/raw/text/ORKA_10K_sections.parquet

=== CRSP — CRISPR Therapeutics AG (CIK 1674416) ===
  CRSP: 10 10-K filings since 2011
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-02-25  FY2018:  mda, properties, risk_factors
    2020-02-12  FY2019:  mda, properties, risk_factors
    2021-02-16  FY2020:  mda, properties, risk_factors
    2022-02-15  FY2021:  mda, properties, risk_factors
    2023-02-21  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 107 public document(s) but only 105 were parsed (accession 0000950170-24-017571). The submission may be truncated or malformed.

    2024-02-21  FY2023:  mda, properties, risk_factors
    2025-02-11  FY2024:  mda, properties, risk_factors
    2026-02-12  FY2025:  mda, properties, risk_factors
  -> 30 rows | 491,811 words | 1.49 MB
  -> /content/bond_shared/data/raw/text/CRSP_10K_sections.parquet

=== PTCT — PTC THERAPEUTICS, INC. (CIK 1070081) ===
  PTCT: 13 10-K filings since 2011 (1 amendment(s) skipped)
    2014-03-06  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-06  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item9ChangesinandDisagreementswithAccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor Item9CDisclosuresRgardingForeignJurisdic sits past the next item)

    2022-02-22  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item9ChangesinandDisagreementswithAccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor Item9CDisclosuresRgardingForeignJurisdic sits past the next item)

    2023-02-21  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 119 public document(s) but only 117 were parsed (accession 0001558370-24-002196). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_439737: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_681121 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)

    2024-02-29  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 128 public document(s) but only 126 were parsed (accession 0001070081-25-000012). The submission may be truncated or malformed.

    2025-02-27  FY2024:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0001104659-26-017575). The submission may be truncated or malformed.

    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 39 rows | 702,795 words | 2.04 MB
  -> /content/bond_shared/data/raw/text/PTCT_10K_sections.parquet

=== ERAS — Erasca, Inc. (CIK 1761918) ===
  ERAS: 5 10-K filings since 2011
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 241,887 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/ERAS_10K_sections.parquet

=== IOVA — IOVANCE BIOTHERAPEUTICS, INC. (CIK 1425205) ===
  IOVA: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-04-14  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-09-23  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-09  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 101 public document(s) but only 99 were parsed (accession 0001558370-24-002036). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_12257: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_474723 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_146901: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_488764: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_418606: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforCommonEquityRelatedStockho: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item9ChangesinandDisagreementswithAccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_771474: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountantsFeesandService: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsFinancialStatementsSchedul: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_418252: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 48 rows | 537,562 words | 1.62 MB
  -> /content/bond_shared/data/raw/text/IOVA_10K_sections.parquet

=== DNTH — Dianthus Therapeutics, Inc. /DE/ (CIK 1690585) ===
  DNTH: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-03-19  FY2018:  mda, properties, risk_factors
    2020-03-03  FY2019:  mda, properties, risk_factors
    2021-03-03  FY2020:  mda, properties, risk_factors
    2022-03-08  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 24 rows | 348,526 words | 1.04 MB
  -> /content/bond_shared/data/raw/text/DNTH_10K_sections.parquet

=== DFTX — Definium Therapeutics, Inc. (CIK 1813814) ===
  DFTX: 5 10-K filings since 2011
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 87 public document(s) but only 85 were parsed (accession 0000950170-24-021656). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 267,557 words | 0.80 MB
  -> /content/bond_shared/data/raw/text/DFTX_10K_sections.parquet

=== EWTX — Edgewise Therapeutics, Inc. (CIK 1710072) ===
  EWTX: 5 10-K filings since 2011
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 101 public document(s) but only 99 were parsed (accession 0001558370-24-001467). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 259,086 words | 0.77 MB
  -> /content/bond_shared/data/raw/text/EWTX_10K_sections.parquet

=== TNGX — Tango Therapeutics, Inc. (CIK 1819133) ===
  TNGX: 6 10-K filings since 2011
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-27  FY2022:  mda, properties, risk_factors
    2024-03-18  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 18 rows | 239,681 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/TNGX_10K_sections.parquet

=== VKTX — Viking Therapeutics, Inc. (CIK 1607678) ===
  VKTX: 11 10-K filings since 2011
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-21  FY2016:  mda, properties, risk_factors
    2018-03-07  FY2017:  mda, properties, risk_factors
    2019-03-13  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-17  FY2020:  mda, properties, risk_factors
    2022-02-09  FY2021:  mda, properties, risk_factors
    2023-02-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 71 public document(s) but only 69 were parsed (accession 0000950170-24-012322). The submission may be truncated or malformed.

    2024-02-07  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-11  FY2025:  mda, properties, risk_factors
  -> 33 rows | 367,673 words | 1.08 MB
  -> /content/bond_shared/data/raw/text/VKTX_10K_sections.parquet

=== ABCL — AbCellera Biologics Inc. (CIK 1703057) ===
  ABCL: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-21  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 251 public document(s) but only 249 were parsed (accession 0001703057-24-000019). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 18 rows | 288,846 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/ABCL_10K_sections.parquet

=== CELC — Celcuity Inc. (CIK 1603454) ===
  CELC: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i7a: part_ii_item_8 keeps the anchor; ['part_ii_item_7a'] still resolve(s) to the same span (part_ii_item_7a: body anchor i7 already claimed)

    2021-02-16  FY2020:  mda, properties, risk_factors
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 27 rows | 183,961 words | 0.58 MB
  -> /content/bond_shared/data/raw/text/CELC_10K_sections.parquet

=== RLAY — Relay Therapeutics, Inc. (CIK 1812364) ===
  RLAY: 6 10-K filings since 2011
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0000950170-24-018797). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 288,453 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/RLAY_10K_sections.parquet

=== XENE — Xenon Pharmaceuticals Inc. (CIK 1582313) ===
  XENE: 12 10-K filings since 2011
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-08  FY2016:  mda, properties, risk_factors
    2018-03-07  FY2017:  mda, properties, risk_factors
    2019-03-06  FY2018:  mda, properties, risk_factors
    2020-03-09  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 80 public document(s) but only 78 were parsed (accession 0000950170-24-023177). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 36 rows | 434,224 words | 1.31 MB
  -> /content/bond_shared/data/raw/text/XENE_10K_sections.parquet

=== ACAD — ACADIA PHARMACEUTICALS INC (CIK 1070494) ===
  ACAD: 16 10-K filings since 2011
    2011-03-10  FY2010:  mda, properties, risk_factors
    2012-03-06  FY2011:  mda, properties, risk_factors
    2013-03-12  FY2012:  mda, properties, risk_factors
    2014-02-27  FY2013:  mda, properties, risk_factors
    2015-02-26  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.3' is not an English number; the raw display text is used instead

    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 94 public document(s) but only 92 were parsed (accession 0000950170-24-021473). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 450,105 words | 1.36 MB
  -> /content/bond_shared/data/raw/text/ACAD_10K_sections.parquet

=== IDYA — IDEAYA Biosciences, Inc. (CIK 1676725) ===
  IDYA: 7 10-K filings since 2011
    2020-03-24  FY2019:  mda, properties, risk_factors
    2021-03-23  FY2020:  mda, properties, risk_factors
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 83 public document(s) but only 81 were parsed (accession 0000950170-24-017093). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-18  FY2024:  mda, properties, risk_factors
    2026-02-17  FY2025:  mda, properties, risk_factors
  -> 21 rows | 392,844 words | 1.16 MB
  -> /content/bond_shared/data/raw/text/IDYA_10K_sections.parquet

=== ARQT — Arcutis Biotherapeutics, Inc. (CIK 1787306) ===
  ARQT: 7 10-K filings since 2011 (2 amendment(s) skipped)
    2020-03-19  FY2019:  mda, properties, risk_factors
    2021-02-16  FY2020:  mda, properties, risk_factors
    2022-02-22  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 102 public document(s) but only 100 were parsed (accession 0001787306-24-000031). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 21 rows | 312,212 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/ARQT_10K_sections.parquet

=== TARS — Tarsus Pharmaceuticals, Inc. (CIK 1819790) ===
  TARS: 6 10-K filings since 2011
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-14  FY2021:  mda, properties, risk_factors
    2023-03-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 109 public document(s) but only 107 were parsed (accession 0001819790-24-000018). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-23  FY2025:  mda, properties, risk_factors
  -> 18 rows | 320,178 words | 0.96 MB
  -> /content/bond_shared/data/raw/text/TARS_10K_sections.parquet

=== ELVN — Enliven Therapeutics, Inc. (CIK 1672619) ===
  ELVN: 6 10-K filings since 2011
    2021-03-05  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-02-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0000950170-24-031495). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 18 rows | 304,619 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/ELVN_10K_sections.parquet

=== DNLI — Denali Therapeutics Inc. (CIK 1714899) ===
  DNLI: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-03-19  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 110 public document(s) but only 108 were parsed (accession 0001714899-24-000086). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 27 rows | 416,836 words | 1.25 MB
  -> /content/bond_shared/data/raw/text/DNLI_10K_sections.parquet

=== RCUS — Arcus Biosciences, Inc. (CIK 1724521) ===
  RCUS: 8 10-K filings since 2011
    2019-03-05  FY2018:  mda, properties, risk_factors
    2020-03-05  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-23  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 104 public document(s) but only 102 were parsed (accession 0001724521-24-000052). The submission may be truncated or malformed.

    2024-02-21  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 24 rows | 259,371 words | 0.79 MB
  -> /content/bond_shared/data/raw/text/RCUS_10K_sections.parquet

=== DYN — Dyne Therapeutics, Inc. (CIK 1818794) ===
  DYN: 6 10-K filings since 2011
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 84 public document(s) but only 82 were parsed (accession 0000950170-24-025402). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 18 rows | 320,049 words | 0.94 MB
  -> /content/bond_shared/data/raw/text/DYN_10K_sections.parquet

=== ZLAB — Zai Lab Ltd (CIK 1704292) ===
  ZLAB: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 151 public document(s) but only 149 were parsed (accession 0001628280-24-007235). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 291,248 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/ZLAB_10K_sections.parquet

=== PGEN — PRECIGEN, INC. (CIK 1356090) ===
  PGEN: 13 10-K filings since 2011 (3 amendment(s) skipped)
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-19  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 39 rows | 383,869 words | 1.17 MB
  -> /content/bond_shared/data/raw/text/PGEN_10K_sections.parquet

=== QURE — uniQure N.V. (CIK 1590560) ===
  QURE: 10 10-K filings since 2011 (1 amendment(s) skipped)
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0001558370-24-001915). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_133094: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_586025 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_606513: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_809926: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_186075: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6Reserved_463009: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_736009: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountingFeesandServices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsFinancialStatementFinancia: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_465633: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 30 rows | 347,404 words | 1.05 MB
  -> /content/bond_shared/data/raw/text/QURE_10K_sections.parquet

=== IRON — Disc Medicine, Inc. (CIK 1816736) ===
  IRON: 6 10-K filings since 2011
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 287,928 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/IRON_10K_sections.parquet

=== CLDX — Celldex Therapeutics, Inc. (CIK 744218) ===
  CLDX: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-09  FY2010:  mda, properties, risk_factors
    2012-03-08  FY2011:  mda, properties, risk_factors
    2013-03-08  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-02-24  FY2014:  mda, properties, risk_factors
    2016-02-23  FY2015:  mda, properties, risk_factors
    2017-03-14  FY2016:  mda, properties, risk_factors
    2018-03-07  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 92 public document(s) but only 90 were parsed (accession 0001410578-24-000076). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2PROPERTIES_225470: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LEGALPROCEEDINGS_101934: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MINESAFETYDISCLOSURES_355906: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MARKETFORREGISTRANTS_239721: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6SELECTEDFINANCIALDATA_500251: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7MANAGEMENTSDISCUSSION_91937: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FINANCIALSTATEMENTS_953180: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DIRECTORSEXECUTIVE_251619: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11EXECUTIVECOMPENSATION_659199: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SECURITYOWNERSHIP_108166: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CERTAINRELATIONSHIPSAND_189337: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PRINCIPALACCOUNTINGFEES_43693: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15EXHIBITSFINANCIALSTATEMENT_652110: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16FORM10KSUMMARY_35393: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 48 rows | 427,193 words | 1.31 MB
  -> /content/bond_shared/data/raw/text/CLDX_10K_sections.parquet

=== IMNM — Immunome Inc. (CIK 1472012) ===
  IMNM: 6 10-K filings since 2011
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-19  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 18 rows | 249,570 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/IMNM_10K_sections.parquet

=== BEAM — Beam Therapeutics Inc. (CIK 1745999) ===
  BEAM: 7 10-K filings since 2011
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:datequarterend; the raw display text is used instead

    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 113 public document(s) but only 111 were parsed (accession 0000950170-24-020622). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 21 rows | 426,220 words | 1.25 MB
  -> /content/bond_shared/data/raw/text/BEAM_10K_sections.parquet

=== HRMY — Harmony Biosciences Holdings, Inc. (CIK 1802665) ===
  HRMY: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-21  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 106 public document(s) but only 104 were parsed (accession 0001558370-24-001466). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolved sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7Management: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8Financial: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 18 rows | 246,123 words | 0.76 MB
  -> /content/bond_shared/data/raw/text/HRMY_10K_sections.parquet

=== NRIX — Nurix Therapeutics, Inc. (CIK 1549595) ===
  NRIX: 6 10-K filings since 2011
    2021-02-16  FY2020:  mda, properties, risk_factors
    2022-01-28  FY2021:  mda, properties, risk_factors
    2023-02-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 106 public document(s) but only 104 were parsed (accession 0001549595-24-000025). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-01-28  FY2024:  mda, properties, risk_factors
    2026-01-28  FY2025:  mda, properties, risk_factors
  -> 18 rows | 312,145 words | 0.92 MB
  -> /content/bond_shared/data/raw/text/NRIX_10K_sections.parquet

=== VERA — Vera Therapeutics, Inc. (CIK 1831828) ===
  VERA: 5 10-K filings since 2011
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 261,728 words | 0.78 MB
  -> /content/bond_shared/data/raw/text/VERA_10K_sections.parquet

=== SLS — SELLAS Life Sciences Group, Inc. (CIK 1390478) ===
  SLS: 16 10-K filings since 2011 (6 amendment(s) skipped)
    2011-04-15  FY2010:  mda, properties, risk_factors
    2012-03-28  FY2011:  mda, properties, risk_factors
    2013-03-12  FY2012:  mda, properties, risk_factors
    2014-03-17  FY2013:  mda, properties, risk_factors
    2015-03-05  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-04-13  FY2017:  mda, properties, risk_factors
    2019-03-22  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-23  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 48 rows | 510,422 words | 1.57 MB
  -> /content/bond_shared/data/raw/text/SLS_10K_sections.parquet

=== VRDN — Viridian Therapeutics, Inc.\DE (CIK 1590750) ===
  VRDN: 12 10-K filings since 2011 (2 amendment(s) skipped)
    2015-03-27  FY2014:  mda, properties, risk_factors
    2016-03-21  FY2015:  mda, properties, risk_factors
    2017-03-24  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-26  FY2020:  mda, properties, risk_factors
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0001590750-24-000007). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 36 rows | 382,530 words | 1.15 MB
  -> /content/bond_shared/data/raw/text/VRDN_10K_sections.parquet

=== AUPH — Aurinia Pharmaceuticals Inc. (CIK 1600620) ===
  AUPH: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 115 public document(s) but only 113 were parsed (accession 0001600620-24-000012). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 115,401 words | 0.37 MB
  -> /content/bond_shared/data/raw/text/AUPH_10K_sections.parquet

=== OCUL — OCULAR THERAPEUTIX, INC (CIK 1393434) ===
  OCUL: 12 10-K filings since 2011
    2015-03-20  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 115 public document(s) but only 113 were parsed (accession 0001558370-24-002902). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_757549: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6Reserved_324657: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)

    2024-03-11  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-05  FY2025:  mda, properties, risk_factors
  -> 36 rows | 529,396 words | 1.55 MB
  -> /content/bond_shared/data/raw/text/OCUL_10K_sections.parquet

=== ADMA — ADMA BIOLOGICS, INC. (CIK 1368514) ===
  ADMA: 15 10-K filings since 2011 (1 amendment(s) skipped)
    2011-09-27  FY2011:  mda, properties, risk_factors
    2013-03-06  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-09  FY2014:  mda, properties, risk_factors
    2016-03-23  FY2015:  mda, properties, risk_factors
    2017-02-24  FY2016:  mda, properties, risk_factors
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-13  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 90 public document(s) but only 88 were parsed (accession 0001140361-24-010147). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 45 rows | 386,769 words | 1.21 MB
  -> /content/bond_shared/data/raw/text/ADMA_10K_sections.parquet

=== TRVI — Trevi Therapeutics, Inc. (CIK 1563880) ===
  TRVI: 7 10-K filings since 2011
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-20  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 21 rows | 344,248 words | 0.99 MB
  -> /content/bond_shared/data/raw/text/TRVI_10K_sections.parquet

=== VCEL — Vericel Corp (CIK 887359) ===
  VCEL: 15 10-K filings since 2011 (1 amendment(s) skipped)
    2012-03-15  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-13  FY2013:  mda, properties, risk_factors
    2015-03-25  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-13  FY2016:  mda, properties, risk_factors
    2018-03-05  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 92 public document(s) but only 90 were parsed (accession 0001628280-24-007824). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 45 rows | 376,946 words | 1.16 MB
  -> /content/bond_shared/data/raw/text/VCEL_10K_sections.parquet

=== KOD — Kodiak Sciences Inc. (CIK 1468748) ===
  KOD: 8 10-K filings since 2011
    2019-03-27  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 24 rows | 324,707 words | 0.99 MB
  -> /content/bond_shared/data/raw/text/KOD_10K_sections.parquet

=== URGN — UroGen Pharma Ltd. (CIK 1668243) ===
  URGN: 8 10-K filings since 2011 (3 amendment(s) skipped)
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-21  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 110 public document(s) but only 108 were parsed (accession 0001437749-24-007753). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 24 rows | 388,476 words | 1.19 MB
  -> /content/bond_shared/data/raw/text/URGN_10K_sections.parquet

=== NUVB — Nuvation Bio Inc. (CIK 1811063) ===
  NUVB: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0000950170-24-023247). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 18 rows | 245,205 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/NUVB_10K_sections.parquet

=== RXRX — RECURSION PHARMACEUTICALS, INC. (CIK 1601830) ===
  RXRX: 5 10-K filings since 2011
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 177 public document(s) but only 175 were parsed (accession 0001601830-24-000019). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 15 rows | 225,737 words | 0.69 MB
  -> /content/bond_shared/data/raw/text/RXRX_10K_sections.parquet

=== PVLA — PALVELLA THERAPEUTICS, INC. (CIK 1583648) ===
  PVLA: 13 10-K filings since 2011 (6 amendment(s) skipped)
    2014-09-12  FY2014:  mda, risk_factors
    2015-03-30  FY2014:  mda, properties, risk_factors
    2016-03-23  FY2015:  mda, properties, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-02  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 38 rows | 467,460 words | 1.40 MB
  -> /content/bond_shared/data/raw/text/PVLA_10K_sections.parquet

=== MRVI — MARAVAI LIFESCIENCES HOLDINGS, INC. (CIK 1823239) ===
  MRVI: 6 10-K filings since 2011
    2021-03-22  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 144 public document(s) but only 142 were parsed (accession 0001823239-24-000032). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 278,445 words | 0.80 MB
  -> /content/bond_shared/data/raw/text/MRVI_10K_sections.parquet

=== SRPT — Sarepta Therapeutics, Inc. (CIK 873303) ===
  SRPT: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-15  FY2010:  mda, properties, risk_factors
    2012-03-13  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-02-26  FY2014:  mda, properties, risk_factors
    2016-02-25  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0000950170-24-022036). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 48 rows | 464,470 words | 1.44 MB
  -> /content/bond_shared/data/raw/text/SRPT_10K_sections.parquet

=== NKTR — NEKTAR THERAPEUTICS (CIK 906709) ===
  NKTR: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-01  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-02-27  FY2013:  mda, properties, risk_factors
    2015-02-26  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0000950170-24-026249). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-03-14  FY2024:  mda, properties, risk_factors
    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 364,087 words | 1.13 MB
  -> /content/bond_shared/data/raw/text/NKTR_10K_sections.parquet

=== AGIO — AGIOS PHARMACEUTICALS, INC. (CIK 1439222) ===
  AGIO: 13 10-K filings since 2011
    2014-03-18  FY2013:  mda, properties, risk_factors
    2015-02-24  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-02-16  FY2016:  mda, properties, risk_factors
    2018-02-14  FY2017:  mda, properties, risk_factors
    2019-02-14  FY2018:  mda, properties, risk_factors
    2020-02-19  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 107 public document(s) but only 105 were parsed (accession 0001439222-24-000035). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-13  FY2024:  mda, properties, risk_factors
    2026-02-12  FY2025:  mda, properties, risk_factors
  -> 39 rows | 446,045 words | 1.34 MB
  -> /content/bond_shared/data/raw/text/AGIO_10K_sections.parquet

=== VIR — Vir Biotechnology, Inc. (CIK 1706431) ===
  VIR: 7 10-K filings since 2011
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:datemonthyear; the raw display text is used instead

    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 102 public document(s) but only 100 were parsed (accession 0001628280-24-006852). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-23  FY2025:  mda, properties, risk_factors
  -> 21 rows | 275,511 words | 0.83 MB
  -> /content/bond_shared/data/raw/text/VIR_10K_sections.parquet

=== XNCR — Xencor Inc (CIK 1326732) ===
  XNCR: 13 10-K filings since 2011 (2 amendment(s) skipped)
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-02-20  FY2014:  mda, properties, risk_factors
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-02-28  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 106 public document(s) but only 104 were parsed (accession 0001326732-24-000006). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 39 rows | 383,340 words | 1.17 MB
  -> /content/bond_shared/data/raw/text/XNCR_10K_sections.parquet

=== NVAX — NOVAVAX INC (CIK 1000694) ===
  NVAX: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-28  FY2010:  mda, properties, risk_factors
    2012-03-14  FY2011:  mda, properties, risk_factors
    2013-03-12  FY2012:  mda, properties, risk_factors
    2014-03-12  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 128 public document(s) but only 126 were parsed (accession 0001000694-24-000007). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 408,010 words | 1.28 MB
  -> /content/bond_shared/data/raw/text/NVAX_10K_sections.parquet

=== ABSI — Absci Corp (CIK 1672688) ===
  ABSI: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-22  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-24  FY2025:  mda, properties, risk_factors
  -> 15 rows | 218,014 words | 0.66 MB
  -> /content/bond_shared/data/raw/text/ABSI_10K_sections.parquet

=== NTLA — Intellia Therapeutics, Inc. (CIK 1652130) ===
  NTLA: 10 10-K filings since 2011 (1 amendment(s) skipped)
    2017-03-14  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 95 public document(s) but only 93 were parsed (accession 0000950170-24-018736). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 30 rows | 401,395 words | 1.22 MB
  -> /content/bond_shared/data/raw/text/NTLA_10K_sections.parquet

=== SNDX — Syndax Pharmaceuticals Inc (CIK 1395937) ===
  SNDX: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-03-14  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-05  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 98 public document(s) but only 96 were parsed (accession 0000950170-24-021253). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 30 rows | 308,227 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/SNDX_10K_sections.parquet

=== STOK — Stoke Therapeutics, Inc. (CIK 1623526) ===
  STOK: 7 10-K filings since 2011
    2020-03-23  FY2019:  mda, properties, risk_factors
    2021-03-09  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 21 rows | 304,888 words | 0.91 MB
  -> /content/bond_shared/data/raw/text/STOK_10K_sections.parquet

=== ANAB — ANAPTYSBIO, INC (CIK 1370053) ===
  ANAB: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-03-08  FY2016:  mda, properties, risk_factors
    2018-03-05  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-07  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 140 public document(s) but only 138 were parsed (accession 0001370053-24-000011). The submission may be truncated or malformed.

    2024-03-11  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 30 rows | 346,544 words | 1.05 MB
  -> /content/bond_shared/data/raw/text/ANAB_10K_sections.parquet

=== TSHA — Taysha Gene Therapies, Inc. (CIK 1806310) ===
  TSHA: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-03  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 18 rows | 314,342 words | 0.94 MB
  -> /content/bond_shared/data/raw/text/TSHA_10K_sections.parquet

=== INVA — Innoviva, Inc. (CIK 1080014) ===
  INVA: 16 10-K filings since 2011 (8 amendment(s) skipped)
    2011-02-28  FY2010:  mda, properties, risk_factors
    2012-02-27  FY2011:  mda, properties, risk_factors
    2013-02-26  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-24  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-02-23  FY2017:  mda, properties, risk_factors
    2019-02-19  FY2018:  mda, properties, risk_factors
    2020-02-19  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0000950170-24-023237). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 48 rows | 390,334 words | 1.18 MB
  -> /content/bond_shared/data/raw/text/INVA_10K_sections.parquet

=== TYRA — Tyra Biosciences, Inc. (CIK 1863127) ===
  TYRA: 5 10-K filings since 2011
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 15 rows | 236,364 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/TYRA_10K_sections.parquet

=== OMER — OMEROS CORP (CIK 1285819) ===
  OMER: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-15  FY2010:  mda, properties, risk_factors
    2012-03-15  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-13  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-13  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 48 rows | 304,663 words | 0.92 MB
  -> /content/bond_shared/data/raw/text/OMER_10K_sections.parquet

=== RARE — Ultragenyx Pharmaceutical Inc. (CIK 1515673) ===
  RARE: 13 10-K filings since 2011
    2014-03-24  FY2013:  mda, properties, risk_factors
    2015-03-27  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-02-17  FY2016:  mda, properties, risk_factors
    2018-02-21  FY2017:  mda, properties, risk_factors
    2019-02-20  FY2018:  mda, properties, risk_factors
    2020-02-14  FY2019:  mda, properties, risk_factors
    2021-02-12  FY2020:  mda, properties, risk_factors
    2022-02-15  FY2021:  mda, properties, risk_factors
    2023-02-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 129 public document(s) but only 127 were parsed (accession 0000950170-24-017879). The submission may be truncated or malformed.

    2024-02-21  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-02-18  FY2025:  mda, properties, risk_factors
  -> 39 rows | 448,439 words | 1.36 MB
  -> /content/bond_shared/data/raw/text/RARE_10K_sections.parquet

=== KRSA — Korsana Biosciences, Inc. (CIK 1755237) ===
  KRSA: 7 10-K filings since 2011 (3 amendment(s) skipped)
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 96 public document(s) but only 94 were parsed (accession 0000950170-24-025935). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-03-04  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 21 rows | 186,330 words | 0.58 MB
  -> /content/bond_shared/data/raw/text/KRSA_10K_sections.parquet

=== ORIC — Oric Pharmaceuticals, Inc. (CIK 1796280) ===
  ORIC: 6 10-K filings since 2011
    2021-03-23  FY2020:  mda, properties, risk_factors
    2022-03-21  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0000950170-24-029298). The submission may be truncated or malformed.

    2024-03-11  FY2023:  mda, properties, risk_factors
    2025-02-18  FY2024:  mda, properties, risk_factors
    2026-02-23  FY2025:  mda, properties, risk_factors
  -> 18 rows | 310,656 words | 0.92 MB
  -> /content/bond_shared/data/raw/text/ORIC_10K_sections.parquet

=== DMRA — Damora Therapeutics, Inc. (CIK 1800315) ===
  DMRA: 6 10-K filings since 2011
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-02-17  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 87 public document(s) but only 85 were parsed (accession 0000950170-24-028610). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-19  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 18 rows | 288,114 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/DMRA_10K_sections.parquet

=== SVRA — Savara Inc (CIK 1160308) ===
  SVRA: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-10  FY2010:  mda, properties, risk_factors
    2012-03-08  FY2011:  mda, properties, risk_factors
    2013-03-19  FY2012:  mda, properties, risk_factors
    2014-03-26  FY2013:  mda, properties, risk_factors
    2015-03-24  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-06  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-13  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-10  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 90 public document(s) but only 88 were parsed (accession 0000950170-24-027920). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 421,882 words | 1.28 MB
  -> /content/bond_shared/data/raw/text/SVRA_10K_sections.parquet

=== REPL — Replimune Group, Inc. (CIK 1737953) ===
  REPL: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-06-28  FY2019:  mda, properties, risk_factors
    2020-06-03  FY2020:  mda, properties, risk_factors
    2021-05-20  FY2021:  mda, properties, risk_factors
    2022-05-19  FY2022:  mda, properties, risk_factors
    2023-05-18  FY2023:  mda, properties, risk_factors
    2024-05-16  FY2024:  mda, properties, risk_factors
    2025-05-22  FY2025:  mda, properties, risk_factors
    2026-06-29  FY2026:  mda, properties, risk_factors
  -> 24 rows | 292,506 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/REPL_10K_sections.parquet

=== VOR — Vor Biopharma Inc. (CIK 1817229) ===
  VOR: 6 10-K filings since 2011
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-14  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-20  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 18 rows | 295,461 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/VOR_10K_sections.parquet

=== MNKD — MANNKIND CORP (CIK 899460) ===
  MNKD: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-03-15  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 128 public document(s) but only 126 were parsed (accession 0000950170-24-021423). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 440,136 words | 1.33 MB
  -> /content/bond_shared/data/raw/text/MNKD_10K_sections.parquet

=== MGTX — MeiraGTx Holdings plc (CIK 1735438) ===
  MGTX: 8 10-K filings since 2011
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 107 public document(s) but only 105 were parsed (accession 0001558370-24-003309). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM1BUSINESS: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor ITEM1BUNRESOLVEDSTAFFCOMMENTS_990071 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM2PROPERTIES_193630: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM3LEGALPROCEEDINGS_611625: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM4MINESAFETYDISCLOSURES_266744: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM5MARKETFORREGISTRANTSCOMMONEQUITYREL: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM6SELECTEDFINANCIALDATA_777746: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM7MANAGEMENTSDISCUSSIONANDANALYSISOFF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM8FINANCIALSTATEMENTSANDSUPPLEMENTARY: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM10DIRECTORSEXECUTIVEOFFICERSANDCORPO: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM11EXECUTIVECOMPENSATION_771675: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM12SECURITYOWNERSHIPOFCERTAINBENEFICI: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM13CERTAINRELATIONSHIPSANDRELATEDTRAN: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM14PRINCIPALACCOUNTANTFEESANDSERVICES: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM15EXHIBITSANDFINANCIALSTATEMENTSCHED: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM16FORM10KSUMMARY_359105: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 24 rows | 387,406 words | 1.17 MB
  -> /content/bond_shared/data/raw/text/MGTX_10K_sections.parquet

=== MLTX — MoonLake Immunotherapeutics (CIK 1821586) ===
  MLTX: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-02-17  FY2021:  mda, properties, risk_factors
    2023-03-20  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 103 public document(s) but only 101 were parsed (accession 0001821586-24-000008). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 18 rows | 182,152 words | 0.54 MB
  -> /content/bond_shared/data/raw/text/MLTX_10K_sections.parquet

=== GLUE — Monte Rosa Therapeutics, Inc. (CIK 1826457) ===
  GLUE: 5 10-K filings since 2011
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 148 public document(s) but only 146 were parsed (accession 0000950170-24-031150). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 15 rows | 242,118 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/GLUE_10K_sections.parquet

=== JANX — Janux Therapeutics, Inc. (CIK 1817713) ===
  JANX: 5 10-K filings since 2011
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 95 public document(s) but only 93 were parsed (accession 0000950170-24-028659). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 238,176 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/JANX_10K_sections.parquet

=== CRVS — Corvus Pharmaceuticals, Inc. (CIK 1626971) ===
  CRVS: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-09  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 30 rows | 346,596 words | 1.03 MB
  -> /content/bond_shared/data/raw/text/CRVS_10K_sections.parquet

=== ABUS — Arbutus Biopharma Corp (CIK 1447028) ===
  ABUS: 13 10-K filings since 2011 (4 amendment(s) skipped)
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-03-09  FY2015:  mda, properties, risk_factors
    2017-03-22  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s5427299DAE1B502E8CA1A09F30BF23AA: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2018-03-16  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sEF0A14E65C7B52D6B84ED89A2A09E2E2: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-05  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0001447028-24-000035). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 39 rows | 295,710 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/ABUS_10K_sections.parquet

=== KURA — Kura Oncology, Inc. (CIK 1422143) ===
  KURA: 16 10-K filings since 2011
    2011-03-31  FY2010:  mda, risk_factors
    2012-03-30  FY2011:  mda, risk_factors
    2013-03-28  FY2012:  mda, risk_factors
    2014-03-31  FY2013:  mda, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-03-17  FY2015:  mda, properties, risk_factors
    2017-03-14  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-05  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 71 public document(s) but only 69 were parsed (accession 0000950170-24-021094). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 44 rows | 395,611 words | 1.18 MB
  -> /content/bond_shared/data/raw/text/KURA_10K_sections.parquet

=== CGEM — Cullinan Therapeutics, Inc. (CIK 1789972) ===
  CGEM: 6 10-K filings since 2011
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 118 public document(s) but only 116 were parsed (accession 0000950170-24-031143). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 18 rows | 295,724 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/CGEM_10K_sections.parquet

=== JBIO — Jade Biosciences, Inc. (CIK 1798749) ===
  JBIO: 5 10-K filings since 2011
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-06  FY2025:  mda, properties, risk_factors
  -> 15 rows | 186,404 words | 0.57 MB
  -> /content/bond_shared/data/raw/text/JBIO_10K_sections.parquet

=== RIGL — RIGEL PHARMACEUTICALS INC (CIK 1034842) ===
  RIGL: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-01  FY2010:  mda, properties, risk_factors
    2012-03-06  FY2011:  mda, properties, risk_factors
    2013-03-05  FY2012:  mda, properties, risk_factors
    2014-03-04  FY2013:  mda, properties, risk_factors
    2015-03-03  FY2014:  mda, properties, risk_factors
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-07  FY2016:  mda, properties, risk_factors
    2018-03-06  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-03-02  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 101 public document(s) but only 99 were parsed (accession 0001558370-24-002475). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_298179: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_266086 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_200104: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_293847: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_36543: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquity_52: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6Reserved: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysis_13: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_786646: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountingFeesandServices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsFinancialStatementSchedule: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_108120: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-03-04  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 48 rows | 444,866 words | 1.35 MB
  -> /content/bond_shared/data/raw/text/RIGL_10K_sections.parquet

=== SANA — Sana Biotechnology, Inc. (CIK 1770121) ===
  SANA: 6 10-K filings since 2011
    2021-03-24  FY2020:  mda, properties, risk_factors
    2022-03-16  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 120 public document(s) but only 118 were parsed (accession 0000950170-24-023119). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 18 rows | 399,384 words | 1.18 MB
  -> /content/bond_shared/data/raw/text/SANA_10K_sections.parquet

=== ARDX — ARDELYX, INC. (CIK 1437402) ===
  ARDX: 12 10-K filings since 2011 (1 amendment(s) skipped)
    2015-03-05  FY2014:  mda, properties, risk_factors
    2016-03-04  FY2015:  mda, properties, risk_factors
    2017-02-17  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-06  FY2018:  mda, properties, risk_factors
    2020-03-06  FY2019:  mda, properties, risk_factors
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 113 public document(s) but only 111 were parsed (accession 0001628280-24-006393). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 36 rows | 403,134 words | 1.21 MB
  -> /content/bond_shared/data/raw/text/ARDX_10K_sections.parquet

=== CADL — Candel Therapeutics, Inc. (CIK 1841387) ===
  CADL: 5 10-K filings since 2011 (2 amendment(s) skipped)
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 295,819 words | 0.88 MB
  -> /content/bond_shared/data/raw/text/CADL_10K_sections.parquet

=== AVTX — Avalo Therapeutics, Inc. (CIK 1534120) ===
  AVTX: 11 10-K filings since 2011 (3 amendment(s) skipped)
    2016-03-23  FY2015:  mda, properties, risk_factors
    2017-03-14  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-03-02  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 33 rows | 409,288 words | 1.23 MB
  -> /content/bond_shared/data/raw/text/AVTX_10K_sections.parquet

=== GERN — GERON CORP (CIK 886744) ===
  GERN: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-02-25  FY2010:  mda, properties, risk_factors
    2012-03-07  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-17  FY2013:  mda, properties, risk_factors
    2015-03-11  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 94 public document(s) but only 92 were parsed (accession 0000950170-24-022056). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 48 rows | 545,009 words | 1.63 MB
  -> /content/bond_shared/data/raw/text/GERN_10K_sections.parquet

=== FDMT — 4D Molecular Therapeutics, Inc. (CIK 1650648) ===
  FDMT: 6 10-K filings since 2011
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 107 public document(s) but only 105 were parsed (accession 0000950170-24-023183). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 18 rows | 300,752 words | 0.90 MB
  -> /content/bond_shared/data/raw/text/FDMT_10K_sections.parquet

=== LXRX — LEXICON PHARMACEUTICALS, INC. (CIK 1062822) ===
  LXRX: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-03-08  FY2011:  mda, properties, risk_factors
    2013-03-11  FY2012:  mda, properties, risk_factors
    2014-03-07  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-06  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-03  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-07  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 48 rows | 296,314 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/LXRX_10K_sections.parquet

=== IMMX — Immix Biopharma, Inc. (CIK 1873835) ===
  IMMX: 5 10-K filings since 2011 (2 amendment(s) skipped)

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-27  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 15 rows | 123,947 words | 0.39 MB
  -> /content/bond_shared/data/raw/text/IMMX_10K_sections.parquet

=== SLDB — Solid Biosciences Inc. (CIK 1707502) ===
  SLDB: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-13  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-14  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 107 public document(s) but only 105 were parsed (accession 0000950170-24-030508). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 27 rows | 429,626 words | 1.27 MB
  -> /content/bond_shared/data/raw/text/SLDB_10K_sections.parquet

=== GYRE — GYRE THERAPEUTICS, INC. (CIK 1124105) ===
  GYRE: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-11  FY2010:  mda, properties, risk_factors
    2012-03-06  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-09  FY2015:  mda, properties, risk_factors
    2017-03-08  FY2016:  mda, properties, risk_factors
    2018-03-19  FY2017:  mda, properties, risk_factors
    2019-03-08  FY2018:  mda, properties, risk_factors
    2020-02-20  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 503,458 words | 1.50 MB
  -> /content/bond_shared/data/raw/text/GYRE_10K_sections.parquet

=== ACHV — ACHIEVE LIFE SCIENCES, INC. (CIK 949858) ===
  ACHV: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-10  FY2010:  mda, properties, risk_factors
    2012-03-08  FY2011:  mda, properties, risk_factors
    2013-03-07  FY2012:  mda, properties, risk_factors
    2014-03-11  FY2013:  mda, properties, risk_factors
    2015-03-26  FY2014:  mda, properties, risk_factors
    2016-03-09  FY2015:  mda, properties, risk_factors
    2017-02-23  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-24  FY2025:  mda, properties, risk_factors
  -> 48 rows | 423,414 words | 1.27 MB
  -> /content/bond_shared/data/raw/text/ACHV_10K_sections.parquet

=== OLMA — Olema Pharmaceuticals, Inc. (CIK 1750284) ===
  OLMA: 6 10-K filings since 2011
    2021-03-17  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 89 public document(s) but only 87 were parsed (accession 0000950170-24-029281). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item1business_656638: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor item1bunresolvedstaffcomments_880672 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item2properties_585425: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item3legalproceedings_877218: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item4minesafetydisclosures_134638: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item5marketforregistrantscommonequity_48: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item6reserved_105312: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item7managementsdiscussionandanalysis_44: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item8fi: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item9changesinanddisagreements_95124: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor item9cdisclosureregardingforeignjurisdic sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item10directorsexecutiveofficers_466454: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item11executivecompensation_62120: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item12securityownershipofcertainbenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item13certainrelationshipsandrelatedtran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item14principalaccountingfees_835104: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item15exhibitsfinancialstatementschedule: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item16form10ksummary_189122: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-11  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item1business_656638: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor item1bunresolvedstaffcomments_880672 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item2properties_585425: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item3legalproceedings_877218: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item4minesafetydisclosures_134638: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item5marketforregistrantscommonequity_48: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item6reserved_105312: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item7managementsdiscussionandanalysis_44: part_ii_item_7 keeps the anchor; ['part_ii_item_7a', 'part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7a: body header shares the same anchor; part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item8fi: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item9changesinanddisagreements_95124: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor item9cdisclosureregardingforeignjurisdic sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item10directorsexecutiveofficers_466454: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item11executivecompensation_62120: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item12securityownershipofcertainbenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item13certainrelationshipsandrelatedtran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item14principalaccountingfees_835104: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item15exhibitsfinancialstatementschedule: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item16form10ksummary_189122: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2025-03-18  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item1business_656638: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor item1bunresolvedstaffcomments_880672 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item2properties_585425: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item3legalproceedings_877218: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item4minesafetydisclosures_134638: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item5marketforregistrantscommonequity_48: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item6reserved_105312: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item7managementsdiscussionandanalysis_44: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item8fi: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item9changesinanddisagreements_95124: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor item9cdisclosureregardingforeignjurisdic sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item10directorsexecutiveofficers_466454: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item11executivecompensation_62120: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item12securityownershipofcertainbenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item13certainrelationshipsandrelatedtran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item14principalaccountingfees_835104: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item15exhibitsfinancialstatementschedule: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item16form10ksummary_189122: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 18 rows | 307,707 words | 0.91 MB
  -> /content/bond_shared/data/raw/text/OLMA_10K_sections.parquet

=== DSGN — Design Therapeutics, Inc. (CIK 1807120) ===
  DSGN: 5 10-K filings since 2011
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.7' is not an English number; the raw display text is used instead

    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 15 rows | 236,752 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/DSGN_10K_sections.parquet

=== ACRS — Aclaris Therapeutics, Inc. (CIK 1557746) ===
  ACRS: 11 10-K filings since 2011 (1 amendment(s) skipped)
    2016-03-23  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0001558370-24-001753). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 81 public document(s) but only 79 were parsed (accession 0001104659-26-020540). The submission may be truncated or malformed.

    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 33 rows | 412,765 words | 1.19 MB
  -> /content/bond_shared/data/raw/text/ACRS_10K_sections.parquet

=== WVE — Wave Life Sciences, Inc. (CIK 1631574) ===
  WVE: 11 10-K filings since 2011 (13 amendment(s) skipped)
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 119 public document(s) but only 117 were parsed (accession 0000950170-24-026876). The submission may be truncated or malformed.

    2024-03-06  FY2023:  mda, properties, risk_factors
    2025-03-04  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 33 rows | 416,854 words | 1.24 MB
  -> /content/bond_shared/data/raw/text/WVE_10K_sections.parquet

=== FTH — Faeth Therapeutics, Inc. (CIK 1829802) ===
  FTH: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 98 public document(s) but only 96 were parsed (accession 0000950170-24-023148). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 18 rows | 252,686 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/FTH_10K_sections.parquet

=== DNA — Ginkgo Bioworks Holdings, Inc. (CIK 1830214) ===
  DNA: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-13  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 169 public document(s) but only 167 were parsed (accession 0001628280-24-008052). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 216,620 words | 0.66 MB
  -> /content/bond_shared/data/raw/text/DNA_10K_sections.parquet

=== VSTM — Verastem, Inc. (CIK 1526119) ===
  VSTM: 15 10-K filings since 2011
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-03-26  FY2012:  mda, properties, risk_factors
    2014-03-06  FY2013:  mda, properties, risk_factors
    2015-03-10  FY2014:  mda, properties, risk_factors
    2016-03-03  FY2015:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2017-03-23  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2018-03-13  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2019-03-12  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 108 public document(s) but only 106 were parsed (accession 0001558370-24-003250). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_630123: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_621403 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_314266: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_948111: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_401479: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6SelectedFinancialData_957616: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8ConsolidatedFinancialStatementsandS: part_ii_item_8 keeps the anchor; ['part_ii_item_8c'] still resolve(s) to the same span (part_ii_item_8c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item9ChangesinandDisagreementswithAccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor Item9CDisclosureREgardingForeignJurisdic sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM10DIRECTORSEXECUTIVEOFFICERSANDCORPO: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM11EXECUTIVECOMPENSATION_242284: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM12SECURITYOWNERSHIPOFCERTAINBENEFICI: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM13CERTAINRELATIONSHIPSANDRELATEDTRAN: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM14PRINCIPALACCOUNTANTFEESANDSERVICES: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-04  FY2025:  mda, properties, risk_factors
  -> 45 rows | 439,487 words | 1.31 MB
  -> /content/bond_shared/data/raw/text/VSTM_10K_sections.parquet

=== ANNX — Annexon, Inc. (CIK 1528115) ===
  ANNX: 6 10-K filings since 2011
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 18 rows | 244,520 words | 0.73 MB
  -> /content/bond_shared/data/raw/text/ANNX_10K_sections.parquet

=== DBVT — DBV Technologies S.A. (CIK 1613780) ===
  DBVT: 6 10-K filings since 2011 (3 amendment(s) skipped)
    2021-03-17  FY2020:  mda, properties, risk_factors
    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 141 public document(s) but only 139 were parsed (accession 0001193125-24-062357). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2025-04-11  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 253,582 words | 0.77 MB
  -> /content/bond_shared/data/raw/text/DBVT_10K_sections.parquet

=== MDXG — MIMEDX GROUP, INC. (CIK 1376339) ===
  MDXG: 15 10-K filings since 2011 (6 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-29  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-04  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2020-03-17  FY2018:  mda, properties, risk_factors
    2020-07-06  FY2019:  mda, properties, risk_factors
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 126 public document(s) but only 124 were parsed (accession 0001376339-24-000009). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 45 rows | 313,947 words | 0.97 MB
  -> /content/bond_shared/data/raw/text/MDXG_10K_sections.parquet

=== OABI — OmniAb, Inc. (CIK 1846253) ===
  OABI: 5 10-K filings since 2011
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-04  FY2025:  mda, properties, risk_factors
  -> 15 rows | 194,404 words | 0.57 MB
  -> /content/bond_shared/data/raw/text/OABI_10K_sections.parquet

=== CLYM — Climb Bio, Inc. (CIK 1768446) ===
  CLYM: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-07  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 15 rows | 211,356 words | 0.64 MB
  -> /content/bond_shared/data/raw/text/CLYM_10K_sections.parquet

=== NVCT — Nuvectis Pharma, Inc. (CIK 1875558) ===
  NVCT: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 80 public document(s) but only 78 were parsed (accession 0001558370-24-002497). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_220267: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor _9c2831c9_b589_44ff_8d5e_eb5599593a14 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_762763: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_482366: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_52515: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6RESERVED_658933: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisoft: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item9ChangesinandDisagreementswithAccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor Item9CDisclosureRegardingForeignJurisdic sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_845418: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountingFeesandServices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_605101: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-11  FY2025:  mda, properties, risk_factors
  -> 15 rows | 110,120 words | 0.34 MB
  -> /content/bond_shared/data/raw/text/NVCT_10K_sections.parquet

=== ZVRA — ZEVRA THERAPEUTICS, INC. (CIK 1434647) ===
  ZVRA: 11 10-K filings since 2011 (1 amendment(s) skipped)
    2016-03-16  FY2015:  mda, properties, risk_factors
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-30  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-12  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 33 rows | 523,763 words | 1.53 MB
  -> /content/bond_shared/data/raw/text/ZVRA_10K_sections.parquet

=== AURA — Aura Biosciences, Inc. (CIK 1501796) ===
  AURA: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 15 rows | 214,948 words | 0.64 MB
  -> /content/bond_shared/data/raw/text/AURA_10K_sections.parquet

=== CRMD — CorMedix Inc. (CIK 1410098) ===
  CRMD: 16 10-K filings since 2011 (6 amendment(s) skipped)
    2011-03-11  FY2010:  mda, properties, risk_factors
    2012-03-19  FY2011:  mda, properties, risk_factors
    2013-03-27  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-19  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_015: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)

    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 71 public document(s) but only 69 were parsed (accession 0001213900-24-021585). The submission may be truncated or malformed.

    2024-03-12  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 48 rows | 320,345 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/CRMD_10K_sections.parquet

=== STTK — Shattuck Labs, Inc. (CIK 1680367) ===
  STTK: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 90 public document(s) but only 88 were parsed (accession 0001680367-24-000014). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 18 rows | 133,970 words | 0.41 MB
  -> /content/bond_shared/data/raw/text/STTK_10K_sections.parquet

=== CBIO — CRESCENT BIOPHARMA, INC. (CIK 1253689) ===
  CBIO: 13 10-K filings since 2011
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-06  FY2017:  mda, properties, risk_factors
    2019-03-06  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-03-02  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-02-13  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 39 rows | 376,051 words | 1.14 MB
  -> /content/bond_shared/data/raw/text/CBIO_10K_sections.parquet

=== ALT — Altimmune, Inc. (CIK 1326190) ===
  ALT: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-08  FY2011:  mda, properties, risk_factors
    2013-03-14  FY2012:  mda, properties, risk_factors
    2014-03-11  FY2013:  mda, properties, risk_factors
    2015-03-11  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-14  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-06  FY2025:  mda, properties, risk_factors
  -> 48 rows | 445,351 words | 1.36 MB
  -> /content/bond_shared/data/raw/text/ALT_10K_sections.parquet

=== CTMX — CytomX Therapeutics, Inc. (CIK 1501989) ===
  CTMX: 11 10-K filings since 2011 (3 amendment(s) skipped)
    2016-03-07  FY2015:  mda, properties, risk_factors
    2017-03-02  FY2016:  mda, properties, risk_factors
    2018-03-07  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0000950170-24-029191). The submission may be truncated or malformed.

    2024-03-11  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 33 rows | 451,041 words | 1.36 MB
  -> /content/bond_shared/data/raw/text/CTMX_10K_sections.parquet

=== PHAT — Phathom Pharmaceuticals, Inc. (CIK 1783183) ===
  PHAT: 7 10-K filings since 2011 (1 amendment(s) skipped)
    2020-03-19  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 98 public document(s) but only 96 were parsed (accession 0000950170-24-027910). The submission may be truncated or malformed.
WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.3' is not an English number; the raw display text is used instead

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 21 rows | 345,542 words | 1.02 MB
  -> /content/bond_shared/data/raw/text/PHAT_10K_sections.parquet

=== MNPR — Monopar Therapeutics (CIK 1645469) ===
  MNPR: 9 10-K filings since 2011 (2 amendment(s) skipped)
    2018-03-26  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 27 rows | 267,601 words | 0.85 MB
  -> /content/bond_shared/data/raw/text/MNPR_10K_sections.parquet

=== ALLO — Allogene Therapeutics, Inc. (CIK 1737287) ===
  ALLO: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-03-08  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-23  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 109 public document(s) but only 107 were parsed (accession 0001737287-24-000021). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 24 rows | 322,050 words | 0.98 MB
  -> /content/bond_shared/data/raw/text/ALLO_10K_sections.parquet

=== NGNE — Neurogene Inc. (CIK 1404644) ===
  NGNE: 12 10-K filings since 2011 (1 amendment(s) skipped)
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-09  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-20  FY2022:  mda, properties, risk_factors
    2024-03-18  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-24  FY2025:  mda, properties, risk_factors
  -> 36 rows | 445,954 words | 1.35 MB
  -> /content/bond_shared/data/raw/text/NGNE_10K_sections.parquet

=== INDP — Indaptus Therapeutics, Inc. (CIK 1857044) ===
  INDP: 5 10-K filings since 2011
    2022-03-21  FY2021:  mda, properties, risk_factors
    2023-03-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 72 public document(s) but only 70 were parsed (accession 0001493152-24-009769). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 15 rows | 137,844 words | 0.43 MB
  -> /content/bond_shared/data/raw/text/INDP_10K_sections.parquet

=== PBYI — PUMA BIOTECHNOLOGY, INC. (CIK 1401667) ===
  PBYI: 16 10-K filings since 2011
    2011-03-30  FY2010:  mda, risk_factors
    2012-03-29  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 96 public document(s) but only 94 were parsed (accession 0001437749-24-006121). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 47 rows | 406,073 words | 1.23 MB
  -> /content/bond_shared/data/raw/text/PBYI_10K_sections.parquet

=== ARVN — ARVINAS, INC. (CIK 1655759) ===
  ARVN: 8 10-K filings since 2011
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 98 public document(s) but only 96 were parsed (accession 0001655759-24-000018). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-11  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 24 rows | 329,725 words | 0.98 MB
  -> /content/bond_shared/data/raw/text/ARVN_10K_sections.parquet

=== RGNX — REGENXBIO Inc. (CIK 1590877) ===
  RGNX: 11 10-K filings since 2011
    2016-03-03  FY2015:  mda, properties, risk_factors
    2017-03-07  FY2016:  mda, properties, risk_factors
    2018-03-06  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 114 public document(s) but only 112 were parsed (accession 0000950170-24-021161). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 33 rows | 438,140 words | 1.29 MB
  -> /content/bond_shared/data/raw/text/RGNX_10K_sections.parquet

=== CAPR — CAPRICOR THERAPEUTICS, INC. (CIK 1133869) ===
  CAPR: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-14  FY2010:  mda, properties, risk_factors
    2012-04-02  FY2011:  mda, properties, risk_factors
    2013-06-21  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-22  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_001: part_i_item_1 keeps the anchor; ['part_i_item_1a'] still resolve(s) to the same span (part_i_item_1a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_009: part_iii_item_10 keeps the anchor; ['part_iii_item_11'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors)

    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 65 public document(s) but only 63 were parsed (accession 0001558370-24-002861). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM2PROPERTIES_686301: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM3LEGALPROCEEDINGS_177465: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM4MINESAFETYDISCLOSURES_831629: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM5MARKETFORREGISTRANTSCOMMONEQUITYREL: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM6SELECTEDFINANCIALDATA_208778: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM7MANAGEMENTSDISCUSSIONANDANALYSISOFF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM8FINANCIALSTATEMENTSANDSUPPLEMENTARY: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM9CHANGESINANDDISAGREEMENTSWITHACCOUN: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM10DIRECTORSEXECUTIVEOFFICERSANDCORPO: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM11EXECUTIVECOMPENSATION_737825: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM12SECURITYOWNERSHIPOFCERTAINBENEFICI: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM13CERTAINRELATIONSHIPSANDRELATEDTRAN: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM14PRINCIPALACCOUNTINGFEESANDSERVICES: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM15EXHIBITSANDFINANCIALSTATEMENTSCHED: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM16FORM10KSUMMARY_363246: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-11  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 79 public document(s) but only 77 were parsed (accession 0001558370-25-003707). The submission may be truncated or malformed.

    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 48 rows | 560,550 words | 1.73 MB
  -> /content/bond_shared/data/raw/text/CAPR_10K_sections.parquet

=== PROK — PROKIDNEY CORP. (CIK 1850270) ===
  PROK: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-22  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 15 rows | 248,330 words | 0.73 MB
  -> /content/bond_shared/data/raw/text/PROK_10K_sections.parquet

=== ASMB — ASSEMBLY BIOSCIENCES, INC. (CIK 1426800) ===
  ASMB: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-04-13  FY2010:  mda, properties, risk_factors
    2012-03-14  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-02  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-03-04  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 48 rows | 332,464 words | 1.03 MB
  -> /content/bond_shared/data/raw/text/ASMB_10K_sections.parquet

=== ENTX — Entera Bio Ltd. (CIK 1638097) ===
  ENTX: 5 10-K filings since 2011 (1 amendment(s) skipped)

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM1601: part_i_item_1 keeps the anchor; ['part_i_item_1601'] still resolve(s) to the same span (part_i_item_1601: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM1601A: part_i_item_1a keeps the anchor; ['part_i_item_1601a'] still resolve(s) to the same span (part_i_item_1601a: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM1601B.160: part_i_item_1b keeps the anchor; ['part_i_item_1601b'] still resolve(s) to the same span (part_i_item_1601b: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1602.: part_i_item_2 keeps the anchor; ['part_i_item_1602'] still resolve(s) to the same span (part_i_item_1602: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1603: part_i_item_3 keeps the anchor; ['part_i_item_1603'] still resolve(s) to the same span (part_i_item_1603: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1604.: part_i_item_4 keeps the anchor; ['part_i_item_1604'] still resolve(s) to the same span (part_i_item_1604: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1605.: part_ii_item_5 keeps the anchor; ['part_ii_item_1605'] still resolve(s) to the same span (part_ii_item_1605: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1606.: part_ii_item_6 keeps the anchor; ['part_ii_item_1606'] still resolve(s) to the same span (part_ii_item_1606: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1607.: part_ii_item_7 keeps the anchor; ['part_ii_item_1607'] still resolve(s) to the same span (part_ii_item_1607: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1607A.: part_ii_item_7a keeps the anchor; ['part_ii_item_1607a'] still resolve(s) to the same span (part_ii_item_1607a: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1608.: part_ii_item_8 keeps the anchor; ['part_ii_item_1608'] still resolve(s) to the same span (part_ii_item_1608: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1609.: part_ii_item_9 keeps the anchor; ['part_ii_item_1609'] still resolve(s) to the same span (part_ii_item_1609: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1609A.: part_ii_item_9a keeps the anchor; ['part_ii_item_1609a'] still resolve(s) to the same span (part_ii_item_1609a: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1609B.: part_ii_item_9b keeps the anchor; ['part_ii_item_1609b'] still resolve(s) to the same span (part_ii_item_1609b: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16011.: part_iii_item_11 keeps the anchor; ['part_iii_item_16011'] still resolve(s) to the same span (part_iii_item_16011: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16012.: part_iii_item_12 keeps the anchor; ['part_iii_item_16012'] still resolve(s) to the same span (part_iii_item_16012: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16013.: part_iii_item_13 keeps the anchor; ['part_iii_item_16013'] still resolve(s) to the same span (part_iii_item_16013: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16014.: part_iii_item_14 keeps the anchor; ['part_iii_item_16014'] still resolve(s) to the same span (part_iii_item_16014: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16015.: part_iv_item_15 keeps the anchor; ['part_iv_item_16015'] still resolve(s) to the same span (part_iv_item_16015: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16016: part_iv_item_16 keeps the anchor; ['part_iv_item_16016'] still resolve(s) to the same span (part_iv_item_16016: no body header for this item)

    2022-03-08  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 15 rows | 202,581 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/ENTX_10K_sections.parquet

=== OVID — Ovid Therapeutics Inc. (CIK 1636651) ===
  OVID: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-13  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 150 public document(s) but only 148 were parsed (accession 0001628280-24-009809). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 27 rows | 287,925 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/OVID_10K_sections.parquet

=== TECX — Tectonic Therapeutic, Inc. (CIK 1681087) ===
  TECX: 8 10-K filings since 2011
    2019-03-25  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 84 public document(s) but only 82 were parsed (accession 0000950170-24-031635). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 24 rows | 369,038 words | 1.11 MB
  -> /content/bond_shared/data/raw/text/TECX_10K_sections.parquet

=== DMAC — DiaMedica Therapeutics Inc. (CIK 1401040) ===
  DMAC: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-03-19  FY2018:  mda, properties, risk_factors
    2020-03-23  FY2019:  mda, properties, risk_factors
    2021-03-10  FY2020:  mda, properties, risk_factors
    2022-03-14  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 24 rows | 168,286 words | 0.53 MB
  -> /content/bond_shared/data/raw/text/DMAC_10K_sections.parquet

=== PRTA — PROTHENA CORP PUBLIC LTD CO (CIK 1559053) ===
  PRTA: 14 10-K filings since 2011 (1 amendment(s) skipped)
    2013-03-29  FY2012:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s0225E3279AD76F33B27859496E8F8CB5: part_i_item_1 keeps the anchor; ['part_i_item_3', 'part_ii_item_5', 'part_iii_item_10'] still resolve(s) to the same span (part_i_item_3: no body-header anchors; part_ii_item_5: no body-header anchors; part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sBC26DCB750C38351FD1C59496EC16830: part_i_item_1a keeps the anchor; ['part_iii_item_11'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s05228BDAD4EE7BEB4E3459496F39C1F6: part_i_item_4 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sA380B0D843D4F5EBEC9259496E3FE1AC: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2014-03-07  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s69D32CD11E1375CC4BAA5409D6C642C3: part_i_item_1 keeps the anchor; ['part_ii_item_5', 'part_iii_item_10'] still resolve(s) to the same span (part_ii_item_5: no body-header anchors; part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sB28B25FF816CE7D308645409D63C2701: part_i_item_1a keeps the anchor; ['part_ii_item_6', 'part_iii_item_11'] still resolve(s) to the same span (part_ii_item_6: no body-header anchors; part_iii_item_11: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s42DB019EB5D66C6C70B55409D7364263: part_i_item_2 keeps the anchor; ['part_iii_item_12'] still resolve(s) to the same span (part_iii_item_12: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s78E828F117A854EABB825409D6E3051C: part_ii_item_9 keeps the anchor; ['part_iii_item_14', 'part_iv_item_15'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors; part_iv_item_15: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sD6457FF4750D0340DF195409DCF18A30: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2015-03-13  FY2014:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sE97101C4B7C6FC59386CCA44CB4C552B: part_i_item_1 keeps the anchor; ['part_ii_item_5', 'part_iii_item_10'] still resolve(s) to the same span (part_ii_item_5: no body-header anchors; part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sACD28272EF20497C528ECA44CAC0199E: part_i_item_1a keeps the anchor; ['part_ii_item_6', 'part_iii_item_11'] still resolve(s) to the same span (part_ii_item_6: no body-header anchors; part_iii_item_11: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s459909B2D73A2EFF7EAACA44CBBAB2E0: part_i_item_2 keeps the anchor; ['part_iii_item_12'] still resolve(s) to the same span (part_iii_item_12: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s648B9C17031D811009B9CA44CB60996A: part_ii_item_9 keeps the anchor; ['part_iii_item_14', 'part_iv_item_15'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors; part_iv_item_15: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sE5D416C13530BE9BEC4ACA44D1C8798B: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2016-02-25  FY2015:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s1B76AF8FD25D64796BDF6A8F1867DFEB: part_i_item_1 keeps the anchor; ['part_ii_item_5', 'part_iii_item_10'] still resolve(s) to the same span (part_ii_item_5: no body-header anchors; part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sEE05969A95ABFA5C4BB96A8F17E5BA62: part_i_item_1a keeps the anchor; ['part_ii_item_6', 'part_iii_item_11'] still resolve(s) to the same span (part_ii_item_6: no body-header anchors; part_iii_item_11: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sD47AD04807BCCFAE8B636A8F18DFC611: part_i_item_2 keeps the anchor; ['part_iii_item_12'] still resolve(s) to the same span (part_iii_item_12: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s634AA6D3DD9A12E36FF76A8F18859739: part_ii_item_9 keeps the anchor; ['part_iii_item_14', 'part_iv_item_15'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors; part_iv_item_15: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sAB43C1B21A29644770836A8F1E611D1C: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2017-02-27  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s5C3505E467E15F1EAB1C7486EE6346B1: part_i_item_1 keeps the anchor; ['part_ii_item_5', 'part_iii_item_10'] still resolve(s) to the same span (part_ii_item_5: no body-header anchors; part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sD07AB17AE3390110CCFD7486EDC7F788: part_i_item_1a keeps the anchor; ['part_ii_item_6', 'part_iii_item_11'] still resolve(s) to the same span (part_ii_item_6: no body-header anchors; part_iii_item_11: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sC8F3CE98F95A5100D27E7486EEC1C96E: part_i_item_2 keeps the anchor; ['part_iii_item_12'] still resolve(s) to the same span (part_iii_item_12: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s1A789E14F3E79F6F5EAD7486EE82C086: part_ii_item_9 keeps the anchor; ['part_iii_item_14', 'part_iv_item_15'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors; part_iv_item_15: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sF9D72F1B9B4DC672A1A97486F6BC158B: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2018-02-26  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sDD6FB4D6F580786525A6E5D6554FB180: part_i_item_1 keeps the anchor; ['part_ii_item_5', 'part_iii_item_10'] still resolve(s) to the same span (part_ii_item_5: no body-header anchors; part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sC0F1ED0614211C9AD10DE5D654E1FFA5: part_i_item_1a keeps the anchor; ['part_ii_item_6', 'part_iii_item_11'] still resolve(s) to the same span (part_ii_item_6: no body-header anchors; part_iii_item_11: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s63205175FE42FA4281C9E5D655DB530F: part_i_item_2 keeps the anchor; ['part_iii_item_12'] still resolve(s) to the same span (part_iii_item_12: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s8D7F80269094C59E4E9CE5D6557DF9E1: part_ii_item_9 keeps the anchor; ['part_iii_item_14', 'part_iv_item_15'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors; part_iv_item_15: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sFA5DF64A213F98D70CE6E5D65BC713C3: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2019-03-15  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s3457C8EF2C2DC68BA1D021D1EEE06833: part_i_item_1 keeps the anchor; ['part_ii_item_5', 'part_iii_item_10'] still resolve(s) to the same span (part_ii_item_5: no body-header anchors; part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s3497ECD8D39CD423A06221D1EE5BCC7E: part_i_item_1a keeps the anchor; ['part_ii_item_6', 'part_iii_item_11'] still resolve(s) to the same span (part_ii_item_6: no body-header anchors; part_iii_item_11: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sA284557168F5DDB9A73021D1EF578CAA: part_i_item_2 keeps the anchor; ['part_iii_item_12'] still resolve(s) to the same span (part_iii_item_12: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s2CD25D8DF8E22EA748E421D1EF02DE8F: part_ii_item_9 keeps the anchor; ['part_iii_item_14', 'part_iv_item_15'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors; part_iv_item_15: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sE61B3D6E4B426D99E20121D1F60BBA8E: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2020-03-03  FY2019:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on idd887af305c54dfcb7e3228c3f6b1813_34: part_i_item_1 keeps the anchor; ['part_ii_item_5', 'part_iii_item_10'] still resolve(s) to the same span (part_ii_item_5: body anchor idd887af305c54dfcb7e3228c3f6b1813_43 already claimed; part_iii_item_10: body anchor idd887af305c54dfcb7e3228c3f6b1813_157 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on idd887af305c54dfcb7e3228c3f6b1813_25: part_i_item_1a keeps the anchor; ['part_ii_item_6', 'part_iii_item_11'] still resolve(s) to the same span (part_ii_item_6: body anchor idd887af305c54dfcb7e3228c3f6b1813_46 sits past the next item; part_iii_item_11: body anchor idd887af305c54dfcb7e3228c3f6b1813_160 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on idd887af305c54dfcb7e3228c3f6b1813_43: part_i_item_2 keeps the anchor; ['part_iii_item_12'] still resolve(s) to the same span (part_iii_item_12: body anchor idd887af305c54dfcb7e3228c3f6b1813_163 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on idd887af305c54dfcb7e3228c3f6b1813_37: part_ii_item_9 keeps the anchor; ['part_iii_item_14', 'part_iv_item_15'] still resolve(s) to the same span (part_iii_item_14: body anchor idd887af305c54dfcb7e3228c3f6b1813_169 sits past the next item; part_iv_item_15: body anchor idd887af305c54dfcb7e3228c3f6b1813_175 sits past the next item)

    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 87 public document(s) but only 85 were parsed (accession 0001559053-24-000008). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 42 rows | 403,335 words | 1.20 MB
  -> /content/bond_shared/data/raw/text/PRTA_10K_sections.parquet

=== AVIR — Atea Pharmaceuticals, Inc. (CIK 1593899) ===
  AVIR: 6 10-K filings since 2011
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0000950170-24-022226). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 18 rows | 334,150 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/AVIR_10K_sections.parquet

=== RZLT — Rezolute, Inc. (CIK 1509261) ===
  RZLT: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-09-22  FY2011:  mda, properties, risk_factors
    2012-11-05  FY2012:  mda, properties, risk_factors
    2013-09-11  FY2013:  mda, properties, risk_factors
    2014-09-30  FY2014:  mda, properties, risk_factors
    2015-09-28  FY2015:  mda, properties, risk_factors
    2016-09-28  FY2016:  mda, properties, risk_factors
    2017-09-22  FY2017:  mda, properties, risk_factors
    2018-10-15  FY2018:  mda, properties, risk_factors
    2019-09-10  FY2019:  mda, properties, risk_factors
    2020-10-13  FY2020:  mda, properties, risk_factors
    2021-09-15  FY2021:  mda, properties, risk_factors
    2022-09-15  FY2022:  mda, properties, risk_factors
    2023-09-14  FY2023:  mda, properties, risk_factors
    2024-09-19  FY2024:  mda, properties, risk_factors
    2025-09-17  FY2025:  mda, properties, risk_factors
    2026-09-24  FY2026:  mda, properties, risk_factors
  -> 48 rows | 213,854 words | 0.65 MB
  -> /content/bond_shared/data/raw/text/RZLT_10K_sections.parquet

=== RLMD — RELMADA THERAPEUTICS, INC. (CIK 1553643) ===
  RLMD: 12 10-K filings since 2011
    2013-12-16  FY2013:  mda, properties
    2015-09-11  FY2015:  mda, properties, risk_factors
    2016-09-09  FY2016:  mda, properties, risk_factors
    2017-09-28  FY2017:  mda, properties, risk_factors
    2018-09-28  FY2018:  mda, properties, risk_factors
    2019-09-24  FY2019:  mda, properties, risk_factors
    2021-03-24  FY2020:  mda, properties, risk_factors
    2022-03-25  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 35 rows | 235,274 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/RLMD_10K_sections.parquet

=== SPRY — ARS Pharmaceuticals, Inc. (CIK 1671858) ===
  SPRY: 6 10-K filings since 2011
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 18 rows | 289,632 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/SPRY_10K_sections.parquet

=== PRLD — Prelude Therapeutics Inc (CIK 1678660) ===
  PRLD: 6 10-K filings since 2011
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 77 public document(s) but only 75 were parsed (accession 0000950170-24-016016). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 18 rows | 269,780 words | 0.80 MB
  -> /content/bond_shared/data/raw/text/PRLD_10K_sections.parquet

=== EDIT — Editas Medicine, Inc. (CIK 1650664) ===
  EDIT: 11 10-K filings since 2011
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-03  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-22  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 102 public document(s) but only 100 were parsed (accession 0001650664-24-000008). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-03-05  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 33 rows | 495,375 words | 1.45 MB
  -> /content/bond_shared/data/raw/text/EDIT_10K_sections.parquet

=== IRD — Opus Genetics, Inc. (CIK 1228627) ===
  IRD: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-03-16  FY2011:  mda, properties, risk_factors
    2013-03-22  FY2012:  mda, properties, risk_factors
    2014-03-21  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-02-24  FY2016:  mda, properties, risk_factors
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-02-21  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 94 public document(s) but only 92 were parsed (accession 0001140361-24-012399). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 366,334 words | 1.13 MB
  -> /content/bond_shared/data/raw/text/IRD_10K_sections.parquet

=== ARCT — Arcturus Therapeutics Holdings Inc. (CIK 1768224) ===
  ARCT: 7 10-K filings since 2011
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 106 public document(s) but only 104 were parsed (accession 0000950170-24-031156). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 21 rows | 184,409 words | 0.57 MB
  -> /content/bond_shared/data/raw/text/ARCT_10K_sections.parquet

=== GALT — GALECTIN THERAPEUTICS INC (CIK 1133416) ===
  GALT: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-15  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-03-29  FY2012:  mda, properties, risk_factors
    2014-03-21  FY2013:  mda, properties, risk_factors
    2015-03-18  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-28  FY2016:  mda, properties, risk_factors
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-06  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 48 rows | 216,856 words | 0.67 MB
  -> /content/bond_shared/data/raw/text/GALT_10K_sections.parquet

=== ZURA — Zura Bio Ltd (CIK 1855644) ===
  ZURA: 5 10-K filings since 2011
    2022-04-11  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 15 rows | 152,740 words | 0.45 MB
  -> /content/bond_shared/data/raw/text/ZURA_10K_sections.parquet

=== AGEN — AGENUS INC (CIK 1098972) ===
  AGEN: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-03-06  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-07  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 126 public document(s) but only 124 were parsed (accession 0000950170-24-031620). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 48 rows | 568,165 words | 1.73 MB
  -> /content/bond_shared/data/raw/text/AGEN_10K_sections.parquet

=== VTVT — vTv Therapeutics Inc. (CIK 1641489) ===
  VTVT: 11 10-K filings since 2011 (2 amendment(s) skipped)
    2016-03-04  FY2015:  mda, properties, risk_factors
    2017-02-24  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-21  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 140 public document(s) but only 138 were parsed (accession 0001641489-24-000012). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 33 rows | 364,641 words | 1.08 MB
  -> /content/bond_shared/data/raw/text/VTVT_10K_sections.parquet

=== IKT — Inhibikase Therapeutics, Inc. (CIK 1750149) ===
  IKT: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 282,453 words | 0.85 MB
  -> /content/bond_shared/data/raw/text/IKT_10K_sections.parquet

=== FENC — FENNEC PHARMACEUTICALS INC. (CIK 1211583) ===
  FENC: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-27  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-28  FY2015:  mda, properties, risk_factors
    2017-03-29  FY2016:  mda, properties, risk_factors
    2018-03-28  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-02-14  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 349,285 words | 1.08 MB
  -> /content/bond_shared/data/raw/text/FENC_10K_sections.parquet

=== CCCC — C4 Therapeutics, Inc. (CIK 1662579) ===
  CCCC: 6 10-K filings since 2011
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 234 public document(s) but only 232 were parsed (accession 0001628280-24-006144). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 268,982 words | 0.80 MB
  -> /content/bond_shared/data/raw/text/CCCC_10K_sections.parquet

=== OBIO — Orchestra BioMed Holdings, Inc. (CIK 1814114) ===
  OBIO: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-10  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-01-25  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 18 rows | 160,827 words | 0.48 MB
  -> /content/bond_shared/data/raw/text/OBIO_10K_sections.parquet

=== CABA — Cabaletta Bio, Inc. (CIK 1759138) ===
  CABA: 7 10-K filings since 2011
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 21 rows | 397,110 words | 1.19 MB
  -> /content/bond_shared/data/raw/text/CABA_10K_sections.parquet

=== SRZN — Surrozen, Inc./DE (CIK 1824893) ===
  SRZN: 6 10-K filings since 2011 (2 amendment(s) skipped)

WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found

    2021-03-31  FY2020:  NONE
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-10  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 15 rows | 208,362 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/SRZN_10K_sections.parquet

=== ENTA — ENANTA PHARMACEUTICALS INC (CIK 1177648) ===
  ENTA: 13 10-K filings since 2011 (1 amendment(s) skipped)
    2013-12-18  FY2013:  mda, properties, risk_factors
    2014-12-11  FY2014:  mda, properties, risk_factors
    2015-12-11  FY2015:  mda, properties, risk_factors
    2016-12-09  FY2016:  mda, properties, risk_factors
    2017-12-11  FY2017:  mda, properties, risk_factors
    2018-11-29  FY2018:  mda, properties, risk_factors
    2019-11-27  FY2019:  mda, properties, risk_factors
    2020-11-25  FY2020:  mda, properties, risk_factors
    2021-11-24  FY2021:  mda, properties, risk_factors
    2022-11-23  FY2022:  mda, properties, risk_factors
    2023-11-22  FY2023:  mda, properties, risk_factors
    2024-11-27  FY2024:  mda, properties, risk_factors
    2025-11-19  FY2025:  mda, properties, risk_factors
  -> 39 rows | 354,584 words | 1.08 MB
  -> /content/bond_shared/data/raw/text/ENTA_10K_sections.parquet

=== OCGN — Ocugen, Inc. (CIK 1372299) ===
  OCGN: 12 10-K filings since 2011 (2 amendment(s) skipped)
    2015-03-27  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-22  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-19  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors
    2024-04-16  FY2023:  mda, properties, risk_factors
    2025-03-05  FY2024:  mda, properties, risk_factors
    2026-03-04  FY2025:  mda, properties, risk_factors
  -> 36 rows | 480,067 words | 1.45 MB
  -> /content/bond_shared/data/raw/text/OCGN_10K_sections.parquet

=== BNTC — Benitec Biopharma Inc. (CIK 1808898) ===
  BNTC: 7 10-K filings since 2011 (1 amendment(s) skipped)
    2020-09-23  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'USA' is not an EDGAR state, province or country name; the raw display text is used instead

    2021-09-20  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'USA' is not an EDGAR state, province or country name; the raw display text is used instead

    2022-09-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'USA' is not an EDGAR state, province or country name; the raw display text is used instead

    2023-09-21  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'USA' is not an EDGAR state, province or country name; the raw display text is used instead

    2024-09-26  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'USA' is not an EDGAR state, province or country name; the raw display text is used instead

    2025-09-22  FY2025:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'USA' is not an EDGAR state, province or country name; the raw display text is used instead

    2026-09-14  FY2026:  mda, properties, risk_factors
  -> 21 rows | 230,869 words | 0.70 MB
  -> /content/bond_shared/data/raw/text/BNTC_10K_sections.parquet

=== LRMR — Larimar Therapeutics, Inc. (CIK 1374690) ===
  LRMR: 12 10-K filings since 2011 (1 amendment(s) skipped)
    2015-03-25  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-05  FY2019:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM2PROPERTIES_264380: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM3LEGALPROCEEDINGS_49550: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM4MINESAFETYDISCLOSURES_57184: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM5MARKETFORREGISTRANTSSCOMMONEQUITY_9: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM6SELECTEDCONSOLIDATEDFINANCIALDATA_6: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM7MANAGEMENTSDISCUSSIONANDANALYSIS_41: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM8FINANCIALSTATEMENTSANDSUPPLEMENTARY: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM9CHANGESINANDDISAGREEMENTSWITHACCOUN: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM10DIRECTORSEXECUTIVEOFFICERSANDCORPO: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM11EXECUTIVECOMPENSATION_214372: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM12SECURITYOWNERSHIPOFCERTAINBENEFICI: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM13CERTAINRELATIONSHIPSANDRELATEDTRAN: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM14PRINCIPALACCOUNTINGFEESANDSERVICES: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM15EXHIBITSFINANCIALSTATEMENTSCHEDULE: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body-header anchors)

    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-25  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 82 public document(s) but only 80 were parsed (accession 0000950170-24-031529). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item1business_796317: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor item1bunresolvedstaffcomments_265117 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item2properties_264380: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item3legalproceedings_49550: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item4minesafetydisclosures_57184: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item5marketforregistrantsscommonequity_9: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item6selectedconsolidatedfinancialdata_6: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item7managementsdiscussionandanalysis_41: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item8financialstatementsandsupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item9changesinanddisagreementswithaccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor item9cforeignjurisdictions sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item10directorsexecutiveofficersandcorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item11executivecompensation_214372: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item12securityownershipofcertainbenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item13certainrelationshipsandrelatedtran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item14principalaccountingfeesandservices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item15exhibitsfinancialstatementschedule: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 36 rows | 416,552 words | 1.25 MB
  -> /content/bond_shared/data/raw/text/LRMR_10K_sections.parquet

=== EYPT — EyePoint, Inc. (CIK 1314102) ===
  EYPT: 15 10-K filings since 2011 (4 amendment(s) skipped)
    2011-09-13  FY2011:  mda, properties, risk_factors
    2012-09-27  FY2012:  mda, properties, risk_factors
    2013-09-27  FY2013:  mda, properties, risk_factors
    2014-09-11  FY2014:  mda, properties, risk_factors
    2015-09-10  FY2015:  mda, properties, risk_factors
    2016-09-13  FY2016:  mda, properties, risk_factors
    2017-09-13  FY2017:  mda, properties, risk_factors
    2018-09-18  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-03-14  FY2021:  mda, properties, risk_factors
    2023-03-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 104 public document(s) but only 102 were parsed (accession 0000950170-24-028523). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 45 rows | 408,742 words | 1.26 MB
  -> /content/bond_shared/data/raw/text/EYPT_10K_sections.parquet

=== ABEO — ABEONA THERAPEUTICS INC. (CIK 318306) ===
  ABEO: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-23  FY2011:  mda, properties, risk_factors
    2013-03-20  FY2012:  mda, properties, risk_factors
    2014-03-26  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-24  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2024-03-18  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 48 rows | 299,212 words | 0.92 MB
  -> /content/bond_shared/data/raw/text/ABEO_10K_sections.parquet

=== VNDA — Vanda Pharmaceuticals Inc. (CIK 1347178) ===
  VNDA: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-10  FY2010:  mda, properties, risk_factors
    2012-03-09  FY2011:  mda, properties, risk_factors
    2013-02-26  FY2012:  mda, properties, risk_factors
    2014-02-25  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-02-12  FY2015:  mda, properties, risk_factors
    2017-02-17  FY2016:  mda, properties, risk_factors
    2018-02-15  FY2017:  mda, properties, risk_factors
    2019-02-19  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-11  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 114 public document(s) but only 112 were parsed (accession 0001628280-24-003785). The submission may be truncated or malformed.

    2024-02-08  FY2023:  mda, properties, risk_factors
    2025-02-14  FY2024:  mda, properties, risk_factors
    2026-02-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 407,691 words | 1.24 MB
  -> /content/bond_shared/data/raw/text/VNDA_10K_sections.parquet

=== IPSC — Century Therapeutics, Inc. (CIK 1850119) ===
  IPSC: 5 10-K filings since 2011
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 162 public document(s) but only 160 were parsed (accession 0001558370-24-003165). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM1BUSINESS_178016: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor ITEM1BUNRESOLVEDSTAFFCOMMENTS_27446 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM2PROPERTIES_612983: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM3LEGALPROCEEDINGS_727712: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM4MINESAFETYDISCLOSURES_177027: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM5MARKETFORREGISTRANTSCOMMONEQUITYREL: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM6RESERVED: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM7MANAGEMENTSDISCUSSIONANDANALYSISOFF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM8FINANCIALSTATEMENTSANDSUPPLEMENTARY: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM10DIRECTORSEXECUTIVEOFFICERSANDCORPO: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM11EXECUTIVECOMPENSATION_430101: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM12SECURITYOWNERSHIPOFCERTAINBENEFICI: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM13CERTAINRELATIONSHIPSANDRELATEDTRAN: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM14PRINCIPALACCOUNTINGFEESANDSERVICES: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM15EXHIBITSFINANCIALSTATEMENTSCHEDULE: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-19  FY2024:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 120 public document(s) but only 118 were parsed (accession 0001104659-26-026759). The submission may be truncated or malformed.

    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 245,421 words | 0.74 MB
  -> /content/bond_shared/data/raw/text/IPSC_10K_sections.parquet

=== SABS — SAB Biotherapeutics, Inc. (CIK 1833214) ===
  SABS: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-04-02  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-04-14  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 18 rows | 199,553 words | 0.61 MB
  -> /content/bond_shared/data/raw/text/SABS_10K_sections.parquet

=== XFOR — X4 Pharmaceuticals, Inc (CIK 1501697) ===
  XFOR: 9 10-K filings since 2011
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-11  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-19  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-21  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 27 rows | 324,007 words | 0.96 MB
  -> /content/bond_shared/data/raw/text/XFOR_10K_sections.parquet

=== FULC — Fulcrum Therapeutics, Inc. (CIK 1680581) ===
  FULC: 7 10-K filings since 2011 (3 amendment(s) skipped)
    2020-03-05  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 96 public document(s) but only 94 were parsed (accession 0000950170-24-021074). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 21 rows | 295,333 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/FULC_10K_sections.parquet

=== RCKT — ROCKET PHARMACEUTICALS, INC. (CIK 1281895) ===
  RCKT: 12 10-K filings since 2011
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-23  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-07  FY2017:  mda, properties, risk_factors
    2019-03-08  FY2018:  mda, properties, risk_factors
    2020-03-06  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 112 public document(s) but only 110 were parsed (accession 0000950170-24-021096). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 36 rows | 384,103 words | 1.18 MB
  -> /content/bond_shared/data/raw/text/RCKT_10K_sections.parquet

=== FATE — FATE THERAPEUTICS INC (CIK 1434316) ===
  FATE: 13 10-K filings since 2011
    2014-03-17  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-03  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-05  FY2017:  mda, properties, risk_factors
    2019-03-05  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 87 public document(s) but only 85 were parsed (accession 0000950170-24-020158). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-03-05  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 39 rows | 470,114 words | 1.37 MB
  -> /content/bond_shared/data/raw/text/FATE_10K_sections.parquet

=== IMRX — Immuneering Corp (CIK 1790340) ===
  IMRX: 5 10-K filings since 2011
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 119 public document(s) but only 117 were parsed (accession 0001790340-24-000024). The submission may be truncated or malformed.

    2024-03-01  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-06  FY2025:  mda, properties, risk_factors
  -> 15 rows | 257,581 words | 0.76 MB
  -> /content/bond_shared/data/raw/text/IMRX_10K_sections.parquet

=== IVVD — Invivyd, Inc. (CIK 1832038) ===
  IVVD: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 15 rows | 324,940 words | 0.96 MB
  -> /content/bond_shared/data/raw/text/IVVD_10K_sections.parquet

=== GLSI — Greenwich LifeSciences, Inc. (CIK 1799788) ===
  GLSI: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-21  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-15  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-06-01  FY2025:  mda, properties, risk_factors
  -> 18 rows | 168,699 words | 0.54 MB
  -> /content/bond_shared/data/raw/text/GLSI_10K_sections.parquet

=== STRO — SUTRO BIOPHARMA, INC. (CIK 1382101) ===
  STRO: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:datequarterend; the raw display text is used instead

    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 24 rows | 395,414 words | 1.19 MB
  -> /content/bond_shared/data/raw/text/STRO_10K_sections.parquet

=== QTTB — Q32 Bio Inc. (CIK 1661998) ===
  QTTB: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 117 public document(s) but only 115 were parsed (accession 0000950170-24-030478). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 24 rows | 391,610 words | 1.17 MB
  -> /content/bond_shared/data/raw/text/QTTB_10K_sections.parquet

=== LCTX — Lineage Cell Therapeutics, Inc. (CIK 876343) ===
  LCTX: 16 10-K filings since 2011 (13 amendment(s) skipped)
    2011-03-15  FY2010:  mda, properties, risk_factors
    2012-03-14  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-17  FY2013:  mda, properties, risk_factors
    2015-03-11  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 116 public document(s) but only 114 were parsed (accession 0000950170-24-027988). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 48 rows | 464,752 words | 1.42 MB
  -> /content/bond_shared/data/raw/text/LCTX_10K_sections.parquet

=== BCYC — BICYCLE THERAPEUTICS PLC (CIK 1761612) ===
  BCYC: 7 10-K filings since 2011
    2020-03-10  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2022-03-01  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 124 public document(s) but only 122 were parsed (accession 0001558370-24-001324). The submission may be truncated or malformed.
WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM1BUSINESS_1823: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor ITEM1BUNRESOLVEDSTAFFCOMMENTS_724560 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM7MANAGEMENTSDISCUSSIONANDANALYSISOFF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM8FINANCIALSTATEMENTSANDSUPPLEMENTARY: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)

    2024-02-20  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2025-02-25  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 21 rows | 364,974 words | 1.10 MB
  -> /content/bond_shared/data/raw/text/BCYC_10K_sections.parquet

=== ZNTL — Zentalis Pharmaceuticals, Inc. (CIK 1725160) ===
  ZNTL: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 228 public document(s) but only 226 were parsed (accession 0001725160-24-000080). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 281,626 words | 0.84 MB
  -> /content/bond_shared/data/raw/text/ZNTL_10K_sections.parquet

=== PALI — PALISADE BIO, INC. (CIK 1357459) ===
  PALI: 16 10-K filings since 2011
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-10  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-23  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-22  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-22  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-20  FY2025:  mda, properties, risk_factors
  -> 48 rows | 275,810 words | 0.85 MB
  -> /content/bond_shared/data/raw/text/PALI_10K_sections.parquet

=== LYEL — Lyell Immunopharma, Inc. (CIK 1806952) ===
  LYEL: 5 10-K filings since 2011
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 111 public document(s) but only 109 were parsed (accession 0001628280-24-007592). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 194,340 words | 0.59 MB
  -> /content/bond_shared/data/raw/text/LYEL_10K_sections.parquet

=== PYXS — Pyxis Oncology, Inc. (CIK 1782223) ===
  PYXS: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 15 rows | 233,418 words | 0.70 MB
  -> /content/bond_shared/data/raw/text/PYXS_10K_sections.parquet

=== MGNX — MACROGENICS INC (CIK 1125345) ===
  MGNX: 13 10-K filings since 2011 (2 amendment(s) skipped)
    2014-03-20  FY2013:  mda, properties, risk_factors
    2015-03-03  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-25  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 88 public document(s) but only 86 were parsed (accession 0001125345-24-000060). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 39 rows | 369,881 words | 1.13 MB
  -> /content/bond_shared/data/raw/text/MGNX_10K_sections.parquet

=== YARW — Yarrow Bioscience, Inc. (CIK 1566044) ===
  YARW: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-03-28  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-03-03  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 94 public document(s) but only 92 were parsed (accession 0001628280-24-008178). The submission may be truncated or malformed.

    2024-03-01  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 27 rows | 318,149 words | 0.97 MB
  -> /content/bond_shared/data/raw/text/YARW_10K_sections.parquet

=== KROS — Keros Therapeutics, Inc. (CIK 1664710) ===
  KROS: 6 10-K filings since 2011
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-03  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 111 public document(s) but only 109 were parsed (accession 0001664710-24-000017). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-03-04  FY2025:  mda, properties, risk_factors
  -> 18 rows | 316,653 words | 0.94 MB
  -> /content/bond_shared/data/raw/text/KROS_10K_sections.parquet

=== CUE — Cue Biopharma, Inc. (CIK 1645460) ===
  CUE: 9 10-K filings since 2011 (4 amendment(s) skipped)
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-09  FY2020:  mda, properties, risk_factors
    2022-03-16  FY2021:  mda, properties, risk_factors
    2023-03-21  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 27 rows | 312,763 words | 0.95 MB
  -> /content/bond_shared/data/raw/text/CUE_10K_sections.parquet

=== RNAC — Cartesian Therapeutics, Inc. (CIK 1453687) ===
  RNAC: 10 10-K filings since 2011 (1 amendment(s) skipped)

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s6c31de25c577413bbfb2ef16faa43761: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2017-03-28  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s293888C2ED9050CC94813A052F9FFCA8: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)

    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 140 public document(s) but only 138 were parsed (accession 0001453687-24-000036). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 30 rows | 351,525 words | 1.06 MB
  -> /content/bond_shared/data/raw/text/RNAC_10K_sections.parquet

=== TRDA — Entrada Therapeutics, Inc. (CIK 1689375) ===
  TRDA: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 132 public document(s) but only 130 were parsed (accession 0001689375-24-000016). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 297,233 words | 0.88 MB
  -> /content/bond_shared/data/raw/text/TRDA_10K_sections.parquet

=== AVXL — ANAVEX LIFE SCIENCES CORP. (CIK 1314052) ===
  AVXL: 15 10-K filings since 2011 (4 amendment(s) skipped)

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_30: part_i_item_1b keeps the anchor; ['part_i_item_2', 'part_i_item_3'] still resolve(s) to the same span (part_i_item_2: no body-header anchors; part_i_item_3: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_31: part_i_item_4 keeps the anchor; ['part_ii_item_5'] still resolve(s) to the same span (part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_33: part_ii_item_6 keeps the anchor; ['part_ii_item_7'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_41: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_43: part_ii_item_9b keeps the anchor; ['part_iii_item_10'] still resolve(s) to the same span (part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_55: part_iii_item_14 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)

    2011-12-22  FY2011:  mda, properties

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_26: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_27: part_i_item_3 keeps the anchor; ['part_i_item_4', 'part_ii_item_5'] still resolve(s) to the same span (part_i_item_4: no body-header anchors; part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_30: part_ii_item_6 keeps the anchor; ['part_ii_item_7'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_36: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_38: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)

    2012-12-31  FY2012:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_23: part_i_item_1b keeps the anchor; ['part_i_item_2', 'part_i_item_3'] still resolve(s) to the same span (part_i_item_2: no body-header anchors; part_i_item_3: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_27: part_ii_item_6 keeps the anchor; ['part_ii_item_7'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_33: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_35: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_47: part_iii_item_13 keeps the anchor; ['part_iii_item_14'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors)

    2013-12-30  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_22: part_i_item_1b keeps the anchor; ['part_i_item_2', 'part_i_item_3', 'part_i_item_4'] still resolve(s) to the same span (part_i_item_2: no body-header anchors; part_i_item_3: no body-header anchors; part_i_item_4: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_25: part_ii_item_6 keeps the anchor; ['part_ii_item_7'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_32: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_34: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)

    2014-12-29  FY2014:  mda, properties, risk_factors
    2015-12-29  FY2015:  mda, properties, risk_factors
    2016-12-14  FY2016:  mda, properties, risk_factors
    2017-12-11  FY2017:  mda, properties, risk_factors
    2018-12-12  FY2018:  mda, properties, risk_factors
    2019-12-16  FY2019:  mda, properties, risk_factors
    2020-12-28  FY2020:  mda, properties, risk_factors
    2021-11-24  FY2021:  mda, properties, risk_factors
    2022-11-28  FY2022:  mda, properties, risk_factors
    2023-11-27  FY2023:  mda, properties, risk_factors
    2024-12-23  FY2024:  mda, properties, risk_factors
    2025-11-25  FY2025:  mda, properties, risk_factors
  -> 44 rows | 198,067 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/AVXL_10K_sections.parquet

=== PLX — Protalix BioTherapeutics, Inc. (CIK 1006281) ===
  PLX: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-02-23  FY2010:  mda, properties, risk_factors
    2012-02-27  FY2011:  mda, properties, risk_factors
    2013-02-28  FY2012:  mda, properties, risk_factors
    2014-03-13  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-06  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 103 public document(s) but only 101 were parsed (accession 0001558370-24-003161). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_89253: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_626044 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_907582: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_932888: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_147620: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6Reserved: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item9ChangesinandDisagreementswithAccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor Item9C sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_376320: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountantFeesandServices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_450405: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 48 rows | 369,079 words | 1.10 MB
  -> /content/bond_shared/data/raw/text/PLX_10K_sections.parquet

=== ALEC — Alector, Inc. (CIK 1653087) ===
  ALEC: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-24  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 95 public document(s) but only 93 were parsed (accession 0000950170-24-021183). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 24 rows | 339,101 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/ALEC_10K_sections.parquet

=== ELDN — Eledon Pharmaceuticals, Inc. (CIK 1404281) ===
  ELDN: 12 10-K filings since 2011 (5 amendment(s) skipped)
    2015-03-26  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-03  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-28  FY2018:  mda, properties, risk_factors
    2020-03-17  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 36 rows | 286,532 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/ELDN_10K_sections.parquet

=== WHWK — Whitehawk Therapeutics, Inc. (CIK 1422142) ===
  WHWK: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-31  FY2010:  mda, risk_factors
    2012-03-30  FY2011:  mda, risk_factors
    2013-03-28  FY2012:  mda, risk_factors
    2014-03-31  FY2013:  mda, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-07  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 94 public document(s) but only 92 were parsed (accession 0001628280-24-010901). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 44 rows | 448,990 words | 1.32 MB
  -> /content/bond_shared/data/raw/text/WHWK_10K_sections.parquet

=== FHTX — Foghorn Therapeutics Inc. (CIK 1822462) ===
  FHTX: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 98 public document(s) but only 96 were parsed (accession 0001628280-24-009539). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ie443eb9107a941be8ee6627d3be7f8ca_1428: part_i_item_1c keeps the anchor; ['part_i_item_1'] still resolve(s) to the same span (part_i_item_1: body anchor ie443eb9107a941be8ee6627d3be7f8ca_13 does not follow the shared one)

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-11  FY2025:  mda, properties, risk_factors
  -> 18 rows | 163,202 words | 0.49 MB
  -> /content/bond_shared/data/raw/text/FHTX_10K_sections.parquet

=== CNTN — Canton Strategic Holdings, Inc. (CIK 1861657) ===
  CNTN: 5 10-K filings since 2011 (1 amendment(s) skipped)

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2022-04-01  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 68 public document(s) but only 66 were parsed (accession 0001493152-24-007612). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 15 rows | 167,910 words | 0.53 MB
  -> /content/bond_shared/data/raw/text/CNTN_10K_sections.parquet

=== CMPX — Compass Therapeutics, Inc. (CIK 1738021) ===
  CMPX: 8 10-K filings since 2011
    2019-07-01  FY2019:  mda, properties, risk_factors
    2020-06-08  FY2020:  mda, properties, risk_factors
    2021-03-05  FY2020:  mda, properties, risk_factors
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 24 rows | 254,134 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/CMPX_10K_sections.parquet

=== NKTX — Nkarta, Inc. (CIK 1787400) ===
  NKTX: 6 10-K filings since 2011
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.4' is not an English number; the raw display text is used instead

    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 18 rows | 266,727 words | 0.81 MB
  -> /content/bond_shared/data/raw/text/NKTX_10K_sections.parquet

=== ORMP — ORAMED PHARMACEUTICALS INC. (CIK 1176309) ===
  ORMP: 15 10-K filings since 2011 (2 amendment(s) skipped)
    2011-11-29  FY2011:  mda, properties, risk_factors
    2012-12-12  FY2012:  mda, properties, risk_factors
    2013-11-27  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on 111: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: no body-header anchors)

    2014-11-14  FY2014:  mda, properties, risk_factors
    2015-11-25  FY2015:  mda, properties, risk_factors
    2016-11-25  FY2016:  mda, properties, risk_factors
    2017-11-29  FY2017:  mda, properties, risk_factors
    2018-11-28  FY2018:  mda, properties, risk_factors
    2019-11-27  FY2019:  mda, properties, risk_factors
    2020-11-24  FY2020:  mda, properties, risk_factors
    2021-11-24  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 103 public document(s) but only 101 were parsed (accession 0001213900-24-020485). The submission may be truncated or malformed.

    2024-03-06  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 45 rows | 205,678 words | 0.63 MB
  -> /content/bond_shared/data/raw/text/ORMP_10K_sections.parquet

=== TARA — Protara Therapeutics, Inc. (CIK 1359931) ===
  TARA: 12 10-K filings since 2011 (2 amendment(s) skipped)
    2015-03-20  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-13  FY2018:  mda, properties, risk_factors
    2020-03-20  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 96 public document(s) but only 94 were parsed (accession 0001213900-24-021982). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-05  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 36 rows | 378,627 words | 1.18 MB
  -> /content/bond_shared/data/raw/text/TARA_10K_sections.parquet

=== ALXO — ALX ONCOLOGY HOLDINGS INC (CIK 1810182) ===
  ALXO: 6 10-K filings since 2011
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 104 public document(s) but only 102 were parsed (accession 0000950170-24-027955). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 18 rows | 286,642 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/ALXO_10K_sections.parquet

=== CHRS — Coherus Oncology, Inc. (CIK 1512762) ===
  CHRS: 12 10-K filings since 2011
    2015-03-23  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-14  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-23  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 150 public document(s) but only 148 were parsed (accession 0001558370-24-003436). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_217063: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_157284 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM1LegalProceedings_470595: part_i_item_3 keeps the anchor; ['part_i_item_1l'] still resolve(s) to the same span (part_i_item_1l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_55198: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_762796: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8ConsolidatedFinancialStatementsandS: part_ii_item_8 keeps the anchor; ['part_ii_item_8c'] still resolve(s) to the same span (part_ii_item_8c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_746019: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountingFeesandServices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_259502: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 126 public document(s) but only 124 were parsed (accession 0001104659-26-025308). The submission may be truncated or malformed.

    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 36 rows | 538,029 words | 1.62 MB
  -> /content/bond_shared/data/raw/text/CHRS_10K_sections.parquet

=== DTIL — PRECISION BIOSCIENCES INC (CIK 1357874) ===
  DTIL: 7 10-K filings since 2011
    2020-03-10  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 21 rows | 390,634 words | 1.17 MB
  -> /content/bond_shared/data/raw/text/DTIL_10K_sections.parquet

=== TNXP — Tonix Pharmaceuticals Holding Corp. (CIK 1430306) ===

WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found

  TNXP: 16 10-K filings since 2011 (4 amendment(s) skipped)

WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found

    2011-03-02  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-03-11  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-03-03  FY2015:  mda, properties, risk_factors
    2017-04-13  FY2016:  mda, properties, risk_factors
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-24  FY2019:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on tnxp10kitem11: part_ii_item_8 keeps the anchor; ['part_ii_item_11'] still resolve(s) to the same span (part_ii_item_11: no body-header anchors)

    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-14  FY2021:  mda, properties, risk_factors
    2023-03-13  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 412,228 words | 1.27 MB
  -> /content/bond_shared/data/raw/text/TNXP_10K_sections.parquet

=== VYGR — Voyager Therapeutics, Inc. (CIK 1640266) ===
  VYGR: 11 10-K filings since 2011
    2016-03-17  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-03-03  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-08  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 93 public document(s) but only 91 were parsed (accession 0001558370-24-001988). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM2PROPERTIES_682609: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM3LEGALPROCEEDINGS_984289: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM4MINESAFETYDISCLOSURES_959299: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM5MARKETFORREGISTRANSCOMMONEQUITY_894: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM6SELECTEDFINANCIALDATA_488868: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM8FINANCIALSTATEMENTSANDSUPPLEMENTARY: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM9CHANGESINANDDISAGREEMENTSWITHACCOUN: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM10DIRECTORSEXECUTIVEOFFICERS_684410: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM11EXECUTIVECOMPENSATION_719927: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM12SECURITYOWNERSHIPOFCERTAINBENEFICI: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM13CERTAILRELATIONSHIPSANDRELATEDTRAN: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM14PRINCIPALACCOUNTANTFEESANDSERVICES: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM15EXHIBITSANDFINANCIALSTATEMENTSCHED: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 33 rows | 540,471 words | 1.61 MB
  -> /content/bond_shared/data/raw/text/VYGR_10K_sections.parquet

=== NERV — Minerva Neurosciences, Inc. (CIK 1598646) ===
  NERV: 12 10-K filings since 2011 (5 amendment(s) skipped)
    2015-03-26  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-13  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-03-09  FY2019:  mda, properties, risk_factors
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 60 public document(s) but only 58 were parsed (accession 0000950170-24-018392). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-03-11  FY2025:  mda, properties, risk_factors
  -> 36 rows | 422,548 words | 1.29 MB
  -> /content/bond_shared/data/raw/text/NERV_10K_sections.parquet

=== ABOS — Acumen Pharmaceuticals, Inc. (CIK 1576885) ===
  ABOS: 5 10-K filings since 2011
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-27  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 234,662 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/ABOS_10K_sections.parquet

=== OTLK — Outlook Therapeutics, Inc. (CIK 1649989) ===
  OTLK: 10 10-K filings since 2011 (6 amendment(s) skipped)
    2016-12-29  FY2016:  mda, properties, risk_factors
    2017-12-29  FY2017:  mda, properties, risk_factors
    2018-12-18  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item5i_007: part_ii_item_5 keeps the anchor; ['part_ii_item_5i'] still resolve(s) to the same span (part_ii_item_5i: no body-header anchors)

    2019-12-19  FY2019:  mda, properties, risk_factors
    2020-12-23  FY2020:  mda, properties, risk_factors
    2021-12-23  FY2021:  mda, properties, risk_factors
    2022-12-29  FY2022:  mda, properties, risk_factors
    2023-12-22  FY2023:  mda, properties, risk_factors
    2024-12-27  FY2024:  mda, properties, risk_factors
    2025-12-19  FY2025:  mda, properties, risk_factors
  -> 30 rows | 422,960 words | 1.26 MB
  -> /content/bond_shared/data/raw/text/OTLK_10K_sections.parquet

=== HUMA — Humacyte, Inc. (CIK 1818382) ===
  HUMA: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-02-16  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 18 rows | 219,097 words | 0.64 MB
  -> /content/bond_shared/data/raw/text/HUMA_10K_sections.parquet

=== CDXS — CODEXIS, INC. (CIK 1200375) ===
  CDXS: 16 10-K filings since 2011
    2011-02-10  FY2010:  mda, properties, risk_factors
    2012-03-05  FY2011:  mda, properties, risk_factors
    2013-04-02  FY2012:  mda, properties, risk_factors
    2014-03-13  FY2013:  mda, properties, risk_factors
    2015-03-06  FY2014:  mda, properties, risk_factors
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-09  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 126 public document(s) but only 124 were parsed (accession 0001200375-24-000009). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-11  FY2025:  mda, properties, risk_factors
  -> 48 rows | 489,912 words | 1.46 MB
  -> /content/bond_shared/data/raw/text/CDXS_10K_sections.parquet

=== KRRO — Korro Bio, Inc. (CIK 1703647) ===
  KRRO: 7 10-K filings since 2011 (1 amendment(s) skipped)
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-10  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 21 rows | 320,865 words | 0.95 MB
  -> /content/bond_shared/data/raw/text/KRRO_10K_sections.parquet

=== SPRB — SPRUCE BIOSCIENCES, INC. (CIK 1683553) ===
  SPRB: 6 10-K filings since 2011
    2021-03-22  FY2020:  mda, properties, risk_factors
    2022-03-14  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-18  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 18 rows | 302,463 words | 0.90 MB
  -> /content/bond_shared/data/raw/text/SPRB_10K_sections.parquet

=== ARMP — Armata Pharmaceuticals, Inc. (CIK 921114) ===
  ARMP: 13 10-K filings since 2011 (4 amendment(s) skipped)
    2014-04-15  FY2013:  mda, properties, risk_factors
    2015-04-15  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-27  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-25  FY2018:  mda, properties, risk_factors
    2020-03-19  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 39 rows | 272,545 words | 0.84 MB
  -> /content/bond_shared/data/raw/text/ARMP_10K_sections.parquet

=== CRBP — Corbus Pharmaceuticals Holdings, Inc. (CIK 1595097) ===
  CRBP: 12 10-K filings since 2011 (1 amendment(s) skipped)
    2015-02-10  FY2014:  mda, properties, risk_factors
    2016-03-28  FY2015:  mda, properties, risk_factors
    2017-03-08  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-08  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 109 public document(s) but only 107 were parsed (accession 0000950170-24-030133). The submission may be truncated or malformed.

    2024-03-12  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 36 rows | 302,870 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/CRBP_10K_sections.parquet

=== TNYA — Tenaya Therapeutics, Inc. (CIK 1858848) ===
  TNYA: 5 10-K filings since 2011
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors
    2024-03-18  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-11  FY2025:  mda, properties, risk_factors
  -> 15 rows | 240,562 words | 0.73 MB
  -> /content/bond_shared/data/raw/text/TNYA_10K_sections.parquet

=== HURA — TuHURA Biosciences, Inc./NV (CIK 1498382) ===
  HURA: 15 10-K filings since 2011 (3 amendment(s) skipped)
    2011-09-28  FY2011:  mda, properties, risk_factors

WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found

    2012-10-15  FY2012:  mda, properties, risk_factors
    2014-03-10  FY2013:  mda, properties, risk_factors
    2015-09-03  FY2015:  mda, properties, risk_factors
    2016-09-13  FY2016:  mda, properties, risk_factors
    2017-09-27  FY2017:  mda, properties, risk_factors
    2018-09-24  FY2018:  mda, properties, risk_factors
    2019-09-09  FY2019:  mda, properties, risk_factors
    2020-09-18  FY2020:  mda, properties, risk_factors
    2021-09-28  FY2021:  mda, properties, risk_factors
    2022-09-27  FY2022:  mda, properties, risk_factors
    2023-09-18  FY2023:  mda, properties, risk_factors
    2024-10-07  FY2024:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 45 rows | 325,879 words | 0.96 MB
  -> /content/bond_shared/data/raw/text/HURA_10K_sections.parquet

=== CRBU — Caribou Biosciences, Inc. (CIK 1619856) ===
  CRBU: 5 10-K filings since 2011
    2022-03-21  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 141 public document(s) but only 139 were parsed (accession 0001619856-24-000013). The submission may be truncated or malformed.

    2024-03-11  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 15 rows | 254,016 words | 0.76 MB
  -> /content/bond_shared/data/raw/text/CRBU_10K_sections.parquet

=== UNCY — Unicycive Therapeutics, Inc. (CIK 1766140) ===
  UNCY: 5 10-K filings since 2011
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 15 rows | 128,004 words | 0.41 MB
  -> /content/bond_shared/data/raw/text/UNCY_10K_sections.parquet

=== NRXP — NRX Pharmaceuticals, Inc. (CIK 1719406) ===
  NRXP: 9 10-K filings since 2011 (6 amendment(s) skipped)
    2018-03-23  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, risk_factors
    2021-04-01  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-14  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:durmonth rejected the content: '825.' is not an English number; the raw display text is used instead

    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 26 rows | 227,320 words | 0.68 MB
  -> /content/bond_shared/data/raw/text/NRXP_10K_sections.parquet

=== IMUX — IMMUNIC, INC. (CIK 1280776) ===
  IMUX: 12 10-K filings since 2011 (2 amendment(s) skipped)
    2015-03-20  FY2014:  mda, properties, risk_factors
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-07  FY2016:  mda, properties, risk_factors
    2018-03-13  FY2017:  mda, properties, risk_factors
    2019-03-04  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 118 public document(s) but only 116 were parsed (accession 0001280776-24-000004). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 36 rows | 409,546 words | 1.23 MB
  -> /content/bond_shared/data/raw/text/IMUX_10K_sections.parquet

=== MNOV — MEDICINOVA INC (CIK 1226616) ===
  MNOV: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-29  FY2011:  mda, properties, risk_factors
    2013-03-28  FY2012:  mda, properties, risk_factors
    2014-03-27  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-02-25  FY2015:  mda, properties, risk_factors
    2017-02-14  FY2016:  mda, properties, risk_factors
    2018-02-13  FY2017:  mda, properties, risk_factors
    2019-02-13  FY2018:  mda, properties, risk_factors
    2020-02-13  FY2019:  mda, properties, risk_factors
    2021-02-19  FY2020:  mda, properties, risk_factors
    2022-02-16  FY2021:  mda, properties, risk_factors
    2023-02-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 65 public document(s) but only 63 were parsed (accession 0000950170-24-015920). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 48 rows | 319,219 words | 0.96 MB
  -> /content/bond_shared/data/raw/text/MNOV_10K_sections.parquet

=== LENZ — LENZ Therapeutics, Inc. (CIK 1815776) ===
  LENZ: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-21  FY2021:  mda, properties, risk_factors
    2023-03-20  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 80 public document(s) but only 78 were parsed (accession 0000950170-24-021135). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-03-19  FY2024:  mda, properties, risk_factors
    2026-03-24  FY2025:  mda, properties, risk_factors
  -> 15 rows | 231,501 words | 0.68 MB
  -> /content/bond_shared/data/raw/text/LENZ_10K_sections.parquet

=== NAUT — Nautilus Biotechnology, Inc. (CIK 1808805) ===
  NAUT: 6 10-K filings since 2011
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 94 public document(s) but only 92 were parsed (accession 0001808805-24-000005). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 210,534 words | 0.63 MB
  -> /content/bond_shared/data/raw/text/NAUT_10K_sections.parquet

=== INO — INOVIO PHARMACEUTICALS, INC. (CIK 1055726) ===
  INO: 16 10-K filings since 2011
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-03-15  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-17  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 103 public document(s) but only 101 were parsed (accession 0001055726-24-000011). The submission may be truncated or malformed.

    2024-03-06  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 355,799 words | 1.10 MB
  -> /content/bond_shared/data/raw/text/INO_10K_sections.parquet

=== OKUR — OnKure Therapeutics, Inc. (CIK 1637715) ===
  OKUR: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-27  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 230,375 words | 0.68 MB
  -> /content/bond_shared/data/raw/text/OKUR_10K_sections.parquet

=== CBUS — Cibus, Inc. (CIK 1705843) ===
  CBUS: 9 10-K filings since 2011 (2 amendment(s) skipped)
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-03-05  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 27 rows | 228,844 words | 0.69 MB
  -> /content/bond_shared/data/raw/text/CBUS_10K_sections.parquet

=== TVGN — Tevogen Inc. (CIK 1860871) ===
  TVGN: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-04-01  FY2021:  mda, properties, risk_factors
    2023-04-17  FY2022:  mda, properties, risk_factors
    2024-04-29  FY2023:  mda, properties, risk_factors
    2025-04-02  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 15 rows | 119,291 words | 0.37 MB
  -> /content/bond_shared/data/raw/text/TVGN_10K_sections.parquet

=== VANI — Vivani Medical, Inc. (CIK 1266806) ===
  VANI: 12 10-K filings since 2011 (5 amendment(s) skipped)
    2015-03-17  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-20  FY2017:  mda, properties, risk_factors
    2019-03-19  FY2018:  mda, properties, risk_factors
    2020-03-19  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2025-03-31  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 36 rows | 322,413 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/VANI_10K_sections.parquet

=== MIST — Milestone Pharmaceuticals Inc. (CIK 1408443) ===
  MIST: 7 10-K filings since 2011 (3 amendment(s) skipped)
    2020-03-06  FY2019:  mda, properties, risk_factors
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-20  FY2025:  mda, properties, risk_factors
  -> 21 rows | 267,184 words | 0.82 MB
  -> /content/bond_shared/data/raw/text/MIST_10K_sections.parquet

=== BDTX — Black Diamond Therapeutics, Inc. (CIK 1701541) ===
  BDTX: 7 10-K filings since 2011
    2020-03-24  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 86 public document(s) but only 84 were parsed (accession 0001701541-24-000011). The submission may be truncated or malformed.

    2024-03-12  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 21 rows | 373,490 words | 1.11 MB
  -> /content/bond_shared/data/raw/text/BDTX_10K_sections.parquet

=== EQ — Equillium, Inc. (CIK 1746466) ===
  EQ: 8 10-K filings since 2011
    2019-03-27  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-24  FY2020:  mda, properties, risk_factors
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 24 rows | 383,740 words | 1.15 MB
  -> /content/bond_shared/data/raw/text/EQ_10K_sections.parquet

=== RANI — Rani Therapeutics Holdings, Inc. (CIK 1856725) ===
  RANI: 5 10-K filings since 2011
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-20  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 281,496 words | 0.83 MB
  -> /content/bond_shared/data/raw/text/RANI_10K_sections.parquet

=== SEER — Seer, Inc. (CIK 1726445) ===
  SEER: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0000950170-24-024967). The submission may be truncated or malformed.

    2024-03-04  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 18 rows | 215,073 words | 0.64 MB
  -> /content/bond_shared/data/raw/text/SEER_10K_sections.parquet

=== TENX — TENAX THERAPEUTICS, INC. (CIK 34956) ===
  TENX: 15 10-K filings since 2011 (2 amendment(s) skipped)
    2011-07-15  FY2011:  mda, properties, risk_factors
    2012-07-25  FY2012:  mda, properties, risk_factors
    2013-06-26  FY2013:  mda, properties, risk_factors
    2014-07-29  FY2014:  mda, properties, risk_factors
    2015-07-14  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 45 rows | 256,467 words | 0.79 MB
  -> /content/bond_shared/data/raw/text/TENX_10K_sections.parquet

=== PMVP — PMV Pharmaceuticals, Inc. (CIK 1699382) ===
  PMVP: 6 10-K filings since 2011
    2021-03-03  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0000950170-24-023062). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-03-06  FY2025:  mda, properties, risk_factors
  -> 18 rows | 296,750 words | 0.88 MB
  -> /content/bond_shared/data/raw/text/PMVP_10K_sections.parquet

=== NTRB — NutriBand Inc. (CIK 1676047) ===
  NTRB: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-05-08  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_011: part_ii_item_6 keeps the anchor; ['part_ii_item_7'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors)

    2018-05-01  FY2018:  mda, properties, risk_factors
    2019-04-19  FY2019:  mda, properties, risk_factors
    2020-04-14  FY2020:  mda, properties, risk_factors
    2021-04-02  FY2021:  mda, properties, risk_factors
    2022-04-29  FY2022:  mda, properties, risk_factors
    2023-04-26  FY2023:  mda, properties, risk_factors
    2024-05-01  FY2024:  mda, properties, risk_factors
    2025-04-28  FY2025:  mda, properties, risk_factors
    2026-04-29  FY2026:  mda, properties, risk_factors
  -> 30 rows | 121,686 words | 0.38 MB
  -> /content/bond_shared/data/raw/text/NTRB_10K_sections.parquet

=== ACET — Adicet Bio, Inc. (CIK 1720580) ===
  ACET: 9 10-K filings since 2011 (3 amendment(s) skipped)
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 27 rows | 422,054 words | 1.25 MB
  -> /content/bond_shared/data/raw/text/ACET_10K_sections.parquet

=== ANIX — Anixa Biosciences Inc (CIK 715446) ===
  ANIX: 16 10-K filings since 2011 (5 amendment(s) skipped)
    2011-02-14  FY2010:  mda, properties, risk_factors
    2012-01-30  FY2011:  mda, properties, risk_factors
    2013-01-29  FY2012:  mda, properties, risk_factors
    2014-01-16  FY2013:  mda, properties, risk_factors
    2015-01-29  FY2014:  mda, properties, risk_factors
    2015-12-23  FY2015:  mda, properties, risk_factors
    2016-12-07  FY2016:  mda, properties, risk_factors
    2018-01-09  FY2017:  mda, properties, risk_factors
    2019-01-11  FY2018:  mda, properties, risk_factors
    2020-01-09  FY2019:  mda, properties, risk_factors
    2021-01-07  FY2020:  mda, properties, risk_factors
    2022-01-04  FY2021:  mda, properties, risk_factors
    2023-01-04  FY2022:  mda, properties, risk_factors
    2024-01-16  FY2023:  mda, properties, risk_factors
    2025-01-10  FY2024:  mda, properties, risk_factors
    2026-01-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 201,280 words | 0.59 MB
  -> /content/bond_shared/data/raw/text/ANIX_10K_sections.parquet

=== CRDF — Cardiff Oncology, Inc. (CIK 1213037) ===
  CRDF: 15 10-K filings since 2011
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-17  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-02-26  FY2017:  mda, properties, risk_factors
    2019-03-06  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 77 public document(s) but only 75 were parsed (accession 0001628280-24-007948). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 45 rows | 281,815 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/CRDF_10K_sections.parquet

=== BMEA — Biomea Fusion, Inc. (CIK 1840439) ===
  BMEA: 5 10-K filings since 2011
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-24  FY2025:  mda, properties, risk_factors
  -> 15 rows | 249,302 words | 0.74 MB
  -> /content/bond_shared/data/raw/text/BMEA_10K_sections.parquet

=== ICCC — IMMUCELL CORP /DE/ (CIK 811641) ===
  ICCC: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-28  FY2010:  mda, properties, risk_factors
    2012-03-27  FY2011:  mda, risk_factors
    2013-03-28  FY2012:  mda, risk_factors
    2014-03-26  FY2013:  mda, risk_factors
    2015-03-26  FY2014:  mda, risk_factors
    2016-03-25  FY2015:  mda, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-22  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 43 rows | 207,311 words | 0.65 MB
  -> /content/bond_shared/data/raw/text/ICCC_10K_sections.parquet

=== CGTX — COGNITION THERAPEUTICS INC (CIK 1455365) ===
  CGTX: 5 10-K filings since 2011
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0001558370-24-003949). The submission may be truncated or malformed.

    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 227,923 words | 0.66 MB
  -> /content/bond_shared/data/raw/text/CGTX_10K_sections.parquet

=== ATRA — Atara Biotherapeutics, Inc. (CIK 1604464) ===
  ATRA: 12 10-K filings since 2011 (1 amendment(s) skipped)
    2015-02-26  FY2014:  mda, properties, risk_factors
    2016-03-04  FY2015:  mda, properties, risk_factors
    2017-03-09  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-08  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-07  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 36 rows | 464,448 words | 1.40 MB
  -> /content/bond_shared/data/raw/text/ATRA_10K_sections.parquet

=== RLYB — Rallybio Corp (CIK 1739410) ===
  RLYB: 5 10-K filings since 2011
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 94 public document(s) but only 92 were parsed (accession 0001739410-24-000035). The submission may be truncated or malformed.

    2024-03-12  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 15 rows | 235,044 words | 0.70 MB
  -> /content/bond_shared/data/raw/text/RLYB_10K_sections.parquet

=== GANX — Gain Therapeutics, Inc. (CIK 1819411) ===
  GANX: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-25  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 167,613 words | 0.52 MB
  -> /content/bond_shared/data/raw/text/GANX_10K_sections.parquet

=== IBIO — iBio, Inc. (CIK 1420720) ===
  IBIO: 16 10-K filings since 2011 (6 amendment(s) skipped)
    2011-09-29  FY2011:  mda, properties, risk_factors
    2012-10-12  FY2012:  mda, properties, risk_factors
    2013-09-30  FY2013:  mda, properties, risk_factors
    2014-09-29  FY2014:  mda, properties, risk_factors
    2015-10-13  FY2015:  mda, properties, risk_factors
    2016-10-13  FY2016:  mda, properties, risk_factors
    2017-09-15  FY2017:  mda, properties, risk_factors
    2018-09-18  FY2018:  mda, properties, risk_factors
    2019-08-26  FY2019:  mda, properties, risk_factors
    2020-10-13  FY2020:  mda, properties, risk_factors
    2021-09-28  FY2021:  mda, properties, risk_factors
    2022-10-11  FY2022:  mda, properties, risk_factors
    2023-09-27  FY2023:  mda, properties, risk_factors
    2024-09-20  FY2024:  mda, properties, risk_factors
    2025-09-05  FY2025:  mda, properties, risk_factors
    2026-08-28  FY2026:  mda, properties, risk_factors
  -> 48 rows | 336,423 words | 1.02 MB
  -> /content/bond_shared/data/raw/text/IBIO_10K_sections.parquet

=== FBIO — Fortress Biotech, Inc. (CIK 1429260) ===
  FBIO: 15 10-K filings since 2011 (3 amendment(s) skipped)
    2012-03-29  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 45 rows | 410,294 words | 1.28 MB
  -> /content/bond_shared/data/raw/text/FBIO_10K_sections.parquet

=== VRCA — Verrica Pharmaceuticals Inc. (CIK 1660334) ===
  VRCA: 8 10-K filings since 2011
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-17  FY2020:  mda, properties, risk_factors
    2022-03-02  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 76 public document(s) but only 74 were parsed (accession 0000950170-24-022659). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-11  FY2025:  mda, properties, risk_factors
  -> 24 rows | 312,310 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/VRCA_10K_sections.parquet

=== RNXT — RenovoRx, Inc. (CIK 1574094) ===
  RNXT: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-04-01  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 15 rows | 184,846 words | 0.58 MB
  -> /content/bond_shared/data/raw/text/RNXT_10K_sections.parquet

=== ALDX — Aldeyra Therapeutics, Inc. (CIK 1341235) ===
  ALDX: 12 10-K filings since 2011 (2 amendment(s) skipped)
    2015-03-23  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-08  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 89 public document(s) but only 87 were parsed (accession 0000950170-24-027933). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 36 rows | 429,307 words | 1.30 MB
  -> /content/bond_shared/data/raw/text/ALDX_10K_sections.parquet

=== SPRO — Spero Therapeutics, Inc. (CIK 1701108) ===
  SPRO: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 107 public document(s) but only 105 were parsed (accession 0000950170-24-030767). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 27 rows | 357,449 words | 1.07 MB
  -> /content/bond_shared/data/raw/text/SPRO_10K_sections.parquet

=== CING — Cingulate Inc. (CIK 1862150) ===
  CING: 5 10-K filings since 2011
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-10  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 15 rows | 212,611 words | 0.65 MB
  -> /content/bond_shared/data/raw/text/CING_10K_sections.parquet

=== KLRS — Kalaris Therapeutics, Inc. (CIK 1754068) ===
  KLRS: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-02-12  FY2020:  mda, properties, risk_factors
    2022-02-10  FY2021:  mda, properties, risk_factors
    2023-02-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0000950170-24-031879). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-07  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 18 rows | 299,718 words | 0.91 MB
  -> /content/bond_shared/data/raw/text/KLRS_10K_sections.parquet

=== CSBR — CHAMPIONS ONCOLOGY, INC. (CIK 771856) ===
  CSBR: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-07-15  FY2011:  mda, properties, risk_factors
    2012-07-18  FY2012:  mda, properties, risk_factors
    2013-07-26  FY2013:  mda, properties, risk_factors
    2014-07-28  FY2014:  mda, properties, risk_factors
    2015-07-29  FY2015:  mda, properties, risk_factors
    2016-07-29  FY2016:  mda, properties, risk_factors
    2017-07-28  FY2017:  mda, properties, risk_factors
    2018-07-30  FY2018:  mda, properties, risk_factors
    2019-07-29  FY2019:  mda, properties, risk_factors
    2020-07-28  FY2020:  mda, properties, risk_factors
    2021-07-26  FY2021:  mda, properties, risk_factors
    2022-07-22  FY2022:  mda, properties, risk_factors
    2023-07-24  FY2023:  mda, properties, risk_factors
    2024-07-19  FY2024:  mda, properties, risk_factors
    2025-07-23  FY2025:  mda, properties, risk_factors
    2026-07-27  FY2026:  mda, properties, risk_factors
  -> 48 rows | 134,268 words | 0.41 MB
  -> /content/bond_shared/data/raw/text/CSBR_10K_sections.parquet

=== PLRX — PLIANT THERAPEUTICS, INC. (CIK 1746473) ===
  PLRX: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 111 public document(s) but only 108 were parsed (accession 0001746473-24-000043). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-03-11  FY2025:  mda, properties, risk_factors
  -> 18 rows | 269,838 words | 0.82 MB
  -> /content/bond_shared/data/raw/text/PLRX_10K_sections.parquet

=== GOSS — Gossamer Bio, Inc. (CIK 1728117) ===
  GOSS: 8 10-K filings since 2011
    2019-03-22  FY2018:  mda, properties, risk_factors
    2020-03-24  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 88 public document(s) but only 86 were parsed (accession 0001728117-24-000019). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 24 rows | 352,172 words | 1.05 MB
  -> /content/bond_shared/data/raw/text/GOSS_10K_sections.parquet

=== XBIT — XBiotech Inc. (CIK 1626878) ===
  XBIT: 11 10-K filings since 2011 (8 amendment(s) skipped)
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 71 public document(s) but only 69 were parsed (accession 0001171843-24-001382). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 33 rows | 200,504 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/XBIT_10K_sections.parquet

=== RNTX — Rein Therapeutics, Inc. (CIK 1420565) ===
  RNTX: 9 10-K filings since 2011 (5 amendment(s) skipped)
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-24  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-20  FY2022:  mda, properties, risk_factors
    2024-04-15  FY2023:  mda, properties, risk_factors
    2025-04-07  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 27 rows | 386,888 words | 1.13 MB
  -> /content/bond_shared/data/raw/text/RNTX_10K_sections.parquet

=== HYPD — HYPERION DEFI, INC. (CIK 1682639) ===
  HYPD: 9 10-K filings since 2011 (3 amendment(s) skipped)
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-27  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-18  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 27 rows | 254,465 words | 0.77 MB
  -> /content/bond_shared/data/raw/text/HYPD_10K_sections.parquet

=== INKT — MiNK Therapeutics, Inc. (CIK 1840229) ===
  INKT: 5 10-K filings since 2011
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 15 rows | 207,418 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/INKT_10K_sections.parquet

=== CLNN — Clene Inc. (CIK 1822791) ===
  CLNN: 6 10-K filings since 2011
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-13  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 104 public document(s) but only 102 were parsed (accession 0001437749-24-007542). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 18 rows | 228,423 words | 0.68 MB
  -> /content/bond_shared/data/raw/text/CLNN_10K_sections.parquet

=== ELOX — Eloxx Pharmaceuticals, Inc. (CIK 1035354) ===
  ELOX: 14 10-K filings since 2011 (7 amendment(s) skipped)
    2011-09-28  FY2011:  mda, properties
    2012-09-28  FY2012:  mda, properties, risk_factors
    2013-09-11  FY2013:  mda, properties, risk_factors
    2014-09-29  FY2014:  mda, properties, risk_factors
    2015-10-09  FY2015:  mda, properties, risk_factors
    2016-10-13  FY2016:  mda, properties, risk_factors
    2017-10-13  FY2017:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-06  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 41 rows | 283,100 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/ELOX_10K_sections.parquet

=== XLO — Xilio Therapeutics, Inc. (CIK 1840233) ===
  XLO: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 15 rows | 292,847 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/XLO_10K_sections.parquet

=== INMB — Inmune Bio, Inc. (CIK 1711754) ===
  INMB: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 24 rows | 171,407 words | 0.55 MB
  -> /content/bond_shared/data/raw/text/INMB_10K_sections.parquet

=== HRTX — HERON THERAPEUTICS, INC. /DE/ (CIK 818033) ===
  HRTX: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-28  FY2010:  mda, properties, risk_factors
    2012-03-26  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-03-07  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-02-19  FY2015:  mda, properties, risk_factors
    2017-02-23  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-22  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 76 public document(s) but only 74 were parsed (accession 0000950170-24-029951). The submission may be truncated or malformed.

    2024-03-12  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 368,669 words | 1.13 MB
  -> /content/bond_shared/data/raw/text/HRTX_10K_sections.parquet

=== ANVS — Annovis Bio, Inc. (CIK 1477845) ===
  ANVS: 7 10-K filings since 2011
    2020-03-25  FY2019:  mda, properties, risk_factors
    2021-03-03  FY2020:  mda, properties, risk_factors
    2022-03-02  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors
    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 21 rows | 258,523 words | 0.78 MB
  -> /content/bond_shared/data/raw/text/ANVS_10K_sections.parquet

=== EDSA — Edesa Biotech, Inc. (CIK 1540159) ===
  EDSA: 11 10-K filings since 2011 (4 amendment(s) skipped)
    2014-11-14  FY2014:  mda, properties, risk_factors
    2015-12-14  FY2015:  mda, properties, risk_factors
    2016-12-14  FY2016:  mda, properties, risk_factors
    2017-12-01  FY2017:  mda, properties, risk_factors
    2018-11-30  FY2018:  mda, properties, risk_factors
    2020-12-07  FY2020:  mda, properties, risk_factors
    2021-12-28  FY2021:  mda, properties, risk_factors
    2022-12-16  FY2022:  mda, properties, risk_factors
    2023-12-15  FY2023:  mda, properties, risk_factors
    2024-12-13  FY2024:  mda, properties, risk_factors
    2025-12-12  FY2025:  mda, properties, risk_factors
  -> 33 rows | 194,359 words | 0.59 MB
  -> /content/bond_shared/data/raw/text/EDSA_10K_sections.parquet

=== IMA — ImageneBio, Inc. (CIK 1835579) ===
  IMA: 5 10-K filings since 2011
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 118 public document(s) but only 116 were parsed (accession 0000950170-24-029651). The submission may be truncated or malformed.

    2024-03-12  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 15 rows | 251,212 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/IMA_10K_sections.parquet

=== SER — Serina Therapeutics, Inc. (CIK 1708599) ===
  SER: 8 10-K filings since 2011 (4 amendment(s) skipped)
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 82 public document(s) but only 80 were parsed (accession 0001493152-24-011022). The submission may be truncated or malformed.
WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2024-03-22  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 24 rows | 286,279 words | 0.88 MB
  -> /content/bond_shared/data/raw/text/SER_10K_sections.parquet

=== LITS — Lite Strategy, Inc. (CIK 1262104) ===
  LITS: 15 10-K filings since 2011 (4 amendment(s) skipped)
    2011-09-28  FY2011:  mda, properties, risk_factors
    2012-09-18  FY2012:  mda, properties, risk_factors
    2013-09-18  FY2013:  mda, properties, risk_factors
    2014-09-09  FY2014:  mda, properties, risk_factors
    2015-09-02  FY2015:  mda, properties, risk_factors
    2016-09-06  FY2016:  mda, properties, risk_factors
    2017-09-05  FY2017:  mda, properties, risk_factors
    2018-08-30  FY2018:  mda, properties, risk_factors
    2019-08-28  FY2019:  mda, properties, risk_factors
    2020-09-09  FY2020:  mda, properties, risk_factors
    2021-09-02  FY2021:  mda, properties, risk_factors
    2022-09-08  FY2022:  mda, properties, risk_factors
    2023-09-26  FY2023:  mda, properties, risk_factors
    2024-09-19  FY2024:  mda, properties, risk_factors
    2025-09-26  FY2025:  mda, properties, risk_factors
  -> 45 rows | 237,937 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/LITS_10K_sections.parquet

=== TIL — Instil Bio, Inc. (CIK 1789769) ===
  TIL: 5 10-K filings since 2011
    2022-03-07  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-04  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 15 rows | 245,703 words | 0.73 MB
  -> /content/bond_shared/data/raw/text/TIL_10K_sections.parquet

=== ELTX — Elicio Therapeutics, Inc. (CIK 1601485) ===
  ELTX: 6 10-K filings since 2011 (3 amendment(s) skipped)
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-17  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 18 rows | 261,595 words | 0.79 MB
  -> /content/bond_shared/data/raw/text/ELTX_10K_sections.parquet

=== HOWL — Werewolf Therapeutics, Inc. (CIK 1785530) ===
  HOWL: 5 10-K filings since 2011
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 91 public document(s) but only 89 were parsed (accession 0001785530-24-000012). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 15 rows | 266,871 words | 0.80 MB
  -> /content/bond_shared/data/raw/text/HOWL_10K_sections.parquet

=== DWTX — Dogwood Therapeutics, Inc. (CIK 1818844) ===
  DWTX: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-23  FY2020:  mda, properties, risk_factors
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 63 public document(s) but only 61 were parsed (accession 0001558370-24-002239). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_673316: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_457500 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)

    2024-03-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 18 rows | 185,073 words | 0.57 MB
  -> /content/bond_shared/data/raw/text/DWTX_10K_sections.parquet

=== PDSB — PDS Biotechnology Corp (CIK 1472091) ===
  PDSB: 11 10-K filings since 2011 (2 amendment(s) skipped)
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-02  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-02-21  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 33 rows | 362,566 words | 1.12 MB
  -> /content/bond_shared/data/raw/text/PDSB_10K_sections.parquet

=== GRCE — Grace Therapeutics, Inc. (CIK 1444192) ===
  GRCE: 7 10-K filings since 2011 (1 amendment(s) skipped)
    2020-06-29  FY2020:  mda, properties, risk_factors
    2021-06-22  FY2021:  mda, properties, risk_factors
    2022-06-21  FY2022:  mda, properties, risk_factors
    2023-06-23  FY2023:  mda, properties, risk_factors
    2024-06-21  FY2024:  mda, properties, risk_factors
    2025-06-23  FY2025:  mda, properties, risk_factors
    2026-06-18  FY2026:  mda, properties, risk_factors
  -> 21 rows | 163,458 words | 0.50 MB
  -> /content/bond_shared/data/raw/text/GRCE_10K_sections.parquet

=== VERU — VERU INC. (CIK 863894) ===
  VERU: 15 10-K filings since 2011 (2 amendment(s) skipped)
    2011-12-02  FY2011:  mda, properties, risk_factors
    2012-12-04  FY2012:  mda, properties, risk_factors
    2013-12-03  FY2013:  mda, properties, risk_factors
    2014-12-02  FY2014:  mda, properties, risk_factors
    2015-12-02  FY2015:  mda, properties, risk_factors
    2016-12-12  FY2016:  mda, properties, risk_factors
    2018-01-02  FY2017:  mda, properties, risk_factors
    2018-12-13  FY2018:  mda, properties, risk_factors
    2019-12-12  FY2019:  mda, properties, risk_factors
    2020-12-10  FY2020:  mda, properties, risk_factors
    2021-12-02  FY2021:  mda, properties, risk_factors
    2022-12-05  FY2022:  mda, properties, risk_factors
    2023-12-08  FY2023:  mda, properties, risk_factors
    2024-12-16  FY2024:  mda, properties, risk_factors
    2025-12-17  FY2025:  mda, properties, risk_factors
  -> 45 rows | 306,219 words | 0.91 MB
  -> /content/bond_shared/data/raw/text/VERU_10K_sections.parquet

=== CELU — Celularity Inc (CIK 1752828) ===
  CELU: 7 10-K filings since 2011 (3 amendment(s) skipped)
    2020-03-24  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.7' is not an English number; the raw display text is used instead

    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-07-30  FY2023:  mda, properties, risk_factors
    2025-05-08  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2026-04-30  FY2025:  mda, properties, risk_factors
  -> 21 rows | 242,394 words | 0.74 MB
  -> /content/bond_shared/data/raw/text/CELU_10K_sections.parquet

=== CRVO — CervoMed Inc. (CIK 1053691) ===
  CRVO: 16 10-K filings since 2011 (5 amendment(s) skipped)
    2011-04-26  FY2010:  mda, properties, risk_factors
    2012-05-21  FY2011:  mda, properties, risk_factors
    2013-04-16  FY2012:  mda, properties, risk_factors
    2014-04-15  FY2013:  mda, properties, risk_factors
    2015-04-03  FY2014:  mda, properties, risk_factors
    2016-03-25  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-19  FY2018:  mda, properties, risk_factors
    2020-03-17  FY2019:  mda, properties, risk_factors
    2021-03-17  FY2020:  mda, properties, risk_factors
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 374,668 words | 1.15 MB
  -> /content/bond_shared/data/raw/text/CRVO_10K_sections.parquet

=== ATNM — Actinium Pharmaceuticals, Inc. (CIK 1388320) ===
  ATNM: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-03  FY2010:  mda, properties, risk_factors
    2012-04-12  FY2011:  mda, properties, risk_factors
    2013-03-29  FY2012:  mda, properties, risk_factors
    2014-02-28  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-05-08  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-25  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 48 rows | 323,639 words | 1.02 MB
  -> /content/bond_shared/data/raw/text/ATNM_10K_sections.parquet

=== KPTI — Karyopharm Therapeutics Inc. (CIK 1503802) ===
  KPTI: 13 10-K filings since 2011
    2014-03-21  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0000950170-24-022650). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-02-13  FY2025:  mda, properties, risk_factors
  -> 39 rows | 503,880 words | 1.52 MB
  -> /content/bond_shared/data/raw/text/KPTI_10K_sections.parquet

=== FLNA — FILANA THERAPEUTICS, INC. (CIK 1069530) ===
  FLNA: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-02-03  FY2010:  mda, properties, risk_factors
    2012-02-09  FY2011:  mda, properties, risk_factors
    2013-02-08  FY2012:  mda, properties, risk_factors
    2014-02-05  FY2013:  mda, properties, risk_factors
    2015-02-18  FY2014:  mda, properties, risk_factors
    2016-03-03  FY2015:  mda, properties, risk_factors
    2017-03-07  FY2016:  mda, properties, risk_factors
    2018-02-06  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-23  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 87 public document(s) but only 85 were parsed (accession 0001437749-24-005894). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 396,972 words | 1.20 MB
  -> /content/bond_shared/data/raw/text/FLNA_10K_sections.parquet

=== MCRB — Seres Therapeutics, Inc. (CIK 1609809) ===
  MCRB: 11 10-K filings since 2011
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-03-06  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-02  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 123 public document(s) but only 121 were parsed (accession 0000950170-24-025464). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 33 rows | 460,193 words | 1.37 MB
  -> /content/bond_shared/data/raw/text/MCRB_10K_sections.parquet

=== ALGS — Aligos Therapeutics, Inc. (CIK 1799448) ===
  ALGS: 6 10-K filings since 2011
    2021-03-23  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 104 public document(s) but only 102 were parsed (accession 0000950170-24-029953). The submission may be truncated or malformed.

    2024-03-12  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 18 rows | 314,982 words | 0.95 MB
  -> /content/bond_shared/data/raw/text/ALGS_10K_sections.parquet

=== NNVC — NANOVIRICIDES, INC. (CIK 1379006) ===
  NNVC: 15 10-K filings since 2011 (6 amendment(s) skipped)
    2011-10-13  FY2011:  mda, properties, risk_factors
    2012-10-15  FY2012:  mda, properties, risk_factors
    2013-09-30  FY2013:  mda, properties, risk_factors
    2014-09-29  FY2014:  mda, properties, risk_factors
    2015-09-14  FY2015:  mda, properties, risk_factors
    2016-09-16  FY2016:  mda, properties, risk_factors
    2017-09-28  FY2017:  mda, properties, risk_factors
    2018-10-12  FY2018:  mda, properties, risk_factors
    2019-08-23  FY2019:  mda, properties, risk_factors
    2020-10-13  FY2020:  mda, properties, risk_factors
    2021-10-12  FY2021:  mda, properties, risk_factors
    2022-10-13  FY2022:  mda, properties, risk_factors
    2023-10-13  FY2023:  mda, properties, risk_factors
    2024-09-27  FY2024:  mda, properties, risk_factors
    2025-09-29  FY2025:  mda, properties, risk_factors
  -> 45 rows | 350,389 words | 1.11 MB
  -> /content/bond_shared/data/raw/text/NNVC_10K_sections.parquet

=== CNTX — Context Therapeutics Inc. (CIK 1842952) ===
  CNTX: 5 10-K filings since 2011
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-23  FY2025:  mda, properties, risk_factors
  -> 15 rows | 143,776 words | 0.44 MB
  -> /content/bond_shared/data/raw/text/CNTX_10K_sections.parquet

=== QNCX — Quince Therapeutics, Inc. (CIK 1662774) ===
  QNCX: 7 10-K filings since 2011
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-04-10  FY2025:  mda, properties, risk_factors
  -> 21 rows | 284,303 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/QNCX_10K_sections.parquet

=== LONA — LeonaBio, Inc. (CIK 1620463) ===
  LONA: 6 10-K filings since 2011
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0000950170-24-018787). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 18 rows | 310,382 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/LONA_10K_sections.parquet

=== ATYR — aTYR PHARMA INC (CIK 1339970) ===
  ATYR: 11 10-K filings since 2011
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-20  FY2017:  mda, properties, risk_factors
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-24  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 72 public document(s) but only 70 were parsed (accession 0000950170-24-031584). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 33 rows | 386,225 words | 1.17 MB
  -> /content/bond_shared/data/raw/text/ATYR_10K_sections.parquet

=== CVM — CEL SCI CORP (CIK 725363) ===
  CVM: 15 10-K filings since 2011 (5 amendment(s) skipped)
    2011-12-23  FY2011:  mda, properties, risk_factors
    2012-12-14  FY2012:  mda, properties, risk_factors
    2013-12-27  FY2013:  mda, properties, risk_factors
    2014-12-23  FY2014:  mda, properties, risk_factors
    2015-12-11  FY2015:  mda, properties, risk_factors
    2016-12-14  FY2016:  mda, properties
    2017-12-29  FY2017:  mda, properties
    2018-12-19  FY2018:  mda, properties
    2019-12-16  FY2019:  mda, properties, risk_factors
    2020-12-29  FY2020:  mda, properties
    2021-12-21  FY2021:  mda, properties
    2022-12-27  FY2022:  mda, properties
    2023-12-21  FY2023:  mda, properties
    2025-01-13  FY2024:  mda, properties
    2025-12-29  FY2025:  mda, properties
  -> 36 rows | 111,200 words | 0.31 MB
  -> /content/bond_shared/data/raw/text/CVM_10K_sections.parquet

=== ABVC — ABVC BIOPHARMA, INC. (CIK 1173313) ===
  ABVC: 16 10-K filings since 2011 (7 amendment(s) skipped)
    2011-01-13  FY2011:  mda, properties, risk_factors
    2011-12-16  FY2011:  mda, properties, risk_factors
    2015-04-15  FY2012:  mda, properties, risk_factors
    2015-04-16  FY2013:  mda, properties, risk_factors
    2015-04-17  FY2014:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item 11: part_iii_item_11 keeps the anchor; ['part_iii_item_12'] still resolve(s) to the same span (part_iii_item_12: no body-header anchors)

    2015-11-27  FY2015:  mda, properties, risk_factors
    2017-01-12  FY2016:  mda, properties, risk_factors
    2018-01-16  FY2017:  mda, properties, risk_factors
    2019-04-15  FY2018:  mda, properties, risk_factors
    2020-05-15  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 103 public document(s) but only 101 were parsed (accession 0001213900-24-022235). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 48 rows | 286,201 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/ABVC_10K_sections.parquet

=== IGC — IGC Pharma, Inc. (CIK 1326205) ===
  IGC: 15 10-K filings since 2011 (4 amendment(s) skipped)
    2011-07-14  FY2011:  mda, properties, risk_factors
    2012-07-16  FY2012:  mda, properties, risk_factors
    2013-07-16  FY2013:  mda, properties, risk_factors
    2014-07-15  FY2014:  mda, properties, risk_factors
    2015-07-14  FY2015:  mda, properties, risk_factors
    2016-07-14  FY2016:  mda, properties, risk_factors
    2017-07-14  FY2017:  mda, properties, risk_factors
    2018-06-21  FY2018:  mda, properties, risk_factors
    2019-06-14  FY2019:  mda, properties, risk_factors
    2020-07-13  FY2020:  mda, properties, risk_factors
    2021-06-14  FY2021:  mda, properties, risk_factors
    2022-06-23  FY2022:  mda, properties, risk_factors
    2023-07-07  FY2023:  mda, properties, risk_factors
    2024-06-24  FY2024:  mda, properties, risk_factors
    2025-06-27  FY2025:  mda, properties, risk_factors
  -> 45 rows | 198,235 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/IGC_10K_sections.parquet

=== RNAZ — Transcode Therapeutics, Inc. (CIK 1829635) ===
  RNAZ: 5 10-K filings since 2011 (2 amendment(s) skipped)
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-04-15  FY2025:  mda, properties, risk_factors
  -> 15 rows | 270,710 words | 0.82 MB
  -> /content/bond_shared/data/raw/text/RNAZ_10K_sections.parquet

=== KYNB — KYNTRA BIO, INC. (CIK 921299) ===
  KYNB: 12 10-K filings since 2011 (1 amendment(s) skipped)
    2015-03-26  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 135 public document(s) but only 133 were parsed (accession 0000950170-24-020161). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 36 rows | 498,263 words | 1.49 MB
  -> /content/bond_shared/data/raw/text/KYNB_10K_sections.parquet

=== GRDX — GridAI Technologies Corp. (CIK 1604191) ===
  GRDX: 10 10-K filings since 2011 (5 amendment(s) skipped)
    2017-03-31  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on data: part_ii_item_6 keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)

    2018-03-16  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item6selected: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item7management: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body-header anchors)

    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-20  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-04-01  FY2024:  mda, properties, risk_factors
    2026-05-01  FY2025:  mda, properties, risk_factors
  -> 30 rows | 211,180 words | 0.65 MB
  -> /content/bond_shared/data/raw/text/GRDX_10K_sections.parquet

=== NXTC — NextCure, Inc. (CIK 1661059) ===
  NXTC: 7 10-K filings since 2011 (1 amendment(s) skipped)
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 21 rows | 265,709 words | 0.79 MB
  -> /content/bond_shared/data/raw/text/NXTC_10K_sections.parquet

=== TCRX — TScan Therapeutics, Inc. (CIK 1783328) ===
  TCRX: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0000950170-24-026875). The submission may be truncated or malformed.

    2024-03-06  FY2023:  mda, properties, risk_factors
    2025-03-05  FY2024:  mda, properties, risk_factors
    2026-03-04  FY2025:  mda, properties, risk_factors
  -> 15 rows | 289,507 words | 0.86 MB
  -> /content/bond_shared/data/raw/text/TCRX_10K_sections.parquet

=== COCP — Cocrystal Pharma, Inc. (CIK 1412486) ===
  COCP: 16 10-K filings since 2011 (7 amendment(s) skipped)
    2011-02-18  FY2010:  mda, properties, risk_factors
    2012-04-16  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_016: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2018-03-21  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_017: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2019-04-01  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_017: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2020-03-27  FY2019:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on v_004: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2021-03-17  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sur_021: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body header for this item; part_iii_item_12: no body header for this item; part_iii_item_13: no body header for this item; part_iii_item_14: no body header for this item)

    2022-03-23  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on k_10: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body header for this item; part_iii_item_12: no body header for this item; part_iii_item_13: no body header for this item; part_iii_item_14: no body header for this item)

    2023-03-29  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on na_011: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body header for this item; part_iii_item_12: no body header for this item; part_iii_item_13: no body header for this item; part_iii_item_14: no body header for this item)

    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 48 rows | 282,827 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/COCP_10K_sections.parquet

=== JSPR — Jasper Therapeutics, Inc. (CIK 1788028) ===
  JSPR: 7 10-K filings since 2011 (3 amendment(s) skipped)
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0001213900-24-020114). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 21 rows | 306,970 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/JSPR_10K_sections.parquet

=== MRKR — Marker Therapeutics, Inc. (CIK 1094038) ===
  MRKR: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-04-18  FY2010:  mda, properties, risk_factors
    2012-04-16  FY2011:  mda, properties, risk_factors
    2013-05-15  FY2012:  mda, properties, risk_factors
    2014-04-15  FY2013:  mda, properties, risk_factors
    2015-04-15  FY2014:  mda, properties, risk_factors
    2016-04-14  FY2015:  mda, properties, risk_factors
    2017-03-14  FY2016:  mda, properties, risk_factors
    2018-03-23  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-03-09  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 48 rows | 354,324 words | 1.08 MB
  -> /content/bond_shared/data/raw/text/MRKR_10K_sections.parquet

=== AKTX — Akari Therapeutics Plc (CIK 1541157) ===
  AKTX: 5 10-K filings since 2011
    2015-02-11  FY2014:  mda, properties, risk_factors
    2016-03-23  FY2015:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2024-03-29  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2025-04-15  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'England and Wales' is not an EDGAR state, province or country name; the raw display text is used instead

    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 15 rows | 138,337 words | 0.42 MB
  -> /content/bond_shared/data/raw/text/AKTX_10K_sections.parquet

=== ATOS — ATOSSA THERAPEUTICS, INC. (CIK 1488039) ===
  ATOS: 14 10-K filings since 2011 (1 amendment(s) skipped)
    2013-03-28  FY2012:  mda, properties, risk_factors
    2014-03-27  FY2013:  mda, properties, risk_factors
    2015-03-30  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-03-28  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 42 rows | 277,791 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/ATOS_10K_sections.parquet

=== LPCN — Lipocine Inc. (CIK 1535955) ===
  LPCN: 15 10-K filings since 2011 (3 amendment(s) skipped)
    2012-03-05  FY2011:  mda, properties, risk_factors
    2013-02-26  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-11  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-06  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-06  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 86 public document(s) but only 84 were parsed (accession 0001493152-24-009127). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 45 rows | 454,436 words | 1.42 MB
  -> /content/bond_shared/data/raw/text/LPCN_10K_sections.parquet

=== CLRB — Cellectar Biosciences, Inc. (CIK 1279704) ===
  CLRB: 16 10-K filings since 2011 (8 amendment(s) skipped)
    2011-04-14  FY2010:  properties, risk_factors
    2012-03-09  FY2011:  mda, properties, risk_factors
    2013-03-28  FY2012:  mda, properties, risk_factors
    2014-03-19  FY2013:  mda, properties, risk_factors
    2015-03-24  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-03-21  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-03-09  FY2019:  mda, properties, risk_factors
    2021-03-02  FY2020:  mda, properties, risk_factors
    2022-03-21  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-04  FY2025:  mda, properties, risk_factors
  -> 47 rows | 236,118 words | 0.74 MB
  -> /content/bond_shared/data/raw/text/CLRB_10K_sections.parquet

=== TVRD — Tvardi Therapeutics, Inc. (CIK 1346830) ===
  TVRD: 13 10-K filings since 2011
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-27  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 118 public document(s) but only 116 were parsed (accession 0001558370-24-002609). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor _73b9eb4f_2534_43b4_8348_0fe40d3d66e9 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommon: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6SelectedFinancialData: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupple: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficers: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertain: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationships: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountantFees: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsFinancialStatement: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)

    2024-03-06  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 39 rows | 530,032 words | 1.56 MB
  -> /content/bond_shared/data/raw/text/TVRD_10K_sections.parquet

=== KPRX — KIORA PHARMACEUTICALS INC (CIK 1372514) ===
  KPRX: 12 10-K filings since 2011 (1 amendment(s) skipped)
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-02-23  FY2016:  mda, properties, risk_factors
    2018-03-02  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-04  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-04-15  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 36 rows | 303,228 words | 0.92 MB
  -> /content/bond_shared/data/raw/text/KPRX_10K_sections.parquet

=== KTTA — Pasithea Therapeutics Corp. (CIK 1841330) ===
  KTTA: 5 10-K filings since 2011 (2 amendment(s) skipped)
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 15 rows | 117,089 words | 0.37 MB
  -> /content/bond_shared/data/raw/text/KTTA_10K_sections.parquet

=== PTN — PALATIN TECHNOLOGIES INC (CIK 911216) ===
  PTN: 15 10-K filings since 2011 (3 amendment(s) skipped)
    2011-09-21  FY2011:  mda, properties, risk_factors
    2012-09-10  FY2012:  mda, properties, risk_factors
    2013-09-27  FY2013:  mda, properties, risk_factors
    2014-09-12  FY2014:  mda, properties, risk_factors
    2015-09-18  FY2015:  mda, properties, risk_factors
    2016-09-19  FY2016:  mda, properties, risk_factors
    2017-09-25  FY2017:  mda, properties, risk_factors
    2018-09-13  FY2018:  mda, properties, risk_factors
    2019-09-12  FY2019:  mda, properties, risk_factors
    2020-09-25  FY2020:  mda, properties, risk_factors
    2021-09-28  FY2021:  mda, properties, risk_factors
    2022-09-22  FY2022:  mda, properties, risk_factors
    2023-09-28  FY2023:  mda, properties, risk_factors
    2024-09-30  FY2024:  mda, properties, risk_factors
    2025-09-23  FY2025:  mda, properties, risk_factors
  -> 45 rows | 256,933 words | 0.78 MB
  -> /content/bond_shared/data/raw/text/PTN_10K_sections.parquet

=== ALLR — Allarity Therapeutics, Inc. (CIK 1860657) ===
  ALLR: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-05-17  FY2021:  mda, properties, risk_factors
    2023-03-13  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 128 public document(s) but only 126 were parsed (accession 0001213900-24-020864). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 15 rows | 232,683 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/ALLR_10K_sections.parquet

=== BCDA — BioCardia, Inc. (CIK 925741) ===
  BCDA: 16 10-K filings since 2011 (4 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-29  FY2011:  mda, properties, risk_factors
    2013-03-22  FY2012:  mda, properties, risk_factors
    2014-03-24  FY2013:  mda, properties, risk_factors
    2015-03-24  FY2014:  mda, properties, risk_factors
    2016-03-25  FY2015:  mda, properties, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-04-02  FY2018:  mda, properties, risk_factors
    2020-04-09  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-24  FY2025:  mda, properties, risk_factors
  -> 48 rows | 351,040 words | 1.08 MB
  -> /content/bond_shared/data/raw/text/BCDA_10K_sections.parquet

=== CTXR — Citius Pharmaceuticals, Inc. (CIK 1506251) ===
  CTXR: 14 10-K filings since 2011 (2 amendment(s) skipped)
    2012-01-13  FY2011:  mda, properties, risk_factors
    2013-01-15  FY2012:  mda, properties, risk_factors
    2014-02-06  FY2013:  mda, properties, risk_factors
    2015-12-14  FY2015:  mda, properties, risk_factors
    2016-12-23  FY2016:  mda, properties, risk_factors
    2017-12-13  FY2017:  mda, properties, risk_factors
    2018-12-11  FY2018:  mda, properties, risk_factors
    2019-12-16  FY2019:  mda, properties, risk_factors
    2020-12-16  FY2020:  mda, properties, risk_factors
    2021-12-15  FY2021:  mda, properties, risk_factors
    2022-12-22  FY2022:  mda, properties, risk_factors
    2023-12-29  FY2023:  mda, properties, risk_factors
    2024-12-27  FY2024:  mda, properties, risk_factors
    2025-12-23  FY2025:  mda, properties, risk_factors
  -> 42 rows | 235,665 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/CTXR_10K_sections.parquet

=== LTRN — Lantern Pharma Inc. (CIK 1763950) ===
  LTRN: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-10  FY2020:  mda, properties, risk_factors
    2022-03-10  FY2021:  mda, properties, risk_factors
    2023-03-20  FY2022:  mda, properties, risk_factors
    2024-03-18  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 18 rows | 222,284 words | 0.69 MB
  -> /content/bond_shared/data/raw/text/LTRN_10K_sections.parquet

=== PASG — Passage BIO, Inc. (CIK 1787297) ===
  PASG: 6 10-K filings since 2011
    2021-03-03  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 89 public document(s) but only 87 were parsed (accession 0001558370-24-002310). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_851218: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor _413b048e_5a55_4ba3_a2d2_32243e24c40c sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2PropertiesandFacilities_24543: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_840413: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_801065: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6SelectedFinancialData_184761: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_324480: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountantFeesandServices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatementSched: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_733791: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-04  FY2023:  mda, properties, risk_factors
    2025-03-04  FY2024:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 93 public document(s) but only 91 were parsed (accession 0001104659-26-022549). The submission may be truncated or malformed.

    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 18 rows | 267,517 words | 0.80 MB
  -> /content/bond_shared/data/raw/text/PASG_10K_sections.parquet

=== DYAI — DYADIC INTERNATIONAL INC (CIK 1213809) ===
  DYAI: 8 10-K filings since 2011 (2 amendment(s) skipped)
    2019-03-27  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 24 rows | 164,651 words | 0.52 MB
  -> /content/bond_shared/data/raw/text/DYAI_10K_sections.parquet

=== CNSY — CERENOME, INC. (CIK 1095981) ===
  CNSY: 16 10-K filings since 2011 (8 amendment(s) skipped)
    2011-03-11  FY2010:  mda, properties, risk_factors
    2012-03-13  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-24  FY2016:  mda, properties, risk_factors
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-02-22  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 75 public document(s) but only 73 were parsed (accession 0000950170-24-025851). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 406,385 words | 1.23 MB
  -> /content/bond_shared/data/raw/text/CNSY_10K_sections.parquet

=== ICU — SeaStar Medical Holding Corp (CIK 1831868) ===
  ICU: 6 10-K filings since 2011 (4 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-04-06  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-04-16  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 18 rows | 140,749 words | 0.41 MB
  -> /content/bond_shared/data/raw/text/ICU_10K_sections.parquet

=== HIND — Vyome Holdings, Inc (CIK 1427570) ===
  HIND: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-02-23  FY2016:  mda, properties, risk_factors
    2018-03-05  FY2017:  mda, properties, risk_factors
    2019-02-22  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-04-08  FY2021:  mda, properties, risk_factors
    2023-04-17  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 96 public document(s) but only 94 were parsed (accession 0001558370-25-004477). The submission may be truncated or malformed.

    2025-04-04  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 30 rows | 304,961 words | 0.91 MB
  -> /content/bond_shared/data/raw/text/HIND_10K_sections.parquet

=== LSTA — LISATA THERAPEUTICS, INC. (CIK 320017) ===
  LSTA: 16 10-K filings since 2011 (9 amendment(s) skipped)
    2011-04-06  FY2010:  mda, properties, risk_factors
    2012-03-20  FY2011:  mda, properties, risk_factors
    2013-03-11  FY2012:  mda, properties, risk_factors
    2014-03-13  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-17  FY2016:  mda, properties, risk_factors
    2018-03-22  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sB630B404525052E8A65C7557C9AFE637: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2019-03-14  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s470E9332AE9954BAB8F2D2D5A6205238: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2020-03-05  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-22  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 227 public document(s) but only 225 were parsed (accession 0000320017-24-000007). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 397,151 words | 1.22 MB
  -> /content/bond_shared/data/raw/text/LSTA_10K_sections.parquet

=== TPST — Tempest Therapeutics, Inc. (CIK 1544227) ===
  TPST: 14 10-K filings since 2011 (3 amendment(s) skipped)
    2013-02-25  FY2012:  mda, properties, risk_factors
    2014-02-27  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-03-02  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-19  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 42 rows | 476,250 words | 1.41 MB
  -> /content/bond_shared/data/raw/text/TPST_10K_sections.parquet

=== AEON — AEON Biopharma, Inc. (CIK 1837607) ===
  AEON: 6 10-K filings since 2011 (5 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-02-22  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 18 rows | 231,218 words | 0.65 MB
  -> /content/bond_shared/data/raw/text/AEON_10K_sections.parquet

=== PLUR — Pluri Inc. (CIK 1158780) ===
  PLUR: 16 10-K filings since 2011
    2011-09-12  FY2011:  mda, properties, risk_factors
    2012-09-10  FY2012:  mda, properties, risk_factors
    2013-09-11  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on 1b: part_i_item_1a keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: no body-header anchors)

    2014-09-11  FY2014:  mda, properties, risk_factors
    2015-09-09  FY2015:  mda, properties, risk_factors
    2016-09-07  FY2016:  mda, properties, risk_factors
    2017-09-07  FY2017:  mda, properties, risk_factors
    2018-09-12  FY2018:  mda, properties, risk_factors
    2019-09-12  FY2019:  mda, properties, risk_factors
    2020-09-10  FY2020:  mda, properties, risk_factors
    2021-09-13  FY2021:  mda, properties, risk_factors
    2022-09-21  FY2022:  mda, properties, risk_factors
    2023-09-12  FY2023:  mda, properties, risk_factors
    2024-09-18  FY2024:  mda, properties, risk_factors
    2025-09-17  FY2025:  mda, properties, risk_factors
    2026-09-10  FY2026:  mda, properties, risk_factors
  -> 48 rows | 230,263 words | 0.70 MB
  -> /content/bond_shared/data/raw/text/PLUR_10K_sections.parquet

=== GTBP — GT Biopharma, Inc. (CIK 109657) ===
  GTBP: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-04-16  FY2011:  mda, properties, risk_factors
    2014-11-18  FY2012:  mda, properties, risk_factors
    2015-01-08  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-04-16  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 48 rows | 211,706 words | 0.64 MB
  -> /content/bond_shared/data/raw/text/GTBP_10K_sections.parquet

=== VTGN — Vistagen Therapeutics, Inc. (CIK 1411685) ===
  VTGN: 16 10-K filings since 2011
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-07-02  FY2012:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on it7a8j: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)

    2013-07-18  FY2013:  mda, properties, risk_factors
    2014-06-25  FY2014:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i13: part_iii_item_13 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)

    2015-06-29  FY2015:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i13: part_iii_item_13 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)

    2016-06-24  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i13: part_iii_item_13 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)

    2017-06-29  FY2017:  properties, risk_factors
    2018-06-26  FY2018:  mda, properties, risk_factors
    2019-06-25  FY2019:  mda, properties, risk_factors
    2020-06-29  FY2020:  mda, properties, risk_factors
    2021-06-29  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item8: part_ii_item_8 keeps the anchor; ['part_ii_item_7a'] still resolve(s) to the same span (part_ii_item_7a: body anchor item7 already claimed)

    2022-06-23  FY2022:  mda, properties, risk_factors
    2023-06-28  FY2023:  mda, properties, risk_factors
    2024-06-11  FY2024:  mda, properties, risk_factors
    2025-06-17  FY2025:  mda, properties, risk_factors
    2026-06-15  FY2026:  mda, properties, risk_factors
  -> 47 rows | 549,015 words | 1.67 MB
  -> /content/bond_shared/data/raw/text/VTGN_10K_sections.parquet

=== BIVI — BIOVIE INC. (CIK 1580149) ===
  BIVI: 13 10-K filings since 2011 (1 amendment(s) skipped)
    2014-09-24  FY2014:  mda, properties, risk_factors
    2015-10-01  FY2015:  mda, properties, risk_factors
    2016-09-28  FY2016:  mda, properties, risk_factors
    2017-08-24  FY2017:  mda, properties, risk_factors
    2018-10-05  FY2018:  mda, risk_factors
    2019-09-27  FY2019:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_003: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_020: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2020-08-06  FY2020:  mda, properties, risk_factors
    2021-08-30  FY2021:  mda, properties, risk_factors
    2022-09-27  FY2022:  mda, properties, risk_factors
    2023-08-16  FY2023:  mda, properties, risk_factors
    2024-09-30  FY2024:  mda, properties, risk_factors
    2025-08-15  FY2025:  mda, properties, risk_factors
    2026-08-13  FY2026:  mda, properties, risk_factors
  -> 38 rows | 202,156 words | 0.64 MB
  -> /content/bond_shared/data/raw/text/BIVI_10K_sections.parquet

=== CALC — CalciMedica, Inc. (CIK 1534133) ===
  CALC: 6 10-K filings since 2011 (3 amendment(s) skipped)
    2021-03-05  FY2020:  mda, properties, risk_factors
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:date-year-month; the raw display text is used instead

    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-03  FY2025:  mda, properties, risk_factors
  -> 18 rows | 278,201 words | 0.83 MB
  -> /content/bond_shared/data/raw/text/CALC_10K_sections.parquet

=== DARE — Dare Bioscience, Inc. (CIK 1401914) ===
  DARE: 12 10-K filings since 2011 (3 amendment(s) skipped)
    2015-03-19  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-03-28  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 36 rows | 496,091 words | 1.47 MB
  -> /content/bond_shared/data/raw/text/DARE_10K_sections.parquet

=== INAB — IN8BIO, INC. (CIK 1740279) ===
  INAB: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 116 public document(s) but only 114 were parsed (accession 0000950170-24-031486). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 230,907 words | 0.70 MB
  -> /content/bond_shared/data/raw/text/INAB_10K_sections.parquet

=== PHIO — Phio Pharmaceuticals Corp. (CIK 1533040) ===
  PHIO: 14 10-K filings since 2011 (1 amendment(s) skipped)
    2013-03-29  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-30  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-03-26  FY2017:  mda, properties, risk_factors
    2019-03-27  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-22  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.95' is not an English number; the raw display text is used instead

    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 42 rows | 182,599 words | 0.58 MB
  -> /content/bond_shared/data/raw/text/PHIO_10K_sections.parquet

=== MBRX — Moleculin Biotech, Inc. (CIK 1659617) ===
  MBRX: 10 10-K filings since 2011 (4 amendment(s) skipped)
    2017-04-03  FY2016:  mda, properties, risk_factors
    2018-03-28  FY2017:  mda, properties, risk_factors
    2019-02-21  FY2018:  mda, properties, risk_factors
    2020-03-19  FY2019:  mda, properties, risk_factors
    2021-03-24  FY2020:  mda, properties, risk_factors
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-22  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 30 rows | 258,010 words | 0.78 MB
  -> /content/bond_shared/data/raw/text/MBRX_10K_sections.parquet

=== ADIL — ADIAL PHARMACEUTICALS, INC. (CIK 1513525) ===
  ADIL: 8 10-K filings since 2011
    2019-02-19  FY2018:  mda, properties, risk_factors
    2020-03-20  FY2019:  mda, properties, risk_factors
    2021-03-22  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-04  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 24 rows | 262,326 words | 0.82 MB
  -> /content/bond_shared/data/raw/text/ADIL_10K_sections.parquet

=== MTVA — MetaVia Inc. (CIK 1638287) ===
  MTVA: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-03-21  FY2016:  mda, properties, risk_factors
    2018-03-20  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-04-15  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 92 public document(s) but only 90 were parsed (accession 0001558370-24-004246). The submission may be truncated or malformed.

    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 30 rows | 331,933 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/MTVA_10K_sections.parquet

=== SNTI — Senti Biosciences Holdings, Inc. (CIK 1854270) ===
  SNTI: 5 10-K filings since 2011 (2 amendment(s) skipped)
    2022-03-07  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 15 rows | 274,138 words | 0.80 MB
  -> /content/bond_shared/data/raw/text/SNTI_10K_sections.parquet

=== TOVX — Theriva Biologics, Inc. (CIK 894158) ===
  TOVX: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-04-16  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-16  FY2014:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-02  FY2016:  mda, properties, risk_factors
    2018-02-22  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-20  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-16  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 302,115 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/TOVX_10K_sections.parquet

=== APRE — Aprea Therapeutics, Inc. (CIK 1781983) ===
  APRE: 7 10-K filings since 2011 (2 amendment(s) skipped)
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 21 rows | 349,703 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/APRE_10K_sections.parquet

=== KALA — KALA BIO, Inc. (CIK 1479419) ===
  KALA: 9 10-K filings since 2011
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-02-12  FY2019:  mda, properties, risk_factors

WARNING:edgar.core:SGML fetch failed for 0001558370-21-001797, falling back to homepage: peer closed connection without sending complete message body (incomplete chunked read)

    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-03  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-04-15  FY2025:  mda, properties, risk_factors
  -> 27 rows | 423,231 words | 1.22 MB
  -> /content/bond_shared/data/raw/text/KALA_10K_sections.parquet

=== LGVN — Longeveron Inc. (CIK 1721484) ===
  LGVN: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 118 public document(s) but only 116 were parsed (accession 0001213900-24-017521). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 18 rows | 226,763 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/LGVN_10K_sections.parquet

=== ALZN — Alzamend Neuro, Inc. (CIK 1677077) ===
  ALZN: 6 10-K filings since 2011
    2021-07-29  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2022-07-19  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2023-07-27  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2024-07-30  FY2024:  mda, properties, risk_factors
    2025-07-22  FY2025:  mda, properties, risk_factors
    2026-07-22  FY2026:  mda, properties, risk_factors
  -> 18 rows | 156,835 words | 0.49 MB
  -> /content/bond_shared/data/raw/text/ALZN_10K_sections.parquet

=== LNAI — Lunai Bioworks Inc. (CIK 1527728) ===
  LNAI: 13 10-K filings since 2011 (8 amendment(s) skipped)
    2012-07-17  FY2012:  mda, risk_factors
    2013-07-16  FY2013:  mda, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-09-28  FY2016:  mda, properties, risk_factors
    2017-09-29  FY2017:  mda, properties, risk_factors
    2018-10-01  FY2018:  mda, properties, risk_factors
    2019-09-30  FY2019:  mda, properties, risk_factors
    2020-09-23  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.52' is not an English number; the raw display text is used instead

    2021-09-24  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.52' is not an English number; the raw display text is used instead

    2023-02-27  FY2022:  mda, properties, risk_factors
    2023-10-02  FY2023:  mda, properties, risk_factors
    2024-10-10  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2025-09-29  FY2025:  mda, properties, risk_factors
  -> 37 rows | 170,071 words | 0.52 MB
  -> /content/bond_shared/data/raw/text/LNAI_10K_sections.parquet

=== TRAW — Traws Pharma, Inc. (CIK 1130598) ===
  TRAW: 13 10-K filings since 2011 (7 amendment(s) skipped)
    2014-03-20  FY2013:  mda, properties, risk_factors
    2015-03-30  FY2014:  mda, properties, risk_factors
    2016-03-28  FY2015:  mda, properties, risk_factors
    2017-03-29  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-21  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-04-15  FY2025:  mda, properties, risk_factors
  -> 39 rows | 335,113 words | 1.02 MB
  -> /content/bond_shared/data/raw/text/TRAW_10K_sections.parquet

=== SNGX — SOLIGENIX, INC. (CIK 812796) ===
  SNGX: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-30  FY2010:  mda, properties, risk_factors
    2012-03-27  FY2011:  mda, properties, risk_factors
    2013-02-26  FY2012:  mda, properties, risk_factors
    2014-03-26  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item16: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2015-03-25  FY2014:  mda, properties, risk_factors
    2016-03-24  FY2015:  mda, properties, risk_factors
    2017-03-27  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 84 public document(s) but only 82 were parsed (accession 0001558370-24-003402). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonE: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6SelectedFinancialData: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnal: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplem: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersa: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainB: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelat: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountantFeesandS: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsandFinancialStatemen: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 48 rows | 262,336 words | 0.81 MB
  -> /content/bond_shared/data/raw/text/SNGX_10K_sections.parquet

=== ENSC — Ensysce Biosciences, Inc. (CIK 1716947) ===
  ENSC: 9 10-K filings since 2011 (2 amendment(s) skipped)
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-11  FY2018:  mda, properties, risk_factors
    2020-03-10  FY2019:  mda, properties, risk_factors
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 78 public document(s) but only 76 were parsed (accession 0001493152-24-009993). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 27 rows | 265,918 words | 0.78 MB
  -> /content/bond_shared/data/raw/text/ENSC_10K_sections.parquet

=== XCUR — EXICURE, INC. (CIK 1698530) ===
  XCUR: 9 10-K filings since 2011 (2 amendment(s) skipped)
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-08  FY2018:  mda, properties, risk_factors
    2020-03-10  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-25  FY2021:  mda, properties, risk_factors
    2023-03-27  FY2022:  mda, properties, risk_factors
    2024-06-06  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 27 rows | 248,758 words | 0.76 MB
  -> /content/bond_shared/data/raw/text/XCUR_10K_sections.parquet

=== IMNN — Imunon, Inc. (CIK 749647) ===
  IMNN: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-28  FY2010:  mda, properties, risk_factors
    2012-03-15  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-13  FY2013:  mda, properties, risk_factors
    2015-03-12  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-24  FY2016:  mda, properties, risk_factors
    2018-03-27  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-25  FY2019:  mda, properties, risk_factors
    2021-03-19  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 48 rows | 332,643 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/IMNN_10K_sections.parquet

=== SKYE — Skye Bioscience, Inc. (CIK 1516551) ===
  SKYE: 13 10-K filings since 2011 (1 amendment(s) skipped)

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_8: part_i_item_1a keeps the anchor; ['part_i_item_1b', 'part_i_item_2'] still resolve(s) to the same span (part_i_item_1b: no body-header anchors; part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_9: part_i_item_3 keeps the anchor; ['part_i_item_4', 'part_ii_item_5'] still resolve(s) to the same span (part_i_item_4: no body-header anchors; part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_10: part_ii_item_6 keeps the anchor; ['part_ii_item_7'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors)

    2014-01-27  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6.SelectedFinancialDa: part_ii_item_5 keeps the anchor; ['part_ii_item_6'] still resolve(s) to the same span (part_ii_item_6: no body-header anchors)

    2015-03-27  FY2014:  mda, properties, risk_factors
    2016-03-21  FY2015:  mda, properties, risk_factors
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-19  FY2017:  mda, properties, risk_factors
    2019-03-14  FY2018:  mda, properties, risk_factors
    2020-03-23  FY2019:  mda, properties, risk_factors
    2021-03-02  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-22  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 39 rows | 313,611 words | 0.94 MB
  -> /content/bond_shared/data/raw/text/SKYE_10K_sections.parquet

=== CNSP — CNS Pharmaceuticals, Inc. (CIK 1729427) ===
  CNSP: 7 10-K filings since 2011 (6 amendment(s) skipped)
    2020-03-12  FY2019:  mda, properties, risk_factors
    2021-02-12  FY2020:  mda, properties, risk_factors
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 21 rows | 93,232 words | 0.29 MB
  -> /content/bond_shared/data/raw/text/CNSP_10K_sections.parquet

=== ACXP — Acurx Pharmaceuticals, Inc. (CIK 1736243) ===
  ACXP: 5 10-K filings since 2011
    2022-03-16  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 77 public document(s) but only 75 were parsed (accession 0001558370-24-003401). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_391704: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_555882 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 144,188 words | 0.44 MB
  -> /content/bond_shared/data/raw/text/ACXP_10K_sections.parquet

=== BOLT — Bolt Biotherapeutics, Inc. (CIK 1641281) ===
  BOLT: 6 10-K filings since 2011
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-24  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 18 rows | 249,850 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/BOLT_10K_sections.parquet

=== CELZ — CREATIVE MEDICAL TECHNOLOGY HOLDINGS, INC. (CIK 1187953) ===
  CELZ: 16 10-K filings since 2011 (9 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-26  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-17  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-04-14  FY2015:  mda, properties, risk_factors
    2017-02-13  FY2016:  mda, properties, risk_factors
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item6: part_ii_item_5 keeps the anchor; ['part_ii_item_6'] still resolve(s) to the same span (part_ii_item_6: no body-header anchors)

    2020-04-06  FY2019:  mda, properties, risk_factors
    2021-03-17  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-22  FY2023:  mda, properties, risk_factors
    2025-03-14  FY2024:  mda, properties, risk_factors
    2026-03-20  FY2025:  mda, properties, risk_factors
  -> 48 rows | 68,299 words | 0.20 MB
  -> /content/bond_shared/data/raw/text/CELZ_10K_sections.parquet

=== ENVB — Enveric Biosciences, Inc. (CIK 890821) ===
  ENVB: 15 10-K filings since 2011 (5 amendment(s) skipped)
    2011-03-07  FY2010:  mda, properties, risk_factors
    2012-03-07  FY2011:  mda, properties, risk_factors
    2013-02-28  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-25  FY2019:  mda, properties, risk_factors
    2021-04-01  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 44 rows | 251,655 words | 0.77 MB
  -> /content/bond_shared/data/raw/text/ENVB_10K_sections.parquet

=== PCSA — Processa Pharmaceuticals, Inc. (CIK 1533743) ===
  PCSA: 13 10-K filings since 2011 (5 amendment(s) skipped)
    2014-03-27  FY2013:  mda, properties, risk_factors
    2015-04-14  FY2014:  mda, properties, risk_factors
    2017-06-19  FY2015:  mda, properties, risk_factors
    2017-09-25  FY2016:  mda, properties, risk_factors
    2018-04-16  FY2017:  mda, properties, risk_factors
    2019-03-28  FY2018:  mda, properties, risk_factors
    2020-03-06  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 39 rows | 242,806 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/PCSA_10K_sections.parquet

=== PULM — Pulmatrix, Inc. (CIK 1574235) ===
  PULM: 13 10-K filings since 2011 (5 amendment(s) skipped)
    2014-06-30  FY2014:  mda, properties, risk_factors
    2015-06-10  FY2015:  mda, properties, risk_factors
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-13  FY2017:  mda, properties, risk_factors
    2019-02-19  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-23  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 39 rows | 287,929 words | 0.90 MB
  -> /content/bond_shared/data/raw/text/PULM_10K_sections.parquet

=== AIM — AIM ImmunoTech Inc. (CIK 946644) ===
  AIM: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-29  FY2010:  mda, properties, risk_factors
    2012-03-14  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-19  FY2014:  mda, properties, risk_factors
    2016-03-29  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-03-30  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.94' is not an English number; the raw display text is used instead

    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.75' is not an English number; the raw display text is used instead

    2024-04-01  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.75' is not an English number; the raw display text is used instead

    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 241,262 words | 0.74 MB
  -> /content/bond_shared/data/raw/text/AIM_10K_sections.parquet

=== CDIO — Cardio Diagnostics Holdings, Inc. (CIK 1870144) ===
  CDIO: 5 10-K filings since 2011
    2022-03-31  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_016: part_iii_item_14 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: no body-header anchors)

    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 15 rows | 156,701 words | 0.49 MB
  -> /content/bond_shared/data/raw/text/CDIO_10K_sections.parquet

=== ERNA — Ernexa Therapeutics Inc. (CIK 748592) ===
  ERNA: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-25  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-03-29  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-27  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-09  FY2016:  mda, properties, risk_factors
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-22  FY2018:  mda, properties, risk_factors
    2020-03-19  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on PARTIII: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body header for this item; part_iii_item_12: no body header for this item; part_iii_item_13: no body header for this item; part_iii_item_14: no body header for this item)

    2022-04-15  FY2021:  mda, properties, risk_factors
    2023-03-20  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 113 public document(s) but only 111 were parsed (accession 0001140361-24-013254). The submission may be truncated or malformed.

    2024-03-14  FY2023:  mda, properties, risk_factors
    2025-03-12  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sq_006: part_ii_item_6 keeps the anchor; ['part_ii_item_5'] still resolve(s) to the same span (part_ii_item_5: body anchor sq_005 already claimed)

    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 253,832 words | 0.78 MB
  -> /content/bond_shared/data/raw/text/ERNA_10K_sections.parquet

=== XBIO — Xenetic Biosciences, Inc. (CIK 1534525) ===
  XBIO: 15 10-K filings since 2011 (17 amendment(s) skipped)
    2012-12-14  FY2012:  mda, properties
    2013-11-27  FY2013:  mda, properties
    2014-04-15  FY2013:  mda, properties, risk_factors
    2015-04-15  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-03-30  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-22  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-18  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 43 rows | 326,732 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/XBIO_10K_sections.parquet

=== LEXX — Lexaria Bioscience Corp. (CIK 1348362) ===
  LEXX: 15 10-K filings since 2011 (5 amendment(s) skipped)

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_13: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_23: part_i_item_3 keeps the anchor; ['part_i_item_4', 'part_ii_item_5'] still resolve(s) to the same span (part_i_item_4: no body-header anchors; part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_31: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_60: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_61: part_ii_item_9b keeps the anchor; ['part_iii_item_10'] still resolve(s) to the same span (part_iii_item_10: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_69: part_iii_item_13 keeps the anchor; ['part_iii_item_14'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors)

    2011-01-31  FY2010:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_13: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_23: part_i_item_3 keeps the anchor; ['part_i_item_4', 'part_ii_item_5'] still resolve(s) to the same span (part_i_item_4: no body-header anchors; part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_25: part_ii_item_6 keeps the anchor; ['part_ii_item_7'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_29: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_55: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_56: part_ii_item_9b keeps the anchor; ['part_iii_item_10'] still resolve(s) to the same span (part_iii_item_10: no body-header anchors)

    2012-01-30  FY2011:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_13: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_23: part_i_item_3 keeps the anchor; ['part_i_item_4', 'part_ii_item_5'] still resolve(s) to the same span (part_i_item_4: no body-header anchors; part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_31: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_60: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_61: part_ii_item_9b keeps the anchor; ['part_iii_item_10'] still resolve(s) to the same span (part_iii_item_10: no body-header anchors)

    2013-01-29  FY2012:  mda, properties, risk_factors
    2014-01-24  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_37: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_38: part_i_item_3 keeps the anchor; ['part_ii_item_5'] still resolve(s) to the same span (part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_41: part_ii_item_6 keeps the anchor; ['part_ii_item_7'] still resolve(s) to the same span (part_ii_item_7: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_48: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_77: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_78: part_ii_item_9b keeps the anchor; ['part_iii_item_10'] still resolve(s) to the same span (part_iii_item_10: no body-header anchors)

    2015-11-27  FY2015:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_28: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_29: part_i_item_3 keeps the anchor; ['part_i_item_4', 'part_ii_item_5'] still resolve(s) to the same span (part_i_item_4: no body-header anchors; part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_41: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_68: part_ii_item_9 keeps the anchor; ['part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_69: part_ii_item_9b keeps the anchor; ['part_iii_item_10'] still resolve(s) to the same span (part_iii_item_10: no body-header anchors)

    2016-11-29  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_29: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_30: part_i_item_3 keeps the anchor; ['part_i_item_4', 'part_ii_item_5'] still resolve(s) to the same span (part_i_item_4: no body-header anchors; part_ii_item_5: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_41: part_ii_item_7a keeps the anchor; ['part_ii_item_8'] still resolve(s) to the same span (part_ii_item_8: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_67: part_ii_item_9b keeps the anchor; ['part_iii_item_10'] still resolve(s) to the same span (part_iii_item_10: no body-header anchors)

    2017-11-27  FY2017:  mda, properties, risk_factors
    2018-11-14  FY2018:  mda, properties, risk_factors
    2019-11-14  FY2019:  mda, properties, risk_factors
    2020-10-15  FY2020:  mda, properties, risk_factors
    2021-11-29  FY2021:  mda, properties, risk_factors
    2022-11-28  FY2022:  mda, properties, risk_factors
    2023-11-20  FY2023:  mda, properties, risk_factors
    2024-11-26  FY2024:  mda, properties, risk_factors
    2025-11-28  FY2025:  mda, properties, risk_factors
  -> 45 rows | 163,386 words | 0.53 MB
  -> /content/bond_shared/data/raw/text/LEXX_10K_sections.parquet

=== PMCB — PharmaCyte Biotech, Inc. (CIK 1157075) ===
  PMCB: 16 10-K filings since 2011 (7 amendment(s) skipped)
    2011-08-15  FY2011:  mda, properties, risk_factors
    2012-08-14  FY2012:  mda, properties, risk_factors
    2013-07-29  FY2013:  mda, properties, risk_factors
    2014-08-04  FY2014:  mda, properties, risk_factors
    2015-07-29  FY2015:  mda, properties, risk_factors
    2016-07-29  FY2016:  mda, properties, risk_factors
    2017-07-27  FY2017:  mda, properties, risk_factors
    2018-07-20  FY2018:  mda, properties, risk_factors
    2019-08-13  FY2019:  mda, properties, risk_factors
    2020-08-13  FY2020:  mda, properties, risk_factors
    2021-08-10  FY2021:  mda, properties, risk_factors
    2022-07-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2023-07-31  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on k_010: part_ii_item_6 keeps the anchor; ['part_ii_item_5'] still resolve(s) to the same span (part_ii_item_5: body anchor k_009 does not follow the shared one)

    2024-08-13  FY2024:  mda, properties, risk_factors
    2025-08-11  FY2025:  mda, properties, risk_factors
    2026-07-29  FY2026:  mda, properties, risk_factors
  -> 48 rows | 410,844 words | 1.27 MB
  -> /content/bond_shared/data/raw/text/PMCB_10K_sections.parquet

=== DRMA — Dermata Therapeutics, Inc. (CIK 1853816) ===
  DRMA: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-02-21  FY2022:  mda, properties, risk_factors
    2024-03-21  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 193,674 words | 0.60 MB
  -> /content/bond_shared/data/raw/text/DRMA_10K_sections.parquet

=== GRI — GRI Bio, Inc. (CIK 1824293) ===
  GRI: 6 10-K filings since 2011
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-02-14  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-14  FY2024:  mda, properties, risk_factors
    2026-01-30  FY2025:  mda, properties, risk_factors
  -> 18 rows | 198,069 words | 0.60 MB
  -> /content/bond_shared/data/raw/text/GRI_10K_sections.parquet

=== CLDI — Calidi Biotherapeutics, Inc. (CIK 1855485) ===
  CLDI: 5 10-K filings since 2011
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0001493152-24-010158). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 15 rows | 225,065 words | 0.66 MB
  -> /content/bond_shared/data/raw/text/CLDI_10K_sections.parquet

=== ONCO — Onconetix, Inc. (CIK 1782107) ===
  ONCO: 5 10-K filings since 2011
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors
    2024-04-11  FY2023:  mda, properties, risk_factors
    2025-06-02  FY2024:  mda, properties, risk_factors
    2026-03-13  FY2025:  mda, properties, risk_factors
  -> 15 rows | 208,723 words | 0.65 MB
  -> /content/bond_shared/data/raw/text/ONCO_10K_sections.parquet

=== PPCB — Propanc Biopharma, Inc. (CIK 1517681) ===
  PPCB: 15 10-K filings since 2011
    2012-10-15  FY2012:  mda, properties, risk_factors
    2013-10-15  FY2013:  mda, properties, risk_factors
    2014-10-14  FY2014:  mda, properties, risk_factors
    2015-09-30  FY2015:  mda, properties, risk_factors
    2016-09-28  FY2016:  mda, properties, risk_factors
    2017-09-28  FY2017:  mda, properties, risk_factors
    2018-09-17  FY2018:  mda, properties, risk_factors
    2019-10-15  FY2019:  mda, properties, risk_factors
    2020-10-01  FY2020:  mda, properties, risk_factors
    2021-09-28  FY2021:  mda, properties, risk_factors
    2022-09-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2023-09-28  FY2023:  mda, properties, risk_factors
    2024-09-30  FY2024:  mda, properties, risk_factors
    2025-09-29  FY2025:  mda, properties, risk_factors
    2026-09-25  FY2026:  mda, properties, risk_factors
  -> 45 rows | 148,013 words | 0.43 MB
  -> /content/bond_shared/data/raw/text/PPCB_10K_sections.parquet

=== MBIO — MUSTANG BIO, INC. (CIK 1680048) ===
  MBIO: 10 10-K filings since 2011
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_001item1business: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item_002: part_i_item_002 keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item_003: part_i_item_003 keeps the anchor; ['part_i_item_3'] still resolve(s) to the same span (part_i_item_3: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on item_004: part_i_item_004 keeps the anchor; ['part_i_item_4'] still resolve(s) to the same span (part_i_item_4: no body-header anchors)

    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-24  FY2020:  mda, properties, risk_factors
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 81 public document(s) but only 79 were parsed (accession 0001558370-24-002899). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_38045: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_855719 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_248983: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_243219: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_526775: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6Reserved_101650: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisoft: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_785771: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountingFees: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsFinancialStatementSchedule: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_443190: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-11  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 87 public document(s) but only 85 were parsed (accession 0001558370-25-003913). The submission may be truncated or malformed.

    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 30 rows | 318,427 words | 0.97 MB
  -> /content/bond_shared/data/raw/text/MBIO_10K_sections.parquet

=== HCWB — HCW Biologics Inc. (CIK 1828673) ===
  HCWB: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 15 rows | 190,488 words | 0.58 MB
  -> /content/bond_shared/data/raw/text/HCWB_10K_sections.parquet

=== REVB — REVELATION BIOSCIENCES, INC. (CIK 1810560) ===
  REVB: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-04-15  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-22  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 18 rows | 169,197 words | 0.51 MB
  -> /content/bond_shared/data/raw/text/REVB_10K_sections.parquet

=== APVO — Aptevo Therapeutics Inc. (CIK 1671584) ===
  APVO: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-03-13  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-25  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0000950170-24-025428). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-02-14  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 30 rows | 303,640 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/APVO_10K_sections.parquet

=== VIVS — VivoSim Labs, INC. (CIK 1497253) ===
  VIVS: 15 10-K filings since 2011 (5 amendment(s) skipped)
    2011-10-13  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-06-10  FY2014:  mda, properties, risk_factors
    2015-06-09  FY2015:  mda, properties, risk_factors
    2016-06-09  FY2016:  mda, properties, risk_factors
    2017-06-07  FY2017:  mda, properties, risk_factors
    2018-05-31  FY2018:  mda, properties, risk_factors
    2019-06-03  FY2019:  mda, properties, risk_factors
    2020-05-28  FY2020:  mda, properties, risk_factors
    2021-06-15  FY2021:  mda, properties, risk_factors
    2022-06-10  FY2022:  mda, properties, risk_factors
    2023-07-14  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:date-year-month; the raw display text is used instead

    2024-05-31  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:date-year-month; the raw display text is used instead

    2025-06-05  FY2025:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:date-year-month; the raw display text is used instead

    2026-07-14  FY2026:  mda, properties, risk_factors
  -> 45 rows | 264,908 words | 0.81 MB
  -> /content/bond_shared/data/raw/text/VIVS_10K_sections.parquet

=== BRTX — BioRestorative Therapies, Inc. (CIK 1505497) ===
  BRTX: 15 10-K filings since 2011 (2 amendment(s) skipped)
    2012-04-16  FY2011:  mda, properties, risk_factors
    2013-04-02  FY2012:  mda, properties, risk_factors
    2014-04-11  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-22  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2021-03-18  FY2019:  mda, properties, risk_factors
    2021-04-30  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-27  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-26  FY2025:  mda, properties, risk_factors
  -> 45 rows | 287,868 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/BRTX_10K_sections.parquet

=== GOVX — GeoVax Labs, Inc. (CIK 832489) ===
  GOVX: 16 10-K filings since 2011 (6 amendment(s) skipped)
    2011-03-04  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-20  FY2014:  mda, properties, risk_factors
    2016-03-16  FY2015:  mda, properties, risk_factors
    2017-03-24  FY2016:  mda, properties, risk_factors
    2018-03-23  FY2017:  mda, properties, risk_factors
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-24  FY2019:  mda, properties, risk_factors
    2021-03-23  FY2020:  mda, properties, risk_factors
    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 68 public document(s) but only 66 were parsed (accession 0001437749-24-006086). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-27  FY2024:  mda, properties, risk_factors
    2026-04-15  FY2025:  mda, properties, risk_factors
  -> 48 rows | 183,266 words | 0.58 MB
  -> /content/bond_shared/data/raw/text/GOVX_10K_sections.parquet

=== SILO — Silo Pharma, Inc. (CIK 1514183) ===
  SILO: 15 10-K filings since 2011 (1 amendment(s) skipped)
    2012-01-26  FY2011:  mda, properties, risk_factors
    2013-03-05  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-06-14  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-04-04  FY2018:  mda, properties, risk_factors
    2020-03-20  FY2019:  mda, properties, risk_factors
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 45 rows | 251,058 words | 0.79 MB
  -> /content/bond_shared/data/raw/text/SILO_10K_sections.parquet

=== TCRT — Alaunos Therapeutics, Inc. (CIK 1107421) ===
  TCRT: 16 10-K filings since 2011 (5 amendment(s) skipped)
    2011-03-01  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-03-18  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-02-26  FY2014:  mda, properties, risk_factors
    2016-02-24  FY2015:  mda, properties, risk_factors
    2017-02-16  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-05  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 48 rows | 414,651 words | 1.27 MB
  -> /content/bond_shared/data/raw/text/TCRT_10K_sections.parquet

=== GNPX — Genprex, Inc. (CIK 1595248) ===
  GNPX: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-04-17  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-26  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-04-01  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 27 rows | 293,665 words | 0.88 MB
  -> /content/bond_shared/data/raw/text/GNPX_10K_sections.parquet

=== VBIO — Valion Bio, Inc. (CIK 1787740) ===
  VBIO: 5 10-K filings since 2011
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 15 rows | 138,643 words | 0.42 MB
  -> /content/bond_shared/data/raw/text/VBIO_10K_sections.parquet

=== JAGX — Jaguar Health, Inc. (CIK 1585608) ===
  JAGX: 11 10-K filings since 2011 (4 amendment(s) skipped)
    2016-03-29  FY2015:  mda, properties, risk_factors
    2017-02-15  FY2016:  mda, properties, risk_factors
    2018-04-09  FY2017:  mda, properties, risk_factors
    2019-04-10  FY2018:  mda, properties, risk_factors
    2020-04-03  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-04-07  FY2025:  mda, properties, risk_factors
  -> 33 rows | 344,327 words | 1.02 MB
  -> /content/bond_shared/data/raw/text/JAGX_10K_sections.parquet

=== ARTL — ARTELO BIOSCIENCES, INC. (CIK 1621221) ===
  ARTL: 11 10-K filings since 2011 (2 amendment(s) skipped)
    2015-12-11  FY2015:  mda, properties, risk_factors
    2016-11-29  FY2016:  mda, properties, risk_factors
    2017-11-29  FY2017:  mda, properties, risk_factors
    2018-11-29  FY2018:  mda, properties, risk_factors
    2019-11-25  FY2019:  mda, properties, risk_factors
    2020-11-04  FY2020:  mda, properties, risk_factors
    2021-11-29  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 60 public document(s) but only 58 were parsed (accession 0001640334-25-000335). The submission may be truncated or malformed.

    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 33 rows | 162,094 words | 0.49 MB
  -> /content/bond_shared/data/raw/text/ARTL_10K_sections.parquet

=== MTNB — Matinas BioPharma Holdings, Inc. (CIK 1582554) ===
  MTNB: 12 10-K filings since 2011 (3 amendment(s) skipped)
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-09  FY2019:  mda, properties, risk_factors
    2021-03-29  FY2020:  mda, properties, risk_factors
    2022-03-08  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 36 rows | 314,481 words | 0.97 MB
  -> /content/bond_shared/data/raw/text/MTNB_10K_sections.parquet

=== OGEN — ORAGENICS INC (CIK 1174940) ===
  OGEN: 16 10-K filings since 2011 (4 amendment(s) skipped)
    2011-03-30  FY2010:  mda, properties, risk_factors
    2012-04-16  FY2011:  mda, properties, risk_factors
    2013-03-26  FY2012:  mda, properties, risk_factors
    2014-02-28  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-02-16  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-04  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-04-17  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-14  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 48 rows | 501,208 words | 1.54 MB
  -> /content/bond_shared/data/raw/text/OGEN_10K_sections.parquet

=== DCOY — Decoy Therapeutics Inc. (CIK 1615219) ===
  DCOY: 12 10-K filings since 2011 (3 amendment(s) skipped)
    2015-03-24  FY2014:  mda, properties, risk_factors
    2016-03-08  FY2015:  mda, properties, risk_factors
    2017-03-08  FY2016:  mda, properties, risk_factors
    2018-03-07  FY2017:  mda, properties, risk_factors
    2019-03-06  FY2018:  mda, properties, risk_factors
    2020-03-23  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-25  FY2021:  mda, properties, risk_factors
    2023-03-27  FY2022:  mda, properties, risk_factors
    2024-03-22  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on directors_executive_officers: part_iii_item_10 keeps the anchor; ['part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_12: body anchor execomp already claimed; part_iii_item_13: body anchor execomp already claimed; part_iii_item_14: body anchor execomp already claimed)

    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 36 rows | 289,984 words | 0.88 MB
  -> /content/bond_shared/data/raw/text/DCOY_10K_sections.parquet

=== CRIS — CURIS INC (CIK 1108205) ===
  CRIS: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-08  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-03-13  FY2012:  mda, properties, risk_factors
    2014-03-13  FY2013:  mda, properties, risk_factors
    2015-02-24  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-09  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-19  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-03-13  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 86 public document(s) but only 84 were parsed (accession 0001108205-24-000010). The submission may be truncated or malformed.

    2024-02-08  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-24  FY2025:  mda, properties, risk_factors
  -> 48 rows | 502,389 words | 1.51 MB
  -> /content/bond_shared/data/raw/text/CRIS_10K_sections.parquet

=== HLSQ — Tessera Defense & Homeland Security Inc. (CIK 1739174) ===
  HLSQ: 8 10-K filings since 2011 (2 amendment(s) skipped)
    2019-08-21  FY2019:  mda, properties, risk_factors
    2020-03-26  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-04-04  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 24 rows | 260,845 words | 0.82 MB
  -> /content/bond_shared/data/raw/text/HLSQ_10K_sections.parquet

=== BBLG — Bone Biologics Corp (CIK 1419554) ===
  BBLG: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-01-31  FY2010:  mda, risk_factors
    2012-01-30  FY2011:  mda, risk_factors
    2013-01-29  FY2012:  mda, risk_factors
    2014-02-13  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-28  FY2015:  mda, properties, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-04-15  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 67 public document(s) but only 65 were parsed (accession 0001493152-24-007432). The submission may be truncated or malformed.

    2024-02-21  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2025-02-26  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 45 rows | 193,611 words | 0.60 MB
  -> /content/bond_shared/data/raw/text/BBLG_10K_sections.parquet

=== EDVA — Endovia Health Sciences, Inc. (CIK 1553788) ===
  EDVA: 14 10-K filings since 2011 (3 amendment(s) skipped)
    2013-04-15  FY2012:  mda, properties, risk_factors
    2014-04-15  FY2013:  mda, properties, risk_factors
    2016-09-21  FY2014:  mda, properties, risk_factors
    2016-10-03  FY2015:  mda, properties, risk_factors
    2017-03-28  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-07-11  FY2024:  mda, properties, risk_factors
    2026-04-15  FY2025:  mda, properties, risk_factors
  -> 42 rows | 83,609 words | 0.26 MB
  -> /content/bond_shared/data/raw/text/EDVA_10K_sections.parquet

=== CDT — CDT Equity Inc. (CIK 1896212) ===
  CDT: 5 10-K filings since 2011
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors
    2024-04-16  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-04-15  FY2025:  mda, properties, risk_factors
  -> 15 rows | 143,651 words | 0.42 MB
  -> /content/bond_shared/data/raw/text/CDT_10K_sections.parquet

=== NVDA — NVIDIA CORP (CIK 1045810) ===
  NVDA: 16 10-K filings since 2011
    2011-03-16  FY2011:  mda, properties, risk_factors
    2012-03-13  FY2012:  mda, properties, risk_factors
    2013-03-12  FY2013:  mda, properties, risk_factors
    2014-03-13  FY2014:  mda, properties, risk_factors
    2015-03-12  FY2015:  mda, properties, risk_factors
    2016-03-17  FY2016:  mda, properties, risk_factors
    2017-03-01  FY2017:  mda, properties, risk_factors
    2018-02-28  FY2018:  mda, properties, risk_factors
    2019-02-21  FY2019:  mda, properties, risk_factors
    2020-02-20  FY2020:  mda, properties, risk_factors
    2021-02-26  FY2021:  mda, properties, risk_factors
    2022-03-18  FY2022:  mda, properties, risk_factors
    2023-02-24  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 114 public document(s) but only 112 were parsed (accession 0001045810-24-000029). The submission may be truncated or malformed.

    2024-02-21  FY2024:  mda, properties, risk_factors
    2025-02-26  FY2025:  mda, properties, risk_factors
    2026-02-25  FY2026:  mda, properties, risk_factors
  -> 48 rows | 353,395 words | 1.08 MB
  -> /content/bond_shared/data/raw/text/NVDA_10K_sections.parquet

=== AVGO — Broadcom Inc. (CIK 1730168) ===
  AVGO: 8 10-K filings since 2011
    2018-12-21  FY2018:  mda, properties, risk_factors
    2019-12-20  FY2019:  mda, properties, risk_factors
    2020-12-18  FY2020:  mda, properties, risk_factors
    2021-12-17  FY2021:  mda, properties, risk_factors
    2022-12-16  FY2022:  mda, properties, risk_factors
    2023-12-14  FY2023:  mda, properties, risk_factors
    2024-12-20  FY2024:  mda, properties, risk_factors
    2025-12-18  FY2025:  mda, properties, risk_factors
  -> 24 rows | 196,953 words | 0.61 MB
  -> /content/bond_shared/data/raw/text/AVGO_10K_sections.parquet

=== MU — MICRON TECHNOLOGY INC (CIK 723125) ===
  MU: 15 10-K filings since 2011
    2011-10-25  FY2011:  mda, properties, risk_factors
    2012-10-29  FY2012:  mda, properties, risk_factors
    2013-10-28  FY2013:  mda, properties, risk_factors
    2014-10-27  FY2014:  mda, properties, risk_factors
    2015-10-27  FY2015:  mda, properties, risk_factors
    2016-10-28  FY2016:  mda, properties, risk_factors
    2017-10-26  FY2017:  mda, properties, risk_factors
    2018-10-15  FY2018:  mda, properties, risk_factors
    2019-10-17  FY2019:  mda, properties, risk_factors
    2020-10-19  FY2020:  mda, properties, risk_factors
    2021-10-08  FY2021:  mda, properties, risk_factors
    2022-10-07  FY2022:  mda, properties, risk_factors
    2023-10-06  FY2023:  mda, properties, risk_factors
    2024-10-04  FY2024:  mda, properties, risk_factors
    2025-10-03  FY2025:  mda, properties, risk_factors
  -> 45 rows | 267,553 words | 0.79 MB
  -> /content/bond_shared/data/raw/text/MU_10K_sections.parquet

=== AMD — ADVANCED MICRO DEVICES INC (CIK 2488) ===
  AMD: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-02-18  FY2010:  mda, properties, risk_factors
    2012-02-24  FY2011:  mda, properties, risk_factors
    2013-02-21  FY2012:  mda, properties, risk_factors
    2014-02-18  FY2013:  mda, properties, risk_factors
    2015-02-19  FY2014:  mda, properties, risk_factors
    2016-02-18  FY2015:  mda, properties, risk_factors
    2017-02-21  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-08  FY2018:  mda, properties, risk_factors
    2020-02-04  FY2019:  mda, properties, risk_factors
    2021-01-29  FY2020:  mda, properties, risk_factors
    2022-02-03  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 117 public document(s) but only 115 were parsed (accession 0000002488-24-000012). The submission may be truncated or malformed.

    2024-01-31  FY2023:  mda, properties, risk_factors
    2025-02-05  FY2024:  mda, properties, risk_factors
    2026-02-04  FY2025:  mda, properties, risk_factors
  -> 48 rows | 397,196 words | 1.15 MB
  -> /content/bond_shared/data/raw/text/AMD_10K_sections.parquet

=== INTC — INTEL CORP (CIK 50863) ===
  INTC: 16 10-K filings since 2011
    2011-02-18  FY2010:  mda, properties, risk_factors
    2012-02-23  FY2011:  mda, properties, risk_factors
    2013-02-19  FY2012:  mda, properties, risk_factors
    2014-02-14  FY2013:  mda, properties, risk_factors
    2015-02-13  FY2014:  mda, properties, risk_factors
    2016-02-12  FY2015:  mda, properties, risk_factors
    2017-02-17  FY2016:  mda, properties, risk_factors
    2018-02-16  FY2017:  mda, properties, risk_factors
    2019-02-01  FY2018:  mda, properties, risk_factors
    2020-01-24  FY2019:  mda, properties, risk_factors
    2021-01-22  FY2020:  mda, properties, risk_factors
    2022-01-27  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i8aaa7b4dbd2e419ca0f5c30af85a11aa_241: part_ii_item_8 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)

    2023-01-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on idf7ed2de495a465caefd5bdf5ef2c708_229: part_ii_item_8 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)

    2024-01-26  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i52fa34b6ba9248c7a0a794e31846504f_229: part_ii_item_8 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)

    2025-01-31  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i0ab1c04f4cd944ffa1b64a7738970255_205: part_ii_item_8 keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)

    2026-01-23  FY2025:  mda, properties, risk_factors
  -> 48 rows | 304,070 words | 0.95 MB
  -> /content/bond_shared/data/raw/text/INTC_10K_sections.parquet

=== TXN — TEXAS INSTRUMENTS INC (CIK 97476) ===
  TXN: 16 10-K filings since 2011
    2011-02-25  FY2010:  mda, properties, risk_factors
    2012-02-24  FY2011:  mda, properties, risk_factors
    2013-02-22  FY2012:  mda, properties, risk_factors
    2014-02-24  FY2013:  mda, properties, risk_factors
    2015-02-24  FY2014:  mda, properties, risk_factors
    2016-02-24  FY2015:  mda, properties, risk_factors
    2017-02-23  FY2016:  mda, properties, risk_factors
    2018-02-22  FY2017:  mda, properties, risk_factors
    2019-02-22  FY2018:  mda, properties, risk_factors
    2020-02-20  FY2019:  mda, properties, risk_factors
    2021-02-05  FY2020:  mda, properties, risk_factors
    2022-02-04  FY2021:  mda, properties, risk_factors
    2023-02-03  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 107 public document(s) but only 105 were parsed (accession 0000097476-24-000007). The submission may be truncated or malformed.

    2024-02-02  FY2023:  mda, properties, risk_factors
    2025-02-14  FY2024:  mda, properties, risk_factors
    2026-02-06  FY2025:  mda, properties, risk_factors
  -> 48 rows | 102,927 words | 0.28 MB
  -> /content/bond_shared/data/raw/text/TXN_10K_sections.parquet

=== MRVL — Marvell Technology, Inc. (CIK 1835632) ===
  MRVL: 5 10-K filings since 2011
    2022-03-10  FY2022:  mda, properties, risk_factors
    2023-03-09  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 148 public document(s) but only 146 were parsed (accession 0001835632-24-000009). The submission may be truncated or malformed.

    2024-03-13  FY2024:  mda, properties, risk_factors
    2025-03-12  FY2025:  mda, properties, risk_factors
    2026-03-11  FY2026:  mda, properties, risk_factors
  -> 15 rows | 143,052 words | 0.44 MB
  -> /content/bond_shared/data/raw/text/MRVL_10K_sections.parquet

=== QCOM — QUALCOMM INC/DE (CIK 804328) ===
  QCOM: 15 10-K filings since 2011
    2011-11-02  FY2011:  mda, properties, risk_factors
    2012-11-07  FY2012:  mda, properties, risk_factors
    2013-11-06  FY2013:  mda, properties, risk_factors
    2014-11-05  FY2014:  mda, properties, risk_factors
    2015-11-04  FY2015:  mda, properties, risk_factors
    2016-11-02  FY2016:  mda, properties, risk_factors
    2017-11-01  FY2017:  mda, properties, risk_factors
    2018-11-07  FY2018:  mda, properties, risk_factors
    2019-11-06  FY2019:  mda, properties, risk_factors
    2020-11-04  FY2020:  mda, properties, risk_factors
    2021-11-03  FY2021:  mda, properties, risk_factors
    2022-11-02  FY2022:  mda, properties, risk_factors
    2023-11-01  FY2023:  mda, properties, risk_factors
    2024-11-06  FY2024:  mda, properties, risk_factors
    2025-11-05  FY2025:  mda, properties, risk_factors
  -> 45 rows | 343,166 words | 1.02 MB
  -> /content/bond_shared/data/raw/text/QCOM_10K_sections.parquet

=== ADI — ANALOG DEVICES INC (CIK 6281) ===
  ADI: 15 10-K filings since 2011
    2011-11-22  FY2011:  mda, properties, risk_factors
    2012-11-27  FY2012:  mda, properties, risk_factors
    2013-11-26  FY2013:  mda, properties, risk_factors
    2014-12-10  FY2014:  mda, properties, risk_factors
    2015-11-24  FY2015:  mda, properties, risk_factors
    2016-11-22  FY2016:  mda, properties, risk_factors
    2017-11-22  FY2017:  mda, properties, risk_factors
    2018-11-27  FY2018:  mda, properties, risk_factors
    2019-11-26  FY2019:  mda, properties, risk_factors
    2020-11-24  FY2020:  mda, properties, risk_factors
    2021-12-03  FY2021:  mda, properties, risk_factors
    2022-11-22  FY2022:  mda, properties, risk_factors
    2023-11-21  FY2023:  mda, properties, risk_factors
    2024-11-26  FY2024:  mda, properties, risk_factors
    2025-11-25  FY2025:  mda, properties, risk_factors
  -> 45 rows | 272,141 words | 0.84 MB
  -> /content/bond_shared/data/raw/text/ADI_10K_sections.parquet

=== MPWR — MONOLITHIC POWER SYSTEMS, INC. (CIK 1280452) ===
  MPWR: 16 10-K filings since 2011
    2011-03-04  FY2010:  mda, properties, risk_factors
    2012-03-12  FY2011:  mda, properties, risk_factors
    2013-03-05  FY2012:  mda, properties, risk_factors
    2014-03-10  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 113 public document(s) but only 111 were parsed (accession 0001437749-24-006133). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 295,928 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/MPWR_10K_sections.parquet

=== NXPI — NXP Semiconductors N.V. (CIK 1413447) ===
  NXPI: 7 10-K filings since 2011
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 164 public document(s) but only 162 were parsed (accession 0001413447-24-000013). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 21 rows | 144,042 words | 0.44 MB
  -> /content/bond_shared/data/raw/text/NXPI_10K_sections.parquet

=== MCHP — MICROCHIP TECHNOLOGY INC (CIK 827054) ===
  MCHP: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-05-31  FY2011:  mda, properties, risk_factors
    2012-05-30  FY2012:  mda, properties, risk_factors
    2013-05-30  FY2013:  mda, properties, risk_factors
    2014-05-30  FY2014:  mda, properties, risk_factors
    2015-05-27  FY2015:  mda, properties, risk_factors
    2016-05-24  FY2016:  mda, properties, risk_factors
    2017-05-30  FY2017:  mda, properties, risk_factors
    2018-05-18  FY2018:  mda, properties, risk_factors
    2019-05-30  FY2019:  mda, properties, risk_factors
    2020-05-22  FY2020:  mda, properties, risk_factors
    2021-05-18  FY2021:  mda, properties, risk_factors
    2022-05-20  FY2022:  mda, properties, risk_factors
    2023-05-25  FY2023:  mda, properties, risk_factors
    2024-05-23  FY2024:  mda, properties, risk_factors
    2025-05-23  FY2025:  mda, properties, risk_factors
    2026-05-21  FY2026:  mda, properties, risk_factors
  -> 48 rows | 419,479 words | 1.26 MB
  -> /content/bond_shared/data/raw/text/MCHP_10K_sections.parquet

=== CRDO — Credo Technology Group Holding Ltd (CIK 1807794) ===
  CRDO: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-06-08  FY2022:  mda, properties, risk_factors
    2023-06-23  FY2023:  mda, properties, risk_factors
    2024-06-24  FY2024:  mda, properties, risk_factors
    2025-07-02  FY2025:  mda, properties, risk_factors
    2026-06-15  FY2026:  mda, properties, risk_factors
  -> 15 rows | 172,158 words | 0.52 MB
  -> /content/bond_shared/data/raw/text/CRDO_10K_sections.parquet

=== ON — ON SEMICONDUCTOR CORP (CIK 1097864) ===
  ON: 16 10-K filings since 2011
    2011-02-24  FY2010:  mda, properties, risk_factors
    2012-02-22  FY2011:  mda, properties, risk_factors
    2013-02-26  FY2012:  mda, properties, risk_factors
    2014-02-21  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-24  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-02-21  FY2017:  mda, properties, risk_factors
    2019-02-20  FY2018:  mda, properties, risk_factors
    2020-02-19  FY2019:  mda, properties, risk_factors
    2021-02-16  FY2020:  mda, properties, risk_factors
    2022-02-14  FY2021:  mda, properties, risk_factors
    2023-02-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 135 public document(s) but only 133 were parsed (accession 0001628280-24-003201). The submission may be truncated or malformed.

    2024-02-05  FY2023:  mda, properties, risk_factors
    2025-02-10  FY2024:  mda, properties, risk_factors
    2026-02-09  FY2025:  mda, properties, risk_factors
  -> 48 rows | 397,349 words | 1.19 MB
  -> /content/bond_shared/data/raw/text/ON_10K_sections.parquet

=== MTSI — MACOM Technology Solutions Holdings, Inc. (CIK 1493594) ===
  MTSI: 14 10-K filings since 2011 (2 amendment(s) skipped)
    2012-11-28  FY2012:  mda, properties, risk_factors
    2013-12-05  FY2013:  mda, properties, risk_factors
    2014-12-09  FY2014:  mda, properties, risk_factors
    2015-11-24  FY2015:  mda, properties, risk_factors
    2016-11-17  FY2016:  mda, properties, risk_factors
    2017-11-15  FY2017:  mda, properties, risk_factors
    2018-11-16  FY2018:  mda, properties, risk_factors
    2019-11-26  FY2019:  mda, properties, risk_factors
    2020-11-18  FY2020:  mda, properties, risk_factors
    2021-11-15  FY2021:  mda, properties, risk_factors
    2022-11-14  FY2022:  mda, properties, risk_factors
    2023-11-13  FY2023:  mda, properties, risk_factors
    2024-11-12  FY2024:  mda, properties, risk_factors
    2025-11-14  FY2025:  mda, properties, risk_factors
  -> 42 rows | 307,917 words | 0.96 MB
  -> /content/bond_shared/data/raw/text/MTSI_10K_sections.parquet

=== SITM — SITIME Corp (CIK 1451809) ===
  SITM: 7 10-K filings since 2011
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-16  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 108 public document(s) but only 106 were parsed (accession 0001451809-24-000052). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-14  FY2024:  mda, properties, risk_factors
    2026-02-11  FY2025:  mda, properties, risk_factors
  -> 21 rows | 177,129 words | 0.53 MB
  -> /content/bond_shared/data/raw/text/SITM_10K_sections.parquet

=== LSCC — LATTICE SEMICONDUCTOR CORP (CIK 855658) ===
  LSCC: 16 10-K filings since 2011 (1 amendment(s) skipped)

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s1C4007A83C10FF94DB15E5D5F32AA743: part_i_item_3 keeps the anchor; ['part_i_item_4'] still resolve(s) to the same span (part_i_item_4: no body-header anchors)

    2011-03-11  FY2011:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s0F3725A32E066F7F36A55D2BD8464955: part_i_item_3 keeps the anchor; ['part_i_item_4'] still resolve(s) to the same span (part_i_item_4: no body-header anchors)

    2012-03-12  FY2011:  mda, properties, risk_factors
    2013-03-08  FY2012:  mda, properties, risk_factors
    2014-03-11  FY2013:  mda, properties, risk_factors
    2015-03-04  FY2015:  mda, properties, risk_factors
    2016-03-02  FY2016:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-24  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2021:  mda, properties, risk_factors
    2022-02-23  FY2022:  mda, properties, risk_factors
    2023-02-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0001437749-24-004522). The submission may be truncated or malformed.

    2024-02-16  FY2023:  mda, properties, risk_factors
    2025-02-14  FY2024:  mda, properties, risk_factors
    2026-02-13  FY2026:  mda, properties, risk_factors
  -> 48 rows | 276,642 words | 0.83 MB
  -> /content/bond_shared/data/raw/text/LSCC_10K_sections.parquet

=== SMTC — SEMTECH CORP (CIK 88941) ===
  SMTC: 16 10-K filings since 2011
    2011-03-31  FY2011:  mda, properties, risk_factors
    2012-03-29  FY2011:  mda, properties, risk_factors
    2013-03-28  FY2013:  mda, properties, risk_factors
    2014-03-27  FY2014:  mda, properties, risk_factors
    2015-03-30  FY2015:  mda, properties, risk_factors
    2016-03-31  FY2016:  mda, properties, risk_factors
    2017-03-23  FY2017:  mda, properties, risk_factors
    2018-03-22  FY2018:  mda, properties, risk_factors
    2019-03-21  FY2019:  mda, properties, risk_factors
    2020-03-20  FY2020:  mda, properties, risk_factors
    2021-03-24  FY2021:  mda, properties, risk_factors
    2022-03-16  FY2022:  mda, properties, risk_factors
    2023-03-30  FY2023:  mda, properties, risk_factors
    2024-03-28  FY2024:  mda, properties, risk_factors
    2025-03-25  FY2025:  mda, properties, risk_factors
    2026-03-23  FY2026:  mda, properties, risk_factors
  -> 48 rows | 377,661 words | 1.15 MB
  -> /content/bond_shared/data/raw/text/SMTC_10K_sections.parquet

=== SWKS — SKYWORKS SOLUTIONS, INC. (CIK 4127) ===
  SWKS: 15 10-K filings since 2011 (16 amendment(s) skipped)
    2011-11-28  FY2011:  mda, properties, risk_factors
    2012-11-21  FY2012:  mda, properties, risk_factors
    2013-11-18  FY2013:  mda, properties, risk_factors
    2014-11-25  FY2014:  mda, properties, risk_factors
    2015-11-24  FY2015:  mda, properties, risk_factors
    2016-11-22  FY2016:  mda, properties, risk_factors
    2017-11-13  FY2017:  mda, properties, risk_factors
    2018-11-15  FY2018:  mda, properties, risk_factors
    2019-11-14  FY2019:  mda, properties, risk_factors
    2020-11-17  FY2020:  mda, properties, risk_factors
    2021-11-24  FY2021:  mda, properties, risk_factors
    2022-11-23  FY2022:  mda, properties, risk_factors
    2023-11-17  FY2023:  mda, properties, risk_factors
    2024-11-15  FY2024:  mda, properties, risk_factors
    2025-11-07  FY2025:  mda, properties, risk_factors
  -> 45 rows | 224,977 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/SWKS_10K_sections.parquet

=== RMBS — RAMBUS INC (CIK 917273) ===
  RMBS: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-02-25  FY2010:  mda, properties, risk_factors
    2012-02-24  FY2011:  mda, properties, risk_factors
    2013-02-22  FY2012:  mda, properties, risk_factors
    2014-02-21  FY2013:  mda, properties, risk_factors
    2015-02-20  FY2014:  mda, properties, risk_factors
    2016-02-19  FY2015:  mda, properties, risk_factors
    2017-02-17  FY2016:  mda, properties, risk_factors
    2018-02-23  FY2017:  mda, properties, risk_factors
    2019-02-22  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 139 public document(s) but only 137 were parsed (accession 0000917273-24-000028). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-02-24  FY2024:  mda, properties, risk_factors
    2026-02-18  FY2025:  mda, properties, risk_factors
  -> 48 rows | 407,004 words | 1.19 MB
  -> /content/bond_shared/data/raw/text/RMBS_10K_sections.parquet

=== QRVO — Qorvo, Inc. (CIK 1604778) ===
  QRVO: 12 10-K filings since 2011
    2015-05-27  FY2015:  mda, properties, risk_factors
    2016-05-31  FY2016:  mda, properties, risk_factors
    2017-05-23  FY2017:  mda, properties, risk_factors
    2018-05-21  FY2018:  mda, properties, risk_factors
    2019-05-17  FY2019:  mda, properties, risk_factors
    2020-05-20  FY2020:  mda, properties, risk_factors
    2021-05-24  FY2021:  mda, properties, risk_factors
    2022-05-20  FY2022:  mda, properties, risk_factors
    2023-05-19  FY2023:  mda, properties, risk_factors
    2024-05-20  FY2024:  mda, properties, risk_factors
    2025-05-19  FY2025:  mda, properties, risk_factors
    2026-05-08  FY2026:  mda, properties, risk_factors
  -> 36 rows | 227,984 words | 0.70 MB
  -> /content/bond_shared/data/raw/text/QRVO_10K_sections.parquet

=== MXL — MAXLINEAR, INC (CIK 1288469) ===
  MXL: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-02-08  FY2010:  mda, properties, risk_factors
    2012-03-14  FY2011:  mda, properties, risk_factors
    2013-02-06  FY2012:  mda, properties, risk_factors
    2014-02-07  FY2013:  mda, properties, risk_factors
    2015-02-23  FY2014:  mda, properties, risk_factors
    2016-02-17  FY2015:  mda, properties, risk_factors
    2017-02-09  FY2016:  mda, properties, risk_factors
    2018-02-20  FY2017:  mda, properties, risk_factors
    2019-02-05  FY2018:  mda, properties, risk_factors
    2020-02-05  FY2019:  mda, properties, risk_factors
    2021-02-11  FY2020:  mda, properties, risk_factors
    2022-02-02  FY2021:  mda, properties, risk_factors
    2023-02-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 117 public document(s) but only 115 were parsed (accession 0001288469-24-000015). The submission may be truncated or malformed.

    2024-01-31  FY2023:  mda, properties, risk_factors
    2025-01-29  FY2024:  mda, properties, risk_factors
    2026-01-29  FY2025:  mda, properties, risk_factors
  -> 48 rows | 468,792 words | 1.40 MB
  -> /content/bond_shared/data/raw/text/MXL_10K_sections.parquet

=== SLAB — SILICON LABORATORIES INC. (CIK 1038074) ===
  SLAB: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-02-10  FY2011:  mda, properties, risk_factors
    2012-02-15  FY2011:  mda, properties, risk_factors
    2013-02-01  FY2012:  mda, properties, risk_factors
    2014-01-31  FY2013:  mda, properties, risk_factors
    2015-02-06  FY2015:  mda, properties, risk_factors
    2016-02-05  FY2016:  mda, properties, risk_factors
    2017-02-01  FY2016:  mda, properties, risk_factors
    2018-01-31  FY2017:  mda, properties, risk_factors
    2019-01-30  FY2018:  mda, properties, risk_factors
    2020-01-29  FY2019:  mda, properties, risk_factors
    2021-02-03  FY2021:  mda, properties, risk_factors
    2022-02-02  FY2022:  mda, properties, risk_factors
    2023-02-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 107 public document(s) but only 105 were parsed (accession 0001104659-24-025535). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-04  FY2024:  mda, properties, risk_factors
    2026-02-10  FY2026:  mda, properties, risk_factors
  -> 48 rows | 249,050 words | 0.77 MB
  -> /content/bond_shared/data/raw/text/SLAB_10K_sections.parquet

=== ALGM — ALLEGRO MICROSYSTEMS, INC. (CIK 866291) ===
  ALGM: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-05-19  FY2021:  mda, properties, risk_factors
    2022-05-18  FY2022:  mda, properties, risk_factors
    2023-05-25  FY2023:  mda, properties, risk_factors
    2024-05-23  FY2024:  mda, properties, risk_factors
    2025-05-22  FY2025:  mda, properties, risk_factors
    2026-05-21  FY2026:  mda, properties, risk_factors
  -> 18 rows | 171,179 words | 0.52 MB
  -> /content/bond_shared/data/raw/text/ALGM_10K_sections.parquet

=== CRUS — CIRRUS LOGIC, INC. (CIK 772406) ===
  CRUS: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-05-25  FY2011:  mda, properties, risk_factors
    2012-05-30  FY2012:  mda, properties, risk_factors
    2013-05-29  FY2013:  mda, properties, risk_factors
    2014-05-28  FY2014:  mda, properties, risk_factors
    2015-05-27  FY2015:  mda, properties, risk_factors
    2016-05-25  FY2016:  mda, properties, risk_factors
    2017-05-24  FY2017:  mda, properties, risk_factors
    2018-05-30  FY2018:  mda, properties, risk_factors
    2019-05-24  FY2019:  mda, properties, risk_factors
    2020-05-20  FY2020:  mda, properties, risk_factors
    2021-05-21  FY2021:  mda, properties, risk_factors
    2022-05-20  FY2022:  mda, properties, risk_factors
    2023-05-19  FY2023:  mda, properties, risk_factors
    2024-05-24  FY2024:  mda, properties, risk_factors
    2025-05-23  FY2025:  mda, properties, risk_factors
    2026-05-21  FY2026:  mda, properties, risk_factors
  -> 48 rows | 253,128 words | 0.78 MB
  -> /content/bond_shared/data/raw/text/CRUS_10K_sections.parquet

=== PI — IMPINJ INC (CIK 1114995) ===
  PI: 10 10-K filings since 2011 (2 amendment(s) skipped)
    2017-03-03  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-17  FY2020:  mda, properties, risk_factors
    2022-02-14  FY2021:  mda, properties, risk_factors
    2023-02-13  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 114 public document(s) but only 112 were parsed (accession 0000950170-24-013874). The submission may be truncated or malformed.

    2024-02-12  FY2023:  mda, properties, risk_factors
    2025-02-10  FY2024:  mda, properties, risk_factors
    2026-02-09  FY2025:  mda, properties, risk_factors
  -> 30 rows | 264,358 words | 0.81 MB
  -> /content/bond_shared/data/raw/text/PI_10K_sections.parquet

=== VSH — VISHAY INTERTECHNOLOGY INC (CIK 103730) ===
  VSH: 16 10-K filings since 2011
    2011-02-25  FY2010:  mda, properties, risk_factors
    2012-02-23  FY2011:  mda, properties, risk_factors
    2013-02-20  FY2012:  mda, properties, risk_factors
    2014-02-19  FY2013:  mda, properties, risk_factors
    2015-02-19  FY2014:  mda, properties, risk_factors
    2016-02-17  FY2015:  mda, properties, risk_factors
    2017-02-17  FY2016:  mda, properties, risk_factors
    2018-02-16  FY2017:  mda, properties, risk_factors
    2019-02-15  FY2018:  mda, properties, risk_factors
    2020-02-14  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-23  FY2021:  mda, properties, risk_factors
    2023-02-22  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 92 public document(s) but only 90 were parsed (accession 0000103730-24-000034). The submission may be truncated or malformed.

    2024-02-16  FY2023:  mda, properties, risk_factors
    2025-02-14  FY2024:  mda, properties, risk_factors
    2026-02-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 337,974 words | 1.04 MB
  -> /content/bond_shared/data/raw/text/VSH_10K_sections.parquet

=== DIOD — DIODES INC /DEL/ (CIK 29002) ===
  DIOD: 16 10-K filings since 2011
    2011-02-28  FY2010:  mda, properties, risk_factors
    2012-02-28  FY2011:  mda, properties, risk_factors
    2013-02-27  FY2012:  mda, properties, risk_factors
    2014-02-27  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-02-20  FY2017:  mda, properties, risk_factors
    2019-02-21  FY2018:  mda, properties, risk_factors
    2020-02-12  FY2019:  mda, properties, risk_factors
    2021-02-22  FY2020:  mda, properties, risk_factors
    2022-02-18  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.5' is not an English number; the raw display text is used instead

    2023-02-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 131 public document(s) but only 129 were parsed (accession 0000950170-24-013363). The submission may be truncated or malformed.

    2024-02-09  FY2023:  mda, properties, risk_factors
    2025-02-14  FY2024:  mda, properties, risk_factors
    2026-02-10  FY2025:  mda, properties, risk_factors
  -> 48 rows | 338,975 words | 1.03 MB
  -> /content/bond_shared/data/raw/text/DIOD_10K_sections.parquet

=== SYNA — SYNAPTICS Inc (CIK 817720) ===
  SYNA: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-08-22  FY2011:  mda, properties, risk_factors
    2012-08-27  FY2012:  mda, properties, risk_factors
    2013-08-19  FY2013:  mda, properties, risk_factors
    2014-08-22  FY2014:  mda, properties, risk_factors
    2015-08-25  FY2015:  mda, properties, risk_factors
    2016-08-26  FY2016:  mda, properties, risk_factors
    2017-08-18  FY2017:  mda, properties, risk_factors
    2018-08-24  FY2018:  mda, properties, risk_factors
    2019-08-23  FY2019:  mda, properties, risk_factors
    2020-08-21  FY2020:  mda, properties, risk_factors
    2021-08-23  FY2021:  mda, properties, risk_factors
    2022-08-22  FY2022:  mda, properties, risk_factors
    2023-08-18  FY2023:  mda, properties, risk_factors
    2024-08-23  FY2024:  mda, properties, risk_factors
    2025-08-21  FY2025:  mda, properties, risk_factors
    2026-08-10  FY2026:  mda, properties, risk_factors
  -> 48 rows | 292,733 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/SYNA_10K_sections.parquet

=== NVTS — Navitas Semiconductor Corp (CIK 1821769) ===
  NVTS: 6 10-K filings since 2011 (7 amendment(s) skipped)
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-04-03  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 114 public document(s) but only 112 were parsed (accession 0001821769-24-000024). The submission may be truncated or malformed.

    2024-03-06  FY2023:  mda, properties, risk_factors
    2025-03-19  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 18 rows | 128,954 words | 0.40 MB
  -> /content/bond_shared/data/raw/text/NVTS_10K_sections.parquet

=== POWI — POWER INTEGRATIONS INC (CIK 833640) ===
  POWI: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-02-25  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-02-22  FY2012:  mda, properties, risk_factors
    2014-02-13  FY2013:  mda, properties, risk_factors
    2015-02-10  FY2014:  mda, properties, risk_factors
    2016-02-11  FY2015:  mda, properties, risk_factors
    2017-02-08  FY2016:  mda, properties, risk_factors
    2018-02-14  FY2017:  mda, properties, risk_factors
    2019-02-13  FY2018:  mda, properties, risk_factors
    2020-02-07  FY2019:  mda, properties, risk_factors
    2021-02-05  FY2020:  mda, properties, risk_factors
    2022-02-07  FY2021:  mda, properties, risk_factors
    2023-02-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 95 public document(s) but only 93 were parsed (accession 0000833640-24-000030). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_584739: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_833889 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_711615: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_132665: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_464792: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item9ChangesinandDisagreementswithAccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor Item9CDisclosuresRegardingJurisdictions sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_830171: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountingFeesandServices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsFinancialStatementSchedule: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_675227: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-02-12  FY2023:  mda, properties, risk_factors
    2025-02-07  FY2024:  mda, properties, risk_factors
    2026-02-06  FY2025:  mda, properties, risk_factors
  -> 48 rows | 196,568 words | 0.59 MB
  -> /content/bond_shared/data/raw/text/POWI_10K_sections.parquet

=== LASR — NLIGHT, INC. (CIK 1124796) ===
  LASR: 8 10-K filings since 2011
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-09  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 109 public document(s) but only 107 were parsed (accession 0001124796-24-000018). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 24 rows | 131,247 words | 0.40 MB
  -> /content/bond_shared/data/raw/text/LASR_10K_sections.parquet

=== WOLF — WOLFSPEED, INC. (CIK 895419) ===
  WOLF: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-08-17  FY2011:  mda, properties, risk_factors
    2012-08-21  FY2012:  mda, properties, risk_factors
    2013-08-28  FY2013:  mda, properties, risk_factors
    2014-08-27  FY2014:  mda, properties, risk_factors
    2015-08-27  FY2015:  mda, properties, risk_factors
    2016-08-25  FY2016:  mda, properties, risk_factors
    2017-08-23  FY2017:  mda, properties, risk_factors
    2018-08-20  FY2018:  mda, properties, risk_factors
    2019-08-21  FY2019:  mda, properties, risk_factors
    2020-08-19  FY2020:  mda, properties, risk_factors
    2021-08-18  FY2021:  mda, properties, risk_factors
    2022-08-22  FY2022:  mda, properties, risk_factors
    2023-08-23  FY2023:  mda, properties, risk_factors
    2024-08-22  FY2024:  mda, properties, risk_factors
    2025-08-26  FY2025:  mda, properties, risk_factors
    2026-08-20  FY2026:  mda, properties, risk_factors
  -> 48 rows | 351,071 words | 1.07 MB
  -> /content/bond_shared/data/raw/text/WOLF_10K_sections.parquet

=== AIP — Arteris, Inc. (CIK 1667011) ===
  AIP: 5 10-K filings since 2011
    2022-03-07  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 123 public document(s) but only 121 were parsed (accession 0001667011-24-000010). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-18  FY2024:  mda, properties, risk_factors
    2026-02-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 181,162 words | 0.56 MB
  -> /content/bond_shared/data/raw/text/AIP_10K_sections.parquet

=== CEVA — CEVA INC (CIK 1173489) ===
  CEVA: 16 10-K filings since 2011
    2011-03-15  FY2010:  mda, properties, risk_factors
    2012-03-15  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-03-11  FY2015:  mda, properties, risk_factors
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-04  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 115 public document(s) but only 113 were parsed (accession 0001437749-24-006970). The submission may be truncated or malformed.

    2024-03-07  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 307,767 words | 0.95 MB
  -> /content/bond_shared/data/raw/text/CEVA_10K_sections.parquet

=== AOSL — ALPHA & OMEGA SEMICONDUCTOR Ltd (CIK 1387467) ===
  AOSL: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-09-09  FY2011:  mda, properties, risk_factors
    2012-08-31  FY2012:  mda, properties, risk_factors
    2013-08-30  FY2013:  mda, properties, risk_factors
    2014-08-29  FY2014:  mda, properties, risk_factors
    2015-08-27  FY2015:  mda, properties, risk_factors
    2016-08-26  FY2016:  mda, properties, risk_factors
    2017-09-05  FY2017:  mda, properties, risk_factors
    2018-08-23  FY2018:  mda, properties, risk_factors
    2019-08-23  FY2019:  mda, properties, risk_factors
    2020-09-02  FY2020:  mda, properties, risk_factors
    2021-08-30  FY2021:  mda, properties, risk_factors
    2022-09-20  FY2022:  mda, properties, risk_factors
    2023-08-29  FY2023:  mda, properties, risk_factors
    2024-08-23  FY2024:  mda, properties, risk_factors
    2025-08-28  FY2025:  mda, properties, risk_factors
    2026-08-27  FY2026:  mda, properties, risk_factors
  -> 48 rows | 427,957 words | 1.28 MB
  -> /content/bond_shared/data/raw/text/AOSL_10K_sections.parquet

=== INDI — indie Semiconductor, Inc. (CIK 1841925) ===
  INDI: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-04-11  FY2021:  mda, properties, risk_factors
    2023-03-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 141 public document(s) but only 139 were parsed (accession 0001628280-24-008027). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 15 rows | 138,218 words | 0.42 MB
  -> /content/bond_shared/data/raw/text/INDI_10K_sections.parquet

=== NVEC — NVE CORP /NEW/ (CIK 724910) ===
  NVEC: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-05-04  FY2011:  mda, properties, risk_factors
    2012-05-02  FY2012:  mda, properties, risk_factors
    2013-05-01  FY2013:  mda, properties, risk_factors
    2014-06-06  FY2014:  mda, properties, risk_factors
    2015-05-06  FY2015:  mda, properties, risk_factors
    2016-05-04  FY2016:  mda, properties, risk_factors
    2017-05-03  FY2017:  mda, properties, risk_factors
    2018-05-02  FY2018:  mda, properties, risk_factors
    2019-05-01  FY2019:  mda, properties, risk_factors
    2020-05-06  FY2020:  mda, properties, risk_factors
    2021-05-05  FY2021:  mda, properties, risk_factors
    2022-05-04  FY2022:  mda, properties, risk_factors
    2023-05-03  FY2023:  mda, properties, risk_factors
    2024-05-01  FY2024:  mda, properties, risk_factors
    2025-05-07  FY2025:  mda, properties, risk_factors
    2026-05-06  FY2026:  mda, properties, risk_factors
  -> 48 rows | 87,101 words | 0.22 MB
  -> /content/bond_shared/data/raw/text/NVEC_10K_sections.parquet

=== MRAM — EVERSPIN TECHNOLOGIES INC. (CIK 1438423) ===
  MRAM: 10 10-K filings since 2011
    2017-03-29  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-04  FY2020:  mda, properties, risk_factors
    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 84 public document(s) but only 82 were parsed (accession 0001558370-24-002185). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_455390: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_985821 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_24726: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_55211: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MinetSafetyDisclosures: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysis_98: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplem: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item9ChangesinandDisagreementswithAccoun: part_ii_item_9 keeps the anchor; ['part_ii_item_9c'] still resolve(s) to the same span (part_ii_item_9c: body anchor Item9CDisclosureRegardingForeign sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutive_385060: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_401027: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelated_230: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountingFees_454446: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15Exhibits_215407: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-04  FY2025:  mda, properties, risk_factors
  -> 30 rows | 188,933 words | 0.57 MB
  -> /content/bond_shared/data/raw/text/MRAM_10K_sections.parquet

=== ALMU — Aeluma, Inc. (CIK 1828805) ===
  ALMU: 6 10-K filings since 2011
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-09-28  FY2022:  mda, properties, risk_factors
    2023-09-25  FY2023:  mda, properties, risk_factors
    2024-09-27  FY2024:  mda, properties, risk_factors
    2025-09-09  FY2025:  mda, properties, risk_factors
    2026-09-16  FY2026:  mda, properties, risk_factors
  -> 18 rows | 53,261 words | 0.17 MB
  -> /content/bond_shared/data/raw/text/ALMU_10K_sections.parquet

=== GSIT — GSI TECHNOLOGY INC (CIK 1126741) ===
  GSIT: 16 10-K filings since 2011
    2011-06-02  FY2011:  mda, properties, risk_factors
    2012-06-04  FY2012:  mda, properties, risk_factors
    2013-06-04  FY2013:  mda, properties, risk_factors
    2014-06-11  FY2014:  mda, properties, risk_factors
    2015-06-11  FY2015:  mda, properties, risk_factors
    2016-06-10  FY2016:  mda, properties, risk_factors
    2017-06-05  FY2017:  mda, properties, risk_factors
    2018-06-01  FY2018:  mda, properties, risk_factors
    2019-06-13  FY2019:  mda, properties, risk_factors
    2020-06-05  FY2020:  mda, properties, risk_factors
    2021-06-04  FY2021:  mda, properties, risk_factors
    2022-06-29  FY2022:  mda, properties, risk_factors
    2023-06-28  FY2023:  mda, properties, risk_factors
    2024-06-13  FY2024:  mda, properties, risk_factors
    2025-06-18  FY2025:  mda, properties, risk_factors
    2026-06-05  FY2026:  mda, properties, risk_factors
  -> 48 rows | 264,994 words | 0.79 MB
  -> /content/bond_shared/data/raw/text/GSIT_10K_sections.parquet

=== GCTS — GCT Semiconductor Holding, Inc. (CIK 1851961) ===
  GCTS: 5 10-K filings since 2011
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 57 public document(s) but only 55 were parsed (accession 0001410578-24-000166). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM2PROPERTIES_862019: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM3LEGALPROCEEDINGS_464260: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM4MINESAFETYDISCLOSURES_97312: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM5MARKETFORREGISTRANTSCOMMONEQUITYREL: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM6SELECTEDFINANCIALDATA_851847: part_ii_item_6 keeps the anchor; ['part_ii_item_6s'] still resolve(s) to the same span (part_ii_item_6s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM7MANAGEMENTSDISCUSSIONANDANALYSISOFF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM8FINANCIALSTATEMENTSANDSUPPLEMENTARY: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM10DIRECTORSEXECUTIVEOFFICERSANDCORPO: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM11EXECUTIVECOMPENSATION_402375: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM12SECURITYOWNERSHIPOFCERTAINBENEFICI: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM13CERTAINRELATIONSHIPSANDRELATEDTRAN: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM14PRINCIPALACCOUNTANTFEESANDSERVICES: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM15EXHIBITSANDFINANCIALSTATEMENTSCHED: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on ITEM16FORM10KSUMMARY_99980: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 15 rows | 140,394 words | 0.39 MB
  -> /content/bond_shared/data/raw/text/GCTS_10K_sections.parquet

=== QUIK — QUICKLOGIC Corp (CIK 882508) ===
  QUIK: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-11  FY2011:  mda, properties, risk_factors
    2012-03-09  FY2012:  mda, properties, risk_factors
    2013-03-08  FY2012:  mda, properties, risk_factors
    2014-03-06  FY2013:  mda, properties, risk_factors
    2015-03-05  FY2014:  mda, properties, risk_factors
    2016-03-18  FY2016:  mda, properties, risk_factors
    2017-03-09  FY2017:  mda, properties, risk_factors
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-23  FY2021:  mda, properties, risk_factors
    2022-03-22  FY2022:  mda, properties, risk_factors
    2023-03-28  FY2023:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 287,368 words | 0.85 MB
  -> /content/bond_shared/data/raw/text/QUIK_10K_sections.parquet

=== MX — MAGNACHIP SEMICONDUCTOR Corp (CIK 1325702) ===
  MX: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-18  FY2010:  mda, properties, risk_factors
    2012-03-08  FY2011:  mda, properties, risk_factors
    2013-02-22  FY2012:  mda, properties, risk_factors
    2015-02-12  FY2013:  mda, properties, risk_factors
    2015-05-28  FY2014:  mda, properties, risk_factors
    2016-02-22  FY2015:  mda, properties, risk_factors
    2017-02-21  FY2016:  mda, properties, risk_factors
    2018-02-22  FY2017:  mda, properties, risk_factors
    2019-02-22  FY2018:  mda, properties, risk_factors
    2020-02-21  FY2019:  mda, properties, risk_factors
    2021-03-09  FY2020:  mda, properties, risk_factors
    2022-02-23  FY2021:  mda, properties, risk_factors
    2023-02-22  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 122 public document(s) but only 120 were parsed (accession 0001193125-24-063674). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-14  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 48 rows | 481,809 words | 1.35 MB
  -> /content/bond_shared/data/raw/text/MX_10K_sections.parquet

=== IPWR — Ideal Power Inc. (CIK 1507957) ===
  IPWR: 13 10-K filings since 2011
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-25  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-29  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-31  FY2019:  mda, properties, risk_factors
    2021-03-26  FY2020:  mda, properties, risk_factors
    2022-03-25  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 39 rows | 144,556 words | 0.44 MB
  -> /content/bond_shared/data/raw/text/IPWR_10K_sections.parquet

=== PXLW — PIXELWORKS, INC (CIK 1040161) ===
  PXLW: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-09  FY2010:  mda, properties, risk_factors
    2012-03-08  FY2011:  mda, properties, risk_factors
    2013-03-06  FY2012:  mda, properties, risk_factors
    2014-03-05  FY2013:  mda, properties, risk_factors
    2015-03-04  FY2014:  mda, properties, risk_factors
    2016-03-09  FY2015:  mda, properties, risk_factors
    2017-03-08  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-13  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-10  FY2020:  mda, properties, risk_factors
    2022-03-09  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 114 public document(s) but only 112 were parsed (accession 0001040161-24-000010). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 294,377 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/PXLW_10K_sections.parquet

=== LEDS — SemiLEDs Corp (CIK 1333822) ===
  LEDS: 15 10-K filings since 2011 (3 amendment(s) skipped)
    2011-11-22  FY2011:  mda, properties, risk_factors
    2012-12-13  FY2012:  mda, properties, risk_factors
    2013-11-26  FY2013:  mda, properties, risk_factors
    2014-12-12  FY2014:  mda, properties, risk_factors
    2015-12-15  FY2015:  mda, properties, risk_factors
    2016-11-21  FY2016:  mda, properties, risk_factors
    2017-11-29  FY2017:  mda, properties, risk_factors
    2018-11-26  FY2018:  mda, properties, risk_factors
    2019-11-20  FY2019:  mda, properties, risk_factors
    2020-11-17  FY2020:  mda, properties, risk_factors
    2021-11-29  FY2021:  mda, properties, risk_factors
    2022-11-08  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.19' is not an English number; the raw display text is used instead

    2023-11-28  FY2023:  mda, properties, risk_factors
    2024-11-27  FY2024:  mda, properties, risk_factors
    2025-11-28  FY2025:  mda, properties, risk_factors
  -> 45 rows | 441,498 words | 1.30 MB
  -> /content/bond_shared/data/raw/text/LEDS_10K_sections.parquet

=== FABC — Fabric.AI, Inc. (CIK 1086745) ===
  FABC: 15 10-K filings since 2011 (6 amendment(s) skipped)
    2011-07-29  FY2011:  mda, properties, risk_factors
    2012-07-30  FY2012:  mda, properties, risk_factors
    2013-07-29  FY2013:  mda, properties, risk_factors
    2014-07-30  FY2014:  mda, properties, risk_factors
    2015-07-29  FY2015:  mda, properties, risk_factors
    2016-07-28  FY2016:  mda, properties, risk_factors
    2017-07-21  FY2017:  mda, properties, risk_factors
    2019-04-03  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 45 rows | 283,005 words | 0.88 MB
  -> /content/bond_shared/data/raw/text/FABC_10K_sections.parquet

=== PRSO — Peraso Inc. (CIK 890394) ===
  PRSO: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-15  FY2010:  mda, properties, risk_factors
    2012-03-15  FY2011:  mda, properties, risk_factors
    2013-03-12  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-03-17  FY2019:  mda, properties, risk_factors
    2021-03-18  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 48 rows | 221,028 words | 0.68 MB
  -> /content/bond_shared/data/raw/text/PRSO_10K_sections.parquet

=== GOOGL — Alphabet Inc. (CIK 1652044) ===
  GOOGL: 11 10-K filings since 2011 (2 amendment(s) skipped)
    2016-02-11  FY2015:  mda, properties, risk_factors
    2017-02-03  FY2016:  mda, properties, risk_factors
    2018-02-06  FY2017:  mda, properties, risk_factors
    2019-02-05  FY2018:  mda, properties, risk_factors
    2020-02-04  FY2019:  mda, properties, risk_factors
    2021-02-03  FY2020:  mda, properties, risk_factors
    2022-02-02  FY2021:  mda, properties, risk_factors
    2023-02-03  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 115 public document(s) but only 113 were parsed (accession 0001652044-24-000022). The submission may be truncated or malformed.

    2024-01-31  FY2023:  mda, properties, risk_factors
    2025-02-05  FY2024:  mda, properties, risk_factors
    2026-02-05  FY2025:  mda, properties, risk_factors
  -> 33 rows | 225,626 words | 0.68 MB
  -> /content/bond_shared/data/raw/text/GOOGL_10K_sections.parquet

=== META — Meta Platforms, Inc. (CIK 1326801) ===
  META: 14 10-K filings since 2011 (2 amendment(s) skipped)
    2013-02-01  FY2012:  mda, properties, risk_factors
    2014-01-31  FY2013:  mda, properties, risk_factors
    2015-01-29  FY2014:  mda, properties, risk_factors
    2016-01-28  FY2015:  mda, properties, risk_factors
    2017-02-03  FY2016:  mda, properties, risk_factors
    2018-02-01  FY2017:  mda, properties, risk_factors
    2019-01-31  FY2018:  mda, properties, risk_factors
    2020-01-30  FY2019:  mda, properties, risk_factors
    2021-01-28  FY2020:  mda, properties, risk_factors
    2022-02-03  FY2021:  mda, properties, risk_factors
    2023-02-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 137 public document(s) but only 135 were parsed (accession 0001326801-24-000012). The submission may be truncated or malformed.

    2024-02-02  FY2023:  mda, properties, risk_factors
    2025-01-30  FY2024:  mda, properties, risk_factors
    2026-01-29  FY2025:  mda, properties, risk_factors
  -> 42 rows | 442,232 words | 1.26 MB
  -> /content/bond_shared/data/raw/text/META_10K_sections.parquet

=== PINS — PINTEREST, INC. (CIK 1506293) ===
  PINS: 7 10-K filings since 2011
    2020-02-07  FY2019:  mda, properties, risk_factors
    2021-02-05  FY2020:  mda, properties, risk_factors
    2022-02-03  FY2021:  mda, properties, risk_factors
    2023-02-06  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0001506293-24-000018). The submission may be truncated or malformed.

    2024-02-08  FY2023:  mda, properties, risk_factors
    2025-02-06  FY2024:  mda, properties, risk_factors
    2026-02-12  FY2025:  mda, properties, risk_factors
  -> 21 rows | 194,444 words | 0.58 MB
  -> /content/bond_shared/data/raw/text/PINS_10K_sections.parquet

=== MTCH — Match Group, Inc. (CIK 891103) ===
  MTCH: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-01  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-02-26  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 120 public document(s) but only 118 were parsed (accession 0000891103-24-000014). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 377,609 words | 1.07 MB
  -> /content/bond_shared/data/raw/text/MTCH_10K_sections.parquet

=== SNAP — Snap Inc (CIK 1564408) ===
  SNAP: 9 10-K filings since 2011
    2018-02-22  FY2017:  mda, properties, risk_factors
    2019-02-06  FY2018:  mda, properties, risk_factors
    2020-02-05  FY2019:  mda, properties, risk_factors
    2021-02-05  FY2020:  mda, properties, risk_factors
    2022-02-04  FY2021:  mda, properties, risk_factors
    2023-02-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 119 public document(s) but only 117 were parsed (accession 0001564408-24-000019). The submission may be truncated or malformed.

    2024-02-07  FY2023:  mda, properties, risk_factors
    2025-02-05  FY2024:  mda, properties, risk_factors
    2026-02-05  FY2025:  mda, properties, risk_factors
  -> 27 rows | 323,953 words | 0.95 MB
  -> /content/bond_shared/data/raw/text/SNAP_10K_sections.parquet

=== Z — ZILLOW GROUP, INC. (CIK 1617640) ===
  Z: 11 10-K filings since 2011
    2016-02-12  FY2015:  mda, properties, risk_factors
    2017-02-07  FY2016:  mda, properties, risk_factors
    2018-02-15  FY2017:  mda, properties, risk_factors
    2019-02-21  FY2018:  mda, properties, risk_factors
    2020-02-19  FY2019:  mda, properties, risk_factors
    2021-02-12  FY2020:  mda, properties, risk_factors
    2022-02-10  FY2021:  mda, properties, risk_factors
    2023-02-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 123 public document(s) but only 121 were parsed (accession 0001617640-24-000022). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-11  FY2024:  mda, properties, risk_factors
    2026-02-11  FY2025:  mda, properties, risk_factors
  -> 33 rows | 384,420 words | 1.11 MB
  -> /content/bond_shared/data/raw/text/Z_10K_sections.parquet

=== RUM — RUM Group Inc. (CIK 1830081) ===
  RUM: 5 10-K filings since 2011
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-25  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 15 rows | 110,097 words | 0.35 MB
  -> /content/bond_shared/data/raw/text/RUM_10K_sections.parquet

=== PPLI — People Inc (CIK 1800227) ===
  PPLI: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-02-17  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 162 public document(s) but only 160 were parsed (accession 0001800227-24-000011). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-20  FY2025:  mda, properties, risk_factors
  -> 18 rows | 207,321 words | 0.58 MB
  -> /content/bond_shared/data/raw/text/PPLI_10K_sections.parquet

=== CARG — CarGurus, Inc. (CIK 1494259) ===
  CARG: 9 10-K filings since 2011
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-14  FY2019:  mda, properties, risk_factors
    2021-02-12  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 108 public document(s) but only 106 were parsed (accession 0000950170-24-020157). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 27 rows | 255,173 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/CARG_10K_sections.parquet

=== DJT — Trump Media & Technology Group Corp. (CIK 1849635) ===
  DJT: 5 10-K filings since 2011 (4 amendment(s) skipped)
    2022-04-13  FY2021:  mda, properties, risk_factors
    2023-04-26  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-02-14  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 15 rows | 147,751 words | 0.46 MB
  -> /content/bond_shared/data/raw/text/DJT_10K_sections.parquet

=== UPWK — UPWORK, INC (CIK 1627475) ===
  UPWK: 8 10-K filings since 2011
    2019-03-07  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-24  FY2020:  mda, properties, risk_factors
    2022-02-15  FY2021:  mda, properties, risk_factors
    2023-02-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0001627475-24-000012). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-13  FY2024:  mda, properties, risk_factors
    2026-02-13  FY2025:  mda, properties, risk_factors
  -> 24 rows | 301,706 words | 0.89 MB
  -> /content/bond_shared/data/raw/text/UPWK_10K_sections.parquet

=== YELP — YELP INC (CIK 1345016) ===
  YELP: 14 10-K filings since 2011 (1 amendment(s) skipped)
    2013-02-27  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-24  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-02-28  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 124 public document(s) but only 122 were parsed (accession 0001345016-24-000009). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 42 rows | 376,727 words | 1.17 MB
  -> /content/bond_shared/data/raw/text/YELP_10K_sections.parquet

=== NXDR — Nextdoor Holdings, Inc. (CIK 1846069) ===
  NXDR: 5 10-K filings since 2011
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 113 public document(s) but only 111 were parsed (accession 0001846069-24-000047). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-18  FY2025:  mda, properties, risk_factors
  -> 15 rows | 161,644 words | 0.49 MB
  -> /content/bond_shared/data/raw/text/NXDR_10K_sections.parquet

=== GRPN — Groupon, Inc. (CIK 1490281) ===
  GRPN: 15 10-K filings since 2011 (3 amendment(s) skipped)
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-02-27  FY2012:  mda, properties, risk_factors
    2014-02-21  FY2013:  mda, properties, risk_factors
    2015-02-13  FY2014:  mda, properties, risk_factors
    2016-02-12  FY2015:  mda, properties, risk_factors
    2017-02-15  FY2016:  mda, properties, risk_factors
    2018-02-14  FY2017:  mda, properties, risk_factors
    2019-02-12  FY2018:  mda, properties, risk_factors
    2020-02-18  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 132 public document(s) but only 130 were parsed (accession 0001490281-24-000024). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 45 rows | 450,103 words | 1.26 MB
  -> /content/bond_shared/data/raw/text/GRPN_10K_sections.parquet

=== EVER — EverQuote, Inc. (CIK 1640428) ===
  EVER: 8 10-K filings since 2011 (1 amendment(s) skipped)
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-13  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 94 public document(s) but only 92 were parsed (accession 0000950170-24-021082). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 24 rows | 199,732 words | 0.59 MB
  -> /content/bond_shared/data/raw/text/EVER_10K_sections.parquet

=== CARS — Cars.com Inc. (CIK 1683606) ===
  CARS: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-03-06  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0000950170-24-018824). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 27 rows | 157,876 words | 0.49 MB
  -> /content/bond_shared/data/raw/text/CARS_10K_sections.parquet

=== MAX — MediaAlpha, Inc. (CIK 1818383) ===
  MAX: 6 10-K filings since 2011
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 110 public document(s) but only 108 were parsed (accession 0001818383-24-000011). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-24  FY2024:  mda, properties, risk_factors
    2026-02-23  FY2025:  mda, properties, risk_factors
  -> 18 rows | 222,498 words | 0.63 MB
  -> /content/bond_shared/data/raw/text/MAX_10K_sections.parquet

=== NRDS — NERDWALLET, INC. (CIK 1625278) ===
  NRDS: 5 10-K filings since 2011
    2022-03-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 113 public document(s) but only 111 were parsed (accession 0001625278-24-000030). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 15 rows | 139,597 words | 0.42 MB
  -> /content/bond_shared/data/raw/text/NRDS_10K_sections.parquet

=== BMBL — Bumble Inc. (CIK 1830043) ===
  BMBL: 6 10-K filings since 2011
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-16  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 129 public document(s) but only 127 were parsed (accession 0000950170-24-022104). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 18 rows | 262,162 words | 0.76 MB
  -> /content/bond_shared/data/raw/text/BMBL_10K_sections.parquet

=== ZIP — ZIPRECRUITER, INC. (CIK 1617553) ===
  ZIP: 5 10-K filings since 2011
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 105 public document(s) but only 103 were parsed (accession 0001617553-24-000011). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 15 rows | 157,281 words | 0.48 MB
  -> /content/bond_shared/data/raw/text/ZIP_10K_sections.parquet

=== ANGI — Angi Inc. (CIK 1705110) ===
  ANGI: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-02-16  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 117 public document(s) but only 115 were parsed (accession 0001705110-24-000012). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-20  FY2025:  mda, properties, risk_factors
  -> 27 rows | 206,529 words | 0.59 MB
  -> /content/bond_shared/data/raw/text/ANGI_10K_sections.parquet

=== SSTK — Shutterstock, Inc. (CIK 1549346) ===
  SSTK: 14 10-K filings since 2011 (2 amendment(s) skipped)
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-02-28  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-24  FY2015:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-02-22  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-13  FY2019:  mda, properties, risk_factors
    2021-02-11  FY2020:  mda, properties, risk_factors
    2022-02-10  FY2021:  mda, properties, risk_factors
    2023-02-14  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 113 public document(s) but only 111 were parsed (accession 0001549346-24-000007). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i240d42e89fb64477b441131da4f6206d_2050: part_i_item_1c keeps the anchor; ['part_i_item_1'] still resolve(s) to the same span (part_i_item_1: body anchor i240d42e89fb64477b441131da4f6206d_16 does not follow the shared one)

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-17  FY2025:  mda, properties, risk_factors
  -> 42 rows | 403,109 words | 1.22 MB
  -> /content/bond_shared/data/raw/text/SSTK_10K_sections.parquet

=== DIBS — 1stdibs.com, Inc. (CIK 1600641) ===
  DIBS: 5 10-K filings since 2011
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-03  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 109 public document(s) but only 107 were parsed (accession 0001600641-24-000022). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 15 rows | 174,914 words | 0.53 MB
  -> /content/bond_shared/data/raw/text/DIBS_10K_sections.parquet

=== UPXI — UPEXI, INC. (CIK 1775194) ===
  UPXI: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-09-28  FY2021:  mda, properties, risk_factors
    2022-09-28  FY2022:  mda, properties, risk_factors
    2023-10-03  FY2023:  mda, properties, risk_factors
    2024-12-16  FY2024:  mda, properties, risk_factors
    2025-09-24  FY2025:  mda, properties, risk_factors
    2026-09-17  FY2026:  mda, properties, risk_factors
  -> 18 rows | 81,731 words | 0.26 MB
  -> /content/bond_shared/data/raw/text/UPXI_10K_sections.parquet

=== BZFD — BuzzFeed, Inc. (CIK 1828972) ===
  BZFD: 6 10-K filings since 2011
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-29  FY2023:  mda, properties, risk_factors
    2025-03-14  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 18 rows | 185,642 words | 0.55 MB
  -> /content/bond_shared/data/raw/text/BZFD_10K_sections.parquet

=== PAAI — Paradium.AI, Inc. (CIK 894871) ===
  PAAI: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-25  FY2010:  mda, properties, risk_factors
    2012-03-28  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-05-10  FY2016:  mda, properties, risk_factors
    2018-05-15  FY2017:  mda, properties, risk_factors
    2021-01-08  FY2018:  mda, properties, risk_factors
    2021-04-09  FY2019:  mda, properties, risk_factors
    2021-08-16  FY2020:  mda, properties, risk_factors
    2022-04-01  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 48 rows | 189,263 words | 0.57 MB
  -> /content/bond_shared/data/raw/text/PAAI_10K_sections.parquet

=== TZOO — TRAVELZOO (CIK 1133311) ===
  TZOO: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-02-21  FY2011:  mda, properties, risk_factors
    2013-02-11  FY2012:  mda, properties, risk_factors
    2014-02-12  FY2013:  mda, properties, risk_factors
    2015-02-17  FY2014:  mda, properties, risk_factors
    2016-03-14  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-11  FY2018:  mda, properties, risk_factors
    2020-03-20  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-22  FY2023:  mda, properties, risk_factors
    2025-03-19  FY2024:  mda, properties, risk_factors
    2026-03-11  FY2025:  mda, properties, risk_factors
  -> 48 rows | 339,661 words | 1.01 MB
  -> /content/bond_shared/data/raw/text/TZOO_10K_sections.parquet

=== TEAD — Teads Holding Co. (CIK 1454938) ===
  TEAD: 5 10-K filings since 2011
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 122 public document(s) but only 120 were parsed (accession 0001454938-24-000024). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-07  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 15 rows | 172,657 words | 0.54 MB
  -> /content/bond_shared/data/raw/text/TEAD_10K_sections.parquet

=== SEAT — Vivid Seats Inc. (CIK 1856031) ===
  SEAT: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 134 public document(s) but only 132 were parsed (accession 0000950170-24-028243). The submission may be truncated or malformed.

    2024-03-08  FY2023:  mda, properties, risk_factors
    2025-03-12  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 15 rows | 122,245 words | 0.37 MB
  -> /content/bond_shared/data/raw/text/SEAT_10K_sections.parquet

=== ZDGE — Zedge, Inc. (CIK 1667313) ===
  ZDGE: 10 10-K filings since 2011 (1 amendment(s) skipped)
    2016-10-26  FY2016:  mda, properties, risk_factors
    2017-10-30  FY2017:  mda, properties, risk_factors
    2018-10-29  FY2018:  mda, properties, risk_factors
    2019-10-28  FY2019:  mda, properties, risk_factors
    2020-10-28  FY2020:  mda, properties, risk_factors
    2021-11-09  FY2021:  mda, properties, risk_factors
    2022-11-14  FY2022:  mda, properties, risk_factors
    2023-10-30  FY2023:  mda, properties, risk_factors
    2024-10-29  FY2024:  mda, properties, risk_factors
    2025-10-28  FY2025:  mda, properties, risk_factors
  -> 30 rows | 251,707 words | 0.83 MB
  -> /content/bond_shared/data/raw/text/ZDGE_10K_sections.parquet

=== BODI — Beachbody Company, Inc. (CIK 1826889) ===
  BODI: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-26  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:datequarterend; the raw display text is used instead

    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 134 public document(s) but only 132 were parsed (accession 0000950170-24-029409). The submission may be truncated or malformed.

    2024-03-11  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 18 rows | 165,525 words | 0.50 MB
  -> /content/bond_shared/data/raw/text/BODI_10K_sections.parquet

=== LVO — LiveOne, Inc. (CIK 1491419) ===
  LVO: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-06-23  FY2011:  mda, properties, risk_factors
    2012-08-15  FY2012:  mda, risk_factors
    2013-07-29  FY2013:  mda, risk_factors
    2014-07-29  FY2014:  mda, risk_factors
    2015-07-14  FY2015:  mda, properties, risk_factors
    2016-07-19  FY2016:  mda, properties, risk_factors
    2017-06-14  FY2017:  mda, properties, risk_factors
    2018-06-29  FY2018:  mda, properties, risk_factors
    2019-06-24  FY2019:  mda, properties, risk_factors
    2020-06-26  FY2020:  mda, properties, risk_factors
    2021-07-14  FY2021:  mda, properties, risk_factors
    2022-06-29  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2023-06-29  FY2023:  mda, properties, risk_factors
    2024-07-01  FY2024:  mda, properties, risk_factors
    2025-07-15  FY2025:  mda, properties, risk_factors
    2026-06-29  FY2026:  mda, properties, risk_factors
  -> 45 rows | 554,795 words | 1.68 MB
  -> /content/bond_shared/data/raw/text/LVO_10K_sections.parquet

=== SLE — Super League Enterprise, Inc. (CIK 1621672) ===
  SLE: 7 10-K filings since 2011 (4 amendment(s) skipped)
    2020-03-23  FY2019:  mda, properties, risk_factors
    2021-03-19  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-15  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 21 rows | 235,913 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/SLE_10K_sections.parquet

=== MSFT — MICROSOFT CORP (CIK 789019) ===
  MSFT: 16 10-K filings since 2011
    2011-07-28  FY2011:  mda, properties, risk_factors
    2012-07-26  FY2012:  mda, properties, risk_factors
    2013-07-30  FY2013:  mda, properties, risk_factors
    2014-07-31  FY2014:  mda, properties, risk_factors
    2015-07-31  FY2015:  mda, properties, risk_factors
    2016-07-28  FY2016:  mda, properties, risk_factors
    2017-08-02  FY2017:  mda, properties, risk_factors
    2018-08-03  FY2018:  mda, properties, risk_factors
    2019-08-01  FY2019:  mda, properties, risk_factors
    2020-07-30  FY2020:  mda, properties, risk_factors
    2021-07-29  FY2021:  mda, properties, risk_factors
    2022-07-28  FY2022:  mda, properties, risk_factors
    2023-07-27  FY2023:  mda, properties, risk_factors
    2024-07-30  FY2024:  mda, properties, risk_factors
    2025-07-30  FY2025:  mda, properties, risk_factors
    2026-07-29  FY2026:  mda, properties, risk_factors
  -> 48 rows | 293,047 words | 0.92 MB
  -> /content/bond_shared/data/raw/text/MSFT_10K_sections.parquet

=== PLTR — Palantir Technologies Inc. (CIK 1321655) ===
  PLTR: 6 10-K filings since 2011
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-21  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 180 public document(s) but only 178 were parsed (accession 0001321655-24-000022). The submission may be truncated or malformed.

    2024-02-20  FY2023:  mda, properties, risk_factors
    2025-02-18  FY2024:  mda, properties, risk_factors
    2026-02-17  FY2025:  mda, properties, risk_factors
  -> 18 rows | 314,422 words | 0.93 MB
  -> /content/bond_shared/data/raw/text/PLTR_10K_sections.parquet

=== ORCL — ORACLE CORP (CIK 1341439) ===
  ORCL: 16 10-K filings since 2011
    2011-06-28  FY2011:  mda, properties, risk_factors
    2012-06-26  FY2012:  mda, properties, risk_factors
    2013-06-26  FY2013:  mda, properties, risk_factors
    2014-06-26  FY2014:  mda, properties, risk_factors
    2015-06-25  FY2015:  mda, properties, risk_factors
    2016-06-22  FY2016:  mda, properties, risk_factors
    2017-06-27  FY2017:  mda, properties, risk_factors
    2018-06-22  FY2018:  mda, properties, risk_factors
    2019-06-21  FY2019:  mda, properties, risk_factors
    2020-06-22  FY2020:  mda, properties, risk_factors
    2021-06-21  FY2021:  mda, properties, risk_factors
    2022-06-21  FY2022:  mda, properties, risk_factors
    2023-06-20  FY2023:  mda, properties, risk_factors
    2024-06-20  FY2024:  mda, properties, risk_factors
    2025-06-18  FY2025:  mda, properties, risk_factors
    2026-06-22  FY2026:  mda, properties, risk_factors
  -> 48 rows | 463,287 words | 1.37 MB
  -> /content/bond_shared/data/raw/text/ORCL_10K_sections.parquet

=== PANW — Palo Alto Networks Inc (CIK 1327567) ===
  PANW: 15 10-K filings since 2011
    2012-10-04  FY2012:  mda, properties, risk_factors
    2013-09-25  FY2013:  mda, properties, risk_factors
    2014-09-18  FY2014:  mda, properties, risk_factors
    2015-09-17  FY2015:  mda, properties, risk_factors
    2016-09-08  FY2016:  mda, properties, risk_factors
    2017-09-07  FY2017:  mda, properties, risk_factors
    2018-09-13  FY2018:  mda, properties, risk_factors
    2019-09-09  FY2019:  mda, properties, risk_factors
    2020-09-04  FY2020:  mda, properties, risk_factors
    2021-09-03  FY2021:  mda, properties, risk_factors
    2022-09-06  FY2022:  mda, properties, risk_factors
    2023-09-01  FY2023:  mda, properties, risk_factors
    2024-09-06  FY2024:  mda, properties, risk_factors
    2025-08-29  FY2025:  mda, properties, risk_factors
    2026-09-10  FY2026:  mda, properties, risk_factors
  -> 45 rows | 433,823 words | 1.30 MB
  -> /content/bond_shared/data/raw/text/PANW_10K_sections.parquet

=== CRWD — CrowdStrike Holdings, Inc. (CIK 1535527) ===
  CRWD: 7 10-K filings since 2011
    2020-03-23  FY2020:  mda, properties, risk_factors
    2021-03-18  FY2021:  mda, properties, risk_factors
    2022-03-16  FY2022:  mda, properties, risk_factors
    2023-03-09  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 163 public document(s) but only 161 were parsed (accession 0001535527-24-000007). The submission may be truncated or malformed.

    2024-03-07  FY2024:  mda, properties, risk_factors
    2025-03-10  FY2025:  mda, properties, risk_factors
    2026-03-05  FY2026:  mda, properties, risk_factors
  -> 21 rows | 249,823 words | 0.74 MB
  -> /content/bond_shared/data/raw/text/CRWD_10K_sections.parquet

=== FTNT — Fortinet, Inc. (CIK 1262039) ===
  FTNT: 16 10-K filings since 2011 (3 amendment(s) skipped)

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sBB23205EA738D026FD0D2F145F40862E: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2011-02-25  FY2010:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sC4E2C8B32F2191A57BF1EC57E18EFDD6: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2012-02-28  FY2011:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s18591BCE9351F92F2187DD6092BF6A11: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2013-02-27  FY2012:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s570BA857FBDEBAB905419AEC9F2FF3AE: part_ii_item_9a keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-02-26  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-19  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 124 public document(s) but only 122 were parsed (accession 0001262039-24-000014). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 48 rows | 539,245 words | 1.63 MB
  -> /content/bond_shared/data/raw/text/FTNT_10K_sections.parquet

=== NET — Cloudflare, Inc. (CIK 1477333) ===
  NET: 7 10-K filings since 2011 (1 amendment(s) skipped)
    2020-03-04  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 106 public document(s) but only 104 were parsed (accession 0001477333-24-000013). The submission may be truncated or malformed.

    2024-02-21  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 21 rows | 335,225 words | 0.98 MB
  -> /content/bond_shared/data/raw/text/NET_10K_sections.parquet

=== SNPS — SYNOPSYS INC (CIK 883241) ===
  SNPS: 15 10-K filings since 2011 (1 amendment(s) skipped)
    2011-12-16  FY2011:  mda, properties, risk_factors
    2012-12-20  FY2012:  mda, properties, risk_factors
    2013-12-20  FY2013:  mda, properties, risk_factors
    2014-12-15  FY2014:  mda, properties, risk_factors
    2015-12-14  FY2015:  mda, properties, risk_factors
    2016-12-12  FY2016:  mda, properties, risk_factors
    2017-12-14  FY2017:  mda, properties, risk_factors
    2018-12-17  FY2018:  mda, properties, risk_factors
    2019-12-20  FY2019:  mda, properties, risk_factors
    2020-12-15  FY2020:  mda, properties, risk_factors
    2021-12-13  FY2021:  mda, properties, risk_factors
    2022-12-12  FY2022:  mda, properties, risk_factors
    2023-12-12  FY2023:  mda, properties, risk_factors
    2024-12-19  FY2024:  mda, properties, risk_factors
    2025-12-22  FY2025:  mda, properties, risk_factors
  -> 45 rows | 254,306 words | 0.76 MB
  -> /content/bond_shared/data/raw/text/SNPS_10K_sections.parquet

=== XYZ — Block, Inc. (CIK 1512673) ===
  XYZ: 11 10-K filings since 2011
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-26  FY2019:  mda, properties, risk_factors
    2021-02-23  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 166 public document(s) but only 164 were parsed (accession 0001628280-24-006354). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-24  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 33 rows | 370,793 words | 1.10 MB
  -> /content/bond_shared/data/raw/text/XYZ_10K_sections.parquet

=== TWLO — TWILIO INC (CIK 1447669) ===
  TWLO: 10 10-K filings since 2011 (1 amendment(s) skipped)
    2017-02-22  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-22  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 133 public document(s) but only 131 were parsed (accession 0001447669-24-000034). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 30 rows | 359,167 words | 1.05 MB
  -> /content/bond_shared/data/raw/text/TWLO_10K_sections.parquet

=== NTAP — NetApp, Inc. (CIK 1002047) ===
  NTAP: 16 10-K filings since 2011
    2011-06-23  FY2011:  mda, properties, risk_factors
    2012-06-19  FY2012:  mda, properties, risk_factors
    2013-06-17  FY2013:  mda, properties, risk_factors
    2014-06-17  FY2014:  mda, properties, risk_factors
    2015-06-12  FY2015:  mda, properties, risk_factors
    2016-06-22  FY2016:  mda, properties, risk_factors
    2017-06-20  FY2017:  mda, properties, risk_factors
    2018-06-19  FY2018:  mda, properties, risk_factors
    2019-06-18  FY2019:  mda, properties, risk_factors
    2020-06-15  FY2020:  mda, properties, risk_factors
    2021-06-21  FY2021:  mda, properties, risk_factors
    2022-06-16  FY2022:  mda, properties, risk_factors
    2023-06-14  FY2023:  mda, properties, risk_factors
    2024-06-10  FY2024:  mda, properties, risk_factors
    2025-06-09  FY2025:  mda, properties, risk_factors
    2026-06-05  FY2026:  mda, properties, risk_factors
  -> 48 rows | 369,139 words | 1.12 MB
  -> /content/bond_shared/data/raw/text/NTAP_10K_sections.parquet

=== OKTA — Okta, Inc. (CIK 1660134) ===
  OKTA: 9 10-K filings since 2011
    2018-03-12  FY2018:  mda, properties, risk_factors
    2019-03-14  FY2019:  mda, properties, risk_factors
    2020-03-06  FY2020:  mda, properties, risk_factors
    2021-03-04  FY2021:  mda, properties, risk_factors
    2022-03-07  FY2022:  mda, properties, risk_factors
    2023-03-03  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 103 public document(s) but only 101 were parsed (accession 0001660134-24-000025). The submission may be truncated or malformed.

    2024-03-01  FY2024:  mda, properties, risk_factors
    2025-03-05  FY2025:  mda, properties, risk_factors
    2026-03-05  FY2026:  mda, properties, risk_factors
  -> 27 rows | 291,460 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/OKTA_10K_sections.parquet

=== MDB — MongoDB, Inc. (CIK 1441816) ===
  MDB: 9 10-K filings since 2011
    2018-03-30  FY2018:  mda, properties, risk_factors
    2019-04-01  FY2019:  mda, properties, risk_factors
    2020-03-27  FY2020:  mda, properties, risk_factors
    2021-03-22  FY2021:  mda, properties, risk_factors
    2022-03-18  FY2022:  mda, properties, risk_factors
    2023-03-17  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 115 public document(s) but only 113 were parsed (accession 0001441816-24-000049). The submission may be truncated or malformed.

    2024-03-15  FY2024:  mda, properties, risk_factors
    2025-03-21  FY2025:  mda, properties, risk_factors
    2026-03-11  FY2026:  mda, properties, risk_factors
  -> 27 rows | 301,841 words | 0.90 MB
  -> /content/bond_shared/data/raw/text/MDB_10K_sections.parquet

=== ZS — Zscaler, Inc. (CIK 1713683) ===
  ZS: 9 10-K filings since 2011
    2018-09-13  FY2018:  mda, properties, risk_factors
    2019-09-18  FY2019:  mda, properties, risk_factors
    2020-09-17  FY2020:  mda, properties, risk_factors
    2021-09-16  FY2021:  mda, properties, risk_factors
    2022-09-15  FY2022:  mda, properties, risk_factors
    2023-09-14  FY2023:  mda, properties, risk_factors
    2024-09-12  FY2024:  mda, properties, risk_factors
    2025-09-11  FY2025:  mda, properties, risk_factors
    2026-09-03  FY2026:  mda, properties, risk_factors
  -> 27 rows | 322,307 words | 0.94 MB
  -> /content/bond_shared/data/raw/text/ZS_10K_sections.parquet

=== CPAY — CORPAY, INC. (CIK 1175454) ===
  CPAY: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-25  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 128 public document(s) but only 126 were parsed (accession 0001628280-24-008060). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 474,790 words | 1.42 MB
  -> /content/bond_shared/data/raw/text/CPAY_10K_sections.parquet

=== VRSN — VERISIGN INC/CA (CIK 1014473) ===
  VRSN: 16 10-K filings since 2011
    2011-02-24  FY2010:  mda, properties, risk_factors
    2012-02-24  FY2011:  mda, properties, risk_factors
    2013-02-28  FY2012:  mda, properties, risk_factors
    2014-02-21  FY2013:  mda, properties, risk_factors
    2015-02-13  FY2014:  mda, properties, risk_factors
    2016-02-19  FY2015:  mda, properties, risk_factors
    2017-02-17  FY2016:  mda, properties, risk_factors
    2018-02-16  FY2017:  mda, properties, risk_factors
    2019-02-15  FY2018:  mda, properties, risk_factors
    2020-02-14  FY2019:  mda, properties, risk_factors
    2021-02-19  FY2020:  mda, properties, risk_factors
    2022-02-18  FY2021:  mda, properties, risk_factors
    2023-02-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 86 public document(s) but only 84 were parsed (accession 0001014473-24-000006). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-13  FY2024:  mda, properties, risk_factors
    2026-02-05  FY2025:  mda, properties, risk_factors
  -> 48 rows | 272,334 words | 0.81 MB
  -> /content/bond_shared/data/raw/text/VRSN_10K_sections.parquet

=== FFIV — F5, INC. (CIK 1048695) ===
  FFIV: 15 10-K filings since 2011
    2011-11-22  FY2011:  mda, properties, risk_factors
    2012-11-21  FY2012:  mda, properties, risk_factors
    2013-11-22  FY2013:  mda, properties, risk_factors
    2014-11-26  FY2014:  mda, properties, risk_factors
    2015-11-06  FY2015:  mda, properties, risk_factors
    2016-11-04  FY2016:  mda, properties, risk_factors
    2017-11-03  FY2017:  mda, properties, risk_factors
    2018-11-21  FY2018:  mda, properties, risk_factors
    2019-11-15  FY2019:  mda, properties, risk_factors
    2020-11-19  FY2020:  mda, properties, risk_factors
    2021-11-16  FY2021:  mda, properties, risk_factors
    2022-11-15  FY2022:  mda, properties, risk_factors
    2023-11-14  FY2023:  mda, properties, risk_factors
    2024-11-18  FY2024:  mda, properties, risk_factors
    2025-11-25  FY2025:  mda, properties, risk_factors
  -> 45 rows | 245,828 words | 0.74 MB
  -> /content/bond_shared/data/raw/text/FFIV_10K_sections.parquet

=== IOT — Samsara Inc. (CIK 1642896) ===
  IOT: 5 10-K filings since 2011
    2022-03-30  FY2022:  mda, properties, risk_factors
    2023-03-21  FY2023:  mda, properties, risk_factors
    2024-03-26  FY2024:  mda, properties, risk_factors
    2025-03-25  FY2025:  mda, properties, risk_factors
    2026-03-16  FY2026:  mda, properties, risk_factors
  -> 15 rows | 210,405 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/IOT_10K_sections.parquet

=== NTNX — Nutanix, Inc. (CIK 1618732) ===
  NTNX: 10 10-K filings since 2011 (1 amendment(s) skipped)
    2017-09-18  FY2017:  mda, properties, risk_factors
    2018-09-24  FY2018:  mda, properties, risk_factors
    2019-09-24  FY2019:  mda, properties, risk_factors
    2020-09-23  FY2020:  mda, properties, risk_factors
    2021-09-21  FY2021:  mda, properties, risk_factors
    2022-09-21  FY2022:  mda, properties, risk_factors
    2023-09-21  FY2023:  mda, properties, risk_factors
    2024-09-19  FY2024:  mda, properties, risk_factors
    2025-09-24  FY2025:  mda, properties, risk_factors
    2026-09-18  FY2026:  mda, properties, risk_factors
  -> 30 rows | 369,590 words | 1.09 MB
  -> /content/bond_shared/data/raw/text/NTNX_10K_sections.parquet

=== TOST — Toast, Inc. (CIK 1650164) ===
  TOST: 5 10-K filings since 2011
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 119 public document(s) but only 117 were parsed (accession 0001650164-24-000084). The submission may be truncated or malformed.

    2024-02-27  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-18  FY2025:  mda, properties, risk_factors
  -> 15 rows | 191,344 words | 0.57 MB
  -> /content/bond_shared/data/raw/text/TOST_10K_sections.parquet

=== DOCN — DigitalOcean Holdings, Inc. (CIK 1582961) ===
  DOCN: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-22  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 120 public document(s) but only 118 were parsed (accession 0001582961-24-000031). The submission may be truncated or malformed.

    2024-02-21  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 15 rows | 163,229 words | 0.50 MB
  -> /content/bond_shared/data/raw/text/DOCN_10K_sections.parquet

=== AKAM — AKAMAI TECHNOLOGIES INC (CIK 1086222) ===
  AKAM: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-01  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 135 public document(s) but only 133 were parsed (accession 0001086222-24-000040). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-24  FY2024:  mda, properties, risk_factors
    2026-02-20  FY2025:  mda, properties, risk_factors
  -> 48 rows | 344,570 words | 1.04 MB
  -> /content/bond_shared/data/raw/text/AKAM_10K_sections.parquet

=== GEN — Gen Digital Inc. (CIK 849399) ===
  GEN: 16 10-K filings since 2011 (8 amendment(s) skipped)
    2011-05-20  FY2011:  mda, properties, risk_factors
    2012-05-21  FY2012:  mda, properties, risk_factors
    2013-05-17  FY2013:  mda, properties, risk_factors
    2014-05-16  FY2014:  mda, properties, risk_factors
    2015-05-22  FY2015:  mda, properties, risk_factors
    2016-05-20  FY2016:  mda, properties, risk_factors
    2017-05-19  FY2017:  mda, properties, risk_factors
    2018-10-26  FY2018:  mda, properties, risk_factors
    2019-05-24  FY2019:  mda, properties, risk_factors
    2020-05-28  FY2020:  mda, properties, risk_factors
    2021-05-21  FY2021:  mda, properties, risk_factors
    2022-05-20  FY2022:  mda, properties, risk_factors
    2023-05-25  FY2023:  mda, properties, risk_factors
    2024-05-16  FY2024:  mda, properties, risk_factors
    2025-05-15  FY2025:  mda, properties, risk_factors
    2026-05-21  FY2026:  mda, properties, risk_factors
  -> 48 rows | 313,071 words | 0.96 MB
  -> /content/bond_shared/data/raw/text/GEN_10K_sections.parquet

=== GDDY — GoDaddy Inc. (CIK 1609711) ===
  GDDY: 11 10-K filings since 2011 (1 amendment(s) skipped)
    2016-03-03  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-02-22  FY2018:  mda, properties, risk_factors
    2020-02-21  FY2019:  mda, properties, risk_factors
    2021-02-19  FY2020:  mda, properties, risk_factors
    2022-02-17  FY2021:  mda, properties, risk_factors
    2023-02-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0001609711-24-000022). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 33 rows | 417,629 words | 1.25 MB
  -> /content/bond_shared/data/raw/text/GDDY_10K_sections.parquet

=== GTLB — Gitlab Inc. (CIK 1653482) ===
  GTLB: 5 10-K filings since 2011
    2022-04-08  FY2022:  mda, properties, risk_factors
    2023-03-30  FY2023:  mda, properties, risk_factors
    2024-03-26  FY2024:  mda, properties, risk_factors
    2025-03-21  FY2025:  mda, properties, risk_factors
    2026-03-17  FY2026:  mda, properties, risk_factors
  -> 15 rows | 171,731 words | 0.52 MB
  -> /content/bond_shared/data/raw/text/GTLB_10K_sections.parquet

=== S — SentinelOne, Inc. (CIK 1583708) ===
  S: 5 10-K filings since 2011
    2022-04-07  FY2022:  mda, properties, risk_factors
    2023-03-29  FY2023:  mda, properties, risk_factors
    2024-03-27  FY2024:  mda, properties, risk_factors
    2025-03-26  FY2025:  mda, properties, risk_factors
    2026-03-19  FY2026:  mda, properties, risk_factors
  -> 15 rows | 180,405 words | 0.55 MB
  -> /content/bond_shared/data/raw/text/S_10K_sections.parquet

=== ZETA — Zeta Global Holdings Corp. (CIK 1851003) ===
  ZETA: 5 10-K filings since 2011
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 124 public document(s) but only 122 were parsed (accession 0000950170-24-021671). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 15 rows | 143,837 words | 0.45 MB
  -> /content/bond_shared/data/raw/text/ZETA_10K_sections.parquet

=== DBX — DROPBOX, INC. (CIK 1467623) ===
  DBX: 8 10-K filings since 2011
    2019-02-25  FY2018:  mda, properties, risk_factors
    2020-02-21  FY2019:  mda, properties, risk_factors
    2021-02-19  FY2020:  mda, properties, risk_factors
    2022-02-18  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 128 public document(s) but only 126 were parsed (accession 0001467623-24-000008). The submission may be truncated or malformed.

    2024-02-16  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-20  FY2025:  mda, properties, risk_factors
  -> 24 rows | 253,317 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/DBX_10K_sections.parquet

=== PATH — UiPath, Inc. (CIK 1734722) ===
  PATH: 5 10-K filings since 2011
    2022-04-04  FY2022:  mda, properties, risk_factors
    2023-03-24  FY2023:  mda, properties, risk_factors
    2024-03-27  FY2024:  mda, properties, risk_factors
    2025-03-24  FY2025:  mda, properties, risk_factors
    2026-03-25  FY2026:  mda, properties, risk_factors
  -> 15 rows | 186,099 words | 0.56 MB
  -> /content/bond_shared/data/raw/text/PATH_10K_sections.parquet

=== WEX — WEX Inc. (CIK 1309108) ===
  WEX: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-02-28  FY2010:  mda, properties, risk_factors
    2012-02-28  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-02-27  FY2013:  mda, properties, risk_factors
    2015-02-26  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-03-06  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 210 public document(s) but only 208 were parsed (accession 0001309108-24-000033). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 426,248 words | 1.27 MB
  -> /content/bond_shared/data/raw/text/WEX_10K_sections.parquet

=== QLYS — QUALYS, INC. (CIK 1107843) ===
  QLYS: 14 10-K filings since 2011 (2 amendment(s) skipped)
    2013-03-05  FY2012:  mda, properties, risk_factors
    2014-02-28  FY2013:  mda, properties, risk_factors
    2015-03-06  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-02-24  FY2016:  mda, properties, risk_factors
    2018-02-23  FY2017:  mda, properties, risk_factors
    2019-02-27  FY2018:  mda, properties, risk_factors
    2020-02-21  FY2019:  mda, properties, risk_factors
    2021-02-22  FY2020:  mda, properties, risk_factors
    2022-02-22  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 110 public document(s) but only 108 were parsed (accession 0001107843-24-000008). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-20  FY2025:  mda, properties, risk_factors
  -> 42 rows | 322,835 words | 0.97 MB
  -> /content/bond_shared/data/raw/text/QLYS_10K_sections.parquet

=== CORZ — Core Scientific, Inc./tx (CIK 1839341) ===
  CORZ: 5 10-K filings since 2011 (2 amendment(s) skipped)
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-04-04  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 159 public document(s) but only 157 were parsed (accession 0001628280-24-010682). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 15 rows | 218,393 words | 0.65 MB
  -> /content/bond_shared/data/raw/text/CORZ_10K_sections.parquet

=== VRNS — VARONIS SYSTEMS INC (CIK 1361113) ===
  VRNS: 12 10-K filings since 2011
    2015-02-19  FY2014:  mda, properties, risk_factors
    2016-02-12  FY2015:  mda, properties, risk_factors
    2017-02-09  FY2016:  mda, properties, risk_factors
    2018-02-13  FY2017:  mda, properties, risk_factors
    2019-02-12  FY2018:  mda, properties, risk_factors
    2020-02-11  FY2019:  mda, properties, risk_factors
    2021-02-09  FY2020:  mda, properties, risk_factors
    2022-02-08  FY2021:  mda, properties, risk_factors
    2023-02-07  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 100 public document(s) but only 98 were parsed (accession 0001628280-24-003498). The submission may be truncated or malformed.

    2024-02-06  FY2023:  mda, properties, risk_factors
    2025-02-06  FY2024:  mda, properties, risk_factors
    2026-02-04  FY2025:  mda, properties, risk_factors
  -> 36 rows | 322,759 words | 0.98 MB
  -> /content/bond_shared/data/raw/text/VRNS_10K_sections.parquet

=== ACIW — ACI WORLDWIDE, INC. (CIK 935036) ===
  ACIW: 16 10-K filings since 2011
    2011-02-18  FY2010:  mda, properties, risk_factors
    2012-02-22  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-02-28  FY2013:  mda, properties, risk_factors
    2015-02-26  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-02-27  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 101 public document(s) but only 99 were parsed (accession 0000935036-24-000007). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 332,814 words | 1.00 MB
  -> /content/bond_shared/data/raw/text/ACIW_10K_sections.parquet

=== BB — BLACKBERRY Ltd (CIK 1070235) ===
  BB: 7 10-K filings since 2011
    2020-04-07  FY2020:  mda, properties, risk_factors
    2021-03-31  FY2021:  mda, properties, risk_factors
    2022-04-01  FY2022:  mda, properties, risk_factors
    2023-03-31  FY2023:  mda, properties, risk_factors
    2024-04-04  FY2024:  mda, properties, risk_factors
    2025-04-02  FY2025:  mda, properties, risk_factors
    2026-04-09  FY2026:  mda, properties, risk_factors
  -> 21 rows | 193,193 words | 0.52 MB
  -> /content/bond_shared/data/raw/text/BB_10K_sections.parquet

=== RELY — Remitly Global, Inc. (CIK 1782170) ===
  RELY: 5 10-K filings since 2011
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 255 public document(s) but only 253 were parsed (accession 0001782170-24-000037). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-02-18  FY2025:  mda, properties, risk_factors
  -> 15 rows | 179,499 words | 0.55 MB
  -> /content/bond_shared/data/raw/text/RELY_10K_sections.parquet

=== BOX — BOX INC (CIK 1372612) ===
  BOX: 12 10-K filings since 2011 (1 amendment(s) skipped)
    2015-03-30  FY2015:  mda, properties, risk_factors
    2016-03-30  FY2016:  mda, properties, risk_factors
    2017-03-24  FY2017:  mda, properties, risk_factors
    2018-03-22  FY2018:  mda, properties, risk_factors
    2019-03-20  FY2019:  mda, properties, risk_factors
    2020-03-19  FY2020:  mda, properties, risk_factors
    2021-03-19  FY2021:  mda, properties, risk_factors
    2022-03-16  FY2022:  mda, properties, risk_factors
    2023-03-13  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 99 public document(s) but only 97 were parsed (accession 0000950170-24-029241). The submission may be truncated or malformed.

    2024-03-11  FY2024:  mda, properties, risk_factors
    2025-03-10  FY2025:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.0' is not an English number; the raw display text is used instead

    2026-03-09  FY2026:  mda, properties, risk_factors
  -> 36 rows | 368,820 words | 1.09 MB
  -> /content/bond_shared/data/raw/text/BOX_10K_sections.parquet

=== PAY — Paymentus Holdings, Inc. (CIK 1841156) ===
  PAY: 5 10-K filings since 2011
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-03-03  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0000950170-24-025084). The submission may be truncated or malformed.

    2024-03-05  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 15 rows | 173,363 words | 0.53 MB
  -> /content/bond_shared/data/raw/text/PAY_10K_sections.parquet

=== TENB — Tenable Holdings, Inc. (CIK 1660280) ===
  TENB: 8 10-K filings since 2011
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-02-23  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 116 public document(s) but only 114 were parsed (accession 0001660280-24-000033). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-24  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 24 rows | 251,269 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/TENB_10K_sections.parquet

=== FOUR — Shift4 Payments, Inc. (CIK 1794669) ===
  FOUR: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 127 public document(s) but only 125 were parsed (accession 0001794669-24-000007). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 18 rows | 227,562 words | 0.67 MB
  -> /content/bond_shared/data/raw/text/FOUR_10K_sections.parquet

=== NTCT — NETSCOUT SYSTEMS INC (CIK 1078075) ===
  NTCT: 16 10-K filings since 2011
    2011-05-27  FY2011:  mda, properties, risk_factors
    2012-05-25  FY2012:  mda, properties, risk_factors
    2013-05-24  FY2013:  mda, properties, risk_factors
    2014-05-20  FY2014:  mda, properties, risk_factors
    2015-05-20  FY2015:  mda, properties, risk_factors
    2016-05-31  FY2016:  mda, properties, risk_factors
    2017-05-24  FY2017:  mda, properties, risk_factors
    2018-05-22  FY2018:  mda, properties, risk_factors
    2019-05-28  FY2019:  mda, properties, risk_factors
    2020-05-20  FY2020:  mda, properties, risk_factors
    2021-05-20  FY2021:  mda, properties, risk_factors
    2022-05-19  FY2022:  mda, properties, risk_factors
    2023-05-16  FY2023:  mda, properties, risk_factors
    2024-05-16  FY2024:  mda, properties, risk_factors
    2025-05-15  FY2025:  mda, properties, risk_factors
    2026-05-14  FY2026:  mda, properties, risk_factors
  -> 48 rows | 345,916 words | 1.03 MB
  -> /content/bond_shared/data/raw/text/NTCT_10K_sections.parquet

=== AVPT — AvePoint, Inc. (CIK 1777921) ===
  AVPT: 7 10-K filings since 2011 (2 amendment(s) skipped)
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-09  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0001437749-24-006145). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 21 rows | 161,150 words | 0.48 MB
  -> /content/bond_shared/data/raw/text/AVPT_10K_sections.parquet

=== TDC — TERADATA CORP /DE/ (CIK 816761) ===
  TDC: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-01  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-02-28  FY2012:  mda, properties, risk_factors
    2014-02-27  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-02-23  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 125 public document(s) but only 123 were parsed (accession 0000816761-24-000023). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-27  FY2025:  mda, properties, risk_factors
  -> 48 rows | 264,643 words | 0.85 MB
  -> /content/bond_shared/data/raw/text/TDC_10K_sections.parquet

=== FIVN — Five9, Inc. (CIK 1288847) ===
  FIVN: 12 10-K filings since 2011

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s8d9056acde0048ffa2506ac91c62906f: part_iii_item_13 keeps the anchor; ['part_iii_item_14'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors)

    2015-03-10  FY2014:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s4B7DD1CBA1E684402256DDB4FAEC14EF: part_iii_item_13 keeps the anchor; ['part_iii_item_14'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors)

    2016-03-03  FY2015:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sFAAA236D174F5390A3101B83AB470895: part_iii_item_13 keeps the anchor; ['part_iii_item_14'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors)

    2017-02-28  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on s0E950969E1B79B7FD4FCC7C47D74C8D8: part_iii_item_13 keeps the anchor; ['part_iii_item_14'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors)

    2018-03-01  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on sE4AFA39676365CA69470C62C67A0B434: part_iii_item_13 keeps the anchor; ['part_iii_item_14'] still resolve(s) to the same span (part_iii_item_14: no body-header anchors)

    2019-02-25  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-28  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 144 public document(s) but only 142 were parsed (accession 0001288847-24-000012). The submission may be truncated or malformed.

    2024-02-22  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-20  FY2025:  mda, properties, risk_factors
  -> 36 rows | 387,364 words | 1.14 MB
  -> /content/bond_shared/data/raw/text/FIVN_10K_sections.parquet

=== APPN — APPIAN CORP (CIK 1441683) ===
  APPN: 9 10-K filings since 2011
    2018-02-23  FY2017:  mda, properties, risk_factors
    2019-02-21  FY2018:  mda, properties, risk_factors
    2020-02-20  FY2019:  mda, properties, risk_factors
    2021-02-18  FY2020:  mda, properties, risk_factors
    2022-02-17  FY2021:  mda, properties, risk_factors
    2023-02-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 108 public document(s) but only 106 were parsed (accession 0001441683-24-000016). The submission may be truncated or malformed.

    2024-02-15  FY2023:  mda, properties, risk_factors
    2025-02-19  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 27 rows | 274,270 words | 0.81 MB
  -> /content/bond_shared/data/raw/text/APPN_10K_sections.parquet

=== EEFT — EURONET WORLDWIDE, INC. (CIK 1029199) ===
  EEFT: 16 10-K filings since 2011
    2011-02-25  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-02-27  FY2012:  mda, properties, risk_factors
    2014-02-27  FY2013:  mda, properties, risk_factors
    2015-02-27  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-01  FY2016:  mda, properties, risk_factors
    2018-03-01  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-02-22  FY2020:  mda, properties, risk_factors
    2022-02-23  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2023-02-22  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 123 public document(s) but only 121 were parsed (accession 0001213900-24-016204). The submission may be truncated or malformed.
WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2024-02-22  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2025-02-25  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 407,783 words | 1.18 MB
  -> /content/bond_shared/data/raw/text/EEFT_10K_sections.parquet

=== PAYO — Payoneer Global Inc. (CIK 1845815) ===
  PAYO: 5 10-K filings since 2011
    2022-03-03  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 134 public document(s) but only 132 were parsed (accession 0001558370-24-001998). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item2Properties_221563: part_i_item_2 keeps the anchor; ['part_i_item_2p'] still resolve(s) to the same span (part_i_item_2p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item3LegalProceedings_640986: part_i_item_3 keeps the anchor; ['part_i_item_3l'] still resolve(s) to the same span (part_i_item_3l: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item4MineSafetyDisclosures_249264: part_i_item_4 keeps the anchor; ['part_i_item_4m'] still resolve(s) to the same span (part_i_item_4m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item5MarketforRegistrantsCommonEquityRel: part_ii_item_5 keeps the anchor; ['part_ii_item_5m'] still resolve(s) to the same span (part_ii_item_5m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item6Reserved4_568370: part_ii_item_6 keeps the anchor; ['part_ii_item_6r'] still resolve(s) to the same span (part_ii_item_6r: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysisofF: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatementsandSupplementary: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item10DirectorsExecutiveOfficersandCorpo: part_iii_item_10 keeps the anchor; ['part_iii_item_10d'] still resolve(s) to the same span (part_iii_item_10d: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item11ExecutiveCompensation_941487: part_iii_item_11 keeps the anchor; ['part_iii_item_11e'] still resolve(s) to the same span (part_iii_item_11e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item12SecurityOwnershipofCertainBenefici: part_iii_item_12 keeps the anchor; ['part_iii_item_12s'] still resolve(s) to the same span (part_iii_item_12s: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item13CertainRelationshipsandRelatedTran: part_iii_item_13 keeps the anchor; ['part_iii_item_13c'] still resolve(s) to the same span (part_iii_item_13c: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item14PrincipalAccountantFeesandServices: part_iii_item_14 keeps the anchor; ['part_iii_item_14p'] still resolve(s) to the same span (part_iii_item_14p: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item15ExhibitsFinancialStatementSchedule: part_iv_item_15 keeps the anchor; ['part_iv_item_15e'] still resolve(s) to the same span (part_iv_item_15e: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item16Form10KSummary_808190: part_iv_item_16 keeps the anchor; ['part_iv_item_16f'] still resolve(s) to the same span (part_iv_item_16f: no body header for this item)

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 15 rows | 143,891 words | 0.45 MB
  -> /content/bond_shared/data/raw/text/PAYO_10K_sections.parquet

=== NN — NEXTNAV INC. (CIK 1865631) ===
  NN: 5 10-K filings since 2011
    2022-03-23  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2023-03-30  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 97 public document(s) but only 95 were parsed (accession 0001213900-24-022183). The submission may be truncated or malformed.
WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2024-03-13  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2025-03-12  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt-sec:yesnoballotbox; the raw display text is used instead

    2026-03-17  FY2025:  mda, properties, risk_factors
  -> 15 rows | 102,908 words | 0.32 MB
  -> /content/bond_shared/data/raw/text/NN_10K_sections.parquet

=== RAMP — LiveRamp Holdings, Inc. (CIK 733269) ===
  RAMP: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-05-27  FY2011:  mda, properties, risk_factors
    2012-05-25  FY2012:  mda, properties, risk_factors
    2013-05-29  FY2013:  mda, properties, risk_factors
    2014-05-28  FY2014:  mda, properties, risk_factors
    2015-05-27  FY2015:  mda, properties, risk_factors
    2016-05-27  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item1Business_289547: part_i_item_1 keeps the anchor; ['part_i_item_1b'] still resolve(s) to the same span (part_i_item_1b: body anchor Item1BUnresolvedStaffComments_142370 sits past the next item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item7ManagementsDiscussionandAnalysis_59: part_ii_item_7 keeps the anchor; ['part_ii_item_7m'] still resolve(s) to the same span (part_ii_item_7m: no body header for this item)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Item8FinancialStatements_852204: part_ii_item_8 keeps the anchor; ['part_ii_item_8f'] still resolve(s) to the same span (part_ii_item_8f: no body header for this item)

    2017-05-26  FY2017:  mda, properties, risk_factors
    2018-05-25  FY2018:  mda, properties, risk_factors
    2019-05-29  FY2019:  mda, properties, risk_factors
    2020-05-26  FY2020:  mda, properties, risk_factors
    2021-05-27  FY2021:  mda, properties, risk_factors
    2022-05-24  FY2022:  mda, properties, risk_factors
    2023-05-24  FY2023:  mda, properties, risk_factors
    2024-05-22  FY2024:  mda, properties, risk_factors
    2025-05-21  FY2025:  mda, properties, risk_factors
    2026-05-21  FY2026:  mda, properties, risk_factors
  -> 48 rows | 233,084 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/RAMP_10K_sections.parquet

=== FLYW — Flywire Corp (CIK 1580560) ===
  FLYW: 5 10-K filings since 2011
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 123 public document(s) but only 121 were parsed (accession 0000950170-24-021713). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 15 rows | 256,720 words | 0.77 MB
  -> /content/bond_shared/data/raw/text/FLYW_10K_sections.parquet

=== CALX — CALIX, INC (CIK 1406666) ===
  CALX: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-02-24  FY2010:  mda, properties, risk_factors
    2012-02-24  FY2011:  mda, properties, risk_factors
    2013-02-22  FY2012:  mda, properties, risk_factors
    2014-02-20  FY2013:  mda, properties, risk_factors
    2015-03-04  FY2014:  mda, properties, risk_factors
    2016-02-26  FY2015:  mda, properties, risk_factors
    2017-02-28  FY2016:  mda, properties, risk_factors
    2018-03-14  FY2017:  mda, properties, risk_factors
    2019-03-01  FY2018:  mda, properties, risk_factors
    2020-02-21  FY2019:  mda, properties, risk_factors
    2021-02-22  FY2020:  mda, properties, risk_factors
    2022-02-22  FY2021:  mda, properties, risk_factors
    2023-02-21  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 93 public document(s) but only 91 were parsed (accession 0001406666-24-000012). The submission may be truncated or malformed.

    2024-02-23  FY2023:  mda, properties, risk_factors
    2025-02-21  FY2024:  mda, properties, risk_factors
    2026-02-20  FY2025:  mda, properties, risk_factors
  -> 48 rows | 346,888 words | 1.06 MB
  -> /content/bond_shared/data/raw/text/CALX_10K_sections.parquet

=== BAND — Bandwidth Inc. (CIK 1514416) ===
  BAND: 9 10-K filings since 2011
    2018-02-26  FY2017:  mda, properties, risk_factors
    2019-02-15  FY2018:  mda, properties, risk_factors
    2020-02-21  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 119 public document(s) but only 117 were parsed (accession 0001514416-24-000024). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 27 rows | 310,547 words | 0.91 MB
  -> /content/bond_shared/data/raw/text/BAND_10K_sections.parquet

=== ATEN — A10 Networks, Inc. (CIK 1580808) ===
  ATEN: 12 10-K filings since 2011 (4 amendment(s) skipped)
    2015-03-11  FY2014:  mda, properties, risk_factors
    2016-03-01  FY2015:  mda, properties, risk_factors
    2017-02-24  FY2016:  mda, properties, risk_factors
    2018-08-29  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-10  FY2019:  mda, properties, risk_factors
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-03-08  FY2021:  mda, properties, risk_factors
    2023-02-27  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 114 public document(s) but only 112 were parsed (accession 0001580808-24-000049). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-02-25  FY2024:  mda, properties, risk_factors
    2026-02-25  FY2025:  mda, properties, risk_factors
  -> 36 rows | 334,731 words | 1.00 MB
  -> /content/bond_shared/data/raw/text/ATEN_10K_sections.parquet

=== MQ — Marqeta, Inc. (CIK 1522540) ===
  MQ: 5 10-K filings since 2011
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 118 public document(s) but only 116 were parsed (accession 0001628280-24-007663). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-26  FY2024:  mda, properties, risk_factors
    2026-02-24  FY2025:  mda, properties, risk_factors
  -> 15 rows | 138,528 words | 0.42 MB
  -> /content/bond_shared/data/raw/text/MQ_10K_sections.parquet

=== AI — C3.ai, Inc. (CIK 1577526) ===
  AI: 6 10-K filings since 2011
    2021-06-25  FY2021:  mda, properties, risk_factors
    2022-06-23  FY2022:  mda, properties, risk_factors
    2023-06-22  FY2023:  mda, properties, risk_factors
    2024-06-18  FY2024:  mda, properties, risk_factors
    2025-06-23  FY2025:  mda, properties, risk_factors
    2026-06-24  FY2026:  mda, properties, risk_factors
  -> 18 rows | 236,779 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/AI_10K_sections.parquet

=== EVTC — EVERTEC, Inc. (CIK 1559865) ===
  EVTC: 13 10-K filings since 2011 (2 amendment(s) skipped)
    2014-03-17  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-05-26  FY2015:  mda, properties, risk_factors
    2017-02-24  FY2016:  mda, properties, risk_factors
    2018-02-28  FY2017:  mda, properties, risk_factors
    2019-02-26  FY2018:  mda, properties, risk_factors
    2020-02-27  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-02-25  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 155 public document(s) but only 153 were parsed (accession 0001559865-24-000008). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-03-02  FY2025:  mda, properties, risk_factors
  -> 39 rows | 285,323 words | 0.87 MB
  -> /content/bond_shared/data/raw/text/EVTC_10K_sections.parquet

=== PRGS — PROGRESS SOFTWARE CORP /MA (CIK 876167) ===
  PRGS: 16 10-K filings since 2011 (8 amendment(s) skipped)
    2011-01-31  FY2010:  mda, properties, risk_factors
    2012-01-30  FY2011:  mda, properties, risk_factors
    2013-01-29  FY2012:  mda, properties, risk_factors
    2014-01-29  FY2013:  mda, properties, risk_factors
    2015-01-29  FY2014:  mda, properties, risk_factors
    2016-01-29  FY2015:  mda, properties, risk_factors
    2017-01-30  FY2016:  mda, properties, risk_factors
    2018-01-26  FY2017:  mda, properties, risk_factors
    2019-01-28  FY2018:  mda, properties, risk_factors
    2020-01-27  FY2019:  mda, properties, risk_factors
    2021-01-27  FY2020:  mda, properties, risk_factors
    2022-01-27  FY2021:  mda, properties, risk_factors
    2023-01-27  FY2022:  mda, properties, risk_factors
    2024-01-26  FY2023:  mda, properties, risk_factors
    2025-01-21  FY2024:  mda, properties, risk_factors
    2026-01-20  FY2025:  mda, properties, risk_factors
  -> 48 rows | 272,707 words | 0.77 MB
  -> /content/bond_shared/data/raw/text/PRGS_10K_sections.parquet

=== AEVA — Aeva Technologies, Inc. (CIK 1789029) ===
  AEVA: 7 10-K filings since 2011 (2 amendment(s) skipped)
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-11  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 103 public document(s) but only 101 were parsed (accession 0000950170-24-032299). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors
    2026-03-20  FY2025:  mda, properties, risk_factors
  -> 21 rows | 149,390 words | 0.46 MB
  -> /content/bond_shared/data/raw/text/AEVA_10K_sections.parquet

=== RXT — Rackspace Technology, Inc. (CIK 1810019) ===
  RXT: 6 10-K filings since 2011
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 139 public document(s) but only 137 were parsed (accession 0001810019-24-000042). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-21  FY2024:  mda, properties, risk_factors
    2026-03-06  FY2025:  mda, properties, risk_factors
  -> 18 rows | 249,081 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/RXT_10K_sections.parquet

=== SABR — Sabre Corp (CIK 1597033) ===
  SABR: 12 10-K filings since 2011
    2015-03-03  FY2014:  mda, properties, risk_factors
    2016-02-19  FY2015:  mda, properties, risk_factors
    2017-02-17  FY2016:  mda, properties, risk_factors
    2018-02-16  FY2017:  mda, properties, risk_factors
    2019-02-15  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i2f58d9c9b64940dbabb704b32d5e7e9e_91: part_ii_item_8 keeps the anchor; ['part_i_item_8'] still resolve(s) to the same span (part_i_item_8: no body header for this item)

    2020-02-26  FY2019:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i708df20e2c71402180b0c33bfe8a88f4_91: part_ii_item_8 keeps the anchor; ['part_i_item_8'] still resolve(s) to the same span (part_i_item_8: no body header for this item)

    2021-02-25  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i97e730ddfc964b19bd27ef0eaf869f85_100: part_ii_item_8 keeps the anchor; ['part_i_item_8'] still resolve(s) to the same span (part_i_item_8: no body header for this item)

    2022-02-18  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on if571bc33c69b43d4a55e853157464629_100: part_ii_item_8 keeps the anchor; ['part_i_item_8'] still resolve(s) to the same span (part_i_item_8: no body header for this item)

    2023-02-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 143 public document(s) but only 141 were parsed (accession 0001597033-24-000020). The submission may be truncated or malformed.
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i55128ad93dca46c1b757f2f37175a9b3_106: part_ii_item_8 keeps the anchor; ['part_i_item_8'] still resolve(s) to the same span (part_i_item_8: no body header for this item)

    2024-02-15  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on idfe50180a41747ee95c12c48e8dcee8e_109: part_ii_item_8 keeps the anchor; ['part_i_item_8'] still resolve(s) to the same span (part_i_item_8: no body header for this item)

    2025-02-20  FY2024:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i48845c293dca47b19bf27e65f2d8ce5b_109: part_ii_item_8 keeps the anchor; ['part_i_item_8'] still resolve(s) to the same span (part_i_item_8: no body header for this item)

    2026-02-18  FY2025:  mda, properties, risk_factors
  -> 36 rows | 387,776 words | 1.15 MB
  -> /content/bond_shared/data/raw/text/SABR_10K_sections.parquet

=== BLZE — Backblaze, Inc. (CIK 1462056) ===
  BLZE: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-11  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 15 rows | 147,854 words | 0.44 MB
  -> /content/bond_shared/data/raw/text/BLZE_10K_sections.parquet

=== RPD — Rapid7, Inc. (CIK 1560327) ===
  RPD: 11 10-K filings since 2011 (1 amendment(s) skipped)
    2016-03-10  FY2015:  mda, properties, risk_factors
    2017-03-09  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-02-28  FY2018:  mda, properties, risk_factors
    2020-02-28  FY2019:  mda, properties, risk_factors
    2021-02-26  FY2020:  mda, properties, risk_factors
    2022-02-24  FY2021:  mda, properties, risk_factors
    2023-02-24  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 119 public document(s) but only 117 were parsed (accession 0001560327-24-000021). The submission may be truncated or malformed.

    2024-02-26  FY2023:  mda, properties, risk_factors
    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-19  FY2025:  mda, properties, risk_factors
  -> 33 rows | 339,039 words | 1.00 MB
  -> /content/bond_shared/data/raw/text/RPD_10K_sections.parquet

=== PAYS — Paysign, Inc. (CIK 1496443) ===
  PAYS: 16 10-K filings since 2011 (4 amendment(s) skipped)
    2011-04-01  FY2010:  mda, properties, risk_factors
    2012-04-02  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-25  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-27  FY2016:  mda, properties, risk_factors
    2018-03-26  FY2017:  mda, properties, risk_factors
    2019-03-12  FY2018:  mda, properties, risk_factors
    2020-04-03  FY2019:  mda, properties, risk_factors
    2021-03-26  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on a_026: part_ii_item_9c keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: body anchor a_025 already claimed)

    2022-03-23  FY2021:  mda, properties, risk_factors
    2023-03-22  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.23' is not an English number; the raw display text is used instead

    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 48 rows | 165,322 words | 0.53 MB
  -> /content/bond_shared/data/raw/text/PAYS_10K_sections.parquet

=== OSPN — OneSpan Inc. (CIK 1044777) ===
  OSPN: 16 10-K filings since 2011
    2011-03-11  FY2010:  mda, properties, risk_factors
    2012-03-09  FY2011:  mda, properties, risk_factors
    2013-03-08  FY2012:  mda, properties, risk_factors
    2014-03-12  FY2013:  mda, properties, risk_factors
    2015-03-13  FY2014:  mda, properties, risk_factors
    2016-02-29  FY2015:  mda, properties, risk_factors
    2017-03-10  FY2016:  mda, properties, risk_factors
    2018-03-08  FY2017:  mda, properties, risk_factors
    2019-03-15  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-02-25  FY2020:  mda, properties, risk_factors
    2022-02-22  FY2021:  mda, properties, risk_factors
    2023-02-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 146 public document(s) but only 144 were parsed (accession 0001628280-24-009466). The submission may be truncated or malformed.

    2024-03-06  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-02-26  FY2025:  mda, properties, risk_factors
  -> 48 rows | 354,129 words | 1.07 MB
  -> /content/bond_shared/data/raw/text/OSPN_10K_sections.parquet

=== CCSI — Consensus Cloud Solutions, Inc. (CIK 1866633) ===
  CCSI: 5 10-K filings since 2011
    2022-04-15  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 134 public document(s) but only 132 were parsed (accession 0001866633-24-000004). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-02-13  FY2025:  mda, properties, risk_factors
  -> 15 rows | 124,912 words | 0.38 MB
  -> /content/bond_shared/data/raw/text/CCSI_10K_sections.parquet

=== PRTH — Priority Technology Holdings, Inc. (CIK 1653558) ===
  PRTH: 10 10-K filings since 2011 (1 amendment(s) skipped)
    2017-03-13  FY2016:  mda, properties, risk_factors
    2018-03-27  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-23  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 136 public document(s) but only 134 were parsed (accession 0001653558-24-000039). The submission may be truncated or malformed.

    2024-03-12  FY2023:  mda, properties, risk_factors
    2025-03-06  FY2024:  mda, properties, risk_factors
    2026-03-10  FY2025:  mda, properties, risk_factors
  -> 30 rows | 134,799 words | 0.41 MB
  -> /content/bond_shared/data/raw/text/PRTH_10K_sections.parquet

=== YEXT — Yext, Inc. (CIK 1614178) ===
  YEXT: 9 10-K filings since 2011
    2018-03-16  FY2018:  mda, properties, risk_factors
    2019-03-15  FY2019:  mda, properties, risk_factors
    2020-03-20  FY2020:  mda, properties, risk_factors
    2021-03-16  FY2021:  mda, properties, risk_factors
    2022-03-18  FY2022:  mda, properties, risk_factors
    2023-03-17  FY2023:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 95 public document(s) but only 93 were parsed (accession 0001614178-24-000023). The submission may be truncated or malformed.

    2024-03-13  FY2024:  mda, properties, risk_factors
    2025-03-13  FY2025:  mda, properties, risk_factors
    2026-03-10  FY2026:  mda, properties, risk_factors
  -> 27 rows | 260,497 words | 0.77 MB
  -> /content/bond_shared/data/raw/text/YEXT_10K_sections.parquet

=== KPLT — Katapult Holdings, Inc. (CIK 1785424) ===
  KPLT: 7 10-K filings since 2011 (1 amendment(s) skipped)
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-03-15  FY2021:  mda, properties, risk_factors
    2023-03-09  FY2022:  mda, properties, risk_factors
    2024-04-24  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-11  FY2025:  mda, properties, risk_factors
  -> 21 rows | 191,219 words | 0.55 MB
  -> /content/bond_shared/data/raw/text/KPLT_10K_sections.parquet

=== IIIV — i3 Verticals, Inc. (CIK 1728688) ===
  IIIV: 8 10-K filings since 2011
    2018-12-07  FY2018:  mda, properties, risk_factors
    2019-11-22  FY2019:  mda, properties, risk_factors
    2020-11-23  FY2020:  mda, properties, risk_factors
    2021-11-22  FY2021:  mda, properties, risk_factors
    2022-11-18  FY2022:  mda, properties, risk_factors
    2023-11-22  FY2023:  mda, properties, risk_factors
    2024-11-25  FY2024:  mda, properties, risk_factors
    2025-11-21  FY2025:  mda, properties, risk_factors
  -> 24 rows | 244,722 words | 0.71 MB
  -> /content/bond_shared/data/raw/text/IIIV_10K_sections.parquet

=== BKKT — Bakkt, Inc. (CIK 1820302) ===
  BKKT: 6 10-K filings since 2011 (2 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-20  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 18 rows | 252,159 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/BKKT_10K_sections.parquet

=== MOVE — Corvex, Inc. (CIK 1734750) ===
  MOVE: 5 10-K filings since 2011 (2 amendment(s) skipped)
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-04-16  FY2023:  mda, properties, risk_factors
    2025-04-09  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 15 rows | 124,251 words | 0.40 MB
  -> /content/bond_shared/data/raw/text/MOVE_10K_sections.parquet

=== LSAK — LESAKA TECHNOLOGIES INC (CIK 1041514) ===
  LSAK: 16 10-K filings since 2011 (3 amendment(s) skipped)

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_32: part_i_item_2 keeps the anchor; ['part_i_item_3', 'part_i_item_4'] still resolve(s) to the same span (part_i_item_3: no body-header anchors; part_i_item_4: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_65: part_ii_item_8 keeps the anchor; ['part_ii_item_9'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_69: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2011-08-25  FY2011:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_32: part_i_item_2 keeps the anchor; ['part_i_item_3', 'part_i_item_4'] still resolve(s) to the same span (part_i_item_3: no body-header anchors; part_i_item_4: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_65: part_ii_item_8 keeps the anchor; ['part_ii_item_9'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_69: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2012-08-23  FY2012:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_31: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_63: part_ii_item_8 keeps the anchor; ['part_ii_item_9'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_66: part_ii_item_9b keeps the anchor; ['part_iv_item_15'] still resolve(s) to the same span (part_iv_item_15: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_67: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2013-08-22  FY2013:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_28: part_i_item_1b keeps the anchor; ['part_i_item_2'] still resolve(s) to the same span (part_i_item_2: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_56: part_ii_item_8 keeps the anchor; ['part_ii_item_9'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_60: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2014-08-28  FY2014:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_31: part_i_item_1b keeps the anchor; ['part_i_item_2', 'part_i_item_3'] still resolve(s) to the same span (part_i_item_2: no body-header anchors; part_i_item_3: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_58: part_ii_item_8 keeps the anchor; ['part_ii_item_9'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_62: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2015-08-20  FY2015:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_32: part_i_item_1b keeps the anchor; ['part_i_item_2', 'part_i_item_3'] still resolve(s) to the same span (part_i_item_2: no body-header anchors; part_i_item_3: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_61: part_ii_item_8 keeps the anchor; ['part_ii_item_9', 'part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors; part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_64: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2016-08-25  FY2016:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_34: part_i_item_1b keeps the anchor; ['part_i_item_2', 'part_i_item_3'] still resolve(s) to the same span (part_i_item_2: no body-header anchors; part_i_item_3: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_63: part_ii_item_8 keeps the anchor; ['part_ii_item_9', 'part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors; part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_66: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2017-08-24  FY2017:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_33: part_i_item_1b keeps the anchor; ['part_i_item_2', 'part_i_item_3'] still resolve(s) to the same span (part_i_item_2: no body-header anchors; part_i_item_3: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_64: part_ii_item_8 keeps the anchor; ['part_ii_item_9', 'part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors; part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_68: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2018-09-12  FY2018:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_31: part_i_item_1b keeps the anchor; ['part_i_item_2', 'part_i_item_3'] still resolve(s) to the same span (part_i_item_2: no body-header anchors; part_i_item_3: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_66: part_ii_item_8 keeps the anchor; ['part_ii_item_9', 'part_ii_item_9a'] still resolve(s) to the same span (part_ii_item_9: no body-header anchors; part_ii_item_9a: no body-header anchors)
WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on page_70: part_iii_item_10 keeps the anchor; ['part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14'] still resolve(s) to the same span (part_iii_item_11: no body-header anchors; part_iii_item_12: no body-header anchors; part_iii_item_13: no body-header anchors; part_iii_item_14: no body-header anchors)

    2019-10-25  FY2019:  mda, properties, risk_factors
    2020-09-10  FY2020:  mda, properties, risk_factors
    2021-09-13  FY2021:  mda, properties, risk_factors
    2022-09-09  FY2022:  mda, properties, risk_factors
    2023-09-12  FY2023:  mda, properties, risk_factors
    2024-09-11  FY2024:  mda, properties, risk_factors
    2025-09-29  FY2025:  mda, properties, risk_factors
    2026-09-09  FY2026:  mda, properties, risk_factors
  -> 48 rows | 431,069 words | 1.41 MB
  -> /content/bond_shared/data/raw/text/LSAK_10K_sections.parquet

=== IMXI — International Money Express, Inc. (CIK 1683695) ===
  IMXI: 10 10-K filings since 2011 (2 amendment(s) skipped)

WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found

    2017-04-19  FY2016:  NONE
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-22  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-07  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 112 public document(s) but only 110 were parsed (accession 0001683695-24-000042). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-06  FY2025:  mda, properties, risk_factors
  -> 27 rows | 207,049 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/IMXI_10K_sections.parquet

=== RPAY — Repay Holdings Corp (CIK 1720592) ===
  RPAY: 8 10-K filings since 2011 (6 amendment(s) skipped)
    2019-03-26  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-01  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-01  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 111 public document(s) but only 109 were parsed (accession 0000950170-24-023102). The submission may be truncated or malformed.

    2024-02-29  FY2023:  mda, properties, risk_factors
    2025-03-03  FY2024:  mda, properties, risk_factors
    2026-03-09  FY2025:  mda, properties, risk_factors
  -> 24 rows | 213,211 words | 0.62 MB
  -> /content/bond_shared/data/raw/text/RPAY_10K_sections.parquet

=== TLS — TELOS CORP (CIK 320121) ===
  TLS: 16 10-K filings since 2011 (2 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-31  FY2014:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on TableofContents: part_ii_item_5 keeps the anchor; ['part_ii_item_9b'] still resolve(s) to the same span (part_ii_item_9b: no body-header anchors)

    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-03-30  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-04-13  FY2019:  mda, properties, risk_factors
    2021-03-25  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 114 public document(s) but only 112 were parsed (accession 0000320121-24-000017). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-10  FY2024:  mda, properties, risk_factors
    2026-03-16  FY2025:  mda, properties, risk_factors
  -> 48 rows | 257,863 words | 0.79 MB
  -> /content/bond_shared/data/raw/text/TLS_10K_sections.parquet

=== PDYN — Palladyne AI Corp. (CIK 1826681) ===
  PDYN: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-03-29  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 102 public document(s) but only 100 were parsed (accession 0000950170-24-022168). The submission may be truncated or malformed.

    2024-02-28  FY2023:  mda, properties, risk_factors
    2025-02-20  FY2024:  mda, properties, risk_factors
    2026-03-05  FY2025:  mda, properties, risk_factors
  -> 18 rows | 167,017 words | 0.50 MB
  -> /content/bond_shared/data/raw/text/PDYN_10K_sections.parquet

=== ZSQR — Z Squared Inc. (CIK 1759186) ===
  ZSQR: 6 10-K filings since 2011 (5 amendment(s) skipped)
    2021-03-31  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:edgarprovcountryen rejected the content: 'British Virgin Islands' is not an EDGAR state, province or country name; the raw display text is used instead

    2022-04-08  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-26  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-19  FY2025:  mda, properties, risk_factors
  -> 18 rows | 63,713 words | 0.21 MB
  -> /content/bond_shared/data/raw/text/ZSQR_10K_sections.parquet

=== DVLT — Datavault AI Inc. (CIK 1682149) ===
  DVLT: 8 10-K filings since 2011
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-03-25  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-17  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 24 rows | 59,054 words | 0.16 MB
  -> /content/bond_shared/data/raw/text/DVLT_10K_sections.parquet

=== AGPU — Axe Compute Inc. (CIK 1446159) ===
  AGPU: 16 10-K filings since 2011 (6 amendment(s) skipped)
    2011-03-31  FY2010:  mda, properties, risk_factors
    2012-04-16  FY2011:  mda, properties, risk_factors
    2013-03-22  FY2012:  mda, properties, risk_factors
    2014-03-27  FY2013:  mda, properties, risk_factors
    2015-04-30  FY2014:  mda, properties, risk_factors
    2016-03-16  FY2015:  mda, properties, risk_factors
    2017-03-15  FY2016:  mda, properties, risk_factors
    2018-04-02  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-04-01  FY2019:  mda, properties, risk_factors
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-21  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 48 rows | 244,130 words | 0.75 MB
  -> /content/bond_shared/data/raw/text/AGPU_10K_sections.parquet

=== VERI — Veritone, Inc. (CIK 1615165) ===
  VERI: 9 10-K filings since 2011 (5 amendment(s) skipped)
    2018-03-09  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-11  FY2019:  mda, properties, risk_factors
    2021-03-05  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-04-01  FY2024:  mda, properties, risk_factors
    2026-04-15  FY2025:  mda, properties, risk_factors
  -> 27 rows | 242,526 words | 0.72 MB
  -> /content/bond_shared/data/raw/text/VERI_10K_sections.parquet

=== TCX — TUCOWS INC /PA/ (CIK 909494) ===
  TCX: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-22  FY2010:  mda, properties, risk_factors
    2012-03-16  FY2011:  mda, properties, risk_factors
    2013-03-15  FY2012:  mda, properties, risk_factors
    2014-03-18  FY2013:  mda, properties, risk_factors
    2015-03-11  FY2014:  mda, properties, risk_factors
    2016-03-09  FY2015:  mda, properties, risk_factors
    2017-03-08  FY2016:  mda, properties, risk_factors
    2018-03-06  FY2017:  mda, properties, risk_factors
    2019-03-05  FY2018:  mda, properties, risk_factors
    2020-03-04  FY2019:  mda, properties, risk_factors
    2021-03-03  FY2020:  mda, properties, risk_factors
    2022-03-01  FY2021:  mda, properties, risk_factors
    2023-03-15  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-12  FY2025:  mda, properties, risk_factors
  -> 48 rows | 505,650 words | 1.50 MB
  -> /content/bond_shared/data/raw/text/TCX_10K_sections.parquet

=== AIFC — AI Financial Corp (CIK 862861) ===
  AIFC: 16 10-K filings since 2011 (10 amendment(s) skipped)
    2011-03-17  FY2011:  mda, properties, risk_factors
    2012-03-15  FY2011:  mda, properties, risk_factors
    2013-03-22  FY2012:  mda, properties, risk_factors
    2014-03-14  FY2013:  mda, properties, risk_factors
    2015-03-30  FY2015:  mda, properties, risk_factors
    2016-04-04  FY2016:  mda, properties, risk_factors
    2017-03-31  FY2016:  mda, properties, risk_factors
    2018-06-12  FY2017:  mda, properties, risk_factors
    2019-03-29  FY2018:  mda, properties, risk_factors
    2020-04-06  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2021:  mda, properties, risk_factors
    2022-04-01  FY2022:  mda, properties, risk_factors
    2023-04-17  FY2022:  mda, properties, risk_factors
    2024-04-08  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-04-13  FY2025:  mda, properties, risk_factors
  -> 48 rows | 220,373 words | 0.67 MB
  -> /content/bond_shared/data/raw/text/AIFC_10K_sections.parquet

=== USIO — Usio, Inc. (CIK 1088034) ===
  USIO: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-04-15  FY2010:  mda, properties, risk_factors
    2012-04-03  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-31  FY2013:  mda, properties, risk_factors
    2015-03-30  FY2014:  mda, properties, risk_factors
    2016-03-30  FY2015:  mda, properties, risk_factors
    2017-04-06  FY2016:  mda, properties, risk_factors
    2018-03-30  FY2017:  mda, properties, risk_factors
    2019-03-27  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-17  FY2021:  mda, properties, risk_factors
    2023-03-08  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-03-26  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 48 rows | 196,581 words | 0.60 MB
  -> /content/bond_shared/data/raw/text/USIO_10K_sections.parquet

=== AISP — Airship AI Holdings, Inc. (CIK 1842566) ===
  AISP: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-04-06  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i1: part_i_item_1a keeps the anchor; ['part_i_item_1'] still resolve(s) to the same span (part_i_item_1: body anchor p1 does not follow the shared one)

    2024-04-01  FY2023:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on i5: part_ii_item_6 keeps the anchor; ['part_ii_item_5'] still resolve(s) to the same span (part_ii_item_5: body anchor p2 does not follow the shared one)

    2025-02-28  FY2024:  mda, properties, risk_factors
    2026-02-17  FY2025:  mda, properties, risk_factors
  -> 15 rows | 130,549 words | 0.39 MB
  -> /content/bond_shared/data/raw/text/AISP_10K_sections.parquet

=== LIDR — AEye, Inc. (CIK 1818644) ===
  LIDR: 6 10-K filings since 2011 (1 amendment(s) skipped)
    2021-03-15  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-16  FY2022:  mda, properties, risk_factors
    2024-03-27  FY2023:  mda, properties, risk_factors
    2025-02-24  FY2024:  mda, properties, risk_factors
    2026-03-18  FY2025:  mda, properties, risk_factors
  -> 18 rows | 163,403 words | 0.50 MB
  -> /content/bond_shared/data/raw/text/LIDR_10K_sections.parquet

=== REKR — Rekor Systems, Inc. (CIK 1697851) ===
  REKR: 9 10-K filings since 2011 (1 amendment(s) skipped)
    2018-04-12  FY2017:  mda, properties, risk_factors
    2019-04-11  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-12  FY2020:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-03-25  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 27 rows | 169,781 words | 0.55 MB
  -> /content/bond_shared/data/raw/text/REKR_10K_sections.parquet

=== BNAI — Brand Engagement Network Inc. (CIK 1838163) ===
  BNAI: 5 10-K filings since 2011
    2022-03-11  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-04-16  FY2025:  mda, properties, risk_factors
  -> 15 rows | 143,608 words | 0.42 MB
  -> /content/bond_shared/data/raw/text/BNAI_10K_sections.parquet

=== AVX — AVAX ONE TECHNOLOGY LTD. (CIK 1826397) ===
  AVX: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-14  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-04-07  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 15 rows | 69,626 words | 0.23 MB
  -> /content/bond_shared/data/raw/text/AVX_10K_sections.parquet

=== VHC — VirnetX Holding Corp (CIK 1082324) ===
  VHC: 16 10-K filings since 2011 (5 amendment(s) skipped)
    2011-03-16  FY2010:  mda, properties, risk_factors
    2012-02-29  FY2011:  mda, properties, risk_factors
    2013-03-01  FY2012:  mda, properties, risk_factors
    2014-03-03  FY2013:  mda, properties, risk_factors
    2015-03-02  FY2014:  mda, properties, risk_factors
    2016-03-15  FY2015:  mda, properties, risk_factors
    2017-03-16  FY2016:  mda, properties, risk_factors
    2018-03-16  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-16  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 77 public document(s) but only 75 were parsed (accession 0001140361-24-013522). The submission may be truncated or malformed.

    2024-03-15  FY2023:  mda, properties, risk_factors
    2025-03-17  FY2024:  mda, properties, risk_factors
    2026-03-24  FY2025:  mda, properties, risk_factors
  -> 48 rows | 221,993 words | 0.69 MB
  -> /content/bond_shared/data/raw/text/VHC_10K_sections.parquet

=== XBP — XBP Global Holdings, Inc. (CIK 1839530) ===
  XBP: 5 10-K filings since 2011 (2 amendment(s) skipped)
    2022-03-31  FY2021:  mda, properties, risk_factors
    2023-03-29  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-03-19  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 15 rows | 87,820 words | 0.26 MB
  -> /content/bond_shared/data/raw/text/XBP_10K_sections.parquet

=== AIXC — AIxCrypto Holdings, Inc. (CIK 1460702) ===
  AIXC: 10 10-K filings since 2011 (4 amendment(s) skipped)
    2016-03-21  FY2015:  mda, properties, risk_factors
    2017-02-27  FY2016:  mda, properties, risk_factors
    2018-03-19  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-31  FY2019:  mda, properties, risk_factors
    2022-03-31  FY2021:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead
WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.90' is not an English number; the raw display text is used instead

    2023-05-02  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: format ixt-sec:duryear rejected the content: '.90' is not an English number; the raw display text is used instead

    2024-04-08  FY2023:  mda, properties, risk_factors
    2025-06-30  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 30 rows | 207,794 words | 0.65 MB
  -> /content/bond_shared/data/raw/text/AIXC_10K_sections.parquet

=== DRK — DarkHorse Technologies Inc. (CIK 1591956) ===
  DRK: 7 10-K filings since 2011 (1 amendment(s) skipped)
    2018-03-21  FY2017:  mda, properties, risk_factors
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-05-14  FY2019:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 116 public document(s) but only 114 were parsed (accession 0001591956-24-000004). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 21 rows | 123,433 words | 0.37 MB
  -> /content/bond_shared/data/raw/text/DRK_10K_sections.parquet

=== BIRD — Smartbird, Inc. (CIK 1653909) ===
  BIRD: 5 10-K filings since 2011
    2022-03-16  FY2021:  mda, properties, risk_factors
    2023-03-10  FY2022:  mda, properties, risk_factors

WARNING:edgar.sgml.sgml_common:SGML header declares 102 public document(s) but only 100 were parsed (accession 0001653909-24-000015). The submission may be truncated or malformed.

    2024-03-13  FY2023:  mda, properties, risk_factors
    2025-03-12  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 15 rows | 206,345 words | 0.63 MB
  -> /content/bond_shared/data/raw/text/BIRD_10K_sections.parquet

=== AIFA — All In FutureTech Alliance, Inc. (CIK 1708341) ===
  AIFA: 9 10-K filings since 2011 (4 amendment(s) skipped)
    2018-03-22  FY2017:  mda, properties, risk_factors
    2019-03-18  FY2018:  mda, properties, risk_factors
    2020-03-16  FY2019:  mda, properties, risk_factors
    2021-04-13  FY2020:  mda, properties, risk_factors
    2022-05-26  FY2021:  mda, properties, risk_factors
    2023-03-24  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-06-09  FY2024:  mda, properties, risk_factors
    2026-05-22  FY2025:  mda, properties, risk_factors
  -> 27 rows | 143,995 words | 0.45 MB
  -> /content/bond_shared/data/raw/text/AIFA_10K_sections.parquet

=== AZIO — AZIO AI HOLDINGS, INC. (CIK 1563568) ===
  AZIO: 9 10-K filings since 2011 (3 amendment(s) skipped)
    2018-03-12  FY2017:  mda, properties, risk_factors
    2019-02-19  FY2018:  mda, properties, risk_factors
    2020-03-10  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-04-26  FY2021:  mda, properties, risk_factors
    2023-09-25  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-04-13  FY2025:  mda, properties, risk_factors
  -> 27 rows | 206,493 words | 0.63 MB
  -> /content/bond_shared/data/raw/text/AZIO_10K_sections.parquet

=== RKTO — Rocket One Inc. (CIK 1711786) ===
  RKTO: 8 10-K filings since 2011
    2019-04-01  FY2018:  mda, properties, risk_factors
    2020-03-02  FY2019:  mda, properties, risk_factors
    2021-03-16  FY2020:  mda, properties, risk_factors
    2022-03-30  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-03-28  FY2023:  mda, properties, risk_factors
    2025-03-28  FY2024:  mda, properties, risk_factors
    2026-03-27  FY2025:  mda, properties, risk_factors
  -> 24 rows | 200,716 words | 0.63 MB
  -> /content/bond_shared/data/raw/text/RKTO_10K_sections.parquet

=== INTZ — INTRUSION INC (CIK 736012) ===
  INTZ: 16 10-K filings since 2011 (1 amendment(s) skipped)
    2011-03-29  FY2010:  mda, properties, risk_factors
    2012-03-30  FY2011:  mda, properties, risk_factors
    2013-03-28  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-27  FY2014:  mda, properties, risk_factors
    2016-03-29  FY2015:  mda, properties, risk_factors
    2017-03-29  FY2016:  mda, properties, risk_factors
    2018-03-29  FY2017:  mda, properties, risk_factors
    2019-03-28  FY2018:  mda, properties, risk_factors
    2020-03-27  FY2019:  mda, properties, risk_factors
    2021-03-09  FY2020:  mda, properties, risk_factors
    2022-03-18  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-01  FY2023:  mda, properties, risk_factors
    2025-02-27  FY2024:  mda, properties, risk_factors
    2026-03-25  FY2025:  mda, properties, risk_factors
  -> 48 rows | 150,074 words | 0.44 MB
  -> /content/bond_shared/data/raw/text/INTZ_10K_sections.parquet

=== BTLN — Brightline Interactive, Inc./NV (CIK 1854445) ===
  BTLN: 5 10-K filings since 2011 (1 amendment(s) skipped)
    2021-09-28  FY2021:  mda, properties, risk_factors
    2022-09-28  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2023-09-28  FY2023:  mda, properties, risk_factors
    2024-09-30  FY2024:  mda, properties, risk_factors
    2025-09-29  FY2025:  mda, properties, risk_factors
  -> 15 rows | 78,624 words | 0.25 MB
  -> /content/bond_shared/data/raw/text/BTLN_10K_sections.parquet

=== CISO — CISO Global, Inc. (CIK 1777319) ===
  CISO: 7 10-K filings since 2011 (2 amendment(s) skipped)
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-31  FY2020:  mda, properties, risk_factors
    2022-04-15  FY2021:  mda, properties, risk_factors
    2023-03-31  FY2022:  mda, properties, risk_factors
    2024-04-16  FY2023:  mda, properties, risk_factors
    2025-03-31  FY2024:  mda, properties, risk_factors
    2026-03-30  FY2025:  mda, properties, risk_factors
  -> 21 rows | 99,107 words | 0.31 MB
  -> /content/bond_shared/data/raw/text/CISO_10K_sections.parquet

=== BLIN — Bridgeline Digital, Inc. (CIK 1378590) ===
  BLIN: 15 10-K filings since 2011 (5 amendment(s) skipped)
    2011-12-29  FY2011:  mda, properties, risk_factors
    2012-12-05  FY2012:  mda, properties, risk_factors
    2013-12-20  FY2013:  mda, properties, risk_factors
    2014-12-29  FY2014:  mda, properties, risk_factors
    2015-12-24  FY2015:  mda, properties, risk_factors
    2016-12-19  FY2016:  mda, properties, risk_factors
    2017-12-21  FY2017:  mda, properties, risk_factors
    2018-12-28  FY2018:  mda, properties, risk_factors
    2019-12-27  FY2019:  mda, properties, risk_factors
    2020-12-23  FY2020:  mda, properties, risk_factors
    2021-12-20  FY2021:  mda, properties, risk_factors
    2022-12-21  FY2022:  mda, properties, risk_factors
    2023-12-27  FY2023:  mda, properties, risk_factors
    2024-12-26  FY2024:  mda, properties, risk_factors
    2025-12-19  FY2025:  mda, properties, risk_factors
  -> 45 rows | 191,081 words | 0.59 MB
  -> /content/bond_shared/data/raw/text/BLIN_10K_sections.parquet

=== AUID — authID Inc. (CIK 1534154) ===
  AUID: 15 10-K filings since 2011 (2 amendment(s) skipped)

WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found

    2012-03-28  FY2011:  mda, properties

WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found
WARNING:edgar.documents.extractors.hybrid_section_detector:All detection strategies failed, no sections found

    2013-04-01  FY2012:  mda, properties
    2014-04-15  FY2013:  mda
    2015-03-31  FY2014:  mda, properties, risk_factors
    2016-11-02  FY2015:  mda, properties, risk_factors
    2017-07-12  FY2016:  mda, properties, risk_factors
    2018-03-15  FY2017:  mda, properties, risk_factors
    2019-03-08  FY2018:  mda, properties, risk_factors
    2020-03-30  FY2019:  mda, properties, risk_factors
    2021-03-08  FY2020:  mda, properties, risk_factors
    2022-03-22  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-03-20  FY2023:  mda, properties, risk_factors
    2025-03-13  FY2024:  mda, properties, risk_factors
    2026-03-31  FY2025:  mda, properties, risk_factors
  -> 41 rows | 179,953 words | 0.57 MB
  -> /content/bond_shared/data/raw/text/AUID_10K_sections.parquet

=== OLB — OLB GROUP, INC. (CIK 1314196) ===
  OLB: 16 10-K filings since 2011 (3 amendment(s) skipped)
    2011-03-25  FY2010:  mda, properties, risk_factors
    2012-03-20  FY2011:  mda, properties, risk_factors
    2013-04-01  FY2012:  mda, properties, risk_factors
    2014-03-28  FY2013:  mda, properties, risk_factors
    2015-03-23  FY2014:  mda, properties, risk_factors
    2016-04-01  FY2015:  mda, properties, risk_factors
    2017-04-12  FY2016:  mda, properties, risk_factors
    2018-04-13  FY2017:  mda, properties, risk_factors
    2019-04-18  FY2018:  mda, properties, risk_factors
    2020-04-29  FY2019:  mda, properties, risk_factors
    2021-03-30  FY2020:  mda, properties, risk_factors
    2022-03-28  FY2021:  mda, properties, risk_factors
    2023-03-30  FY2022:  mda, properties, risk_factors
    2024-04-15  FY2023:  mda, properties, risk_factors
    2025-04-15  FY2024:  mda, properties, risk_factors
    2026-04-01  FY2025:  mda, properties, risk_factors
  -> 48 rows | 264,940 words | 0.81 MB
  -> /content/bond_shared/data/raw/text/OLB_10K_sections.parquet

=== YYAI — AIRWA INC. (CIK 1674440) ===
  YYAI: 10 10-K filings since 2011 (4 amendment(s) skipped)
    2017-08-03  FY2017:  mda, properties, risk_factors
    2018-08-14  FY2018:  mda, properties, risk_factors
    2019-08-06  FY2019:  mda, properties, risk_factors
    2020-08-24  FY2020:  mda, properties, risk_factors
    2021-08-06  FY2021:  mda, properties, risk_factors
    2023-05-17  FY2022:  mda, properties, risk_factors

WARNING:edgar.documents.strategies.xbrl_extraction:Inline XBRL: unsupported format ixt:numunitdecimalin; the raw display text is used instead

    2023-09-14  FY2023:  mda, properties, risk_factors
    2024-07-25  FY2024:  mda, properties, risk_factors
    2025-08-13  FY2025:  mda, properties, risk_factors
    2026-09-21  FY2026:  mda, properties, risk_factors
  -> 30 rows | 177,400 words | 0.54 MB
  -> /content/bond_shared/data/raw/text/YYAI_10K_sections.parquet

=== CETX — CEMTREX INC (CIK 1435064) ===
  CETX: 16 10-K filings since 2011 (17 amendment(s) skipped)
    2011-01-14  FY2010:  mda, properties, risk_factors
    2012-01-10  FY2011:  mda, properties, risk_factors
    2012-12-26  FY2012:  mda, properties, risk_factors
    2014-01-16  FY2013:  mda, properties, risk_factors
    2014-12-29  FY2014:  mda, properties, risk_factors
    2015-12-21  FY2015:  mda, properties, risk_factors
    2016-12-28  FY2016:  mda, properties, risk_factors
    2017-12-13  FY2017:  mda, properties, risk_factors
    2019-01-11  FY2018:  mda, properties, risk_factors
    2020-01-14  FY2019:  mda, properties, risk_factors
    2021-01-05  FY2020:  mda, properties, risk_factors

WARNING:edgar.documents.utils.toc_analyzer:TOC anchor collision on Su_025: part_iv_item_15 keeps the anchor; ['part_iv_item_16'] still resolve(s) to the same span (part_iv_item_16: body anchor Su_024 does not follow the shared one)

    2022-01-21  FY2021:  mda, properties, risk_factors
    2022-12-28  FY2022:  mda, properties, risk_factors
    2023-12-28  FY2023:  mda, properties, risk_factors
    2024-12-30  FY2024:  mda, properties, risk_factors
    2025-12-29  FY2025:  mda, properties, risk_factors
  -> 48 rows | 150,150 words | 0.45 MB
  -> /content/bond_shared/data/raw/text/CETX_10K_sections.parquet

Stored 592 file(s); 0 failed.

## 7. Read the parquet files back

In [86]:
import glob

files = sorted(glob.glob(os.path.join(DROPBOX_RAW, "*_10K_sections.parquet")))
print(f"Parquet files in {DROPBOX_RAW}:")
for f in files:
    print(f"  {os.path.basename(f)}  ({os.path.getsize(f) / 1e6:.2f} MB)")

sections = pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)
print(f"\nCombined shape: {sections.shape}")
print("Columns:", list(sections.columns))

Parquet files in /content/bond_shared/data/raw/text:
  ABCL_10K_sections.parquet  (0.87 MB)
  ABEO_10K_sections.parquet  (0.92 MB)
  ABOS_10K_sections.parquet  (0.71 MB)
  ABSI_10K_sections.parquet  (0.66 MB)
  ABUS_10K_sections.parquet  (0.89 MB)
  ABVC_10K_sections.parquet  (0.89 MB)
  ACAD_10K_sections.parquet  (1.36 MB)
  ACET_10K_sections.parquet  (1.25 MB)
  ACHV_10K_sections.parquet  (1.27 MB)
  ACIW_10K_sections.parquet  (1.00 MB)
  ACRS_10K_sections.parquet  (1.19 MB)
  ACXP_10K_sections.parquet  (0.44 MB)
  ADIL_10K_sections.parquet  (0.82 MB)
  ADI_10K_sections.parquet  (0.84 MB)
  ADMA_10K_sections.parquet  (1.21 MB)
  AEON_10K_sections.parquet  (0.65 MB)
  AEVA_10K_sections.parquet  (0.46 MB)
  AGEN_10K_sections.parquet  (1.73 MB)
  AGIO_10K_sections.parquet  (1.34 MB)
  AGPU_10K_sections.parquet  (0.75 MB)
  AIFA_10K_sections.parquet  (0.45 MB)
  AIFC_10K_sections.parquet  (0.67 MB)
  AIM_10K_sections.parquet  (0.74 MB)
  AIP_10K_sections.parquet  (0.56 MB)
  AISP_10K_sections.parquet  (0.39 MB)
  AIXC_10K_sections.parquet  (0.65 MB)
  AI_10K_sections.parquet  (0.71 MB)
  AKAM_10K_sections.parquet  (1.04 MB)
  AKTX_10K_sections.parquet  (0.42 MB)
  ALDX_10K_sections.parquet  (1.30 MB)
  ALEC_10K_sections.parquet  (1.01 MB)
  ALGM_10K_sections.parquet  (0.52 MB)
  ALGS_10K_sections.parquet  (0.95 MB)
  ALLO_10K_sections.parquet  (0.98 MB)
  ALLR_10K_sections.parquet  (0.71 MB)
  ALMU_10K_sections.parquet  (0.17 MB)
  ALNY_10K_sections.parquet  (1.71 MB)
  ALT_10K_sections.parquet  (1.36 MB)
  ALXO_10K_sections.parquet  (0.86 MB)
  ALZN_10K_sections.parquet  (0.49 MB)
  AMD_10K_sections.parquet  (1.15 MB)
  ANAB_10K_sections.parquet  (1.05 MB)
  ANGI_10K_sections.parquet  (0.59 MB)
  ANIX_10K_sections.parquet  (0.59 MB)
  ANNX_10K_sections.parquet  (0.73 MB)
  ANVS_10K_sections.parquet  (0.78 MB)
  AOSL_10K_sections.parquet  (1.28 MB)
  APPN_10K_sections.parquet  (0.81 MB)
  APRE_10K_sections.parquet  (1.01 MB)
  APVO_10K_sections.parquet  (0.93 MB)
  ARCT_10K_sections.parquet  (0.57 MB)
  ARDX_10K_sections.parquet  (1.21 MB)
  ARMP_10K_sections.parquet  (0.84 MB)
  ARQT_10K_sections.parquet  (0.93 MB)
  ARTL_10K_sections.parquet  (0.49 MB)
  ARVN_10K_sections.parquet  (0.98 MB)
  ARWR_10K_sections.parquet  (0.90 MB)
  ASMB_10K_sections.parquet  (1.03 MB)
  ATEN_10K_sections.parquet  (1.00 MB)
  ATNM_10K_sections.parquet  (1.02 MB)
  ATOS_10K_sections.parquet  (0.87 MB)
  ATRA_10K_sections.parquet  (1.40 MB)
  ATYR_10K_sections.parquet  (1.17 MB)
  AUID_10K_sections.parquet  (0.57 MB)
  AUPH_10K_sections.parquet  (0.37 MB)
  AURA_10K_sections.parquet  (0.64 MB)
  AVGO_10K_sections.parquet  (0.61 MB)
  AVIR_10K_sections.parquet  (1.01 MB)
  AVPT_10K_sections.parquet  (0.48 MB)
  AVTX_10K_sections.parquet  (1.23 MB)
  AVXL_10K_sections.parquet  (0.62 MB)
  AVX_10K_sections.parquet  (0.23 MB)
  AXSM_10K_sections.parquet  (1.50 MB)
  AZIO_10K_sections.parquet  (0.63 MB)
  BAND_10K_sections.parquet  (0.91 MB)
  BBIO_10K_sections.parquet  (1.24 MB)
  BBLG_10K_sections.parquet  (0.60 MB)
  BB_10K_sections.parquet  (0.52 MB)
  BCDA_10K_sections.parquet  (1.08 MB)
  BCYC_10K_sections.parquet  (1.10 MB)
  BDTX_10K_sections.parquet  (1.11 MB)
  BEAM_10K_sections.parquet  (1.25 MB)
  BIRD_10K_sections.parquet  (0.63 MB)
  BIVI_10K_sections.parquet  (0.64 MB)
  BKKT_10K_sections.parquet  (0.75 MB)
  BLIN_10K_sections.parquet  (0.59 MB)
  BLZE_10K_sections.parquet  (0.44 MB)
  BMBL_10K_sections.parquet  (0.76 MB)
  BMEA_10K_sections.parquet  (0.74 MB)
  BMRN_10K_sections.parquet  (1.46 MB)
  BNAI_10K_sections.parquet  (0.42 MB)
  BNTC_10K_sections.parquet  (0.70 MB)
  BODI_10K_sections.parquet  (0.50 MB)
  BOLT_10K_sections.parquet  (0.75 MB)
  BOX_10K_sections.parquet  (1.09 MB)
  BRTX_10K_sections.parquet  (0.89 MB)
  BTLN_10K_sections.parquet  (0.25 MB)
  BZFD_10K_sections.parquet  (0.55 MB)
  CABA_10K_sections.parquet  (1.19 MB)
  CADL_10K_sections.parquet  (0.88 MB)
  CALC_10K_sections.parquet  (0.83 MB)
  CALX_10K_sections.parquet  (1.06 MB)
  CAPR_10K_sections.parquet  (1.73 MB)
  CARG_10K_sections.parquet  (0.72 MB)
  CARS_10K_sections.parquet  (0.49 MB)
  CBIO_10K_sections.parquet  (1.14 MB)
  CBUS_10K_sections.parquet  (0.69 MB)
  CCCC_10K_sections.parquet  (0.80 MB)
  CCSI_10K_sections.parquet  (0.38 MB)
  CDIO_10K_sections.parquet  (0.49 MB)
  CDT_10K_sections.parquet  (0.42 MB)
  CDXS_10K_sections.parquet  (1.46 MB)
  CELC_10K_sections.parquet  (0.58 MB)
  CELU_10K_sections.parquet  (0.74 MB)
  CELZ_10K_sections.parquet  (0.20 MB)
  CETX_10K_sections.parquet  (0.45 MB)
  CEVA_10K_sections.parquet  (0.95 MB)
  CGEM_10K_sections.parquet  (0.89 MB)
  CGTX_10K_sections.parquet  (0.66 MB)
  CHRS_10K_sections.parquet  (1.62 MB)
  CING_10K_sections.parquet  (0.65 MB)
  CISO_10K_sections.parquet  (0.31 MB)
  CLDI_10K_sections.parquet  (0.66 MB)
  CLDX_10K_sections.parquet  (1.31 MB)
  CLNN_10K_sections.parquet  (0.68 MB)
  CLRB_10K_sections.parquet  (0.74 MB)
  CLYM_10K_sections.parquet  (0.64 MB)
  CMPX_10K_sections.parquet  (0.75 MB)
  CNSP_10K_sections.parquet  (0.29 MB)
  CNSY_10K_sections.parquet  (1.23 MB)
  CNTN_10K_sections.parquet  (0.53 MB)
  CNTX_10K_sections.parquet  (0.44 MB)
  COCP_10K_sections.parquet  (0.89 MB)
  COGT_10K_sections.parquet  (0.63 MB)
  CORT_10K_sections.parquet  (0.90 MB)
  CORZ_10K_sections.parquet  (0.65 MB)
  CPAY_10K_sections.parquet  (1.42 MB)
  CRBP_10K_sections.parquet  (0.93 MB)
  CRBU_10K_sections.parquet  (0.76 MB)
  CRDF_10K_sections.parquet  (0.86 MB)
  CRDO_10K_sections.parquet  (0.52 MB)
  CRIS_10K_sections.parquet  (1.51 MB)
  CRMD_10K_sections.parquet  (1.01 MB)
  CRSP_10K_sections.parquet  (1.49 MB)
  CRUS_10K_sections.parquet  (0.78 MB)
  CRVO_10K_sections.parquet  (1.15 MB)
  CRVS_10K_sections.parquet  (1.03 MB)
  CRWD_10K_sections.parquet  (0.74 MB)
  CSBR_10K_sections.parquet  (0.41 MB)
  CTMX_10K_sections.parquet  (1.36 MB)
  CTXR_10K_sections.parquet  (0.72 MB)
  CUE_10K_sections.parquet  (0.95 MB)
  CVM_10K_sections.parquet  (0.31 MB)
  CYTK_10K_sections.parquet  (1.43 MB)
  DARE_10K_sections.parquet  (1.47 MB)
  DBVT_10K_sections.parquet  (0.77 MB)
  DBX_10K_sections.parquet  (0.75 MB)
  DCOY_10K_sections.parquet  (0.88 MB)
  DFTX_10K_sections.parquet  (0.80 MB)
  DIBS_10K_sections.parquet  (0.53 MB)
  DIOD_10K_sections.parquet  (1.03 MB)
  DJT_10K_sections.parquet  (0.46 MB)
  DMAC_10K_sections.parquet  (0.53 MB)
  DMRA_10K_sections.parquet  (0.86 MB)
  DNA_10K_sections.parquet  (0.66 MB)
  DNLI_10K_sections.parquet  (1.25 MB)
  DNTH_10K_sections.parquet  (1.04 MB)
  DOCN_10K_sections.parquet  (0.50 MB)
  DRK_10K_sections.parquet  (0.37 MB)
  DRMA_10K_sections.parquet  (0.60 MB)
  DSGN_10K_sections.parquet  (0.71 MB)
  DTIL_10K_sections.parquet  (1.17 MB)
  DVLT_10K_sections.parquet  (0.16 MB)
  DWTX_10K_sections.parquet  (0.57 MB)
  DYAI_10K_sections.parquet  (0.52 MB)
  DYN_10K_sections.parquet  (0.94 MB)
  EDIT_10K_sections.parquet  (1.45 MB)
  EDSA_10K_sections.parquet  (0.59 MB)
  EDVA_10K_sections.parquet  (0.26 MB)
  EEFT_10K_sections.parquet  (1.18 MB)
  ELDN_10K_sections.parquet  (0.86 MB)
  ELOX_10K_sections.parquet  (0.86 MB)
  ELTX_10K_sections.parquet  (0.79 MB)
  ELVN_10K_sections.parquet  (0.89 MB)
  ENSC_10K_sections.parquet  (0.78 MB)
  ENTA_10K_sections.parquet  (1.08 MB)
  ENTX_10K_sections.parquet  (0.62 MB)
  ENVB_10K_sections.parquet  (0.77 MB)
  EQ_10K_sections.parquet  (1.15 MB)
  ERAS_10K_sections.parquet  (0.72 MB)
  ERNA_10K_sections.parquet  (0.78 MB)
  EVER_10K_sections.parquet  (0.59 MB)
  EVTC_10K_sections.parquet  (0.87 MB)
  EWTX_10K_sections.parquet  (0.77 MB)
  EXEL_10K_sections.parquet  (1.29 MB)
  EYPT_10K_sections.parquet  (1.26 MB)
  FABC_10K_sections.parquet  (0.88 MB)
  FATE_10K_sections.parquet  (1.37 MB)
  FBIO_10K_sections.parquet  (1.28 MB)
  FDMT_10K_sections.parquet  (0.90 MB)
  FENC_10K_sections.parquet  (1.08 MB)
  FFIV_10K_sections.parquet  (0.74 MB)
  FHTX_10K_sections.parquet  (0.49 MB)
  FIVN_10K_sections.parquet  (1.14 MB)
  FLNA_10K_sections.parquet  (1.20 MB)
  FLYW_10K_sections.parquet  (0.77 MB)
  FOUR_10K_sections.parquet  (0.67 MB)
  FTH_10K_sections.parquet  (0.75 MB)
  FTNT_10K_sections.parquet  (1.63 MB)
  FULC_10K_sections.parquet  (0.86 MB)
  GALT_10K_sections.parquet  (0.67 MB)
  GANX_10K_sections.parquet  (0.52 MB)
  GCTS_10K_sections.parquet  (0.39 MB)
  GDDY_10K_sections.parquet  (1.25 MB)
  GEN_10K_sections.parquet  (0.96 MB)
  GERN_10K_sections.parquet  (1.63 MB)
  GLSI_10K_sections.parquet  (0.54 MB)
  GLUE_10K_sections.parquet  (0.72 MB)
  GNPX_10K_sections.parquet  (0.88 MB)
  GOOGL_10K_sections.parquet  (0.68 MB)
  GOSS_10K_sections.parquet  (1.05 MB)
  GOVX_10K_sections.parquet  (0.58 MB)
  GRCE_10K_sections.parquet  (0.50 MB)
  GRDX_10K_sections.parquet  (0.65 MB)
  GRI_10K_sections.parquet  (0.60 MB)
  GRPN_10K_sections.parquet  (1.26 MB)
  GSIT_10K_sections.parquet  (0.79 MB)
  GTBP_10K_sections.parquet  (0.64 MB)
  GTLB_10K_sections.parquet  (0.52 MB)
  GYRE_10K_sections.parquet  (1.50 MB)
  HALO_10K_sections.parquet  (0.93 MB)
  HCWB_10K_sections.parquet  (0.58 MB)
  HIND_10K_sections.parquet  (0.91 MB)
  HLSQ_10K_sections.parquet  (0.82 MB)
  HOWL_10K_sections.parquet  (0.80 MB)
  HRMY_10K_sections.parquet  (0.76 MB)
  HRTX_10K_sections.parquet  (1.13 MB)
  HUMA_10K_sections.parquet  (0.64 MB)
  HURA_10K_sections.parquet  (0.96 MB)
  HYPD_10K_sections.parquet  (0.77 MB)
  IBIO_10K_sections.parquet  (1.02 MB)
  IBRX_10K_sections.parquet  (1.80 MB)
  ICCC_10K_sections.parquet  (0.65 MB)
  ICU_10K_sections.parquet  (0.41 MB)
  IDYA_10K_sections.parquet  (1.16 MB)
  IGC_10K_sections.parquet  (0.62 MB)
  IIIV_10K_sections.parquet  (0.71 MB)
  IKT_10K_sections.parquet  (0.85 MB)
  IMA_10K_sections.parquet  (0.75 MB)
  IMMX_10K_sections.parquet  (0.39 MB)
  IMNM_10K_sections.parquet  (0.75 MB)
  IMNN_10K_sections.parquet  (1.01 MB)
  IMRX_10K_sections.parquet  (0.76 MB)
  IMUX_10K_sections.parquet  (1.23 MB)
  IMVT_10K_sections.parquet  (1.03 MB)
  IMXI_10K_sections.parquet  (0.62 MB)
  INAB_10K_sections.parquet  (0.70 MB)
  INCY_10K_sections.parquet  (1.19 MB)
  INDI_10K_sections.parquet  (0.42 MB)
  INDP_10K_sections.parquet  (0.43 MB)
  INKT_10K_sections.parquet  (0.62 MB)
  INMB_10K_sections.parquet  (0.55 MB)
  INO_10K_sections.parquet  (1.10 MB)
  INSM_10K_sections.parquet  (1.20 MB)
  INTC_10K_sections.parquet  (0.95 MB)
  INTZ_10K_sections.parquet  (0.44 MB)
  INVA_10K_sections.parquet  (1.18 MB)
  IONS_10K_sections.parquet  (0.91 MB)
  IOT_10K_sections.parquet  (0.62 MB)
  IOVA_10K_sections.parquet  (1.62 MB)
  IPSC_10K_sections.parquet  (0.74 MB)
  IPWR_10K_sections.parquet  (0.44 MB)
  IRD_10K_sections.parquet  (1.13 MB)
  IRON_10K_sections.parquet  (0.86 MB)
  IVVD_10K_sections.parquet  (0.96 MB)
  JAGX_10K_sections.parquet  (1.02 MB)
  JANX_10K_sections.parquet  (0.72 MB)
  JAZZ_10K_sections.parquet  (2.19 MB)
  JBIO_10K_sections.parquet  (0.57 MB)
  JSPR_10K_sections.parquet  (0.93 MB)
  KALA_10K_sections.parquet  (1.22 MB)
  KLRS_10K_sections.parquet  (0.91 MB)
  KOD_10K_sections.parquet  (0.99 MB)
  KPLT_10K_sections.parquet  (0.55 MB)
  KPRX_10K_sections.parquet  (0.92 MB)
  KPTI_10K_sections.parquet  (1.52 MB)
  KROS_10K_sections.parquet  (0.94 MB)
  KRRO_10K_sections.parquet  (0.95 MB)
  KRSA_10K_sections.parquet  (0.58 MB)
  KRYS_10K_sections.parquet  (0.89 MB)
  KTTA_10K_sections.parquet  (0.37 MB)
  KURA_10K_sections.parquet  (1.18 MB)
  KYMR_10K_sections.parquet  (0.86 MB)
  KYNB_10K_sections.parquet  (1.49 MB)
  LASR_10K_sections.parquet  (0.40 MB)
  LCTX_10K_sections.parquet  (1.42 MB)
  LEDS_10K_sections.parquet  (1.30 MB)
  LENZ_10K_sections.parquet  (0.68 MB)
  LEXX_10K_sections.parquet  (0.53 MB)
  LGND_10K_sections.parquet  (0.91 MB)
  LGVN_10K_sections.parquet  (0.72 MB)
  LIDR_10K_sections.parquet  (0.50 MB)
  LITS_10K_sections.parquet  (0.72 MB)
  LNAI_10K_sections.parquet  (0.52 MB)
  LONA_10K_sections.parquet  (0.93 MB)
  LPCN_10K_sections.parquet  (1.42 MB)
  LRMR_10K_sections.parquet  (1.25 MB)
  LSAK_10K_sections.parquet  (1.41 MB)
  LSCC_10K_sections.parquet  (0.83 MB)
  LSTA_10K_sections.parquet  (1.22 MB)
  LTRN_10K_sections.parquet  (0.69 MB)
  LVO_10K_sections.parquet  (1.68 MB)
  LXRX_10K_sections.parquet  (0.87 MB)
  LYEL_10K_sections.parquet  (0.59 MB)
  MAX_10K_sections.parquet  (0.63 MB)
  MBIO_10K_sections.parquet  (0.97 MB)
  MBRX_10K_sections.parquet  (0.78 MB)
  MCHP_10K_sections.parquet  (1.26 MB)
  MCRB_10K_sections.parquet  (1.37 MB)
  MDB_10K_sections.parquet  (0.90 MB)
  MDGL_10K_sections.parquet  (1.20 MB)
  MDXG_10K_sections.parquet  (0.97 MB)
  META_10K_sections.parquet  (1.26 MB)
  MGNX_10K_sections.parquet  (1.13 MB)
  MGTX_10K_sections.parquet  (1.17 MB)
  MIRM_10K_sections.parquet  (1.08 MB)
  MIST_10K_sections.parquet  (0.82 MB)
  MLTX_10K_sections.parquet  (0.54 MB)
  MNKD_10K_sections.parquet  (1.33 MB)
  MNOV_10K_sections.parquet  (0.96 MB)
  MNPR_10K_sections.parquet  (0.85 MB)
  MOVE_10K_sections.parquet  (0.40 MB)
  MPWR_10K_sections.parquet  (0.87 MB)
  MQ_10K_sections.parquet  (0.42 MB)
  MRAM_10K_sections.parquet  (0.57 MB)
  MRKR_10K_sections.parquet  (1.08 MB)
  MRNA_10K_sections.parquet  (1.12 MB)
  MRVI_10K_sections.parquet  (0.80 MB)
  MRVL_10K_sections.parquet  (0.44 MB)
  MSFT_10K_sections.parquet  (0.92 MB)
  MTCH_10K_sections.parquet  (1.07 MB)
  MTNB_10K_sections.parquet  (0.97 MB)
  MTSI_10K_sections.parquet  (0.96 MB)
  MTVA_10K_sections.parquet  (1.01 MB)
  MU_10K_sections.parquet  (0.79 MB)
  MXL_10K_sections.parquet  (1.40 MB)
  MX_10K_sections.parquet  (1.35 MB)
  NAUT_10K_sections.parquet  (0.63 MB)
  NERV_10K_sections.parquet  (1.29 MB)
  NET_10K_sections.parquet  (0.98 MB)
  NGNE_10K_sections.parquet  (1.35 MB)
  NKTR_10K_sections.parquet  (1.13 MB)
  NKTX_10K_sections.parquet  (0.81 MB)
  NNVC_10K_sections.parquet  (1.11 MB)
  NN_10K_sections.parquet  (0.32 MB)
  NRDS_10K_sections.parquet  (0.42 MB)
  NRIX_10K_sections.parquet  (0.92 MB)
  NRXP_10K_sections.parquet  (0.68 MB)
  NTAP_10K_sections.parquet  (1.12 MB)
  NTCT_10K_sections.parquet  (1.03 MB)
  NTLA_10K_sections.parquet  (1.22 MB)
  NTNX_10K_sections.parquet  (1.09 MB)
  NTRB_10K_sections.parquet  (0.38 MB)
  NUVB_10K_sections.parquet  (0.75 MB)
  NVAX_10K_sections.parquet  (1.28 MB)
  NVCT_10K_sections.parquet  (0.34 MB)
  NVDA_10K_sections.parquet  (1.08 MB)
  NVEC_10K_sections.parquet  (0.22 MB)
  NVTS_10K_sections.parquet  (0.40 MB)
  NXDR_10K_sections.parquet  (0.49 MB)
  NXPI_10K_sections.parquet  (0.44 MB)
  NXTC_10K_sections.parquet  (0.79 MB)
  OABI_10K_sections.parquet  (0.57 MB)
  OBIO_10K_sections.parquet  (0.48 MB)
  OCGN_10K_sections.parquet  (1.45 MB)
  OCUL_10K_sections.parquet  (1.55 MB)
  OGEN_10K_sections.parquet  (1.54 MB)
  OKTA_10K_sections.parquet  (0.87 MB)
  OKUR_10K_sections.parquet  (0.68 MB)
  OLB_10K_sections.parquet  (0.81 MB)
  OLMA_10K_sections.parquet  (0.91 MB)
  OMER_10K_sections.parquet  (0.92 MB)
  ONCO_10K_sections.parquet  (0.65 MB)
  ONC_10K_sections.parquet  (1.79 MB)
  ON_10K_sections.parquet  (1.19 MB)
  ORCL_10K_sections.parquet  (1.37 MB)
  ORIC_10K_sections.parquet  (0.92 MB)
  ORKA_10K_sections.parquet  (1.13 MB)
  ORMP_10K_sections.parquet  (0.63 MB)
  OSPN_10K_sections.parquet  (1.07 MB)
  OTLK_10K_sections.parquet  (1.26 MB)
  OVID_10K_sections.parquet  (0.87 MB)
  PAAI_10K_sections.parquet  (0.57 MB)
  PALI_10K_sections.parquet  (0.85 MB)
  PANW_10K_sections.parquet  (1.30 MB)
  PASG_10K_sections.parquet  (0.80 MB)
  PATH_10K_sections.parquet  (0.56 MB)
  PAYO_10K_sections.parquet  (0.45 MB)
  PAYS_10K_sections.parquet  (0.53 MB)
  PAY_10K_sections.parquet  (0.53 MB)
  PBYI_10K_sections.parquet  (1.23 MB)
  PCSA_10K_sections.parquet  (0.75 MB)
  PCVX_10K_sections.parquet  (0.89 MB)
  PDSB_10K_sections.parquet  (1.12 MB)
  PDYN_10K_sections.parquet  (0.50 MB)
  PGEN_10K_sections.parquet  (1.17 MB)
  PHAT_10K_sections.parquet  (1.02 MB)
  PHIO_10K_sections.parquet  (0.58 MB)
  PINS_10K_sections.parquet  (0.58 MB)
  PI_10K_sections.parquet  (0.81 MB)
  PLRX_10K_sections.parquet  (0.82 MB)
  PLTR_10K_sections.parquet  (0.93 MB)
  PLUR_10K_sections.parquet  (0.70 MB)
  PLX_10K_sections.parquet  (1.10 MB)
  PMCB_10K_sections.parquet  (1.27 MB)
  PMVP_10K_sections.parquet  (0.88 MB)
  POWI_10K_sections.parquet  (0.59 MB)
  PPCB_10K_sections.parquet  (0.43 MB)
  PPLI_10K_sections.parquet  (0.58 MB)
  PRAX_10K_sections.parquet  (0.90 MB)
  PRGS_10K_sections.parquet  (0.77 MB)
  PRLD_10K_sections.parquet  (0.80 MB)
  PROK_10K_sections.parquet  (0.73 MB)
  PRSO_10K_sections.parquet  (0.68 MB)
  PRTA_10K_sections.parquet  (1.20 MB)
  PRTH_10K_sections.parquet  (0.41 MB)
  PTCT_10K_sections.parquet  (2.04 MB)
  PTGX_10K_sections.parquet  (0.94 MB)
  PTN_10K_sections.parquet  (0.78 MB)
  PULM_10K_sections.parquet  (0.90 MB)
  PVLA_10K_sections.parquet  (1.40 MB)
  PXLW_10K_sections.parquet  (0.89 MB)
  PYXS_10K_sections.parquet  (0.70 MB)
  QCOM_10K_sections.parquet  (1.02 MB)
  QLYS_10K_sections.parquet  (0.97 MB)
  QNCX_10K_sections.parquet  (0.86 MB)
  QRVO_10K_sections.parquet  (0.70 MB)
  QTTB_10K_sections.parquet  (1.17 MB)
  QUIK_10K_sections.parquet  (0.85 MB)
  QURE_10K_sections.parquet  (1.05 MB)
  RAMP_10K_sections.parquet  (0.71 MB)
  RANI_10K_sections.parquet  (0.83 MB)
  RARE_10K_sections.parquet  (1.36 MB)
  RCKT_10K_sections.parquet  (1.18 MB)
  RCUS_10K_sections.parquet  (0.79 MB)
  REGN_10K_sections.parquet  (1.80 MB)
  REKR_10K_sections.parquet  (0.55 MB)
  RELY_10K_sections.parquet  (0.55 MB)
  REPL_10K_sections.parquet  (0.86 MB)
  REVB_10K_sections.parquet  (0.51 MB)
  RGNX_10K_sections.parquet  (1.29 MB)
  RIGL_10K_sections.parquet  (1.35 MB)
  RKTO_10K_sections.parquet  (0.63 MB)
  RLAY_10K_sections.parquet  (0.86 MB)
  RLMD_10K_sections.parquet  (0.75 MB)
  RLYB_10K_sections.parquet  (0.70 MB)
  RMBS_10K_sections.parquet  (1.19 MB)
  RNAC_10K_sections.parquet  (1.06 MB)
  RNAZ_10K_sections.parquet  (0.82 MB)
  RNTX_10K_sections.parquet  (1.13 MB)
  RNXT_10K_sections.parquet  (0.58 MB)
  ROIV_10K_sections.parquet  (1.02 MB)
  RPAY_10K_sections.parquet  (0.62 MB)
  RPD_10K_sections.parquet  (1.00 MB)
  RPRX_10K_sections.parquet  (0.72 MB)
  RUM_10K_sections.parquet  (0.35 MB)
  RVMD_10K_sections.parquet  (1.00 MB)
  RXRX_10K_sections.parquet  (0.69 MB)
  RXT_10K_sections.parquet  (0.72 MB)
  RYTM_10K_sections.parquet  (1.31 MB)
  RZLT_10K_sections.parquet  (0.65 MB)
  SABR_10K_sections.parquet  (1.15 MB)
  SABS_10K_sections.parquet  (0.61 MB)
  SANA_10K_sections.parquet  (1.18 MB)
  SEAT_10K_sections.parquet  (0.37 MB)
  SEER_10K_sections.parquet  (0.64 MB)
  SER_10K_sections.parquet  (0.88 MB)
  SILO_10K_sections.parquet  (0.79 MB)
  SITM_10K_sections.parquet  (0.53 MB)
  SKYE_10K_sections.parquet  (0.94 MB)
  SLAB_10K_sections.parquet  (0.77 MB)
  SLDB_10K_sections.parquet  (1.27 MB)
  SLE_10K_sections.parquet  (0.71 MB)
  SLS_10K_sections.parquet  (1.57 MB)
  SMMT_10K_sections.parquet  (0.66 MB)
  SMTC_10K_sections.parquet  (1.15 MB)
  SNAP_10K_sections.parquet  (0.95 MB)
  SNDX_10K_sections.parquet  (0.93 MB)
  SNGX_10K_sections.parquet  (0.81 MB)
  SNPS_10K_sections.parquet  (0.76 MB)
  SNTI_10K_sections.parquet  (0.80 MB)
  SPRB_10K_sections.parquet  (0.90 MB)
  SPRO_10K_sections.parquet  (1.07 MB)
  SPRY_10K_sections.parquet  (0.87 MB)
  SRPT_10K_sections.parquet  (1.44 MB)
  SRRK_10K_sections.parquet  (1.05 MB)
  SRZN_10K_sections.parquet  (0.62 MB)
  SSTK_10K_sections.parquet  (1.22 MB)
  STOK_10K_sections.parquet  (0.91 MB)
  STRO_10K_sections.parquet  (1.19 MB)
  STTK_10K_sections.parquet  (0.41 MB)
  SVRA_10K_sections.parquet  (1.28 MB)
  SWKS_10K_sections.parquet  (0.71 MB)
  SYNA_10K_sections.parquet  (0.89 MB)
  SYRE_10K_sections.parquet  (1.17 MB)
  S_10K_sections.parquet  (0.55 MB)
  TARA_10K_sections.parquet  (1.18 MB)
  TARS_10K_sections.parquet  (0.96 MB)
  TCRT_10K_sections.parquet  (1.27 MB)
  TCRX_10K_sections.parquet  (0.86 MB)
  TCX_10K_sections.parquet  (1.50 MB)
  TDC_10K_sections.parquet  (0.85 MB)
  TEAD_10K_sections.parquet  (0.54 MB)

### Verify actual files in `DROPBOX_RAW`

In [87]:
import os

print(f"Listing files in the actual DROPBOX_RAW directory: {DROPBOX_RAW}")
for root, dirs, files in os.walk(DROPBOX_RAW):
    for file in files:
        print(os.path.join(root, file))

Listing files in the actual DROPBOX_RAW directory: /content/bond_shared/data/raw/text
/content/bond_shared/data/raw/text/SNDX_10K_sections.parquet
/content/bond_shared/data/raw/text/IIIV_10K_sections.parquet
/content/bond_shared/data/raw/text/MPWR_10K_sections.parquet
/content/bond_shared/data/raw/text/LPCN_10K_sections.parquet
/content/bond_shared/data/raw/text/URGN_10K_sections.parquet
/content/bond_shared/data/raw/text/PDSB_10K_sections.parquet
/content/bond_shared/data/raw/text/CDXS_10K_sections.parquet
/content/bond_shared/data/raw/text/YEXT_10K_sections.parquet
/content/bond_shared/data/raw/text/AUID_10K_sections.parquet
/content/bond_shared/data/raw/text/CVM_10K_sections.parquet
/content/bond_shared/data/raw/text/KTTA_10K_sections.parquet
/content/bond_shared/data/raw/text/RPAY_10K_sections.parquet
/content/bond_shared/data/raw/text/QTTB_10K_sections.parquet
/content/bond_shared/data/raw/text/DTIL_10K_sections.parquet
/content/bond_shared/data/raw/text/ABVC_10K_sections.parquet
/content/bond_shared/data/raw/text/GLUE_10K_sections.parquet
/content/bond_shared/data/raw/text/CYTK_10K_sections.parquet
/content/bond_shared/data/raw/text/TENB_10K_sections.parquet
/content/bond_shared/data/raw/text/PHAT_10K_sections.parquet
/content/bond_shared/data/raw/text/VIR_10K_sections.parquet
/content/bond_shared/data/raw/text/APRE_10K_sections.parquet
/content/bond_shared/data/raw/text/AIP_10K_sections.parquet
/content/bond_shared/data/raw/text/ADMA_10K_sections.parquet
/content/bond_shared/data/raw/text/VANI_10K_sections.parquet
/content/bond_shared/data/raw/text/LRMR_10K_sections.parquet
/content/bond_shared/data/raw/text/ANVS_10K_sections.parquet
/content/bond_shared/data/raw/text/MBIO_10K_sections.parquet
/content/bond_shared/data/raw/text/NVDA_10K_sections.parquet
/content/bond_shared/data/raw/text/NRDS_10K_sections.parquet
/content/bond_shared/data/raw/text/VTGN_10K_sections.parquet
/content/bond_shared/data/raw/text/OKTA_10K_sections.parquet
/content/bond_shared/data/raw/text/XBP_10K_sections.parquet
/content/bond_shared/data/raw/text/MRNA_10K_sections.parquet
/content/bond_shared/data/raw/text/CPAY_10K_sections.parquet
/content/bond_shared/data/raw/text/BMRN_10K_sections.parquet
/content/bond_shared/data/raw/text/SPRO_10K_sections.parquet
/content/bond_shared/data/raw/text/DBVT_10K_sections.parquet
/content/bond_shared/data/raw/text/IOT_10K_sections.parquet
/content/bond_shared/data/raw/text/PRTA_10K_sections.parquet
/content/bond_shared/data/raw/text/NERV_10K_sections.parquet
/content/bond_shared/data/raw/text/HUMA_10K_sections.parquet
/content/bond_shared/data/raw/text/IMXI_10K_sections.parquet
/content/bond_shared/data/raw/text/LGVN_10K_sections.parquet
/content/bond_shared/data/raw/text/TOST_10K_sections.parquet
/content/bond_shared/data/raw/text/QUIK_10K_sections.parquet
/content/bond_shared/data/raw/text/KURA_10K_sections.parquet
/content/bond_shared/data/raw/text/MBRX_10K_sections.parquet
/content/bond_shared/data/raw/text/CBIO_10K_sections.parquet
/content/bond_shared/data/raw/text/STRO_10K_sections.parquet
/content/bond_shared/data/raw/text/MRAM_10K_sections.parquet
/content/bond_shared/data/raw/text/PCVX_10K_sections.parquet
/content/bond_shared/data/raw/text/PXLW_10K_sections.parquet
/content/bond_shared/data/raw/text/RKTO_10K_sections.parquet
/content/bond_shared/data/raw/text/LONA_10K_sections.parquet
/content/bond_shared/data/raw/text/ZLAB_10K_sections.parquet
/content/bond_shared/data/raw/text/IVVD_10K_sections.parquet
/content/bond_shared/data/raw/text/CARS_10K_sections.parquet
/content/bond_shared/data/raw/text/OKUR_10K_sections.parquet
/content/bond_shared/data/raw/text/LEDS_10K_sections.parquet
/content/bond_shared/data/raw/text/CORT_10K_sections.parquet
/content/bond_shared/data/raw/text/CSBR_10K_sections.parquet
/content/bond_shared/data/raw/text/EEFT_10K_sections.parquet
/content/bond_shared/data/raw/text/XCUR_10K_sections.parquet
/content/bond_shared/data/raw/text/OSPN_10K_sections.parquet
/content/bond_shared/data/raw/text/TNGX_10K_sections.parquet
/content/bond_shared/data/raw/text/RCKT_10K_sections.parquet
/content/bond_shared/data/raw/text/SMMT_10K_sections.parquet
/content/bond_shared/data/raw/text/RUM_10K_sections.parquet
/content/bond_shared/data/raw/text/ARCT_10K_sections.parquet
/content/bond_shared/data/raw/text/NVAX_10K_sections.parquet
/content/bond_shared/data/raw/text/PANW_10K_sections.parquet
/content/bond_shared/data/raw/text/TWST_10K_sections.parquet
/content/bond_shared/data/raw/text/CTXR_10K_sections.parquet
/content/bond_shared/data/raw/text/TECH_10K_sections.parquet
/content/bond_shared/data/raw/text/NRIX_10K_sections.parquet
/content/bond_shared/data/raw/text/SITM_10K_sections.parquet
/content/bond_shared/data/raw/text/NTRB_10K_sections.parquet
/content/bond_shared/data/raw/text/SANA_10K_sections.parquet
/content/bond_shared/data/raw/text/CABA_10K_sections.parquet
/content/bond_shared/data/raw/text/EDVA_10K_sections.parquet
/content/bond_shared/data/raw/text/PLUR_10K_sections.parquet
/content/bond_shared/data/raw/text/PALI_10K_sections.parquet
/content/bond_shared/data/raw/text/JSPR_10K_sections.parquet
/content/bond_shared/data/raw/text/CRBU_10K_sections.parquet
/content/bond_shared/data/raw/text/TRDA_10K_sections.parquet
/content/bond_shared/data/raw/text/ACXP_10K_sections.parquet
/content/bond_shared/data/raw/text/BCYC_10K_sections.parquet
/content/bond_shared/data/raw/text/ORCL_10K_sections.parquet
/content/bond_shared/data/raw/text/CNSP_10K_sections.parquet
/content/bond_shared/data/raw/text/FABC_10K_sections.parquet
/content/bond_shared/data/raw/text/TCX_10K_sections.parquet
/content/bond_shared/data/raw/text/VRNS_10K_sections.parquet
/content/bond_shared/data/raw/text/ZSQR_10K_sections.parquet
/content/bond_shared/data/raw/text/MGNX_10K_sections.parquet
/content/bond_shared/data/raw/text/NTNX_10K_sections.parquet
/content/bond_shared/data/raw/text/DNA_10K_sections.parquet
/content/bond_shared/data/raw/text/CRVO_10K_sections.parquet
/content/bond_shared/data/raw/text/PRLD_10K_sections.parquet
/content/bond_shared/data/raw/text/ICCC_10K_sections.parquet
/content/bond_shared/data/raw/text/OVID_10K_sections.parquet
/content/bond_shared/data/raw/text/IRD_10K_sections.parquet
/content/bond_shared/data/raw/text/GOOGL_10K_sections.parquet
/content/bond_shared/data/raw/text/HOWL_10K_sections.parquet
/content/bond_shared/data/raw/text/VCEL_10K_sections.parquet
/content/bond_shared/data/raw/text/ALNY_10K_sections.parquet
/content/bond_shared/data/raw/text/ABSI_10K_sections.parquet
/content/bond_shared/data/raw/text/IMNM_10K_sections.parquet
/content/bond_shared/data/raw/text/AVXL_10K_sections.parquet
/content/bond_shared/data/raw/text/NGNE_10K_sections.parquet
/content/bond_shared/data/raw/text/CDT_10K_sections.parquet
/content/bond_shared/data/raw/text/OGEN_10K_sections.parquet
/content/bond_shared/data/raw/text/CEVA_10K_sections.parquet
/content/bond_shared/data/raw/text/CGTX_10K_sections.parquet
/content/bond_shared/data/raw/text/TGTX_10K_sections.parquet
/content/bond_shared/data/raw/text/TVGN_10K_sections.parquet
/content/bond_shared/data/raw/text/IRON_10K_sections.parquet
/content/bond_shared/data/raw/text/SLE_10K_sections.parquet
/content/bond_shared/data/raw/text/BTLN_10K_sections.parquet
/content/bond_shared/data/raw/text/MTVA_10K_sections.parquet
/content/bond_shared/data/raw/text/LYEL_10K_sections.parquet
/content/bond_shared/data/raw/text/PRTH_10K_sections.parquet
/content/bond_shared/data/raw/text/ALXO_10K_sections.parquet
/content/bond_shared/data/raw/text/RGNX_10K_sections.parquet
/content/bond_shared/data/raw/text/XBIO_10K_sections.parquet
/content/bond_shared/data/raw/text/LSTA_10K_sections.parquet
/content/bond_shared/data/raw/text/AZIO_10K_sections.parquet
/content/bond_shared/data/raw/text/ALMU_10K_sections.parquet
/content/bond_shared/data/raw/text/PCSA_10K_sections.parquet
/content/bond_shared/data/raw/text/LIDR_10K_sections.parquet
/content/bond_shared/data/raw/text/DWTX_10K_sections.parquet
/content/bond_shared/data/raw/text/DSGN_10K_sections.parquet
/content/bond_shared/data/raw/text/TEAD_10K_sections.parquet
/content/bond_shared/data/raw/text/PAYS_10K_sections.parquet
/content/bond_shared/data/raw/text/BKKT_10K_sections.parquet
/content/bond_shared/data/raw/text/ANIX_10K_sections.parquet
/content/bond_shared/data/raw/text/DJT_10K_sections.parquet
/content/bond_shared/data/raw/text/AURA_10K_sections.parquet
/content/bond_shared/data/raw/text/GLSI_10K_sections.parquet
/content/bond_shared/data/raw/text/VYGR_10K_sections.parquet
/content/bond_shared/data/raw/text/INSM_10K_sections.parquet
/content/bond_shared/data/raw/text/UPWK_10K_sections.parquet
/content/bond_shared/data/raw/text/CLDX_10K_sections.parquet
/content/bond_shared/data/raw/text/BBIO_10K_sections.parquet
/content/bond_shared/data/raw/text/AMD_10K_sections.parquet
/content/bond_shared/data/raw/text/RPD_10K_sections.parquet
/content/bond_shared/data/raw/text/GCTS_10K_sections.parquet
/content/bond_shared/data/raw/text/ONC_10K_sections.parquet
/content/bond_shared/data/raw/text/LITS_10K_sections.parquet
/content/bond_shared/data/raw/text/ARTL_10K_sections.parquet
/content/bond_shared/data/raw/text/CCCC_10K_sections.parquet
/content/bond_shared/data/raw/text/KPLT_10K_sections.parquet
/content/bond_shared/data/raw/text/AXSM_10K_sections.parquet
/content/bond_shared/data/raw/text/SLAB_10K_sections.parquet
/content/bond_shared/data/raw/text/MSFT_10K_sections.parquet
/content/bond_shared/data/raw/text/RPRX_10K_sections.parquet
/content/bond_shared/data/raw/text/COCP_10K_sections.parquet
/content/bond_shared/data/raw/text/IBIO_10K_sections.parquet
/content/bond_shared/data/raw/text/LSAK_10K_sections.parquet
/content/bond_shared/data/raw/text/RXRX_10K_sections.parquet
/content/bond_shared/data/raw/text/CRSP_10K_sections.parquet
/content/bond_shared/data/raw/text/SYRE_10K_sections.parquet
/content/bond_shared/data/raw/text/SSTK_10K_sections.parquet
/content/bond_shared/data/raw/text/MAX_10K_sections.parquet
/content/bond_shared/data/raw/text/RNAC_10K_sections.parquet
/content/bond_shared/data/raw/text/TPST_10K_sections.parquet
/content/bond_shared/data/raw/text/RXT_10K_sections.parquet
/content/bond_shared/data/raw/text/MU_10K_sections.parquet
/content/bond_shared/data/raw/text/FTH_10K_sections.parquet
/content/bond_shared/data/raw/text/AGEN_10K_sections.parquet
/content/bond_shared/data/raw/text/LXRX_10K_sections.parquet
/content/bond_shared/data/raw/text/KROS_10K_sections.parquet
/content/bond_shared/data/raw/text/TRAW_10K_sections.parquet
/content/bond_shared/data/raw/text/TWLO_10K_sections.parquet
/content/bond_shared/data/raw/text/REGN_10K_sections.parquet
/content/bond_shared/data/raw/text/UNCY_10K_sections.parquet
/content/bond_shared/data/raw/text/JANX_10K_sections.parquet
/content/bond_shared/data/raw/text/AISP_10K_sections.parquet
/content/bond_shared/data/raw/text/VSH_10K_sections.parquet
/content/bond_shared/data/raw/text/CNTX_10K_sections.parquet
/content/bond_shared/data/raw/text/GERN_10K_sections.parquet
/content/bond_shared/data/raw/text/PMVP_10K_sections.parquet
/content/bond_shared/data/raw/text/SABR_10K_sections.parquet
/content/bond_shared/data/raw/text/VERU_10K_sections.parquet
/content/bond_shared/data/raw/text/VERI_10K_sections.parquet
/content/bond_shared/data/raw/text/HRMY_10K_sections.parquet
/content/bond_shared/data/raw/text/AIM_10K_sections.parquet
/content/bond_shared/data/raw/text/CDIO_10K_sections.parquet
/content/bond_shared/data/raw/text/ANAB_10K_sections.parquet
/content/bond_shared/data/raw/text/RLMD_10K_sections.parquet
/content/bond_shared/data/raw/text/IONS_10K_sections.parquet
/content/bond_shared/data/raw/text/HURA_10K_sections.parquet
/content/bond_shared/data/raw/text/PTN_10K_sections.parquet
/content/bond_shared/data/raw/text/HCWB_10K_sections.parquet
/content/bond_shared/data/raw/text/MQ_10K_sections.parquet
/content/bond_shared/data/raw/text/TVTX_10K_sections.parquet
/content/bond_shared/data/raw/text/FENC_10K_sections.parquet
/content/bond_shared/data/raw/text/IMNN_10K_sections.parquet
/content/bond_shared/data/raw/text/VNDA_10K_sections.parquet
/content/bond_shared/data/raw/text/AEON_10K_sections.parquet
/content/bond_shared/data/raw/text/CRUS_10K_sections.parquet
/content/bond_shared/data/raw/text/KPTI_10K_sections.parquet
/content/bond_shared/data/raw/text/CELC_10K_sections.parquet
/content/bond_shared/data/raw/text/RMBS_10K_sections.parquet
/content/bond_shared/data/raw/text/IMUX_10K_sections.parquet
/content/bond_shared/data/raw/text/FLYW_10K_sections.parquet
/content/bond_shared/data/raw/text/GNPX_10K_sections.parquet
/content/bond_shared/data/raw/text/APVO_10K_sections.parquet
/content/bond_shared/data/raw/text/MNOV_10K_sections.parquet
/content/bond_shared/data/raw/text/DBX_10K_sections.parquet
/content/bond_shared/data/raw/text/MRKR_10K_sections.parquet
/content/bond_shared/data/raw/text/BCDA_10K_sections.parquet
/content/bond_shared/data/raw/text/SEAT_10K_sections.parquet
/content/bond_shared/data/raw/text/ATYR_10K_sections.parquet
/content/bond_shared/data/raw/text/EYPT_10K_sections.parquet
/content/bond_shared/data/raw/text/CRVS_10K_sections.parquet
/content/bond_shared/data/raw/text/ZNTL_10K_sections.parquet
/content/bond_shared/data/raw/text/HALO_10K_sections.parquet
/content/bond_shared/data/raw/text/SNTI_10K_sections.parquet
/content/bond_shared/data/raw/text/HYPD_10K_sections.parquet
/content/bond_shared/data/raw/text/MCRB_10K_sections.parquet
/content/bond_shared/data/raw/text/SABS_10K_sections.parquet
/content/bond_shared/data/raw/text/FHTX_10K_sections.parquet
/content/bond_shared/data/raw/text/RANI_10K_sections.parquet
/content/bond_shared/data/raw/text/PDYN_10K_sections.parquet
/content/bond_shared/data/raw/text/IMA_10K_sections.parquet
/content/bond_shared/data/raw/text/MTCH_10K_sections.parquet
/content/bond_shared/data/raw/text/DNLI_10K_sections.parquet
/content/bond_shared/data/raw/text/RLAY_10K_sections.parquet
/content/bond_shared/data/raw/text/CRWD_10K_sections.parquet
/content/bond_shared/data/raw/text/KALA_10K_sections.parquet
/content/bond_shared/data/raw/text/SRZN_10K_sections.parquet
/content/bond_shared/data/raw/text/XNCR_10K_sections.parquet
/content/bond_shared/data/raw/text/IMVT_10K_sections.parquet
/content/bond_shared/data/raw/text/BZFD_10K_sections.parquet
/content/bond_shared/data/raw/text/PYXS_10K_sections.parquet
/content/bond_shared/data/raw/text/REKR_10K_sections.parquet
/content/bond_shared/data/raw/text/RELY_10K_sections.parquet
/content/bond_shared/data/raw/text/S_10K_sections.parquet
/content/bond_shared/data/raw/text/EDSA_10K_sections.parquet
/content/bond_shared/data/raw/text/KPRX_10K_sections.parquet
/content/bond_shared/data/raw/text/ANNX_10K_sections.parquet
/content/bond_shared/data/raw/text/MNKD_10K_sections.parquet
/content/bond_shared/data/raw/text/MTNB_10K_sections.parquet
/content/bond_shared/data/raw/text/LNAI_10K_sections.parquet
/content/bond_shared/data/raw/text/ARMP_10K_sections.parquet
/content/bond_shared/data/raw/text/FTNT_10K_sections.parquet
/content/bond_shared/data/raw/text/CNTN_10K_sections.parquet
/content/bond_shared/data/raw/text/CARG_10K_sections.parquet
/content/bond_shared/data/raw/text/TXN_10K_sections.parquet
/content/bond_shared/data/raw/text/IBRX_10K_sections.parquet
/content/bond_shared/data/raw/text/OLMA_10K_sections.parquet
/content/bond_shared/data/raw/text/DIBS_10K_sections.parquet
/content/bond_shared/data/raw/text/MTSI_10K_sections.parquet
/content/bond_shared/data/raw/text/ALDX_10K_sections.parquet
/content/bond_shared/data/raw/text/ROIV_10K_sections.parquet
/content/bond_shared/data/raw/text/SER_10K_sections.parquet
/content/bond_shared/data/raw/text/OMER_10K_sections.parquet
/content/bond_shared/data/raw/text/IOVA_10K_sections.parquet
/content/bond_shared/data/raw/text/TVRD_10K_sections.parquet
/content/bond_shared/data/raw/text/MNPR_10K_sections.parquet
/content/bond_shared/data/raw/text/ALT_10K_sections.parquet
/content/bond_shared/data/raw/text/IGC_10K_sections.parquet
/content/bond_shared/data/raw/text/POWI_10K_sections.parquet
/content/bond_shared/data/raw/text/LVO_10K_sections.parquet
/content/bond_shared/data/raw/text/ATEN_10K_sections.parquet
/content/bond_shared/data/raw/text/IMMX_10K_sections.parquet
/content/bond_shared/data/raw/text/SNGX_10K_sections.parquet
/content/bond_shared/data/raw/text/INTZ_10K_sections.parquet
/content/bond_shared/data/raw/text/VHC_10K_sections.parquet
/content/bond_shared/data/raw/text/LENZ_10K_sections.parquet
/content/bond_shared/data/raw/text/CADL_10K_sections.parquet
/content/bond_shared/data/raw/text/SKYE_10K_sections.parquet
/content/bond_shared/data/raw/text/ZVRA_10K_sections.parquet
/content/bond_shared/data/raw/text/CUE_10K_sections.parquet
/content/bond_shared/data/raw/text/DARE_10K_sections.parquet
/content/bond_shared/data/raw/text/OLB_10K_sections.parquet
/content/bond_shared/data/raw/text/XYZ_10K_sections.parquet
/content/bond_shared/data/raw/text/MDXG_10K_sections.parquet
/content/bond_shared/data/raw/text/PTGX_10K_sections.parquet
/content/bond_shared/data/raw/text/APPN_10K_sections.parquet
/content/bond_shared/data/raw/text/AVX_10K_sections.parquet
/content/bond_shared/data/raw/text/RCUS_10K_sections.parquet
/content/bond_shared/data/raw/text/YARW_10K_sections.parquet
/content/bond_shared/data/raw/text/PI_10K_sections.parquet
/content/bond_shared/data/raw/text/PRSO_10K_sections.parquet
/content/bond_shared/data/raw/text/ZDGE_10K_sections.parquet
/content/bond_shared/data/raw/text/GANX_10K_sections.parquet
/content/bond_shared/data/raw/text/IKT_10K_sections.parquet
/content/bond_shared/data/raw/text/ELOX_10K_sections.parquet
/content/bond_shared/data/raw/text/CNSY_10K_sections.parquet
/content/bond_shared/data/raw/text/ABUS_10K_sections.parquet
/content/bond_shared/data/raw/text/PLTR_10K_sections.parquet
/content/bond_shared/data/raw/text/BIRD_10K_sections.parquet
/content/bond_shared/data/raw/text/ADIL_10K_sections.parquet
/content/bond_shared/data/raw/text/PMCB_10K_sections.parquet
/content/bond_shared/data/raw/text/DCOY_10K_sections.parquet
/content/bond_shared/data/raw/text/BODI_10K_sections.parquet
/content/bond_shared/data/raw/text/ARDX_10K_sections.parquet
/content/bond_shared/data/raw/text/SPRY_10K_sections.parquet
/content/bond_shared/data/raw/text/KOD_10K_sections.parquet
/content/bond_shared/data/raw/text/SYNA_10K_sections.parquet
/content/bond_shared/data/raw/text/ELVN_10K_sections.parquet
/content/bond_shared/data/raw/text/ENSC_10K_sections.parquet
/content/bond_shared/data/raw/text/TARA_10K_sections.parquet
/content/bond_shared/data/raw/text/INO_10K_sections.parquet
/content/bond_shared/data/raw/text/ACAD_10K_sections.parquet
/content/bond_shared/data/raw/text/SLS_10K_sections.parquet
/content/bond_shared/data/raw/text/MGTX_10K_sections.parquet
/content/bond_shared/data/raw/text/SILO_10K_sections.parquet
/content/bond_shared/data/raw/text/ANGI_10K_sections.parquet
/content/bond_shared/data/raw/text/FIVN_10K_sections.parquet
/content/bond_shared/data/raw/text/VERA_10K_sections.parquet
/content/bond_shared/data/raw/text/IMRX_10K_sections.parquet
/content/bond_shared/data/raw/text/NAUT_10K_sections.parquet
/content/bond_shared/data/raw/text/CMPX_10K_sections.parquet
/content/bond_shared/data/raw/text/ALLO_10K_sections.parquet
/content/bond_shared/data/raw/text/CBUS_10K_sections.parquet
/content/bond_shared/data/raw/text/EDIT_10K_sections.parquet
/content/bond_shared/data/raw/text/CRIS_10K_sections.parquet
/content/bond_shared/data/raw/text/RIGL_10K_sections.parquet
/content/bond_shared/data/raw/text/NVEC_10K_sections.parquet
/content/bond_shared/data/raw/text/PAYO_10K_sections.parquet
/content/bond_shared/data/raw/text/ACET_10K_sections.parquet
/content/bond_shared/data/raw/text/BMEA_10K_sections.parquet
/content/bond_shared/data/raw/text/HLSQ_10K_sections.parquet
/content/bond_shared/data/raw/text/MOVE_10K_sections.parquet
/content/bond_shared/data/raw/text/ERNA_10K_sections.parquet

In [88]:
print("Rows per company and section:")
print(pd.crosstab(sections["ticker"], sections["section"]).to_string())

print("\nFiscal-year coverage:")
for t, g in sections.groupby("ticker"):
    print(f"  {t}: FY{g.fiscal_year.min()}-FY{g.fiscal_year.max()} "
          f"({g.fiscal_year.nunique()} years, {g.accession_no.nunique()} filings)")

print("\nMissing values per column:")
print(sections.isna().sum().to_string())

print("\nWord counts by section:")
print(sections.groupby("section")["n_words"].agg(["min", "median", "max", "sum"]).to_string())

Rows per company and section:
section  mda  properties  risk_factors
ticker
ABCL       6           6             6
ABEO      16          16            16
ABOS       5           5             5
ABSI       5           5             5
ABUS      13          13            13
ABVC      16          16            16
ACAD      16          16            16
ACET       9           9             9
ACHV      16          16            16
ACIW      16          16            16
ACRS      11          11            11
ACXP       5           5             5
ADI       15          15            15
ADIL       8           8             8
ADMA      15          15            15
AEON       6           6             6
AEVA       7           7             7
AGEN      16          16            16
AGIO      13          13            13
AGPU      16          16            16
AI         6           6             6
AIFA       9           9             9
AIFC      16          16            16
AIM       16          16            16
AIP        5           5             5
AISP       5           5             5
AIXC      10          10            10
AKAM      16          16            16
AKTX       5           5             5
ALDX      12          12            12
ALEC       8           8             8
ALGM       6           6             6
ALGS       6           6             6
ALLO       8           8             8
ALLR       5           5             5
ALMU       6           6             6
ALNY      16          16            16
ALT       16          16            16
ALXO       6           6             6
ALZN       6           6             6
AMD       16          16            16
ANAB      10          10            10
ANGI       9           9             9
ANIX      16          16            16
ANNX       6           6             6
ANVS       7           7             7
AOSL      16          16            16
APPN       9           9             9
APRE       7           7             7
APVO      10          10            10
ARCT       7           7             7
ARDX      12          12            12
ARMP      13          13            13
ARQT       7           7             7
ARTL      11          11            11
ARVN       8           8             8
ARWR      15          15            15
ASMB      16          16            16
ATEN      12          12            12
ATNM      16          16            16
ATOS      14          14            14
ATRA      12          12            12
ATYR      11          11            11
AUID      15          14            12
AUPH       6           6             6
AURA       5           5             5
AVGO       8           8             8
AVIR       6           6             6
AVPT       7           7             7
AVTX      11          11            11
AVX        5           5             5
AVXL      15          15            14
AXSM      11          11            11
AZIO       9           9             9
BAND       9           9             9
BB         7           7             7
BBIO       7           7             7
BBLG      16          13            16
BCDA      16          16            16
BCYC       7           7             7
BDTX       7           7             7
BEAM       7           7             7
BIRD       5           5             5
BIVI      13          12            13
BKKT       6           6             6
BLIN      15          15            15
BLZE       5           5             5
BMBL       6           6             6
BMEA       5           5             5
BMRN      16          16            16
BNAI       5           5             5
BNTC       7           7             7
BODI       6           6             6
BOLT       6           6             6
BOX       12          12            12
BRTX      15          15            15
BTLN       5           5             5
BZFD       6           6             6
CABA       7           7             7
CADL       5           5             5
CALC       6           6             6
CALX      16          16            16
CAPR      16          16            16
CARG       9           9             9
CARS       9           9             9
CBIO      13          13            13
CBUS       9           9             9
CCCC       6           6             6
CCSI       5           5             5
CDIO       5           5             5
CDT        5           5             5
CDXS      16          16            16
CELC       9           9             9
CELU       7           7             7
CELZ      16          16            16
CETX      16          16            16
CEVA      16          16            16
CGEM       6           6             6
CGTX       5           5             5
CHRS      12          12            12
CING       5           5             5
CISO       7           7             7
CLDI       5           5             5
CLDX      16          16            16
CLNN       6           6             6
CLRB      15          16            16
CLYM       5           5             5
CMPX       8           8             8
CNSP       7           7             7
CNSY      16          16            16
CNTN       5           5             5
CNTX       5           5             5
COCP      16          16            16
COGT       8           8             8
CORT      16          16            16
CORZ       5           5             5
CPAY      16          16            16
CRBP      12          12            12
CRBU       5           5             5
CRDF      15          15            15
CRDO       5           5             5
CRIS      16          16            16
CRMD      16          16            16
CRSP      10          10            10
CRUS      16          16            16
CRVO      16          16            16
CRVS      10          10            10
CRWD       7           7             7
CSBR      16          16            16
CTMX      11          11            11
CTXR      14          14            14
CUE        9           9             9
CVM       15          15             6
CYTK      16          16            16
DARE      12          12            12
DBVT       6           6             6
DBX        8           8             8
DCOY      12          12            12
DFTX       5           5             5
DIBS       5           5             5
DIOD      16          16            16
DJT        5           5             5
DMAC       8           8             8
DMRA       6           6             6
DNA        5           5             5
DNLI       9           9             9
DNTH       8           8             8
DOCN       5           5             5
DRK        7           7             7
DRMA       5           5             5
DSGN       5           5             5
DTIL       7           7             7
DVLT       8           8             8
DWTX       6           6             6
DYAI       8           8             8
DYN        6           6             6
EDIT      11          11            11
EDSA      11          11            11
EDVA      14          14            14
EEFT      16          16            16
ELDN      12          12            12
ELOX      14          14            13
ELTX       6           6             6
ELVN       6           6             6
ENSC       9           9             9
ENTA      13          13            13
ENTX       5           5             5
ENVB      15          14            15
EQ         8           8             8
ERAS       5           5             5
ERNA      16          16            16
EVER       8           8             8
EVTC      13          13            13
EWTX       5           5             5
EXEL      16          16            16
EYPT      15          15            15
FABC      15          15            15
FATE      13          13            13
FBIO      15          15            15
FDMT       6           6             6
FENC      16          16            16
FFIV      15          15            15
FHTX       6           6             6
FIVN      12          12            12
FLNA      16          16            16
FLYW       5           5             5
FOUR       6           6             6
FTH        6           6             6
FTNT      16          16            16
FULC       7           7             7
GALT      16          16            16
GANX       5           5             5
GCTS       5           5             5
GDDY      11          11            11
GEN       16          16            16
GERN      16          16            16
GLSI       6           6             6
GLUE       5           5             5
GNPX       9           9             9
GOOGL     11          11            11
GOSS       8           8             8
GOVX      16          16            16
GRCE       7           7             7
GRDX      10          10            10
GRI        6           6             6
GRPN      15          15            15
GSIT      16          16            16
GTBP      16          16            16
GTLB       5           5             5
GYRE      16          16            16
HALO      16          16            16
HCWB       5           5             5
HIND      10          10            10
HLSQ       8           8             8
HOWL       5           5             5
HRMY       6           6             6
HRTX      16          16            16
HUMA       6           6             6
HURA      15          15            15
HYPD       9           9             9
IBIO      16          16            16
IBRX      11          11            11
ICCC      16          11            16
ICU        6           6             6
IDYA       7           7             7
IGC       15          15            15
IIIV       8           8             8
IKT        6           6             6
IMA        5           5             5
IMMX       5           5             5
IMNM       6           6             6
IMNN      16          16            16
IMRX       5           5             5
IMUX      12          12            12
IMVT       7           7             7
IMXI       9           9             9
INAB       5           5             5
INCY      16          16            16
INDI       5           5             5
INDP       5           5             5
INKT       5           5             5
INMB       8           8             8
INO       16          16            16
INSM      16          16            16
INTC      16          16            16
INTZ      16          16            16
INVA      16          16            16
IONS      16          16            16
IOT        5           5             5
IOVA      16          16            16
IPSC       5           5             5
IPWR      13          13            13
IRD       16          16            16
IRON       6           6             6
IVVD       5           5             5
JAGX      11          11            11
JANX       5           5             5
JAZZ      16          16            16
JBIO       5           5             5
JSPR       7           7             7
KALA       9           9             9
KLRS       6           6             6
KOD        8           8             8
KPLT       7           7             7
KPRX      12          12            12
KPTI      13          13            13
KROS       6           6             6
KRRO       7           7             7
KRSA       7           7             7
KRYS       9           9             9
KTTA       5           5             5
KURA      16          12            16
KYMR       6           6             6
KYNB      12          12            12
LASR       8           8             8
LCTX      16          16            16
LEDS      15          15            15
LENZ       5           5             5
LEXX      15          15            15
LGND      16          16            16
LGVN       6           6             6
LIDR       6           6             6
LITS      15          15            15
LNAI      13          11            13
LONA       6           6             6
LPCN      15          15            15
LRMR      12          12            12
LSAK      16          16            16
LSCC      16          16            16
LSTA      16          16            16
LTRN       6           6             6
LVO       16          13            16
LXRX      16          16            16
LYEL       5           5             5
MAX        6           6             6
MBIO      10          10            10
MBRX      10          10            10
MCHP      16          16            16
MCRB      11          11            11
MDB        9           9             9
MDGL      16          16            16
MDXG      15          15            15
META      14          14            14
MGNX      13          13            13
MGTX       8           8             8
MIRM       7           7             7
MIST       7           7             7
MLTX       6           6             6
MNKD      16          16            16
MNOV      16          16            16
MNPR       9           9             9
MOVE       5           5             5
MPWR      16          16            16
MQ         5           5             5
MRAM      10          10            10
MRKR      16          16            16
MRNA       8           8             8
MRVI       6           6             6
MRVL       5           5             5
MSFT      16          16            16
MTCH      16          16            16
MTNB      12          12            12
MTSI      14          14            14
MTVA      10          10            10
MU        15          15            15
MX        16          16            16
MXL       16          16            16
NAUT       6           6             6
NERV      12          12            12
NET        7           7             7
NGNE      12          12            12
NKTR      16          16            16
NKTX       6           6             6
NN         5           5             5
NNVC      15          15            15
NRDS       5           5             5
NRIX       6           6             6
NRXP       9           8             9
NTAP      16          16            16
NTCT      16          16            16
NTLA      10          10            10
NTNX      10          10            10
NTRB      10          10            10
NUVB       6           6             6
NVAX      16          16            16
NVCT       5           5             5
NVDA      16          16            16
NVEC      16          16            16
NVTS       6           6             6
NXDR       5           5             5
NXPI       7           7             7
NXTC       7           7             7
OABI       5           5             5
OBIO       6           6             6
OCGN      12          12            12
OCUL      12          12            12
OGEN      16          16            16
OKTA       9           9             9
OKUR       5           5             5
OLB       16          16            16
OLMA       6           6             6
OMER      16          16            16
ON        16          16            16
ONC       11          11            11
ONCO       5           5             5
ORCL      16          16            16
ORIC       6           6             6
ORKA      16          16            16
ORMP      15          15            15
OSPN      16          16            16
OTLK      10          10            10
OVID       9           9             9
PAAI      16          16            16
PALI      16          16            16
PANW      15          15            15
PASG       6           6             6
PATH       5           5             5
PAY        5           5             5
PAYO       5           5             5
PAYS      16          16            16
PBYI      16          15            16
PCSA      13          13            13
PCVX       6           6             6
PDSB      11          11            11
PDYN       6           6             6
PGEN      13          13            13
PHAT       7           7             7
PHIO      14          14            14
PI        10          10            10
PINS       7           7             7
PLRX       6           6             6
PLTR       6           6             6
PLUR      16          16            16
PLX       16          16            16
PMCB      16          16            16
PMVP       6           6             6
POWI      16          16            16
PPCB      15          15            15
PPLI       6           6             6
PRAX       6           6             6
PRGS      16          16            16
PRLD       6           6             6
PROK       5           5             5
PRSO      16          16            16
PRTA      14          14            14
PRTH      10          10            10
PTCT      13          13            13
PTGX      10          10            10
PTN       15          15            15
PULM      13          13            13
PVLA      13          12            13
PXLW      16          16            16
PYXS       5           5             5
QCOM      15          15            15
QLYS      14          14            14
QNCX       7           7             7
QRVO      12          12            12
QTTB       8           8             8
QUIK      16          16            16
QURE      10          10            10
RAMP      16          16            16
RANI       5           5             5
RARE      13          13            13
RCKT      12          12            12
RCUS       8           8             8
REGN      16          16            16
REKR       9           9             9
RELY       5           5             5
REPL       8           8             8
REVB       6           6             6
RGNX      11          11            11
RIGL      16          16            16
RKTO       8           8             8
RLAY       6           6             6
RLMD      12          12            11
RLYB       5           5             5
RMBS      16          16            16
RNAC      10          10            10
RNAZ       5           5             5
RNTX       9           9             9
RNXT       5           5             5
ROIV       5           5             5
RPAY       8           8             8
RPD       11          11            11
RPRX       6           6             6
RUM        5           5             5
RVMD       7           7             7
RXRX       5           5             5
RXT        6           6             6
RYTM       9           9             9
RZLT      16          16            16
S          5           5             5
SABR      12          12            12
SABS       6           6             6
SANA       6           6             6
SEAT       5           5             5
SEER       6           6             6
SER        8           8             8
SILO      15          15            15
SITM       7           7             7
SKYE      13          13            13
SLAB      16          16            16
SLDB       9           9             9
SLE        7           7             7
SLS       16          16            16
SMMT       6           6             6
SMTC      16          16            16
SNAP       9           9             9
SNDX      10          10            10
SNGX      16          16            16
SNPS      15          15            15
SNTI       5           5             5
SPRB       6           6             6
SPRO       9           9             9
SPRY       6           6             6
SRPT      16          16            16
SRRK       8           8             8
SRZN       5           5             5
SSTK      14          14            14
STOK       7           7             7
STRO       8           8             8
STTK       6           6             6
SVRA      16          16            16
SWKS      15          15            15
SYNA      16          16            16
SYRE      10          10            10
TARA      12          12            12
TARS       6           6             6
TCRT      16          16            16
TCRX       5           5             5

In [89]:
# Metadata view (text column dropped so the table is readable).
display(sections.drop(columns=["text"]).head(12))

,ticker,cik,company_name,form,section,item_label,filing_date,period_of_report,fiscal_year,accession_no,n_chars,n_words,source_url
0,ABCL,1703057,AbCellera Biologics Inc.,10-K,mda,Item 7 - Management's Discussion and Analysis,2021-03-30,2020-12-31,2020,0001564590-21-016713,91244,13991,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
1,ABCL,1703057,AbCellera Biologics Inc.,10-K,properties,Item 2 - Properties,2021-03-30,2020-12-31,2020,0001564590-21-016713,796,122,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
2,ABCL,1703057,AbCellera Biologics Inc.,10-K,risk_factors,Item 1A - Risk Factors,2021-03-30,2020-12-31,2020,0001564590-21-016713,208177,31786,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
3,ABCL,1703057,AbCellera Biologics Inc.,10-K,mda,Item 7 - Management's Discussion and Analysis,2022-02-25,2021-12-31,2021,0001564590-22-007077,79885,12074,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
4,ABCL,1703057,AbCellera Biologics Inc.,10-K,properties,Item 2 - Properties,2022-02-25,2021-12-31,2021,0001564590-22-007077,1045,162,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
5,ABCL,1703057,AbCellera Biologics Inc.,10-K,risk_factors,Item 1A - Risk Factors,2022-02-25,2021-12-31,2021,0001564590-22-007077,215569,32823,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
6,ABCL,1703057,AbCellera Biologics Inc.,10-K,mda,Item 7 - Management's Discussion and Analysis,2023-02-21,2022-12-31,2022,0001564590-23-002128,74525,11219,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
7,ABCL,1703057,AbCellera Biologics Inc.,10-K,properties,Item 2 - Properties,2023-02-21,2022-12-31,2022,0001564590-23-002128,1098,170,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
8,ABCL,1703057,AbCellera Biologics Inc.,10-K,risk_factors,Item 1A - Risk Factors,2023-02-21,2022-12-31,2022,0001564590-23-002128,236418,35754,https://www.sec.gov/Archives/edgar/data/1703057/00015645...
9,ABCL,1703057,AbCellera Biologics Inc.,10-K,mda,Item 7 - Management's Discussion and Analysis,2024-02-20,2023-12-31,2023,0001703057-24-000019,67047,9902,https://www.sec.gov/Archives/edgar/data/1703057/00017030...
10,ABCL,1703057,AbCellera Biologics Inc.,10-K,properties,Item 2 - Properties,2024-02-20,2023-12-31,2023,0001703057-24-000019,1183,180,https://www.sec.gov/Archives/edgar/data/1703057/00017030...
11,ABCL,1703057,AbCellera Biologics Inc.,10-K,risk_factors,Item 1A - Risk Factors,2024-02-20,2023-12-31,2023,0001703057-24-000019,239705,36201,https://www.sec.gov/Archives/edgar/data/1703057/00017030...

In [90]:
# Spot-check the actual text that was captured.
for section in ["mda", "properties", "risk_factors"]:
    row = sections[(sections.ticker == sections.ticker.iloc[0]) &
                   (sections.section == section)].iloc[-1]
    print("=" * 100)
    print(f"{row.ticker}  FY{row.fiscal_year}  {row.item_label}  "
          f"({row.n_words:,} words, {row.n_chars:,} chars)")
    print(f"{row.source_url}")
    print("-" * 100)
    print(row.text[:700].strip())
    print("   ... [middle omitted] ...")
    print(row.text[-400:].strip())
    print()

====================================================================================================
ABCL  FY2025  Item 7 - Management's Discussion and Analysis  (7,580 words, 52,093 chars)
https://www.sec.gov/Archives/edgar/data/1703057/000170305726000012/abcl-20251231.htm
----------------------------------------------------------------------------------------------------
Item 7. Management’s Discussion and Analysis of Financial Condition and Results of Operations.

You should read the following discussion and analysis of our financial condition and results of operations together with our consolidated financial statements and the related notes thereto included elsewhere in this annual report. Some of the information contained in this discussion and analysis or set forth in other parts of this annual report contain forward-looking statements that involve risks, uncertainties and assumptions. As a result of many factors, including those factors set forth in Part I, Item 1A, Risk Factors, our actual results could differ materially from those discussed in or imp
   ... [middle omitted] ...
Black-Scholes option pricing model to determine the estimated fair value of our stock options granted in the years ended December 31, 2023, 2024, and 2025.

Recent Accounting Pronouncements

See Note 3 to our annual consolidated financial statements appearing elsewhere in this Annual Report for a description of recent accounting pronouncements applicable to our consolidated financial statements.

====================================================================================================
ABCL  FY2025  Item 2 - Properties  (256 words, 1,678 chars)
https://www.sec.gov/Archives/edgar/data/1703057/000170305726000012/abcl-20251231.htm
----------------------------------------------------------------------------------------------------
Item 2. Properties.

Our corporate headquarters and research and development facilities are located in Vancouver, British Columbia, where we lease approximately 260,000 square feet of space under leases expiring between 2026 and 2037. Through our Dayhu joint venture, we completed our new, dedicated corporate headquarters in 2024, that provides us 167,000 square feet of laboratory and office space. In December 2025, we obtained financing secured against this laboratory and office space as further described in Note 8 of our annual consolidated financial statements for the year ended December 31, 2025. Through our Beedie joint venture, we are nearing the completion of construction of 220,000 s
   ... [middle omitted] ...
ory space in Sydney, Australia, with a lease that expires in 2031. We also lease an additional 10,000 square feet of office and laboratory space across the other jurisdictions in which we operate, and we believe our facilities are adequate

79

and suitable for our current needs and that should it be needed, suitable additional or alternative space will be available to accommodate our operations.

====================================================================================================
ABCL  FY2025  Item 1A - Risk Factors  (43,756 words, 291,685 chars)
https://www.sec.gov/Archives/edgar/data/1703057/000170305726000012/abcl-20251231.htm
----------------------------------------------------------------------------------------------------
Item 1A. Risk Factors.

Risks Related to Our Financial Position and Need for Additional Capital

We have incurred losses in certain years since inception, including in 2025, and we may not be able to generate sufficient revenue to achieve profitability.

We expect to continue to incur expenditures as we operate our business. We expect to incur losses for the foreseeable future. We cannot accurately predict the timing or amount of our increased expenses, or when, if at all, we may achieve profitability. Our net loss for the years ended December 31, 2025 and 2024 was $146.4 million and $162.9 million, respectively. Our accumulated losses at December 31, 2025 and accumulated earnings at 2024 wa
   ... [middle omitted] ...
r the loss of uninsured deposits or other financial assets;

•Potential or actual breach of statutory, regulatory or contractual obligations, including obligations that require the Company to maintain letters of credit or other credit support arrangements; and

•Termination of cash management arrangements and/or delays in accessing, or actual loss of, funds subject to cash management arrangements.

### Boundary check

A section that over-ran its item would contain the *body heading* of a later item. This
confirms each slice stops where it should.

In [91]:
BLEED = {
    "risk_factors": r"item\s*8\.?\s*[-–—:.]?\s*financial\s+statements\s+and\s+supplementary",
    "properties":   r"item\s*7\.?\s*[-–—:.]?\s*management.s\s+discussion",
    "mda":          r"item\s*9a\.?\s*[-–—:.]?\s*controls\s+and\s+procedures",
}

flagged = 0
for _, r in sections.iterrows():
    hits = [m.start() for m in re.finditer(BLEED[r.section], r.text, re.I) if m.start() > 2000]
    if hits:
        flagged += 1
        print(f"  over-run: {r.ticker} FY{r.fiscal_year} {r.section} at {hits[:2]} of {r.n_chars}")

print("All section boundaries clean." if not flagged else f"{flagged} row(s) flagged.")

  over-run: BBLG FY2017 mda at [4963] of 28198
  over-run: BMBL FY2022 risk_factors at [152051] of 210595
  over-run: BMBL FY2023 risk_factors at [137881] of 185923
  over-run: BMBL FY2024 risk_factors at [143851, 192740] of 194044
  over-run: BMBL FY2025 risk_factors at [181989] of 182514
  over-run: HRMY FY2025 risk_factors at [200619] of 234123
  over-run: IGC FY2011 mda at [2708] of 45817
  over-run: INTZ FY2010 mda at [26512] of 26544
  over-run: INTZ FY2011 mda at [26832] of 26864
  over-run: INTZ FY2012 mda at [27519] of 27551
  over-run: INTZ FY2013 mda at [27457] of 27489
  over-run: INTZ FY2014 mda at [26927] of 26959
  over-run: INTZ FY2015 mda at [26469] of 26501
  over-run: MAX FY2024 risk_factors at [12099] of 161377
  over-run: MAX FY2025 risk_factors at [14042] of 156400
  over-run: MDXG FY2021 risk_factors at [105648] of 128894
  over-run: MU FY2016 risk_factors at [16726, 22517] of 57292
  over-run: MU FY2017 risk_factors at [27779] of 58890
  over-run: MU FY2018 risk_factors at [27197, 28964] of 63906
  over-run: MU FY2019 risk_factors at [25344, 43107] of 79846
  over-run: MU FY2020 risk_factors at [30521, 49052] of 79897
  over-run: MU FY2021 risk_factors at [55453, 61566] of 91521
  over-run: MU FY2022 risk_factors at [57074, 60493] of 79448
  over-run: MU FY2023 risk_factors at [55472, 58683] of 83033
  over-run: MU FY2024 risk_factors at [65935, 69790] of 91473
  over-run: MU FY2025 risk_factors at [32784, 48120] of 102389
  over-run: MX FY2010 mda at [10903] of 168472
  over-run: MX FY2011 mda at [10715] of 148372
  over-run: MX FY2013 mda at [3083] of 108210
  over-run: MX FY2013 risk_factors at [45599, 45851] of 98962
  over-run: MX FY2015 risk_factors at [2991] of 84755
  over-run: MX FY2019 risk_factors at [35112] of 80979
  over-run: MX FY2020 risk_factors at [38130] of 74071
  over-run: MX FY2021 risk_factors at [74213, 77407] of 85576
  over-run: MX FY2022 risk_factors at [78151] of 84094
  over-run: MX FY2023 risk_factors at [75197] of 79812
  over-run: MX FY2024 risk_factors at [77858] of 84417
  over-run: MX FY2025 risk_factors at [78192] of 85237
  over-run: NRXP FY2019 risk_factors at [14551] of 161313
  over-run: NRXP FY2020 risk_factors at [21773] of 21860
  over-run: NVDA FY2011 risk_factors at [209911] of 384208
  over-run: PAYO FY2022 risk_factors at [19405] of 125692
  over-run: PAYO FY2023 risk_factors at [17878] of 124330
  over-run: PAYO FY2024 risk_factors at [32158] of 128725
  over-run: PAYO FY2025 risk_factors at [33234] of 132021
  over-run: PPLI FY2021 risk_factors at [27288] of 73872
  over-run: PPLI FY2022 risk_factors at [29997] of 72969
  over-run: PPLI FY2023 risk_factors at [31552, 54517] of 75160
  over-run: PPLI FY2024 risk_factors at [61970] of 101529
  over-run: PPLI FY2025 risk_factors at [47806] of 82644
  over-run: RNAZ FY2025 mda at [83264] of 87677
  over-run: SKYE FY2020 properties at [5429] of 26906
52 row(s) flagged.

In [93]:
import shutil

# Define the destination folder in your Google Drive
# You can change '10K_sections' to any folder name you prefer in your Drive
drive_output_folder = '/content/drive/MyDrive/10K_sections'

# Create the destination folder in Google Drive if it doesn't exist
os.makedirs(drive_output_folder, exist_ok=True)

print(f"Copying files from {DROPBOX_RAW} to {drive_output_folder}...")

# Copy each parquet file from the source directory to the Google Drive destination
for file_name in os.listdir(DROPBOX_RAW):
    if file_name.endswith('.parquet'):
        source_file_path = os.path.join(DROPBOX_RAW, file_name)
        destination_file_path = os.path.join(drive_output_folder, file_name)
        shutil.copy2(source_file_path, destination_file_path)
        print(f"Copied: {file_name}")

print("All parquet files copied to Google Drive.")

Copying files from /content/bond_shared/data/raw/text to /content/drive/MyDrive/10K_sections...
Copied: SNDX_10K_sections.parquet
Copied: IIIV_10K_sections.parquet
Copied: MPWR_10K_sections.parquet
Copied: LPCN_10K_sections.parquet
Copied: URGN_10K_sections.parquet
Copied: PDSB_10K_sections.parquet
Copied: CDXS_10K_sections.parquet
Copied: YEXT_10K_sections.parquet
Copied: AUID_10K_sections.parquet
Copied: CVM_10K_sections.parquet
Copied: KTTA_10K_sections.parquet
Copied: RPAY_10K_sections.parquet
Copied: QTTB_10K_sections.parquet
Copied: DTIL_10K_sections.parquet
Copied: ABVC_10K_sections.parquet
Copied: GLUE_10K_sections.parquet
Copied: CYTK_10K_sections.parquet
Copied: TENB_10K_sections.parquet
Copied: PHAT_10K_sections.parquet
Copied: VIR_10K_sections.parquet
Copied: APRE_10K_sections.parquet
Copied: AIP_10K_sections.parquet
Copied: ADMA_10K_sections.parquet
Copied: VANI_10K_sections.parquet
Copied: LRMR_10K_sections.parquet
Copied: ANVS_10K_sections.parquet
Copied: MBIO_10K_sections.parquet
Copied: NVDA_10K_sections.parquet
Copied: NRDS_10K_sections.parquet
Copied: VTGN_10K_sections.parquet
Copied: OKTA_10K_sections.parquet
Copied: XBP_10K_sections.parquet
Copied: MRNA_10K_sections.parquet
Copied: CPAY_10K_sections.parquet
Copied: BMRN_10K_sections.parquet
Copied: SPRO_10K_sections.parquet
Copied: DBVT_10K_sections.parquet
Copied: IOT_10K_sections.parquet
Copied: PRTA_10K_sections.parquet
Copied: NERV_10K_sections.parquet
Copied: HUMA_10K_sections.parquet
Copied: IMXI_10K_sections.parquet
Copied: LGVN_10K_sections.parquet
Copied: TOST_10K_sections.parquet
Copied: QUIK_10K_sections.parquet
Copied: KURA_10K_sections.parquet
Copied: MBRX_10K_sections.parquet
Copied: CBIO_10K_sections.parquet
Copied: STRO_10K_sections.parquet
Copied: MRAM_10K_sections.parquet
Copied: PCVX_10K_sections.parquet
Copied: PXLW_10K_sections.parquet
Copied: RKTO_10K_sections.parquet
Copied: LONA_10K_sections.parquet
Copied: ZLAB_10K_sections.parquet
Copied: IVVD_10K_sections.parquet
Copied: CARS_10K_sections.parquet
Copied: OKUR_10K_sections.parquet
Copied: LEDS_10K_sections.parquet
Copied: CORT_10K_sections.parquet
Copied: CSBR_10K_sections.parquet
Copied: EEFT_10K_sections.parquet
Copied: XCUR_10K_sections.parquet
Copied: OSPN_10K_sections.parquet
Copied: TNGX_10K_sections.parquet
Copied: RCKT_10K_sections.parquet
Copied: SMMT_10K_sections.parquet
Copied: RUM_10K_sections.parquet
Copied: ARCT_10K_sections.parquet
Copied: NVAX_10K_sections.parquet
Copied: PANW_10K_sections.parquet
Copied: TWST_10K_sections.parquet
Copied: CTXR_10K_sections.parquet
Copied: TECH_10K_sections.parquet
Copied: NRIX_10K_sections.parquet
Copied: SITM_10K_sections.parquet
Copied: NTRB_10K_sections.parquet
Copied: SANA_10K_sections.parquet
Copied: CABA_10K_sections.parquet
Copied: EDVA_10K_sections.parquet
Copied: PLUR_10K_sections.parquet
Copied: PALI_10K_sections.parquet
Copied: JSPR_10K_sections.parquet
Copied: CRBU_10K_sections.parquet
Copied: TRDA_10K_sections.parquet
Copied: ACXP_10K_sections.parquet
Copied: BCYC_10K_sections.parquet
Copied: ORCL_10K_sections.parquet
Copied: CNSP_10K_sections.parquet
Copied: FABC_10K_sections.parquet
Copied: TCX_10K_sections.parquet
Copied: VRNS_10K_sections.parquet
Copied: ZSQR_10K_sections.parquet
Copied: MGNX_10K_sections.parquet
Copied: NTNX_10K_sections.parquet
Copied: DNA_10K_sections.parquet
Copied: CRVO_10K_sections.parquet
Copied: PRLD_10K_sections.parquet
Copied: ICCC_10K_sections.parquet
Copied: OVID_10K_sections.parquet
Copied: IRD_10K_sections.parquet
Copied: GOOGL_10K_sections.parquet
Copied: HOWL_10K_sections.parquet
Copied: VCEL_10K_sections.parquet
Copied: ALNY_10K_sections.parquet
Copied: ABSI_10K_sections.parquet
Copied: IMNM_10K_sections.parquet
Copied: AVXL_10K_sections.parquet
Copied: NGNE_10K_sections.parquet
Copied: CDT_10K_sections.parquet
Copied: OGEN_10K_sections.parquet
Copied: CEVA_10K_sections.parquet
Copied: CGTX_10K_sections.parquet
Copied: TGTX_10K_sections.parquet
Copied: TVGN_10K_sections.parquet
Copied: IRON_10K_sections.parquet
Copied: SLE_10K_sections.parquet
Copied: BTLN_10K_sections.parquet
Copied: MTVA_10K_sections.parquet
Copied: LYEL_10K_sections.parquet
Copied: PRTH_10K_sections.parquet
Copied: ALXO_10K_sections.parquet
Copied: RGNX_10K_sections.parquet
Copied: XBIO_10K_sections.parquet
Copied: LSTA_10K_sections.parquet
Copied: AZIO_10K_sections.parquet
Copied: ALMU_10K_sections.parquet
Copied: PCSA_10K_sections.parquet
Copied: LIDR_10K_sections.parquet
Copied: DWTX_10K_sections.parquet
Copied: DSGN_10K_sections.parquet
Copied: TEAD_10K_sections.parquet
Copied: PAYS_10K_sections.parquet
Copied: BKKT_10K_sections.parquet
Copied: ANIX_10K_sections.parquet
Copied: DJT_10K_sections.parquet
Copied: AURA_10K_sections.parquet
Copied: GLSI_10K_sections.parquet
Copied: VYGR_10K_sections.parquet
Copied: INSM_10K_sections.parquet
Copied: UPWK_10K_sections.parquet
Copied: CLDX_10K_sections.parquet
Copied: BBIO_10K_sections.parquet
Copied: AMD_10K_sections.parquet
Copied: RPD_10K_sections.parquet
Copied: GCTS_10K_sections.parquet
Copied: ONC_10K_sections.parquet
Copied: LITS_10K_sections.parquet
Copied: ARTL_10K_sections.parquet
Copied: CCCC_10K_sections.parquet
Copied: KPLT_10K_sections.parquet
Copied: AXSM_10K_sections.parquet
Copied: SLAB_10K_sections.parquet
Copied: MSFT_10K_sections.parquet
Copied: RPRX_10K_sections.parquet
Copied: COCP_10K_sections.parquet
Copied: IBIO_10K_sections.parquet
Copied: LSAK_10K_sections.parquet
Copied: RXRX_10K_sections.parquet
Copied: CRSP_10K_sections.parquet
Copied: SYRE_10K_sections.parquet
Copied: SSTK_10K_sections.parquet
Copied: MAX_10K_sections.parquet
Copied: RNAC_10K_sections.parquet
Copied: TPST_10K_sections.parquet
Copied: RXT_10K_sections.parquet
Copied: MU_10K_sections.parquet
Copied: FTH_10K_sections.parquet
Copied: AGEN_10K_sections.parquet
Copied: LXRX_10K_sections.parquet
Copied: KROS_10K_sections.parquet
Copied: TRAW_10K_sections.parquet
Copied: TWLO_10K_sections.parquet
Copied: REGN_10K_sections.parquet
Copied: UNCY_10K_sections.parquet
Copied: JANX_10K_sections.parquet
Copied: AISP_10K_sections.parquet
Copied: VSH_10K_sections.parquet
Copied: CNTX_10K_sections.parquet
Copied: GERN_10K_sections.parquet
Copied: PMVP_10K_sections.parquet
Copied: SABR_10K_sections.parquet
Copied: VERU_10K_sections.parquet
Copied: VERI_10K_sections.parquet
Copied: HRMY_10K_sections.parquet
Copied: AIM_10K_sections.parquet
Copied: CDIO_10K_sections.parquet
Copied: ANAB_10K_sections.parquet
Copied: RLMD_10K_sections.parquet
Copied: IONS_10K_sections.parquet
Copied: HURA_10K_sections.parquet
Copied: PTN_10K_sections.parquet
Copied: HCWB_10K_sections.parquet
Copied: MQ_10K_sections.parquet
Copied: TVTX_10K_sections.parquet
Copied: FENC_10K_sections.parquet
Copied: IMNN_10K_sections.parquet
Copied: VNDA_10K_sections.parquet
Copied: AEON_10K_sections.parquet
Copied: CRUS_10K_sections.parquet
Copied: KPTI_10K_sections.parquet
Copied: CELC_10K_sections.parquet
Copied: RMBS_10K_sections.parquet
Copied: IMUX_10K_sections.parquet
Copied: FLYW_10K_sections.parquet
Copied: GNPX_10K_sections.parquet
Copied: APVO_10K_sections.parquet
Copied: MNOV_10K_sections.parquet
Copied: DBX_10K_sections.parquet
Copied: MRKR_10K_sections.parquet
Copied: BCDA_10K_sections.parquet
Copied: SEAT_10K_sections.parquet
Copied: ATYR_10K_sections.parquet
Copied: EYPT_10K_sections.parquet
Copied: CRVS_10K_sections.parquet
Copied: ZNTL_10K_sections.parquet
Copied: HALO_10K_sections.parquet
Copied: SNTI_10K_sections.parquet
Copied: HYPD_10K_sections.parquet
Copied: MCRB_10K_sections.parquet
Copied: SABS_10K_sections.parquet
Copied: FHTX_10K_sections.parquet
Copied: RANI_10K_sections.parquet
Copied: PDYN_10K_sections.parquet
Copied: IMA_10K_sections.parquet
Copied: MTCH_10K_sections.parquet
Copied: DNLI_10K_sections.parquet
Copied: RLAY_10K_sections.parquet
Copied: CRWD_10K_sections.parquet
Copied: KALA_10K_sections.parquet
Copied: SRZN_10K_sections.parquet
Copied: XNCR_10K_sections.parquet
Copied: IMVT_10K_sections.parquet
Copied: BZFD_10K_sections.parquet
Copied: PYXS_10K_sections.parquet
Copied: REKR_10K_sections.parquet
Copied: RELY_10K_sections.parquet
Copied: S_10K_sections.parquet
Copied: EDSA_10K_sections.parquet
Copied: KPRX_10K_sections.parquet
Copied: ANNX_10K_sections.parquet
Copied: MNKD_10K_sections.parquet
Copied: MTNB_10K_sections.parquet
Copied: LNAI_10K_sections.parquet
Copied: ARMP_10K_sections.parquet
Copied: FTNT_10K_sections.parquet
Copied: CNTN_10K_sections.parquet
Copied: CARG_10K_sections.parquet
Copied: TXN_10K_sections.parquet
Copied: IBRX_10K_sections.parquet
Copied: OLMA_10K_sections.parquet
Copied: DIBS_10K_sections.parquet
Copied: MTSI_10K_sections.parquet
Copied: ALDX_10K_sections.parquet
Copied: ROIV_10K_sections.parquet
Copied: SER_10K_sections.parquet
Copied: OMER_10K_sections.parquet
Copied: IOVA_10K_sections.parquet
Copied: TVRD_10K_sections.parquet
Copied: MNPR_10K_sections.parquet
Copied: ALT_10K_sections.parquet
Copied: IGC_10K_sections.parquet
Copied: POWI_10K_sections.parquet
Copied: LVO_10K_sections.parquet
Copied: ATEN_10K_sections.parquet
Copied: IMMX_10K_sections.parquet
Copied: SNGX_10K_sections.parquet
Copied: INTZ_10K_sections.parquet
Copied: VHC_10K_sections.parquet
Copied: LENZ_10K_sections.parquet
Copied: CADL_10K_sections.parquet
Copied: SKYE_10K_sections.parquet
Copied: ZVRA_10K_sections.parquet
Copied: CUE_10K_sections.parquet
Copied: DARE_10K_sections.parquet
Copied: OLB_10K_sections.parquet
Copied: XYZ_10K_sections.parquet
Copied: MDXG_10K_sections.parquet
Copied: PTGX_10K_sections.parquet
Copied: APPN_10K_sections.parquet
Copied: AVX_10K_sections.parquet
Copied: RCUS_10K_sections.parquet
Copied: YARW_10K_sections.parquet
Copied: PI_10K_sections.parquet
Copied: PRSO_10K_sections.parquet
Copied: ZDGE_10K_sections.parquet
Copied: GANX_10K_sections.parquet
Copied: IKT_10K_sections.parquet
Copied: ELOX_10K_sections.parquet
Copied: CNSY_10K_sections.parquet
Copied: ABUS_10K_sections.parquet
Copied: PLTR_10K_sections.parquet
Copied: BIRD_10K_sections.parquet
Copied: ADIL_10K_sections.parquet
Copied: PMCB_10K_sections.parquet
Copied: DCOY_10K_sections.parquet
Copied: BODI_10K_sections.parquet
Copied: ARDX_10K_sections.parquet
Copied: SPRY_10K_sections.parquet
Copied: KOD_10K_sections.parquet
Copied: SYNA_10K_sections.parquet
Copied: ELVN_10K_sections.parquet
Copied: ENSC_10K_sections.parquet
Copied: TARA_10K_sections.parquet
Copied: INO_10K_sections.parquet
Copied: ACAD_10K_sections.parquet
Copied: SLS_10K_sections.parquet
Copied: MGTX_10K_sections.parquet
Copied: SILO_10K_sections.parquet
Copied: ANGI_10K_sections.parquet
Copied: FIVN_10K_sections.parquet
Copied: VERA_10K_sections.parquet
Copied: IMRX_10K_sections.parquet
Copied: NAUT_10K_sections.parquet
Copied: CMPX_10K_sections.parquet
Copied: ALLO_10K_sections.parquet
Copied: CBUS_10K_sections.parquet
Copied: EDIT_10K_sections.parquet
Copied: CRIS_10K_sections.parquet
Copied: RIGL_10K_sections.parquet
Copied: NVEC_10K_sections.parquet
Copied: PAYO_10K_sections.parquet
Copied: ACET_10K_sections.parquet
Copied: BMEA_10K_sections.parquet
Copied: HLSQ_10K_sections.parquet
Copied: MOVE_10K_sections.parquet
Copied: ERNA_10K_sections.parquet
Copied: DMAC_10K_sections.parquet
Copied: GOSS_10K_sections.parquet
Copied: MRVL_10K_sections.parquet
Copied: AI_10K_sections.parquet
Copied: JAZZ_10K_sections.parquet
Copied: GTLB_10K_sections.parquet
Copied: MIST_10K_sections.parquet
Copied: IPSC_10K_sections.parquet
Copied: USIO_10K_sections.parquet
Copied: CAPR_10K_sections.parquet
Copied: BEAM_10K_sections.parquet
Copied: CLYM_10K_sections.parquet
Copied: KRYS_10K_sections.parquet
Copied: TENX_10K_sections.parquet
Copied: INDP_10K_sections.parquet
Copied: GOVX_10K_sections.parquet
Copied: FBIO_10K_sections.parquet
Copied: RZLT_10K_sections.parquet
Copied: ENTX_10K_sections.parquet
Copied: ZETA_10K_sections.parquet
Copied: RARE_10K_sections.parquet
Copied: RVMD_10K_sections.parquet
Copied: TSHA_10K_sections.parquet
Copied: SRPT_10K_sections.parquet
Copied: PBYI_10K_sections.parquet
Copied: VKTX_10K_sections.parquet
Copied: BB_10K_sections.parquet
Copied: QLYS_10K_sections.parquet
Copied: BLZE_10K_sections.parquet
Copied: STTK_10K_sections.parquet
Copied: MDGL_10K_sections.parquet
Copied: RNAZ_10K_sections.parquet
Copied: ACRS_10K_sections.parquet
Copied: NKTX_10K_sections.parquet
Copied: NNVC_10K_sections.parquet
Copied: XBIT_10K_sections.parquet
Copied: ATNM_10K_sections.parquet
Copied: DVLT_10K_sections.parquet
Copied: ELDN_10K_sections.parquet
Copied: ICU_10K_sections.parquet
Copied: WEX_10K_sections.parquet
Copied: INCY_10K_sections.parquet
Copied: ABOS_10K_sections.parquet
Copied: INDI_10K_sections.parquet
Copied: AGPU_10K_sections.parquet
Copied: Z_10K_sections.parquet
Copied: QRVO_10K_sections.parquet
Copied: PLRX_10K_sections.parquet
Copied: HIND_10K_sections.parquet
Copied: ACIW_10K_sections.parquet
Copied: SPRB_10K_sections.parquet
Copied: BNAI_10K_sections.parquet
Copied: AVIR_10K_sections.parquet
Copied: AUPH_10K_sections.parquet
Copied: BOLT_10K_sections.parquet
Copied: PAY_10K_sections.parquet
Copied: ERAS_10K_sections.parquet
Copied: TDC_10K_sections.parquet
Copied: BRTX_10K_sections.parquet
Copied: ALGS_10K_sections.parquet
Copied: CALX_10K_sections.parquet
Copied: GYRE_10K_sections.parquet
Copied: TCRX_10K_sections.parquet
Copied: ACHV_10K_sections.parquet
Copied: OCGN_10K_sections.parquet
Copied: GRPN_10K_sections.parquet
Copied: LEXX_10K_sections.parquet
Copied: TCRT_10K_sections.parquet
Copied: PLX_10K_sections.parquet
Copied: AKAM_10K_sections.parquet
Copied: SVRA_10K_sections.parquet
Copied: NVTS_10K_sections.parquet
Copied: ASMB_10K_sections.parquet
Copied: KLRS_10K_sections.parquet
Copied: SWKS_10K_sections.parquet
Copied: ORIC_10K_sections.parquet
Copied: PRAX_10K_sections.parquet
Copied: RAMP_10K_sections.parquet
Copied: PVLA_10K_sections.parquet
Copied: ENTA_10K_sections.parquet
Copied: DRMA_10K_sections.parquet
Copied: BBLG_10K_sections.parquet
Copied: VOR_10K_sections.parquet
Copied: VTVT_10K_sections.parquet
Copied: NRXP_10K_sections.parquet
Copied: AEVA_10K_sections.parquet
Copied: YELP_10K_sections.parquet
Copied: VRTX_10K_sections.parquet
Copied: AVTX_10K_sections.parquet
Copied: CRMD_10K_sections.parquet
Copied: AIFA_10K_sections.parquet
Copied: DRK_10K_sections.parquet
Copied: SRRK_10K_sections.parquet
Copied: VIVS_10K_sections.parquet
Copied: INAB_10K_sections.parquet
Copied: ALZN_10K_sections.parquet
Copied: ALEC_10K_sections.parquet
Copied: RLYB_10K_sections.parquet
Copied: FFIV_10K_sections.parquet
Copied: VBIO_10K_sections.parquet
Copied: TZOO_10K_sections.parquet
Copied: AVPT_10K_sections.parquet
Copied: VRSN_10K_sections.parquet
Copied: CISO_10K_sections.parquet
Copied: DYN_10K_sections.parquet
Copied: NET_10K_sections.parquet
Copied: TNYA_10K_sections.parquet
Copied: PHIO_10K_sections.parquet
Copied: KRRO_10K_sections.parquet
Copied: MX_10K_sections.parquet
Copied: AVGO_10K_sections.parquet
Copied: ELTX_10K_sections.parquet
Copied: PULM_10K_sections.parquet
Copied: BMBL_10K_sections.parquet
Copied: MLTX_10K_sections.parquet
Copied: OBIO_10K_sections.parquet
Copied: ABEO_10K_sections.parquet
Copied: QURE_10K_sections.parquet
Copied: CLNN_10K_sections.parquet
Copied: SEER_10K_sections.parquet
Copied: PPCB_10K_sections.parquet
Copied: PASG_10K_sections.parquet
Copied: DMRA_10K_sections.parquet
Copied: AGIO_10K_sections.parquet
Copied: CLRB_10K_sections.parquet
Copied: FDMT_10K_sections.parquet
Copied: CLDI_10K_sections.parquet
Copied: CGEM_10K_sections.parquet
Copied: NXDR_10K_sections.parquet
Copied: GRI_10K_sections.parquet
Copied: DNTH_10K_sections.parquet
Copied: PINS_10K_sections.parquet
Copied: XENE_10K_sections.parquet
Copied: TECX_10K_sections.parquet
Copied: NXTC_10K_sections.parquet
Copied: CRBP_10K_sections.parquet
Copied: KRSA_10K_sections.parquet
Copied: REPL_10K_sections.parquet
Copied: CTMX_10K_sections.parquet
Copied: ARVN_10K_sections.parquet
Copied: MRVI_10K_sections.parquet
Copied: AKTX_10K_sections.parquet
Copied: CING_10K_sections.parquet
Copied: ADI_10K_sections.parquet
Copied: SNAP_10K_sections.parquet
Copied: AOSL_10K_sections.parquet
Copied: WOLF_10K_sections.parquet
Copied: ZS_10K_sections.parquet
Copied: TYRA_10K_sections.parquet
Copied: FATE_10K_sections.parquet
Copied: CRDF_10K_sections.parquet
Copied: CCSI_10K_sections.parquet
Copied: JBIO_10K_sections.parquet
Copied: GRDX_10K_sections.parquet
Copied: KYNB_10K_sections.parquet
Copied: NN_10K_sections.parquet
Copied: RYTM_10K_sections.parquet
Copied: ZIP_10K_sections.parquet
Copied: EQ_10K_sections.parquet
Copied: GRCE_10K_sections.parquet
Copied: MCHP_10K_sections.parquet
Copied: PAAI_10K_sections.parquet
Copied: LTRN_10K_sections.parquet
Copied: RNTX_10K_sections.parquet
Copied: ALGM_10K_sections.parquet
Copied: CELU_10K_sections.parquet
Copied: PGEN_10K_sections.parquet
Copied: NXPI_10K_sections.parquet
Copied: AIXC_10K_sections.parquet
Copied: LSCC_10K_sections.parquet
Copied: BNTC_10K_sections.parquet
Copied: GEN_10K_sections.parquet
Copied: INVA_10K_sections.parquet
Copied: OABI_10K_sections.parquet
Copied: MDB_10K_sections.parquet
Copied: LCTX_10K_sections.parquet
Copied: LGND_10K_sections.parquet
Copied: CRDO_10K_sections.parquet
Copied: XFOR_10K_sections.parquet
Copied: WHWK_10K_sections.parquet
Copied: ORMP_10K_sections.parquet
Copied: YYAI_10K_sections.parquet
Copied: TIL_10K_sections.parquet
Copied: VRCA_10K_sections.parquet
Copied: FOUR_10K_sections.parquet
Copied: QNCX_10K_sections.parquet
Copied: NTCT_10K_sections.parquet
Copied: ORKA_10K_sections.parquet
Copied: ATRA_10K_sections.parquet
Copied: EVTC_10K_sections.parquet
Copied: FULC_10K_sections.parquet
Copied: XLO_10K_sections.parquet
Copied: REVB_10K_sections.parquet
Copied: ARWR_10K_sections.parquet
Copied: ZURA_10K_sections.parquet
Copied: UPXI_10K_sections.parquet
Copied: BLIN_10K_sections.parquet
Copied: TOVX_10K_sections.parquet
Copied: ON_10K_sections.parquet
Copied: COGT_10K_sections.parquet
Copied: DIOD_10K_sections.parquet
Copied: EVER_10K_sections.parquet
Copied: AIFC_10K_sections.parquet
Copied: INTC_10K_sections.parquet
Copied: GALT_10K_sections.parquet
Copied: EWTX_10K_sections.parquet
Copied: PROK_10K_sections.parquet
Copied: SNPS_10K_sections.parquet
Copied: LASR_10K_sections.parquet
Copied: TRVI_10K_sections.parquet
Copied: HRTX_10K_sections.parquet
Copied: GTBP_10K_sections.parquet
Copied: CELZ_10K_sections.parquet
Copied: JAGX_10K_sections.parquet
Copied: PPLI_10K_sections.parquet
Copied: SMTC_10K_sections.parquet
Copied: BOX_10K_sections.parquet
Copied: MXL_10K_sections.parquet
Copied: BDTX_10K_sections.parquet
Copied: GDDY_10K_sections.parquet
Copied: CALC_10K_sections.parquet
Copied: NVCT_10K_sections.parquet
Copied: NTLA_10K_sections.parquet
Copied: INMB_10K_sections.parquet
Copied: ONCO_10K_sections.parquet
Copied: WVE_10K_sections.parquet
Copied: CHRS_10K_sections.parquet
Copied: FLNA_10K_sections.parquet
Copied: CETX_10K_sections.parquet
Copied: ATOS_10K_sections.parquet
Copied: NUVB_10K_sections.parquet
Copied: TARS_10K_sections.parquet
Copied: RNXT_10K_sections.parquet
Copied: BIVI_10K_sections.parquet
Copied: OTLK_10K_sections.parquet
Copied: BAND_10K_sections.parquet
Copied: ENVB_10K_sections.parquet
Copied: SLDB_10K_sections.parquet
Copied: DFTX_10K_sections.parquet
Copied: PRGS_10K_sections.parquet
Copied: PTCT_10K_sections.parquet
Copied: MIRM_10K_sections.parquet
Copied: ARQT_10K_sections.parquet
Copied: NKTR_10K_sections.parquet
Copied: ALLR_10K_sections.parquet
Copied: INKT_10K_sections.parquet
Copied: STOK_10K_sections.parquet
Copied: EXEL_10K_sections.parquet
Copied: ABCL_10K_sections.parquet
Copied: VRDN_10K_sections.parquet
Copied: OCUL_10K_sections.parquet
Copied: PATH_10K_sections.parquet
Copied: TLS_10K_sections.parquet
Copied: DYAI_10K_sections.parquet
Copied: NTAP_10K_sections.parquet
Copied: IPWR_10K_sections.parquet
Copied: META_10K_sections.parquet
Copied: GSIT_10K_sections.parquet
Copied: TNXP_10K_sections.parquet
Copied: QCOM_10K_sections.parquet

In [94]:
import pandas as pd
import os

vrtx_file_path = os.path.join(DROPBOX_RAW, "VRTX_10K_sections.parquet")

if os.path.exists(vrtx_file_path):
    print(f"Reading {vrtx_file_path}...")
    vrtx_df = pd.read_parquet(vrtx_file_path)
    # Display all rows of the DataFrame
    with pd.option_context('display.max_rows', None, 'display.max_columns', None):
        display(vrtx_df)
else:
    print(f"Error: The file {vrtx_file_path} does not exist. Please ensure the extraction process for VRTX was completed successfully.")

Reading /content/bond_shared/data/raw/text/VRTX_10K_sections.parquet...

,ticker,cik,company_name,form,section,item_label,filing_date,period_of_report,fiscal_year,accession_no,text,n_chars,n_words,source_url
0,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2011-02-17,2010-12-31,2010,0001047469-11-001025,ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS OF FINANCIA...,80486,12244,https://www.sec.gov/Archives/edgar/data/875320/000104746...
1,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2011-02-17,2010-12-31,2010,0001047469-11-001025,ITEM 2. PROPERTIES \n\n We lease an aggregate of approxi...,3351,529,https://www.sec.gov/Archives/edgar/data/875320/000104746...
2,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2011-02-17,2010-12-31,2010,0001047469-11-001025,ITEM 1A. RISK FACTORS \n\n RISK FACTORS \n\n Investing i...,81291,12252,https://www.sec.gov/Archives/edgar/data/875320/000104746...
3,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2012-02-22,2011-12-31,2011,0001047469-12-001298,ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS OF FINANCIA...,79821,12049,https://www.sec.gov/Archives/edgar/data/875320/000104746...
4,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2012-02-22,2011-12-31,2011,0001047469-12-001298,ITEM 2. PROPERTIES \n\n We lease an aggregate of approxi...,3323,524,https://www.sec.gov/Archives/edgar/data/875320/000104746...
5,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2012-02-22,2011-12-31,2011,0001047469-12-001298,ITEM 1A. RISK FACTORS \n\n RISK FACTORS \n\n Investing i...,80352,12040,https://www.sec.gov/Archives/edgar/data/875320/000104746...
6,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2013-03-01,2012-12-31,2012,0000875320-13-000009,Table of Contents\n\nITEM 7. MANAGEMENT'S DISCUSSION AND...,87067,13301,https://www.sec.gov/Archives/edgar/data/875320/000087532...
7,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2013-03-01,2012-12-31,2012,0000875320-13-000009,ITEM 2. PROPERTIES\n\nMassachusetts Headquarters\n\nWe l...,3862,598,https://www.sec.gov/Archives/edgar/data/875320/000087532...
8,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2013-03-01,2012-12-31,2012,0000875320-13-000009,Table of Contents\n\nITEM 1A. RISK FACTORS\n\nRISK FACTO...,91892,13829,https://www.sec.gov/Archives/edgar/data/875320/000087532...
9,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2014-02-11,2013-12-31,2013,0000875320-14-000015,ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS OF FINANCIA...,76453,11598,https://www.sec.gov/Archives/edgar/data/875320/000087532...
10,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2014-02-11,2013-12-31,2013,0000875320-14-000015,ITEM 2. PROPERTIES\n\nCorporate Headquarters\n\nIn the f...,2974,441,https://www.sec.gov/Archives/edgar/data/875320/000087532...
11,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2014-02-11,2013-12-31,2013,0000875320-14-000015,ITEM 1A. RISK FACTORS\n\nRISK FACTORS\n\nInvesting in ou...,85332,12847,https://www.sec.gov/Archives/edgar/data/875320/000087532...
12,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2015-02-13,2014-12-31,2014,0000875320-15-000012,ITEM 7. MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIA...,70654,10651,https://www.sec.gov/Archives/edgar/data/875320/000087532...
13,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2015-02-13,2014-12-31,2014,0000875320-15-000012,ITEM 2. PROPERTIES\n\nCorporate Headquarters\n\nIn the f...,2398,354,https://www.sec.gov/Archives/edgar/data/875320/000087532...
14,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2015-02-13,2014-12-31,2014,0000875320-15-000012,ITEM 1A. RISK FACTORS\n\nRISK FACTORS\n\nInvesting in ou...,102150,15314,https://www.sec.gov/Archives/edgar/data/875320/000087532...
15,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2016-02-16,2015-12-31,2015,0000875320-16-000067,ITEM 7. MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIA...,70265,10602,https://www.sec.gov/Archives/edgar/data/875320/000087532...
16,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2016-02-16,2015-12-31,2015,0000875320-16-000067,ITEM 2. PROPERTIES\n\nCorporate Headquarters\n\nWe lease...,1978,305,https://www.sec.gov/Archives/edgar/data/875320/000087532...
17,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2016-02-16,2015-12-31,2015,0000875320-16-000067,ITEM 1A. RISK FACTORS\n\nRISK FACTORS\n\nInvesting in ou...,107223,16160,https://www.sec.gov/Archives/edgar/data/875320/000087532...
18,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2017-02-23,2016-12-31,2016,0000875320-17-000017,ITEM 7. MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIA...,75049,11259,https://www.sec.gov/Archives/edgar/data/875320/000087532...
19,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2017-02-23,2016-12-31,2016,0000875320-17-000017,ITEM 2. PROPERTIES\n\nCorporate Headquarters\n\nWe lease...,2014,309,https://www.sec.gov/Archives/edgar/data/875320/000087532...
20,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2017-02-23,2016-12-31,2016,0000875320-17-000017,ITEM 1A. RISK FACTORS\n\nRISK FACTORS\n\nInvesting in ou...,111153,16654,https://www.sec.gov/Archives/edgar/data/875320/000087532...
21,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2018-02-15,2017-12-31,2017,0000875320-18-000009,ITEM 7. MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIA...,85745,12957,https://www.sec.gov/Archives/edgar/data/875320/000087532...
22,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2018-02-15,2017-12-31,2017,0000875320-18-000009,ITEM 2. PROPERTIES\n\nCorporate Headquarters\n\nWe lease...,1553,244,https://www.sec.gov/Archives/edgar/data/875320/000087532...
23,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2018-02-15,2017-12-31,2017,0000875320-18-000009,ITEM 1A. RISK FACTORS\n\nRISK FACTORS\n\nInvesting in ou...,112023,16773,https://www.sec.gov/Archives/edgar/data/875320/000087532...
24,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2019-02-13,2018-12-31,2018,0000875320-19-000006,ITEM 7. MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIA...,82275,12393,https://www.sec.gov/Archives/edgar/data/875320/000087532...
25,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2019-02-13,2018-12-31,2018,0000875320-19-000006,ITEM 2. PROPERTIES\n\nCorporate Headquarters\n\nWe lease...,1281,197,https://www.sec.gov/Archives/edgar/data/875320/000087532...
26,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2019-02-13,2018-12-31,2018,0000875320-19-000006,ITEM 1A. RISK FACTORS\n\nRISK FACTORS\n\nInvesting in ou...,111499,16710,https://www.sec.gov/Archives/edgar/data/875320/000087532...
27,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2020-02-13,2019-12-31,2019,0000875320-20-000007,ITEM 7. MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIA...,74293,11118,https://www.sec.gov/Archives/edgar/data/875320/000087532...
28,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2020-02-13,2019-12-31,2019,0000875320-20-000007,ITEM 2. PROPERTIES\n\nCorporate Headquarters\n\nWe lease...,759,113,https://www.sec.gov/Archives/edgar/data/875320/000087532...
29,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2020-02-13,2019-12-31,2019,0000875320-20-000007,ITEM 1A. RISK FACTORS\n\nRISK FACTORS\n\nInvesting in ou...,110952,16567,https://www.sec.gov/Archives/edgar/data/875320/000087532...
30,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2021-02-11,2020-12-31,2020,0000875320-21-000006,ITEM 7.MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL...,66461,9908,https://www.sec.gov/Archives/edgar/data/875320/000087532...
31,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2021-02-11,2020-12-31,2020,0000875320-21-000006,ITEM 2.PROPERTIES\n\nCorporate Headquarters\n\nWe lease ...,863,126,https://www.sec.gov/Archives/edgar/data/875320/000087532...
32,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2021-02-11,2020-12-31,2020,0000875320-21-000006,ITEM 1A. RISK FACTORS\n\nInvesting in our common stock i...,136459,20390,https://www.sec.gov/Archives/edgar/data/875320/000087532...
33,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2022-02-09,2021-12-31,2021,0000875320-22-000007,ITEM 7.MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL...,58454,8795,https://www.sec.gov/Archives/edgar/data/875320/000087532...
34,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2022-02-09,2021-12-31,2021,0000875320-22-000007,ITEM 2.PROPERTIES\n\nCorporate Headquarters\n\nWe lease ...,858,125,https://www.sec.gov/Archives/edgar/data/875320/000087532...
35,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2022-02-09,2021-12-31,2021,0000875320-22-000007,ITEM 1A. RISK FACTORS\n\nInvesting in our common stock i...,154904,22974,https://www.sec.gov/Archives/edgar/data/875320/000087532...
36,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2023-02-10,2022-12-31,2022,0000875320-23-000007,ITEM 7.MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL...,62476,9344,https://www.sec.gov/Archives/edgar/data/875320/000087532...
37,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2023-02-10,2022-12-31,2022,0000875320-23-000007,ITEM 2.PROPERTIES\n\nCorporate Headquarters\n\nWe lease ...,858,125,https://www.sec.gov/Archives/edgar/data/875320/000087532...
38,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2023-02-10,2022-12-31,2022,0000875320-23-000007,ITEM 1A. RISK FACTORS\n\nInvesting in our common stock i...,159903,23721,https://www.sec.gov/Archives/edgar/data/875320/000087532...
39,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2024-02-15,2023-12-31,2023,0000875320-24-000062,ITEM 7.MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL...,67514,10146,https://www.sec.gov/Archives/edgar/data/875320/000087532...
40,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2024-02-15,2023-12-31,2023,0000875320-24-000062,ITEM 2.PROPERTIES\n\nCorporate Headquarters\n\nWe lease ...,858,125,https://www.sec.gov/Archives/edgar/data/875320/000087532...
41,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2024-02-15,2023-12-31,2023,0000875320-24-000062,ITEM 1A. RISK FACTORS\n\nInvesting in our common stock i...,156930,23249,https://www.sec.gov/Archives/edgar/data/875320/000087532...
42,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2025-02-13,2024-12-31,2024,0000875320-25-000053,ITEM 7.MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL...,75058,11166,https://www.sec.gov/Archives/edgar/data/875320/000087532...
43,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2025-02-13,2024-12-31,2024,0000875320-25-000053,ITEM 2.PROPERTIES\n\nCorporate Headquarters\n\nWe lease ...,918,136,https://www.sec.gov/Archives/edgar/data/875320/000087532...
44,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2025-02-13,2024-12-31,2024,0000875320-25-000053,ITEM 1A. RISK FACTORS\n\nInvesting in our common stock i...,160795,23706,https://www.sec.gov/Archives/edgar/data/875320/000087532...
45,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,mda,Item 7 - Management's Discussion and Analysis,2026-02-13,2025-12-31,2025,0000875320-26-000056,ITEM 7.MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL...,61121,8920,https://www.sec.gov/Archives/edgar/data/875320/000087532...
46,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,properties,Item 2 - Properties,2026-02-13,2025-12-31,2025,0000875320-26-000056,ITEM 2.PROPERTIES\n\nCorporate Headquarters\n\nWe lease ...,1182,174,https://www.sec.gov/Archives/edgar/data/875320/000087532...
47,VRTX,875320,VERTEX PHARMACEUTICALS INC / MA,10-K,risk_factors,Item 1A - Risk Factors,2026-02-13,2025-12-31,2025,0000875320-26-000056,25\n\nITEM 1A. RISK FACTORS\n\nInvesting in our common s...,72834,10422,https://www.sec.gov/Archives/edgar/data/875320/000087532...

## 8. Running the whole universe

Everything above is already written for the full list — this run only stopped at
`N_COMPANIES = 3`. To process every remaining company:

```python
N_COMPANIES = len(universe)
targets = universe                 # then re-run sections 5 and 6
```

Practical notes before you do:

- **Time.** Roughly 5–15 seconds per filing, ~10 filings per company. Every company in
  `universe` now has at least one 10-K, so budget several hours for the full run. It is safe
  to stop and restart — set
  `overwrite=False` in `store_sections_parquet` and completed companies are skipped.
- **Size.** These three companies produced ~1.4 MB of parquet each. The full universe will run
  to roughly 1–2 GB, so let Dropbox finish syncing.
- **Rate limits.** Every SEC call in this notebook goes through `_throttle()`, so leave
  `MIN_INTERVAL` at 0.13 and do not raise `max_workers`.
- **Failures.** Wrap the loop in a `failed` list (as in section 6) and retry those tickers
  afterwards — most failures are transient.


```
bond_shared/data/raw/
├── financials/{TICKER}/10K/{year}_{income|balance|cashflow|equity}.parquet   # XBRL
└── text/{TICKER}_10K_sections.parquet                                        # this notebook
```

Because every file is one flat `{TICKER}_10K_sections.parquet`, the whole text corpus loads
in one line once the full run is done:

```python
corpus = pd.read_parquet(DROPBOX_RAW)     # pyarrow reads the directory as one dataset
```